### ISSUE TITLE
any schedule?

### ISSUE THREAD

**Issue by EMLVIRUS** [bitwarden/desktop#1]
It's still empty since 2016, any release schedule?

**Comment by kspearrin** [comment]
Unfortunately we've been busy with the other apps and haven't got around to starting this yet.

**Comment by EMLVIRUS** [comment]
Gotta, thx for answer

**Comment by weihanglo** [comment]
@kspearrin Is there anything I can help?

**Comment by kspearrin** [comment]
Well, first step is to choose an application framework. The most logical choice for us at the moment is Electron, but that hasn't been too popular with folks as of late. Some research into that will be needed.

**Comment by goldsziggy** [comment]
Was thinking about throwing something together like this as well.  Out of curiosity is the bitwarden API documented anywhere?  I went to the repo and didn't see a swagger or anything.

**Comment by kspearrin** [comment]
Development is underway here now. Expected release is 4-6 weeks.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/bitwarden/desktop/issues/1#issuecomment-334017563

[Electron](http://github.com/electron/electron) is not ideal. [The mobile application](http://github.com/bitwarden/mobile) is an example of how much better more native technologies are. Using the [Gnome ToolKit](http://gitlab.gnome.org/GNOME/gtk) or [Qt](http://code.qt.io/cgit) for [GNU](http://gnu.org)/[Linux](http://github.com/torvalds/linux), and the [Universal Windows Platform](http://docs.microsoft.com/windows/uwp) and [WinUI](http://github.com/microsoft/microsoft-ui-xaml) for http://wikipedia.org/wiki/Microsoft_Windows, would be difficult at first, but the latter is very important, and the former options much more pleasant to use. Thus, do reconsider this decision sometime.

**Comment by charlesroddie** [comment]
A big shame that electron was chosen, especially as the mobile apps use Xamarin.Forms which works on desktop too. I wouldn't install an electron app unless absolutely necessary, given the memory and performance penalties that it would impose on my system.
