### ISSUE TITLE
Minimize Not Working On ArchLinux

### ISSUE THREAD

**Issue by icrunchbanger** [bitwarden/desktop#10]
Hi, i tested latest release for Linux. I like the design. Anyhow minimizing is not working and also lock option "Never" is ignored so you have to type password upon opening. Arch Linux with i3 WM. Ping me if you have any question.

**Comment by kspearrin** [comment]
What package are you using? rpm, AppImage?

**Comment by icrunchbanger** [comment]
AppImage "bitwarden-0.0.5-x86_64.AppImage"

**Comment by kspearrin** [comment]
I don't have an installation of Arch Linux available to test on. Could you explain more about "minimizing is not working"? It's working fine on my Ubuntu installation from what I can see. Also, on Fedora with Gnome I don't even seem to have a minimize option available. I am not a Linux user so I am not really sure how that is suppose to work in the first place though.

**Comment by kspearrin** [comment]
Also tested the "Never" lock option on Fedora and was not able to reproduce the problem either.

**Comment by icrunchbanger** [comment]
@kspearrin srry but "Never" lock was my bad. I didnt have keyring installed. About minimizing, i think that this could by i3 WM issues but i do have apps that run in background and can be minimized to system tray.
Check this video: https://photos.app.goo.gl/mgBLm6FO9TuSaLrB2

**Comment by icrunchbanger** [comment]
App didnt crash once, it just acted like the option "on restart" and every time it locked. It seems a bit more complicated than just keyring installation because i3 is not actual desktop environment but just a window manager. Key ring does come by default with all mayor desktop environments like Gnome, KDE, etc. Let me look up at that thing a bit more and il get back to you. For now it seems that dependency required are keyring /gnome-keyring which i installed/ and also zenity /https://github.com/GNOME/zenity/ for GUI boxes.

**Comment by kspearrin** [comment]
Installing zenity fixed the minimize problem?

**Comment by icrunchbanger** [comment]
Nah, needed for keyring to function properly. Minimizing is still a problem.

**Comment by x80486** [comment]
Ouch! I have the same issue. I'm using GNOME `3.28`.

It's weird though, it only happens the very first time I click on it. I can minimize the app's window only once, after that, it gets stuck there...like if the minimize button in the title wouldn't have any action(s) attached to it.

By the way, do you have any plans for a Flatpak?

**Comment by IQIDOX** [comment]
Please add option of minimization to tray when closing the window. So it will be much more convenient.

**Comment by PeteJodo** [comment]
yeah minimizing to system tray is not working for me in Ubuntu 18.10 Gnome 3.30.1 Bitwarden 1.7.0
