### ISSUE TITLE
Bitwarden Crashing on startup following 10.15.7 Catalina update

### ISSUE THREAD

**Issue by atjbramley** [bitwarden/desktop#1003]
## Describe the Bug

Bitwarden Desktop crashes consistently upon system boot following Catalina update to 10.15.7.
Bitwarden Desktop did not crash prior to Catalina update.

## Steps To Reproduce

Set Bitwarden desktop to 'Start automatically on login' via app properties.
Boot system.

## Expected Result

Bitwarden crashes with the error at the gist below:

https://gist.github.com/atjbramley/bf833e8657190ad06595ef94e32f6061

## Environment

- Operating system:  Mac OS Catalina - recent update to 10.15.7
- Machine - Early 2013 15" rMBP, (16gb/650GT)
- Installation method: Downloaded from Bitwarden.com
- Bitwarden Version 1.27.1 (531)

## Additional Context

Relaunching the app after the crash always results in a successful run without further issues.

**Comment by sso-bitwarden** [comment]
Will you first try uninstalling the application, removing any leftover data, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/article/data-storage/#on-your-local-machine

**Comment by atjbramley** [comment]
A clean re-install (uninstall via app-cleaner) seems to have done the job!
