### ISSUE TITLE
Bitwarden doesn't fill in username on logon page of QNAP (QTS)

### ISSUE THREAD

**Issue by YerGrannie** [bitwarden/desktop#1004]
## Describe the Bug
Bitwarden won't fill in username on logon page of QNAP (QTS)

When I select the correct entry in Bitwarden, with username and password neatly filled into the correct fields, only the password field is filled. I have to manually fill in the username field. As far as I've seen this only happens on the login page.
## Steps To Reproduce
Contact me. The logon page is private.

Just open up the login page and see for yourself.
4. Click on '...'

## Expected Result
Only the password field is filled

I expect a change in Bitwarden resulting in an update that will make Bitwarden fill in the username as well as the password on this page, as well as on all the others on which it already works
## Actual Result
Me being able to logon with the few clicks required.

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]
Happens in Windows 10 and MacOS..

**Comment by clayadams5226** [comment]
Sorry to hear you're having issues. We have a separate thread for all auto-fill issues. Please report your issue there. I am going to close this ticket as a duplicate. 

https://github.com/bitwarden/browser/issues/1621

**Comment by Szeraax** [comment]
Found the issue: QNAP changed the field from an input to a textarea. 

Source: https://1password.community/discussion/112744/autofill-has-ceased-working-on-qnap-qts-4-4-2-1270-login-page

I've verified that editing from the NAS admin user /home/httpd/cgi-bin/login.html (NOT index.html!!!) fixes this up entirely.
