### ISSUE TITLE
Bitwarden Desktop crashes on startup Ubuntu

### ISSUE THREAD

**Issue by person1234-ux** [bitwarden/desktop#1005]
## Steps To Reproduce

1. Go to the bitwarden application 
2. Click on click on bitwarden
3. bitwarden doesn't load.

## Expected Result
Bitwarden opens up and i can access all of my passwords 

## Actual Result

![Screenshot of the error message](https://user-images.githubusercontent.com/76968588/127237867-c7115f50-e5dc-4001-94ee-e2166d7bd4c7.png)

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: snap 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]
- 1.27.1

**Comment by person1234-ux** [comment]
I was able to fix it by reinstalling bitwarden.

**Comment by clayadams5226** [comment]
Glad to hear you were able to get it resolved with a reinstall. I'm going to go ahead and close the ticket out, but if it happens again feel free to reopen it.
