### ISSUE TITLE
MacOS Desktop loggin attempt error failed to fetch

### ISSUE THREAD

**Issue by autroncoso** [bitwarden/desktop#1009]
## Describe the Bug

"An error has occurred. Failed to fetch" messaged pops up when I click to login on the MAC OS appstore desktop app. 

## Steps To Reproduce

Simply download the app from the app store and attempt to login. possible causes? recently factory reset my mac. But the Safari and Firefox extension works fine. Have tried reinstalling the app, restarting my mac, and clearing this folder: ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden

## Expected Result

I expect to be able to login and see my vault.

## Actual Result

error message as described above and stays on the login screen.

## Screenshots or Videos

N/A

## Environment

- Operating system:  Mac OS Big Sur 11.5.1
- Installation method: Downloaded from Mac App Store
- Build Version (go to "Settings" → "About"): Version 1.27.1 (531)

## Additional Context

N/A

**Comment by SergeantConfused** [comment]
Hi @autroncoso,

This usually indicates that the Bitwarden client you're using is unable to reach our cloud servers (or your server, if you're self-hosting).
1. Please deactivate any firewall or security application you have running on your machine.
2. Please try rebooting your router/network appliance.
If you're still unable to log in, please create a support ticket using this form: https://bitwarden.com/contact/ and we'll continue assisting you.

All the best,
