### ISSUE TITLE
exporting data to Mac desktop results in empty .csv

### ISSUE THREAD

**Issue by danwalkowski** [bitwarden/desktop#101]
exporting  data to Mac desktop results in empty .csv ( file )s

**Comment by kspearrin** [comment]
How are you exporting data? This option does not yet exist in the desktop app?

**Comment by danwalkowski** [comment]
perhaps I was using the web exporter instead?

**Comment by kspearrin** [comment]
Perhaps. There is a repo for web vault if you want to open an issue there.
