### ISSUE TITLE
Bitwarden's Appx Package Install Button Greyed Out

### ISSUE THREAD

**Issue by Nihal247** [bitwarden/desktop#1010]
## Describe the Bug

I have downloaded Bitwarden appx package, and when I install it, it shows me that Bitwarden is an Untrusted App, and the Install button is greyed out.

## Steps To Reproduce

1. Go to 'https://github.com/bitwarden/desktop'
2. Click on 'Version 1.27.1'
3. Scroll down to 'Bitwarden-1.27.1-x64-store.appx' or 'Bitwarden-1.27.1-x64.appx'
4. Click on it to download

## Expected Result

Showing Bitwarden is a Trusted App and the Install button shouldn't be greyed out.

## Actual Result

Showing Bitwarden is an Untrusted App and the Install button is greyed out.

## Screenshots or Videos

![Screenshot (100)](https://user-images.githubusercontent.com/80682093/127969065-16f19c8d-005c-4739-89d0-cc684a15ae1b.png)

## Environment

- Operating system: Windows 10 Home Single Language (10.0.19043.1151)
- Installation method: Bitwarden's Desktop Github Repository 
- Build Version: 1.27.1

**Comment by SergeantConfused** [comment]
Hi @Nihal247,

This is the package that is offered through the Microsoft Store, and it's designed to be installed from it. Alternatively, you can install the Bitwarden desktop client using the .exe file, if you'd rather not use the Microsoft Store.

Please do not hesitate to let me know if you have any questions.

**Comment by Nihal247** [comment]
Thanks @SergeantConfused, but why it shows Bitwarden an Untrusted App?

**Comment by kspearrin** [comment]
> 
> 
> Thanks @SergeantConfused, but why it shows Bitwarden an Untrusted App?

@Nihal247 Because the app is not signed by Microsoft, which happens when it is distributed through the Windows Store.

**Comment by Nihal247** [comment]
Thanks @kspearrin
