### ISSUE TITLE
Auto-fill breaks CAPTCHA

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/desktop#1014]
Auto-fill breaks CAPTCHA

## Describe the Bug

Using Auto-fill causes CAPTCHA to fail. User ca’t login.

## Steps To Reproduce

1. Go to (many websites including) https://www.hilton.com/en/ or https://enterprise.ascap.com/mylicense/glslogin.aspx
2. Click on enter login credentials via auto-fill Safari extension or via auto-fill on page load enabled
3. auto-fill interferes with CAPTCHA

## Expected Result

User able to complete CAPTCHA

## Actual Result

User is unable to complete CAPTCHA

"Error: Invalid API parameter(s). Try reloading the page.
I'm not a robot
reCAPTCHA"

## Screenshots or Videos

![Screen Shot 2021-08-04 at 5 14 07 PM](https://user-images.githubusercontent.com/68088552/128271578-3471993f-0438-4ebf-989a-069e0a32fc16.png)

## Environment

- Operating system: macOS 11.5.1
- Installation method: Mac App Store 
- Build Version
-    App: Version 1.25.1 (518)
-    Safari extension: Version: 1.49.1

## Additional Context

This is new behavior. No search results for CAPTCHA

**Comment by eliykat** [comment]
Thanks for reporting this issue. We know that autofill doesn't work consistently for all sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

Also, please ensure that any issues with the browser extension are submitted to the [browser repo](https://github.com/bitwarden/browser).
