### ISSUE TITLE
Bitwarden process don't exit after unlocking Bitwarden edge/chrome extension by Windows Hello PIN

### ISSUE THREAD

**Issue by tqjason** [bitwarden/desktop#1016]
Bitwarden process don't exit after Unlock Bitwarden edge/chrome extension by windows Hello PIN

## Describe the Bug

Bitwarden process that is spawned when unlock Bitwarden edge/chrome extension by Windows Hello PIN don't exit after edge/chrome closed.
And parent edge/chrome process in the same process tree don't exit either.

They should be exit I think.

## Steps To Reproduce

1. Click on Bitwarden edge/chrome extension icon
2. Click on 'Unlock with biometrics'
3. Type PIN in windows hello dialog to unlock Bitwarden extension
4. then close edge/chrome browser
5. find the remaining Bitwarden process in taskmgr

## Screenshots or Videos

![processtree](https://user-images.githubusercontent.com/37337136/128819064-13d4746d-8500-4bb1-b075-262265114f8d.jpg)

## Environment

- Win10 20H2
- Bitwarden v1.27.1
- Bitwarden edge/chrome extension v1.51.1

**Comment by Hinton** [comment]
@tqjason In the provided screenshot `msedge.exe` is still running. Is this still an issue when all browsers with the extension installed are completely closed?

If so this is most likely a bug in Chromium and it would be more appropriate to file it against Chromium directly. Since there's not much we can do on our end.

**Comment by Hinton** [comment]
Quick update. I've managed to duplicate the bug on Edge and found an article suggesting we should exit the process ourself, when `stdin` is closed. It seems chrome handles this for us which is why I was initially confused.

**Comment by tqjason** [comment]
> In the provided screenshot `msedge.exe` is still running
yes, that happened after I closed edge/chrome totally.
the whole `msedge.exe`  process tree exited after I killed the bitwarden process in taskmgr.

Actually,  bitwarden process as native messaging proxy should exit  immediately after using. no need to wait all edge/chrome closed.

**Comment by Hinton** [comment]
@tqjason Thanks for reporting this. I've merged the fix, unfortunately it missed the merge window for the upcoming release but it should be included in the next.
