### ISSUE TITLE
Bitwarden will interfere the system security input on MacOS

### ISSUE THREAD

**Issue by nico-zck** [bitwarden/desktop#1023]
## Describe the Bug
Bitwarden works good, however, it will lock the "system security input" and then cause other apps become dysfunctional.

### Alfred 4
The first victim is Alfred 4, which has a feature to replace the currently typed text by a certain string pattern. But when I started Bitwarden, this feature will be  disfunction, and when I quit the Bitwarden it will return to work quickly. I also found that Alfred 4 will gives out a warning when it detects the disfunction:
![image](https://user-images.githubusercontent.com/10665923/129502325-31cd7545-98fa-4d35-8a89-c1a01c04db61.png)
It only shows on which application this function fail to run, such as iTerm or other apps. So please ignore this hint.

### Logi Options and Logi devices
The second victim is Logi Options. When the above problem happened, my Logi mouse and keyboard also lose the key mapping configure, such as the  preferred direction of scroll wheel and other settings. 
The most unbearable thing is this problem also prevent the Logi Options to find new device if I try to unpair and pair them again.

### My  speculation
I guess Bitwarden will lock security input in consideration of security, however, it will not release the related resource even Bitwarden runs in the background, thus make other apps fail to allocate.
Actually, I think other apps requiring "accessibility" will also be affected by Bitwarden.  But it is very hard to discern the source of this problem.
![image](https://user-images.githubusercontent.com/10665923/129502295-f78bb74c-89cf-4bb9-8460-5e087edab6a3.png)

### Others 
After I had been struggling with this problem for months, I can ensure this is caused by Bitwarden, at least on my Mac.
At first, I thought this problem was caused by the defaults of Big Sur, so I tried restart Mac and even reinstalled the whole Mac, however, this problem still persistent. Finally, I found Bitwarden is the true culprit of this problem, when I quit Bitwarden and the problem disappeared.
I cannot guarantee under what circumstances this problem will happen, but after I use it for a period of time, this problem will appear, and then I quit Bitwarden and the problem will be resolved.

## Environment
- Operating system: Mac OS Big Sur (x86)
- Installation method:  Mac App Store
- Build Version (go to "Settings" → "About"): 1.27.1 (531)

**Comment by eliykat** [comment]
Hi @nico-zck, thanks for taking the time to report this. This issue has already been reported in #298 and was fixed in #970. The fix will be in the upcoming release, which is expected in the next week or two. Keep an eye out, and if the problem persists after upgrading, please ping me in #298 so I can follow up.

**Comment by nico-zck** [comment]
Thanks @eliykat, I'm glad to hear this problem has been solved.
