### ISSUE TITLE
Shift+Alt brings up the "File" menu

### ISSUE THREAD

**Issue by kotek14** [bitwarden/desktop#103]
Every time I'm changing the keyboard layout with the combination "Shift+Alt" the vault brings up the File menu. I did not find any option to disable that shortcut or any shortcuts in general.

OS: Xubuntu 18.04

Vault:
```Version 1.2.0
Shell 1.8.4
Renderer 59.0.3071.115
Node 8.2.1
Architecture x64

**Comment by riptide-dev** [comment]
@ssgibnev Is this still occuring in the latest version:

Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

**Comment by ssgibnev** [comment]
@fireandtide-dev 
Yes. Checked it right now

Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64
