### ISSUE TITLE
Syncing failed after update to 1.28.0

### ISSUE THREAD

**Issue by mvilleneuvenormand** [bitwarden/desktop#1033]
## Describe the Bug
Since 1.28.0 I'm unable to sync using the Windows Desktop app on my self hosted 1.41.5 (Latest version available since 1.42 not released yet on self hosted). When I downgrade to 1.27.1 it works fine.

## Steps To Reproduce
Update the windows app to 1.28.0 and click sync.

## Expected Result
Sync my vault.

## Actual Result
Syncing failed red message.

## Screenshots or Videos
Not needed

## Environment

- Operating system: Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version (go to "Settings" → "About"): 1.28.0

## Additional Context
Working with chrome extension and iOS app.

**Comment by eliykat** [comment]
Thanks for the report @mvilleneuvenormand, I've been able to reproduce and will raise it with the team for a fix.

**Comment by mase1981** [comment]
Same, thanks to the team for looking into this.

**Comment by Hinton** [comment]
We've merged the hotfix into jslib, and it will be included in the pending hotfix which should be available shortly.
