### ISSUE TITLE
Desktop client 2FA login broken

### ISSUE THREAD

**Issue by jokey2k** [bitwarden/desktop#1036]
## Describe the Bug

Desktop client on Windows 10 stops working after upgrade from 1.27.1 to 1.28.0 when 2FA and self-hosted environment is used.
Login using U2F Yubi fails, 2FA Yubi works but the sync afterwards empties local storage of passwords.

## Steps To Reproduce

1. Remove %appdata%\Bitwarden to ensure clean install
2. Install 1.28.0
3. Click Settings to update server url
4. Login using mailadress and masterpassword
5. Wait for Webauthn popup to appear

## Expected Result

See windows dialog "push key on security device"

## Actual Result

"Webauthn" Button is small, has no text in it and reports "Parse error"

## Screenshots or Videos

<img width="840" alt="bitwarden1 27 1" src="https://user-images.githubusercontent.com/248585/130267587-8e5903f9-30bc-4e96-a822-ccfeb45f9653.png">
<img width="715" alt="bitwarden1 28 0" src="https://user-images.githubusercontent.com/248585/130267590-80fd7540-787b-49e8-9b31-ad8440aa1030.png">

## Environment

- Operating system: Windows 10
- Installation method: Downloaded from Bitwarden.com (1.28.0)

## Additional Context

Using steps above to install https://github.com/bitwarden/desktop 1.27.1 and everything works fine again
Server version is installed using bitwarden.sh 1.41.5, Docker Version 20.10.7, docker-compose 1.29.2, updated to most recent version

**Comment by luc-bw** [comment]
Hi @jokey2k

Thank you for the report. This issue has been addressed with the [following PR](https://github.com/bitwarden/jslib/pull/462).

**Comment by cscharf** [comment]
This is now resolved with the latest version, https://github.com/bitwarden/desktop/releases/tag/v1.28.1 (please let us know if it is still an issue for you)

**Comment by jokey2k** [comment]
Yep, has been resolved, works again, thanks for the quick response :)

**Comment by prometheanfire** [comment]
@cscharf running 1.28.2, should I expect u2f/webauthn login to work on linux, or is this windows only?

**Comment by eliykat** [comment]
@prometheanfire WebAuthn on the desktop client is currently only available for Windows ([source from our help docs](https://bitwarden.com/help/article/setup-two-step-login-fido/)). I believe Electron is missing support for other platforms (mentioned [here](https://github.com/electron/electron/pull/28349) and [here](https://github.com/electron/electron/issues/27355)).
