### ISSUE TITLE
v1.28 not syncing with self hosted site

### ISSUE THREAD

**Issue by philreck** [bitwarden/desktop#1037]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: Windows 10 Pro x64 
- Installation method: automatic update by bitwarden desktop app v1.27
- Build Version 19042.1165

**Comment by luc-bw** [comment]
Hi @philreck 

Thank you for the report. Thank you for the report. This issue has been addressed with the [following PR](https://github.com/bitwarden/jslib/pull/461).

**Comment by jw-afc** [comment]
@philreck I had the same problem.  I suspect you may need to update your self-hosted server.  For whatever reason, the bitwarden.ps1 server update script references older versions of the core and web so doing -updateself and -update doesn't actually update your server to the latest version.  

I manually changed the version numbers in the script and ran the update which fixed the issue.  You can get the latest versions numbers via the admin portal - currently core 1.42.1 and web 2.22.1.

https://github.com/bitwarden/server/blob/74218d46396a7b64fa92b4dd0a72d776fd0966b3/scripts/bitwarden.ps1#L29

**Comment by cscharf** [comment]
This is now resolved with the latest version, https://github.com/bitwarden/desktop/releases/tag/v1.28.1 (please let us know if it is still an issue for you)
