### ISSUE TITLE
Windows application skips 2-factor authentication (2FA)

### ISSUE THREAD

**Issue by riess82** [bitwarden/desktop#1039]
## Steps To Reproduce

1. Log in and enter password.
2. To make sure, use logout, so that the account is not simply locked.
3. Log in again. No 2fa is requested.
4. I counter-checked using the web access, there the 2fa is requested after the password input.

## Expected Result
Working 2fa in windows client.

## Actual Result

Login complete after password.

## Environment

- Operating system: Win 10
- Installation method: self hosted bitwarden server, version 1.38.2-1
- Build Version 1.28.1

**Comment by eliykat** [comment]
Hi @riess82, can you confirm that you haven't previously clicked "Remember me" in the 2FA screen? That would cause you to skip the 2FA screen in the future on that device.

To make sure, please log out & exit your Bitwarden application, then clear your local storage (see [here](https://bitwarden.com/help/article/data-storage/) for a list of locations). Try to log in again and let me know whether you are presented with the 2FA screen.

**Comment by riess82** [comment]
I deleted %AppData%\Bitwarden\Local Storage\leveldb\* as suggested. Still no 2FA.

Using Authy, which works fine in web and Firefox-Extension. It had been working in the Windows Application as well until 1 or 2 updates ago, unfortunately I do not know exactly when it stopped working.

**Comment by Hinton** [comment]
Hello @riess82. It sounds like you've accidentally selected `remember me`, which means you won't get prompted on the same device for 30 days. This can be manually cleared by deleting the `data.json` in `%AppData%\Bitwarden`. Note this will reset *all* settings of the desktop application.

For future support feel free to contact our customer support at https://bitwarden.com/contact/ and our customer support team will be happy to assist you.

**Comment by riess82** [comment]
Deleting the data.json in %AppData%\Bitwarden solved the problem. Thank you very much for your help.
