### ISSUE TITLE
Can't open Bitwarden: white window

### ISSUE THREAD

**Issue by cloclo9** [bitwarden/desktop#1043]
![Capture bitwarden](https://user-images.githubusercontent.com/89463784/130625090-c8caae40-fe3e-4e47-ad2d-a47f73520159.JPG)

## Describe the Bug
Hi, 
I'm French sorry for mistakes.
When I open Bitwarden, the window stay white and doesn't become grey as usual to enter our e-mail address and key word.
I can't go on it since 2 days. 
How can I do ?

Thank you for your help.

## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by Greenderella** [comment]
Will you first try uninstalling the application, removing any leftover data, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/article/data-storage/#on-your-local-machine
Let me know if that helps.
