### ISSUE TITLE
Black screen on startup Pop Os

### ISSUE THREAD

**Issue by PixsaOJ** [bitwarden/desktop#1045]
## Describe the Bug

On startup, Bitwarden is just black screen. I can not quit it by clicking quit window or X button which is in my overview screen.

## Steps To Reproduce

1. Install the latest Bitwarden from Flatpak
2. Check that you have startup script:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bitwarden --file-forwarding com.bitwarden.desktop @@u %U @@`
3. Reboot your computer or shut down and turn back on.

## Expected Result

Bitwarden starts normally

## Actual Result

I only see a black rectangle 

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/12684017/130744287-4066141a-c0ed-4ac0-a148-f6c346f75465.png)

## Environment

OS info:
```
OS: Pop!_OS 21.04 x86_64
CPU: Intel i5-8300H (8) @
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
DE: GNOME
WM: Mutter
Kernel: 5.11.0-7620-generic
```

Installed from Flatpak
![image](https://user-images.githubusercontent.com/12684017/130617480-ef58ee5d-a378-4912-a8ca-038fff663add.png)

## Additional Context
It has been like that for months...

I have latest and greatest Nvidia drivers installed.

`Journalctl -xe` output:

When I click quit while bugged out:
```
Aug 24 16:20:38 undefined gnome-shell[7176]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x56539afc3060), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug 24 16:20:38 undefined gnome-shell[7176]: == Stack trace for context 0x565399b481e0 ==
Aug 24 16:20:38 undefined gnome-shell[7176]: #0   56539d413550 i   resource:///org/gnome/shell/ui/panel.js:119 (1ae3469688d0 @ 56)
Aug 24 16:20:38 undefined gnome-shell[7176]: #1   56539d4134c8 i   resource:///org/gnome/shell/ui/panel.js:112 (1ae346968920 @ 13)
```

When I click new window and it fixes itself:
```
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 742.
Aug 24 16:24:28 undefined systemd[2668]: app-gnome-com.bitwarden.desktop-13870.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit UNIT has successfully entered the 'dead' state.
Aug 24 16:24:28 undefined com.bitwarden.desktop.desktop[13886]: [2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
Aug 24 16:24:28 undefined systemd[2668]: Started app-flatpak-com.bitwarden.desktop-13896.scope.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 746.
Aug 24 16:24:28 undefined com.bitwarden.desktop.desktop[13886]: (node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
Aug 24 16:24:28 undefined com.bitwarden.desktop.desktop[13886]: Gtk-Message: 16:24:28.989: Failed to load module "appmenu-gtk-module"
Aug 24 16:24:29 undefined com.bitwarden.desktop.desktop[13886]: Gtk-Message: 16:24:29.027: Failed to load module "canberra-gtk-module"
Aug 24 16:24:29 undefined com.bitwarden.desktop.desktop[13886]: Gtk-Message: 16:24:29.027: Failed to load module "canberra-gtk-module"
Aug 24 16:24:29 undefined systemd[2668]: app-flatpak-com.bitwarden.desktop-13896.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit UNIT has successfully entered the 'dead' state.
Aug 24 16:24:29 undefined systemd[2668]: app-flatpak-com.bitwarden.desktop-13870.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit UNIT has successfully entered the 'dead' state.
```

**Comment by eliykat** [comment]
The Flatpak repo is community maintained and is not officially supported. Please download an official release and see if that fixes the issue. 

If the problem persists, please contact our Customer Success team for further assistance. You can contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by PixsaOJ** [comment]
@eliykat Is snap package official?

**Comment by eliykat** [comment]
Yes. You can see the officially supported installation sources here: https://bitwarden.com/download/ (click "more desktop installation options").
