### ISSUE TITLE
Flatpak listing

### ISSUE THREAD

**Issue by Loki-L1130** [bitwarden/desktop#1049]
Why Flatpak package is not listed under Releases of this Github Repo & it is also not listed under Bitwarden [Download](https://bitwarden.com/download/) under More Desktop Installation Options ?

**Comment by djsmith85** [comment]
Hi @Loki-L1130 thank you for reaching out. 

The flatpak release is a unofficial distribution of Bitwarden, which is managed by community members. As we do not build/distribute/support this release it is not included on our release/download page.

We have asked the distributers to disclaim this here:
https://github.com/flathub/com.bitwarden.desktop/issues/76
