### ISSUE TITLE
SECCOMP audit messages reported to syslog on Ubuntu 18.04 (snap version 1.20)

### ISSUE THREAD

**Issue by jamesbo13** [bitwarden/desktop#105]
Running snap version 1.2 on Ubuntu 18.04 the following messages are sent to syslog on a frequent basis (700+ times over ~8 hours time)

```
Jun 20 15:12:39 myhost kernel: [ 3863.700286] audit: type=1326 audit(1529532759.867:376): auid=1000 uid=1000 gid=1000 ses=3 pid=9952 comm="bitwarden" exe="/snap/bitwarden/4/app/bitwarden" sig=0 arch=c000003e syscall=92 compat=0 ip=0x7f826f324307 code=0x50000
Jun 20 15:12:40 myhost kernel: [ 3863.911282] audit: type=1326 audit(1529532760.079:377): auid=1000 uid=1000 gid=1000 ses=3 pid=9952 comm="bitwarden" exe="/snap/bitwarden/4/app/bitwarden" sig=0 arch=c000003e syscall=92 compat=0 ip=0x7f826f324307 code=0x50000
Jun 20 15:12:40 myhost kernel: [ 3864.663436] audit: type=1326 audit(1529532760.831:378): auid=1000 uid=1000 gid=1000 ses=3 pid=9952 comm="bitwarden" exe="/snap/bitwarden/4/app/bitwarden" sig=0 arch=c000003e syscall=92 compat=0 ip=0x7f826f324307 code=0x50000
Jun 20 15:12:56 myhost kernel: [ 3880.666447] audit: type=1326 audit(1529532776.835:379): auid=1000 uid=1000 gid=1000 ses=3 pid=9952 comm="bitwarden" exe="/snap/bitwarden/4/app/bitwarden" sig=0 arch=c000003e syscall=92 compat=0 ip=0x7f826f324307 code=0x50000
```
`type=1326` indicates a SECCOMP issue (see https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/audit.h).

`syscall=92` correlates to the `chmod()` syscall (see https://elixir.bootlin.com/linux/v3.0/source/arch/x86/include/asm/unistd_64.h)

Running strace against a running copy of bitwarden shows the following (personal info obscured):

```
xxxx@myhost:~$ sudo strace -p 9952 -e chmod 
strace: Process 9952 attached
chmod("/home/xxxx/snap/bitwarden/4/appdata/data.json.3442461127", 0100664) = 0
chmod("/home/xxxx/snap/bitwarden/4/appdata/data.json.1167817458", 0100664) = 0
```
I suspect there is some permissions issue related to snaps and/or the chrome sandboxing that is causing these errors. I don't see the referenced files in the paths given so I suspect they are temporary files that are then moved atomically to appdata/data.json. That file has permissions 0664.

**Comment by jamesbo13** [comment]
Installed deb package 1.3.0 from alternate downloads page and ran directly from command line (to ensure did not run snap version instead). After approximately 10 minutes of running (including modifying some entries), no audit messages reported to syslog. (Using snap version there would be several per minute)

Seems likely either related to snap packaging or the older version 1.2.0.

**Comment by kspearrin** [comment]
I don't know a whole log about snaps. We just package the app with a tool called [electron-builder ](https://github.com/electron-userland/electron-builder). I'm certain that this is related to the snap packaging and not 1.3.0.

@popey Do you have any idea what this is about?

**Comment by jamesbo13** [comment]
One error in my analysis ... syscall=92 is chown not chmod. 

Looked at the seccomp profile installed for (bitwarden/var/lib/snapd/seccomp/bpf/snap.bitwarden.bitwarden.src) and saw:
```
# snappy doesn't currently support per-app UID/GIDs. All daemons run as 'root'
# so allow chown to 'root'. DAC will prevent non-root from chowning to root.
chown - u:root g:root
chown32 - u:root g:root
fchown - u:root g:root
fchown32 - u:root g:root
fchownat - - u:root g:root
lchown - u:root g:root
lchown32 - u:root g:root
```
Rerunning with strace and looking for chown output I see:
```
[pid 14653] chown("/home/xxx/snap/bitwarden/4/appdata/data.json.1549114313", 1000, 1000) = -1 EPERM (Operation not permitted)
```

Looks like it is trying to change the owner/group of the file to my uid/gid but is being disallowed.

**Comment by jamesbo13** [comment]
Appears to be a known issue with snaps. Some relevant links:

- [Snapcraft forum - Chown to current user](https://forum.snapcraft.io/t/chown-to-current-user/2831)
- [Snapcraft forum - Multiple users and groups in snaps](https://forum.snapcraft.io/t/multiple-users-and-groups-in-snaps/1461)
- [Snapcraft forum - Strict Mode SECCOMP policy violations ...](https://forum.snapcraft.io/t/strict-mode-seccomp-policy-violations-now-set-errno-to-eperm-instead-of-killing-the-process/4397)

Workarounds mentioned seem to point to remove chown from executed code or using a form of library preload. Did some digging through bitwarden code but didn't see any direct calls to chown so I suspect somewhere in included node libraries there is something calling it during a write-rename operation:

```
[pid 14653] open("/home/xxxx/snap/bitwarden/4/appdata/data.json.1549114313", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0100664) = 25
[pid 14653] pwrite64(25, "{\n\t\"lockOption\": 5,\n\t\"mainWindow"..., 48760, 0) = 48760
[pid 14653] madvise(0x36c549730000, 1466368, MADV_DONTNEED) = 0
[pid 14653] fsync(25)                   = 0
[pid 14653] close(25)                   = 0
[pid 14653] chown("/home/xxxx/snap/bitwarden/4/appdata/data.json.1549114313", 1000, 1000) = -1 EPERM (Operation not permitted)
[pid 14653] getuid()                    = 1000
[pid 14653] chmod("/home/xxxx/snap/bitwarden/4/appdata/data.json.1549114313", 0100664) = 0
[pid 14653] rename("/home/xxxx/snap/bitwarden/4/appdata/data.json.1549114313", "/home/xxxx/snap/bitwarden/4/appdata/data.json") = 0
[pid 14653] rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
[pid 14653] read(7, "*", 1)             = 1
```

**Comment by kspearrin** [comment]
Maybe caused by this line?

https://github.com/bitwarden/jslib/blob/master/src/services/lowdbStorage.service.ts#L21
https://github.com/bitwarden/jslib/blob/master/src/misc/nodeUtils.ts#L11

This is the code that deals with that `appdata/data.json` file in the stack trace.

**Comment by jamesbo13** [comment]
I don't doubt it is lowdbStorage or its dependencies but not sure it is the lines pointed out. That looks to be more chmod than chown related. (apologize again for misdiagnosing the syscall originally)

**Comment by thakyZ** [comment]
I am getting this as well on Windows through the Event Logs. It's quite annoying.
The two "TargetNames" are Bitwarden/key and Bitwarden_auto/key

Here are the event log XML files
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}"/>
    <EventID>5379</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>13824</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8020000000000000</Keywords>
    <TimeCreated SystemTime="2021-11-14T18:28:50.6245473Z"/>
    <EventRecordID>32128</EventRecordID>
    <Correlation ActivityID="{6ad2b3b6-d97b-000a-4eb4-d26a7bd9d701}"/>
    <Execution ProcessID="688" ThreadID="708"/>
    <Channel>Security</Channel>
    <Computer>COMPUTER</Computer>
    <Security/>
  </System>
  <EventData>
    <Data Name="SubjectUserSid">WindowsUID</Data>
    <Data Name="SubjectUserName">USER</Data>
    <Data Name="SubjectDomainName">COMPUTER</Data>
    <Data Name="SubjectLogonId">0x128d86</Data>
    <Data Name="TargetName">Bitwarden_auto/key</Data>
    <Data Name="Type">1</Data>
    <Data Name="CountOfCredentialsReturned">1</Data>
    <Data Name="ReadOperation">%%8099</Data>
    <Data Name="ReturnCode">3221226021</Data>
    <Data Name="ProcessCreationTime">2021-11-14T17:17:58.3936219Z</Data>
    <Data Name="ClientProcessId">5292</Data>
  </EventData>
</Event>
```
and
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}"/>
    <EventID>5379</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>13824</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8020000000000000</Keywords>
    <TimeCreated SystemTime="2021-11-14T18:29:00.6234835Z"/>
    <EventRecordID>32129</EventRecordID>
    <Correlation ActivityID="{6ad2b3b6-d97b-000a-4eb4-d26a7bd9d701}"/>
    <Execution ProcessID="688" ThreadID="708"/>
    <Channel>Security</Channel>
    <Computer>COMPUTER</Computer>
    <Security/>
  </System>
  <EventData>
    <Data Name="SubjectUserSid">WindowsUID</Data>
    <Data Name="SubjectUserName">USER</Data></Data>
    <Data Name="SubjectDomainName"></Data>
    <Data Name="SubjectLogonId">0x128d86</Data>
    <Data Name="TargetName">Bitwarden/key</Data>
    <Data Name="Type">1</Data>
    <Data Name="CountOfCredentialsReturned">1</Data>
    <Data Name="ReadOperation">%%8099</Data>
    <Data Name="ReturnCode">3221226021</Data>
    <Data Name="ProcessCreationTime">2021-11-14T17:17:58.3936219Z</Data>
    <Data Name="ClientProcessId">5292</Data>
  </EventData>
</Event>
```
