### ISSUE TITLE
Boolean custom fields cannot be set to true except in web vault

### ISSUE THREAD

**Issue by anonymouse3** [bitwarden/desktop#106]
Both the desktop application and the browser extension throw an error when trying to save an item that has a boolean custom field set to true. The web vault has no trouble.

Specific error message (from developer tools):

```
TypeError: Failed to execute 'encrypt' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'
```

I have been able to reproduce this 100% of the time, on all different types of items. It's not a huge problem, but it is something I would like to see fixed.

**Comment by kspearrin** [comment]
Thanks. I can now confirm the fix came two days after the release, so it will be fixed in the next version.

**Comment by MasterJames** [comment]
I am getting this in 11.7
