### ISSUE TITLE
Right click copy password does not minimise the first time after initial launch

### ISSUE THREAD

**Issue by keeneye** [bitwarden/desktop#1077]
### Steps To Reproduce

1. Ensure 'minimise on copy password' is on in settings
2. Exit the app on Windows
2. Re-launch the app
3. Right click on an item and copy its password - the app will stay on screen
4. Then click on the item and use the password copy link in it - the app will minimise
5. After this, right click and copy password will minimise correctly

### Expected Result

App should mimimise

### Actual Result

App stays on screen (until you've used the other 'copy password' method

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.2

**Comment by ArthurWolfhound** [comment]
Adding in to that issue (I have it too). Actually "copy password" with right-click does not require you to use the copy within the entry details. It wants you to click on the element itself (so details would be displayed in the right-pane) to be working properly.

### Operating System Version
Edition: Windows 11 Home
Version: 21H2
OS build: 22000.348
Experience: Windows Feature Experience Pack 1000.22000.348.0

### Build Version
Version 1.29.1
Shell 14.0.1
Renderer 93.0.4577.63
Node 14.17.0
Architecture x64
