### ISSUE TITLE
"Never lock" option doesn't work on Linux

### ISSUE THREAD

**Issue by vhborges** [bitwarden/desktop#108]
I have Bitwarden Desktop both on Windows and Manjaro Linux, but although I've set the "Lock options" to "never" on both, every time I start the Linux version it asks me for the master password, while the Windows version never does.

**Comment by kspearrin** [comment]
Do you have the GNOME keyring available? You need libsecret to securely store the key.

**Comment by vhborges** [comment]
@kspearrin 
I use KDE as my desktop environment, do I still need gnome keyring? I mean... is there any way I can use KDE Wallet instead?

As for libsecret, I already have it installed.

**Comment by kspearrin** [comment]
This is the library we use for managing secrets:

https://github.com/atom/node-keytar

>  on Linux they are managed by the Secret Service API/libsecret

Looks like an issue here about it on KDE:
https://github.com/atom/node-keytar/issues/74

**Comment by vhborges** [comment]
@kspearrin 
Thanks for clarifying. I installed gnome-keyring and it's now working as expected. I'll keep an eye on that issue you mentioned.

You can close this now if you want.
