### ISSUE TITLE
MacOS universal .pkg file + application cannot be opened once installed

### ISSUE THREAD

**Issue by danielkean** [bitwarden/desktop#1090]
### Steps To Reproduce

1. Download 'Bitwarden-{version}-universal.pkg
2. Attempt to open the .pkg file without right-clicking

OR

1. Open .pkg file using right-click -> 'Open' method
2. Once installed, attempt to open the application

### Expected Result

The .pkg file should be able to be opened without using the right-click method, and the application should be able to be opened once installed.

### Actual Result

The application does not open and a popup saying "You do not have permission to open the application 'Bitwarden'" appears. The .pkg file can also not be opened unless you right-click, and then click 'open'.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/64756591/134799896-d3cd63b9-1803-4a38-b974-f18b641d38c3.png)
![image](https://user-images.githubusercontent.com/64756591/134800391-0967ef2f-4d9c-45ac-babe-97eb46aaf53f.png)

### Additional Context

This was discovered after my pull request to implement the universal binary for the Homebrew package manager was merged. The merge is in the process of being reversed.

### Operating System

macOS

### Operating System Version

11.6

### Installation method

Homebrew, Other

### Build Version

1.28.3

**Comment by eliykat** [comment]
This is reproducible and I've asked our devOps team to look into how/if we're signing the `pkg` releases.

**Comment by dolphinjoke** [comment]
@danielkean You have Rosetta 2 installed? There is another issue #1046 regarding the universal pkg that prevent the pkg to be installed on aarch64 macs without rosetta2.

**Comment by danielkean** [comment]
@eliykat Thanks for looking into it.

@dolphinjoke Hi there, I have Rosetta 2 installed so I don't think that is the cause of the issue, but rather something to do with the signing process of the `pkg` files. Thanks for your suggestion though.

**Comment by dolphinjoke** [comment]
@danielkean Yes, it's not the issue of the ticket or the signing process, but a blocker for using the pkg with homebrew cask.

**Comment by danielkean** [comment]
@dolphinjoke Sorry I'm not sure what you mean, the steps involved in this issue don't actually require installing through Homebrew but is using the .pkg file straight from the GitHub 'releases' page. I might just be misunderstanding your message.

**Comment by Hinton** [comment]
Hi,

This is the expected behavior. The `universal-pkg` release is the Mac App Store artifact that gets published to Mac App Store and can only be installed from the App Store. It's published as part of the release for traceability, but can't actually be run.

I'll investigate if we can be more explicit about this on the release page to avoid confusion.
