### ISSUE TITLE
Unexpected token < in JSON at position 0 (Windows 10 Client & Linux selfhosted)

### ISSUE THREAD

**Issue by kangaroo72** [bitwarden/desktop#1096]
### Steps To Reproduce

Fresh installation of Bitwarden Client for Windows.
Typed in own server
Typed in EMail and Password

### Expected Result

The app should start without problems

### Actual Result

![grafik](https://user-images.githubusercontent.com/6906390/135473750-e9f3b011-e05c-4f1d-80cf-87e092ba97dc.png)

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/6906390/135473405-9f8f85cf-a0fa-4b9e-8336-80e2bc7daa53.png)

### Operating System

Windows

### Operating System Version

Windows 10 Professional 21H1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.3

**Comment by kspearrin** [comment]
What server version are you using?

**Comment by kangaroo72** [comment]
![grafik](https://user-images.githubusercontent.com/6906390/135474585-dab6d332-ecbe-4f03-a329-05d6e68c76cd.png)

**Comment by kspearrin** [comment]
Looks like you are using Vaultwarden. I would bring this issue up with that project since it appears to be unrelated to the client app.
