### ISSUE TITLE
2FA on Desktop App Gone

### ISSUE THREAD

**Issue by blizzyblake278** [bitwarden/desktop#1098]
### Steps To Reproduce

Login w/ Master password
Goes straight to Vault

### Expected Result

2FA screen should have asked for 2FA code

### Actual Result

Once the master password was entered it no longer asked for my 2FA code. It will do it on the web app however though, just not the desktop version. 

### Operating System

Windows

### Operating System Version

21H1 19043.1237

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.3

**Comment by SergeantConfused** [comment]
Hi @blizzyblake278,

It sounds like you may have accidentally toggled 'Remember me' on your Bitwarden Desktop client's 2FA prompt. Please follow this: https://bitwarden.com/help/article/twostep-faqs/#q-why-is-bitwarden-not-asking-for-my-enabled-two-step-login-method and Deauthorize all your sessions. If that does not help, please get in touch with us using this form: https://bitwarden.com/contact/ and we'll proceed in assisting you with this.


Thank you in advance,

**Comment by blizzyblake278** [comment]
> Hi @blizzyblake278,
> 
> It sounds like you may have accidentally toggled 'Remember me' on your Bitwarden Desktop client's 2FA prompt. Please follow this: https://bitwarden.com/help/article/twostep-faqs/#q-why-is-bitwarden-not-asking-for-my-enabled-two-step-login-method and Deauthorize all your sessions. If that does not help, please get in touch with us using this form: https://bitwarden.com/contact/ and we'll proceed in assisting you with this.
> 
> Thank you in advance,

Yes that did work. Thank you so much! I don't know how I missed that FAQ either. But thank you.
