### ISSUE TITLE
Passphrase generation enforces non-empty word separator

### ISSUE THREAD

**Issue by alanfranz** [bitwarden/desktop#1099]
### Steps To Reproduce

1. Create new item by pressing +
2. Click the "generate password" button
3. Choose options
4. Choose "Passphrase"
5. Check the "Word Separator" field content. It should be empty. If it is not empty, remove any content from it.

### Expected Result

When the "word separator" field is empty, I'd expect the generated passphrase to have no whitespace or other separator.

### Actual Result

The generated passphrase has whitespace as a word separator.

### Screenshots or Videos

<img width="299" alt="image" src="https://user-images.githubusercontent.com/230827/136211524-b5ccf4b7-4e03-4988-88ff-90eca6948939.png">

### Additional Context

There seems to be no way to remove the standard whitespace. As tedious as it is, I can still find a lot of websites that don't accept passwords with whitespace in it, so my way-to-go is usually to generate a CamelCasePasswordWith1NumberInIt .

But I cannot remove the whitespace when generating the password with bitwarden.

I'll be happy to investigate and contribute the bugfix, I'd just like to be sure that this is not a deliberate design decision.

### Operating System

macOS

### Operating System Version

10.14.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.3 (535)

**Comment by alanfranz** [comment]
Thanks @eliykat for your answers. Some notes:

> I believe it's because without a separator, words from the wordlist could combine in ways that cause duplicate results, which would decrease the randomness of the generated passwords.

Mmh, I'm not sure about whether this is meaningful. Sure, there could be some combinations (when NOT using CamelCase of course) where some word combination happens to match even another word combination, but I doubt it's relevant in the whole passphrase search space. You mean that "for" and "ever" could be matched by a search for "forever"... but how many words randomly combine that way?

And, by the way, the user is allowed to choose camelcase or not, and how many words I'm using, and whether I add a number; so, **it's already me, the user, who chooses how strong their password is**; bitwarden doesn't say anything about that.

Why should bitwarden argue about the missing namespace?

By the way, if that's the real reason and it's compelling (but I beg you to check), I still think it's a bug; in that case, the user should be prevented from making the field empty - it should be a fixed width of 1, and the user should just be able to overwrite whatever char they choose, but not to delete the field content.

Thanks,

Alan

**Comment by eliykat** [comment]
Hey Alan, all good points. I double checked my assumptions and indeed it was just a UX decision, which we can revisit. I'll reopen this so we can track it here.

**Comment by alanfranz** [comment]
Hello @eliykat thanks!

So, what do you think about my original proposal, now? I'd be happy to contribute a patch if there're chances for it to be accept.

To be clear, **I'd retain the same default behaviour as today**; the generation tool would start with a whitespace separator by default, but with the ability to delete it.
