### ISSUE TITLE
Fatal GPU Process Core Dump

### ISSUE THREAD

**Issue by TahomaSoft** [bitwarden/desktop#1115]
### Steps To Reproduce

1. Start bitwarden client for Linux on command line or clicking desktop/menu icon
2. Watch Bitwarden client attempt to run
3. Watch Bitwarden client crash

Seems to be a problem on Fedora 35 with appImage installations and RPM installations. 
Possible problem occurs only if system is running NVIDIA X11 display modules (but not sure).

### Expected Result

Bitwarden for Linux desktop runs normally.

## [Side Note] ##
(node:6401) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:6401) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

# [Main Dump Message] #
**[6401:1017/151245.465403:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.**
**Trace/breakpoint trap (core dumped)**

### Operating System

Linux

### Operating System Version

Fedora 35, various kernel versions

### Installation method

Other

### Build Version

1.28.3-x86_64

**Comment by spstarr** [comment]
as a note run with `-no-sandbox` to get around GPU core dump even if less secure til this is fixed
