### ISSUE TITLE
Javascript error Mac OSX High Sierra Bitwarden v1.28.3

### ISSUE THREAD

**Issue by jblucky13** [bitwarden/desktop#1120]
### Steps To Reproduce

1. Download App from App Store
2. Open
3. Immediate error

A JavaScript error occurred in the main process

### Expected Result

Open and login

### Actual Result

Dialog box opens
A JavaScript error occurred in the main process

Cannot launch into the application

### Screenshots or Videos

![Screen Shot 2021-10-24 at 7 20 58 PM](https://user-images.githubusercontent.com/93104089/138619037-1af17257-1757-4210-a7ce-e5a8eb696b36.png)

### Additional Context

also download from Site and installed from download with same error

### Operating System

macOS

### Operating System Version

10.13.6

### Installation method

Mac App Store

### Build Version

1.28.3

**Comment by eliykat** [comment]
The latest version of the desktop client is incompatible with High Sierra / Safari 13. Please download the frozen legacy version here: https://github.com/bitwarden/desktop/releases/tag/v1.24.7.

If you're still experiencing issues, please contact our Customer Success team here: https://bitwarden.com/contact/
