### ISSUE TITLE
Safari 15.1 integration broken with macOS desktop app 1.29.0

### ISSUE THREAD

**Issue by bfren** [bitwarden/desktop#1126]
### Steps To Reproduce

1. Running macOS Monterey
2. Update to latest Bitwarden version via App Store
3. Safari integration disappears
4. Uninstall / reinstall of Bitwarden app makes no difference

### Expected Result

Bitwarden should appear in list of Safari extensions, Bitwarden button should appear in toolbar

### Actual Result

Bitwarden does not appear anywhere in Safari

### Screenshots or Videos

<img width="739" alt="Screenshot 2021-10-28 at 21 30 47" src="https://user-images.githubusercontent.com/17511478/139331043-ec56a227-899e-4d2c-9e5b-ac65502fe118.png">

### Operating System

macOS

### Operating System Version

12.0.1

### Installation method

Mac App Store

### Build Version

Bitwarden 1.29.0 (1790)
Safari 15.1 (17612.2.9.1.20)

**Comment by iamrecursion** [comment]
For those coming here, the update appears to be out now.

**Comment by zmilonas** [comment]
@kspearrin Thank you for prompt fix for this. Are you planning a post mortem for this by any chance? Seemed like pretty serious "downtime", I had no access to Bitwarden in Safari for something like 2-3 days in total, as a paying customer that seems pretty annoying.

**Comment by zmilonas** [comment]
I'd like to also point out that all preferences seem to be wiped. I had to relogin to the extension and set my settings for autofill, locking/unlocking, matching etc. That's a really bad side effects, isn't it possible to save this settings in a less volatile storage?

**Comment by lexwon01** [comment]
It seems that the Safari extension only allows for WebAuthn ? No Yubico option ?

**Comment by jdsk789** [comment]
I have updated to 1.29.1 but still no extension. Did it fix for you guys?

**Comment by en0mia** [comment]
> I have updated to 1.29.1 but still no extension. Did it fix for you guys?

Same problem, still no extension

**Comment by tgreer-bw** [comment]
So many threads on this topic 🙃

Those who aren't seeing the extension after the 1.29.1 update, please try the following:

1. Run this in the terminal app: `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`
2. Restart Safari
3. Enable Bitwarden

**Comment by ChrisBegley** [comment]
@jdsk789 @en0mia go into Safari's preferences and reactivate the Bitwarden extension. It won't automatically turn back on just by updating the app. You have to log in and set up all your settings again too.

**Comment by edwinh** [comment]
Thanks @tgreer-bw! It worked!

**Comment by bfren** [comment]
Fixed for me, but I had to re-activate it, and it had lost all my settings.

**Comment by mfriedenhagen** [comment]
I am on Big Sur and with the new version the extension does show up again. As others already reported, I had to set up everything from start again (login with 2FA, timeout, password eviction etc.)
