### ISSUE TITLE
Contributing.md is not helpful for first time contributors

### ISSUE THREAD

**Issue by geowarin** [bitwarden/desktop#113]
Hello everyone,

I love BitWarden and I thought I'd try to see if I can contribute (modestly) to the desktop application.
However, I am not able to run the application on my mac.

After running `npm i` and `npm run electron`, I have a blank screen and some Content Security Policies error when loading the index.html file.

Any help would be welcome. Maybe we could then update the CONTRIBUTING file for other noobs like me 😃

**Comment by kspearrin** [comment]
Try running it again with `npm run electron`, sometimes the Google WebFonts plugin causes it not to load on the first try.
