### ISSUE TITLE
Version 1.24.7 geting Unexpected error when launching with MacOS 10.12.6

### ISSUE THREAD

**Issue by NJEric** [bitwarden/desktop#1137]
### Steps To Reproduce

Launch on Mac
insert user name and password
press login

I tried to install latest version of the desktop app but it crashes. So I deleted and installed version 1.24.7

### Expected Result

Login to vault

### Actual Result

see attached screen shot

### Screenshots or Videos

<img width="702" alt="Screen Shot 2021-11-02 at 3 01 00 PM" src="https://user-images.githubusercontent.com/93614443/139928342-1faaef0f-c728-4882-8188-69623f45de11.png">

### Operating System

macOS

### Operating System Version

10.12.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.24.7

**Comment by Greenderella** [comment]
Will you first try uninstalling the application, removing any leftover data, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/article/data-storage/#on-your-local-machine

You can also try to install something like the app OnyX to clear system cache and other system junk.

Once your system is clean, please reset your device (Power Off/On) and try installing once again the 1.24.7 (Frozen) version of the Bitwarden desktop client from our GitHub page (https://github.com/bitwarden/desktop/releases/tag/v1.24.7). Don't try to install any newer version, as it won't work.

Let me know if that helps.

**Comment by ToGitOrNotToGit** [comment]
Experiencing the same thing with Big Sur macOS 11.4 (20F71)
Bitwarden Version 1.25.1 (518)
Mac mini (2018)
Typing or copying and pasting the Master Password (from Bitwarden app remotely), I can login to the BW vault website but not the macOS app of the Safari extension.

**Comment by Hinton** [comment]
Hello,

Just wanted to let everyone know that the 1.24.7 is no longer supported.

The download page has been updated with more information.
> This release is no longer functional or working with our current cloud services and infrastructure. You may still use the browser extension with Firefox and Chrome, as well as continue to access the Web Vault however Apple set the End-of-life (EOL) for High Sierra a year back and we are no longer able to maintain reverse compatibility.
