### ISSUE TITLE
Auto updater not updating correctly on Windows 10

### ISSUE THREAD

**Issue by Sc0tTyXL** [bitwarden/desktop#1138]
Hello,

I've been using Bitwarden on Windows for nearly a year now but there has been one major issue I've been dealing with.

Every time the auto updater updates Bitwarden it only removes the installation it doesn't install the new version.

### Steps To Reproduce
Step 1: run auto updater
Step 2: click next until finished
Step 3: run Bitwarden

### Expected Result
Updater installs the newest version

### Actual Result
Bitwarden is removed and not installed.
![image](https://user-images.githubusercontent.com/24222938/140055833-2b6120f3-d04d-4d5b-b80d-f9dfe127424d.png)
I have to manually download and install the latest version from the website. 

### Operating System
Windows 10 20H2 on my laptop 
Windows 10 20H1 on my desktop

### Installation method
Direct Download (from bitwarden.com)

### Build Version
Every build in at least the last 6 moths

**Comment by eliykat** [comment]
This is a known issue that is being tracked in bitwarden/clients#2622. I'll close this as a duplicate. I'd be curious to know whether you have a space in your username, like the other users in that thread? (Please post in bitwarden/clients#2622 with any info)
