### ISSUE TITLE
bitwarden uninstalling?

### ISSUE THREAD

**Issue by evilscrappy** [bitwarden/desktop#1148]
### Steps To Reproduce

4. Click on '...'

### Expected Result

when I try to update I think it is it seems to uninstall at least shortcuts say its no longer there

### Actual Result

when I try to update I think it is it seems to uninstall at least shortcuts say its no longer there,I reinstall everything is fine till it trys to update againI

### Operating System

Windows

### Operating System Version

windows 10 pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.29.0 Shell 14.0.1 Renderer 93.0.4577.63 Node 14.17.0 Architecture x64

**Comment by eliykat** [comment]
Hi, this is a known issue that we're tracking in bitwarden/clients#2622. Please add any comments or additional information in that thread. Thanks!
