### ISSUE TITLE
Search results are displayed in the wrong order (except iOS app)

### ISSUE THREAD

**Issue by keisimq** [bitwarden/desktop#1158]
### Steps To Reproduce

My vault where I noticed the problem has several hundred items, 10 folders, different types of items. I tried to cause the same problem in another clean vault by creating a few new items but the problem was not present.

### Expected Result

Search results always sorted alphabetically by item name (case-insensitive) in all Bitwarden client apps.

### Actual Result

Search results by string (e.g. 'router') in my Bitwarden vault are not sorted alphabetically, I attach a screenshot of the search. The list of all items (before search) is properly, alphabetically sorted. The problem occurs on the following Bitwarden clients: Windows desktop, web browser, web. The results are in the same wrong order on these clients. Problem does not occure on iOS - the search results are sorted correctly in alphabetical order in the iOS client app! All tests were carried out on the same vault, with searches on the same phrase ('router'). 

### Screenshots or Videos

![2021 11 13_16 50 18](https://user-images.githubusercontent.com/62240710/141651938-986bf0c3-560a-49ad-a3b3-0faedf2220ec.PNG)

### Operating System

Windows

### Operating System Version

Windows 10 Pro 19043.1348

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.29.1

**Comment by SergeantConfused** [comment]
Hi @keisimq,

The clients that are displaying the results in a non-alphabetical order are the clients that support full-text search, and they are sorting the results by their relevance. Our mobile clients on Android and iOS do not support full-text search, and that is why the order of the results is different. You can learn more on this in general here: https://bitwarden.com/help/article/searching-vault/ and more specifically here: https://lunrjs.com/guides/searching.html

I hope this clarifies everything up for you. If you have any further questions about this, please feel free to create a support ticket using this form: https://bitwarden.com/contact/


All the best,
