### ISSUE TITLE
Can't log in to windows app with U2F via Duo 

### ISSUE THREAD

**Issue by brianpierce** [bitwarden/desktop#116]
Windows 10 Pro with newest version of desktop app and commercial Bitwarden account secured with Duo Security produces error message when U2F option is chosen at login:

"Your browser does not support U2F token authentication.

Please use a U2F compatible browser."

Chrome is installed and Firefox with U2F enabled as well.

**Comment by kspearrin** [comment]
Sounds like an issue with Duo's Web SDK that we use. I'll have to let them know.

**Comment by kspearrin** [comment]
Wait, this is the desktop app, sorry. Yes, U2F protocol is only supported in web browsers at this time, so it will not work in the desktop app or mobile.

**Comment by brianpierce** [comment]
Oh, will add that to the requested feature list.  thx
