### ISSUE TITLE
Bitwarden does not keep password filled on a specific website

### ISSUE THREAD

**Issue by mfcosta** [bitwarden/desktop#1164]
### Steps To Reproduce

1. Go to www.amil.com
2. Click on the BitWarden extension con on Microsoft Edge, Google Chrome or Mozilla Firefox
3. Ask the credentials to be automatically filled.
4. Bitwarden fills the username and password, but when you move the muse, the password field automatically cleans
5. Same happens if you try to copy and past password straight from BitWarden

Workaround
Copy and paste password on a pure text editor (Notepad), them copy and paste it again to website.

### Expected Result

Password should be automatically filled and stay filled before click on sign in button.

### Actual Result

Password automatically cleans up before you are able to sign in

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com), Microsoft Store

### Build Version

1.29.1

**Comment by djsmith85** [comment]
Hi @mfcosta thank you for reporting this issue. As this has to do with the browser extension and we already track it here: https://github.com/bitwarden/browser/issues/1621 could you please add your information there. That the password gets changed/deleted after Bitwarden has auto-filled is an indication, that the issue has to do with the website. Closing this now.
