### ISSUE TITLE
Safari Extension Missing after Update

### ISSUE THREAD

**Issue by flobokoerich** [bitwarden/desktop#1192]
### Steps To Reproduce

1. Go to Safari
2. Click on Safari, then Preferences
3. Go to Extensions
4. See that Bitwarden is missing

### Expected Result

I was expecting the Bitwarden extension in Safari.

### Actual Result

The Safari extension is missing. It updated automatically recently and the extension disappeared. I have deleted it three times already (twice using AppCleaner, once while also restarting immediately after deleting it) and installed it directly from the App store all three times. I had already gone through this process after a prior update too.

### Operating System

macOS

### Operating System Version

Version 11.6.1 (20G224)

### Installation method

Mac App Store

### Build Version

1.30.0 (1935)

**Comment by Jerry-informal** [comment]
same problem
macos 10.15.7
safari 15.1

**Comment by Hinton** [comment]
Hi,

This is a known issue with macOS, see https://github.com/bitwarden/browser/issues/1696 for more details, and 
https://github.com/bitwarden/browser/issues/1696#issuecomment-874122595 for current workarounds.
