### ISSUE TITLE
Linux desktop 1.0.4, 1.0.5 segfaults with glibc2.28, display malformed

### ISSUE THREAD

**Issue by JSkier21** [bitwarden/desktop#120]
Trying the deb pkg or AppImage on ArchLinux, glibc2.28-1 causes both versions (.4 and .5) to segfault. 
dmesg output:
`[33560.106233] bitwarden[17271]: segfault at b87650 ip 0000000000b87650 sp 00007ffc7e304168 error 15 in bitwarden[200000+160c000]`
strace here: 
https://pastebin.com/iQLMxAvx

If I downgrade glibc to 2.27, both 1.0.4 packages will work. 1.0.5 packages start, but lock up and don't display anything in the window contents. It's basically a window into whatever is behind active Bitwarden window. 
 
Let me know if you need more details.

**Comment by kspearrin** [comment]
I fix was suggested in our forums here:
https://community.bitwarden.com/t/linux-version-stops-launching-after-system-upgrade/1826/9

**Comment by JSkier21** [comment]
Thank you, @kspearrin. Trying the fix appears to get bitwarden 1.0.5 displaying correctly as well 1.0.4 working properly still. 

Closing this as it is related to the ArchLinux glibc package, not bitwarden itself.
