### ISSUE TITLE
MasterPW bug?

### ISSUE THREAD

**Issue by LonelyBirb47** [bitwarden/desktop#121]
Sooo.. 
This app is somewhat fucking up with me. 

Bug to report is that sometimes the bitwarden doesnt recognize masterpw , altrhough through browser it works with no problem. 
Didnt notice any pattern sofar. I got it unbugged by deleting and instaling it again. Before i uninstaled it i tried running throguh terminal and got a error message [in JVscript i think] unfortunately didnt copy it. Reporting it to let you know there might be some problem with login part , even with right 'mail +MPW.

**Comment by benklaasen** [comment]
Please close this issue. There's nothing actionable here. The person who logged it doesn't even mention what platform they were running BitWarden on. The first paragraph is *entirely* unnecessary.
