### ISSUE TITLE
Why does snap client connect to redirector.gvt1.com ?

### ISSUE THREAD

**Issue by impredicative** [bitwarden/desktop#1215]
### Steps To Reproduce

When I open the [Bitwarden snap client](https://snapcraft.io/bitwarden), why does it first attempt to connect to redirector.gvt1.com ? It subsequently connects to bitwarden.com.

### Expected Result

The client should not connect to any unofficial site.

### Actual Result

The client connects to an unofficial site.

### Operating System

Linux

### Operating System Version

21.10

### Installation method

Snap

### Build Version

1.30.0

**Comment by Hinton** [comment]
The request to `redirector.gvt1.com` is for electron to download the spellcheck dictionaries.

**Comment by impredicative** [comment]
@Hinton Thanks. Am I to understand that disabling the spellchecker as per #1225 will prevent this connection?

**Comment by Hinton** [comment]
@impredicative Correct, according to https://www.electronjs.org/docs/latest/tutorial/spellchecker#does-the-spellchecker-use-any-google-services it fetches a dictionary from Googles Services. Disabling spellchecking completely (as it's not used anywhere) should prevent this connection. Please let me know if the issue persist in our next release.
