### ISSUE TITLE
Segmentation Fault on Launch (Linux)

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/desktop#122]
I can no longer user the Bitwarden desktop app on Linux due to a Segmentation fault:

```
~ » bitwarden
[1]    18011 segmentation fault (core dumped)  bitwarden
```

This looks related to a similar issue I had with the Slack desktop app for linux, around glib 2.27.3 (see conversation for the AUR package around 2018-08-13 - https://aur.archlinux.org/packages/slack-desktop/)

**Comment by kspearrin** [comment]
See https://community.bitwarden.com/t/linux-version-stops-launching-after-system-upgrade/1826
