### ISSUE TITLE
Bump desktop-idle to version 1.1.2

### ISSUE THREAD

**Issue by ghisvail** [bitwarden/desktop#125]
I am  in the process of submitting a [flatpak](https://github.com/flathub/flathub/pull/547) for the Bitwarden desktop application.

During my first iterations, I noticed the application could not be built on ARM architectures due to an unnecessary restriction in `desktop-idle` version `1.1.1`. The upstream developer kindly lifted this restriction in version `1.1.2`. Would you mind upgrading your dependencies to this version, please?

P.S.: I am a paid subscriber to Bitwarden and find it awesome. Thank you for your work on it.

**Comment by kspearrin** [comment]
Done
