### ISSUE TITLE
Capital C acts as backspace on Postmarket OS for Pinephone

### ISSUE THREAD

**Issue by natebartram** [bitwarden/desktop#1261]
### Steps To Reproduce

1. Add the Flatpak repository to the phone
2. Install Bitwarden (https://flathub.org/apps/details/com.bitwarden.desktop)
3. At any point, try to type a capital C.

### Expected Result

A capital C should appear on screen.

### Actual Result

 If you have input any text prior to this, it will function as a backspace button.

### Additional Context

I also keep getting an "unexpected error" message when attempting to login.

### Operating System

Linux

### Operating System Version

Postmarket OS

### Installation method

Other

### Build Version

1.7.0

**Comment by Hinton** [comment]
Hi @natebartram,

We are unable to provide support for the flatpack build since it's not distributed by Bitwarden. Please use one of the official distributions available on the website, https://bitwarden.com/download/ and feel free to re-open this issue if you manage to replicate it.
