### ISSUE TITLE
[linux] very strange permissions for ~/.config/Bitwarden

### ISSUE THREAD

**Issue by Yujah** [bitwarden/desktop#127]
I am just now experimenting with Bitwarden for the first time so not sure if this is standard or not but I couldn't find the issue on the Web so expect not...

On Linux Mint 19 (i.e., Ubuntu 18.04) and with version 1.7.0 of the Bitwarden desktop client, both the amd64.deb and the the AppImage, Bitwarden creates ~/.config/Bitwarden with permissions 01361: 

```sh
$ ls -ld .config/Bitwarden
d-wxrw---t 3 user user 4096 aug 27 22:27 .config/Bitwarden
```
Other than being weird this (specifically, no read access for user) also breaks my backups. I can of course manually adjust but is this as intended or is something broken?

**Comment by kspearrin** [comment]
I am guessing this is how electron is creating the application directory by default. I am not sure that is is this way. How is the app even able to read from it? I guess since the group has read access?

**Comment by Yujah** [comment]
group permissions wouldn't do that, no, but as long as one knows the name of a file under ~/.config/Bitwarden and said file is not itself unreadable, you can read it fine: 

'''sh
$ ls -l .config/Bitwarden
ls: cannot open directory '.config/Bitwarden': Permission denied
$ touch .config/Bitwarden/Preferences
'''
The 01361 looks almost random, especially what with that "sticky" bit. I am about as far removed from the languages this project is written in as possible so can't really look myself but did you perhaps forget to initialize a variable and/or mask in the code that creates the configuration directory?

I expect you only see this when installing the current version new; an existing ~/.config/Bitwarden created by a previous version is supposedly left untouched. On Linux, launching the app for the first time on a newly created test account would do to reproduce.

**Comment by kspearrin** [comment]
I figured it out. It was passing the permission as 755 (integer) instead of '755'. The string version gets properly parsed as an octal integer. I also changed it to use '700' instead of '755'.

Thanks for the report.
