### ISSUE TITLE
Modifier characters (e.g. accents) in Master Password are not parsed when text is hidden

### ISSUE THREAD

**Issue by SamuAlfageme** [bitwarden/desktop#128]
I have a Spanish keyboard layout and thus, I use modifier characters (e.g. "ACCENT ACUTE": `´` + `A` = `Á`) in my master password to add even more entropy and avoid brute force attacks. 

When keeping the password hidden, these modifier characters do not parse from keyboard at all - i.e. only the next key pressed goes in the password. However, If you "Toogle Visibility" and type the same, it does work: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/44709172-3cbcc800-aaa9-11e8-9a6d-3fddd74cf5d5.gif"/>
</p>

**Comment by SamuAlfageme** [comment]
@kspearrin interesting enough, I checked with Firefox 61.0.2 and it worked. Switched to Chrome 68.0.3440 and failed miserably.

I'm guessing this is an upstream issue in electron/chromium with Angular2's `input` (https://github.com/bitwarden/web/blob/1873ce41b6f2a94baca8b6dac396adf7ce1a7a13/src/app/accounts/login.component.html#L15-L16). Since the only thing that changes in the DOM when toggling the visibility is `input`'s `type` from `password` to `text`. Shall I move the issue to `bitwarden/web`?

**Comment by kspearrin** [comment]
No need to move it. Sounds like a n issue with Chromium in general so I am not sure if there is anything we can do about it. Have you tried looking for the problem on chromium's bug reports board?

**Comment by SamuAlfageme** [comment]
Actually; It seems to be unrelated to Angular **but rather macOS (cocoa) + chromium/webkit** bug. Ref: 

- https://stackoverflow.com/questions/50114072/google-chrome-macos-password-field-wont-accept-non-ascii-characters
- https://bugs.webkit.org/show_bug.cgi?id=57817 
- https://bugs.chromium.org/p/chromium/issues/detail?id=78048

... I remember seeing something similar happening on onePassword's menubar dropdown

**Comment by kspearrin** [comment]
Thanks for finding those. I am going to close this since it is an upstream issue. At least you have a workaround.

**Comment by SamuAlfageme** [comment]
@kspearrin happy to announce this one has already been fixed in Chromium and therefore on the Bitwarden client. Tested with Version 1.16.6:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/69040827-c6c6b880-09ee-11ea-99f5-6f91660ef509.gif"/>
</p>

ref. https://bugs.chromium.org/p/chromium/issues/detail?id=78048#c24
