### ISSUE TITLE
Support browser integration with only HKLM\SOFTWARE\Google\Chrome

### ISSUE THREAD

**Issue by BierDav** [bitwarden/desktop#1282]
### Steps To Reproduce

1. Open Bitwarden Desktop
2. Press F12 to open de Developer Tools
3. Go to settings and disable/enable Browser Integration
4. On the console this errors should be logged:
![image](https://user-images.githubusercontent.com/46626041/152133705-73af78bf-516d-46db-85f7-f47ee3fa5a25.png)

### Expected Result

That the Brower integration works! I've already looked into the source code: The registry paths you access:
HKLM\SOFTWARE\Mozilla\Firefox
HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.8bit.bitwarden
HKCU\SOFTWARE\Google\Chrome
HKCU\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.8bit.bitwarden
Don't exist.

I'm running Windows 11 and I have only:
HKLM\SOFTWARE\Google\Chrome
HKLM\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.8bit.bitwarden

If I generate the manifest manually and put the according path into this above mentioned registry than everything works fine. I already thought about a Push Request, but I didn't have time to think over all edge-cases and test it on all platforms so I just present you the way to go ;)

After a reinstall I didn't get the logs anymore, but it still doesn't work.

### Actual Result

Mentioned above

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com), Microsoft Store

### Build Version

1.30.0

**Comment by Hinton** [comment]
Hi @BierDav,

Thanks for taking the time to trouble shoot this. Writing keys to `HKLM` is tricky since it requires an elevated prompt. Which is not something we currently have a way of doing.

**Comment by Hinton** [comment]
Additionally, `HKLM` is probably undesirably for our scenario. The manifests are currently on a per-user basis. And if we start writing them to `HKLM` they would need to placed in a path that can be accessed by any user.

**Comment by BierDav** [comment]
I'm aware of that. That's the reason why I let you find out how to solve this. 😉

**Comment by usamac** [comment]
Really disappointed my browser extension updated today. Biometric Integration was working flawlessly before this. I use Brave Browser as well. Yesterday, I had no issues whatsoever, now when I open Brave and click on the Shield with the new little lock icon, and login without integration, I get the errors shown in the attached image. I have to navigate to settings>sync>sync now, even though it shows at the bottom that the vault was just synced, to fix the errors in the extension once unlocked. 

I tried the suggested fix on both laptops and had no luck, unfortunately. Can I rollback the extension so my laptops work properly again?

Two laptops, one with Win 11 using a fingerprint scanner the other  with Win 10 and it uses facial biometrics. 

![image](https://user-images.githubusercontent.com/55719365/153690090-e1cbc4e5-c319-4ddd-98a5-afaed7a89e4f.png)

**Comment by BierDav** [comment]
Same error, but I think thats a different issue

**Comment by Hinton** [comment]
I've updated the title to better reflect what this issue is tracking.

**Comment by ljycrystal** [comment]
> This was working for me recently in Brave (Chrome) and Firefox, to be sure. Pretty sure even after my Win11 upgrade. Now I can get it to work in Firefox, but not in Chrome or Brave.
> 
> UPDATE - Firefox was working as I mentioned. I had to follow these steps EXACTLY to get this working again in Chrome and Brave (thanks to this poster [here](https://community.bitwarden.com/t/browser-integration-not-enabled/30993/7) from June '21.
> 
> In Bitwarden Desktop
> 
> 1. Disable Login With Windows Hello
> 2. Disable Browser integration.
>    (Clicked Close on settings just in case - may not be needed)
> 
> Now 3. Enable Browser Integration 4. Enable Windows Hello / Biometric. (Clicked Close on settings just in case - may not be needed)
> 
> In Browser 5, Enable Biometric.
> 
> Other things that may or may not have been necessary: I switched back from Windows Store BW desktop app to the one directly from the BW site, and in my Chrome and Brave extension details I enabled "Allow access to file URLs".

Microsoft Edge. Works!
