### ISSUE TITLE
MacOS 12.2 (M1): Captcha does not load, preventing login

### ISSUE THREAD

**Issue by AdemirSp** [bitwarden/desktop#1284]
### Steps To Reproduce

Login screen: Type username and password, and click "Log in". Captcha is not displayed initially

### Expected Result

User is logged in

### Actual Result

Getting captcha box with gray background, unable to log in

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/14043592/152214113-e734e9ed-f0a3-45d5-978a-07e3135ceaaf.png)

### Operating System

macOS

### Operating System Version

12.2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.30.0

**Comment by Greenderella** [comment]
Hi @AdemirSp 

Does the issue persist if you try to authenticate yourself in a different browser? Also, could reboot your modem / router, then test again to see if that provides any relief? What happens if you test on a different Wi-Fi network or over LTE as well? Are you able to log when the connection changes?

**Comment by AdemirSp** [comment]
Hi @Greenderella 

After restarting the modem, it works. Thank you so much ! :)

I did try to login through VPN connection yesterday, but it wasn't helping.

Thanks

**Comment by michalchecinski** [comment]
The same happens to me except everything works in the browser, but the captcha is not displayed in the macOS app. Changing DNS didn't fix the issue.

**Comment by luvicsoura** [comment]
The same thing is happening to my on the Chrome extension. 

I'm trying to use the extension on Vivaldi (5.1.2567.49 (Stable channel) stable (64-bit)) for Linux. I've tried disabling all other extensions, but it didn't solve the issue nor did changing my IP address by the means of a VPN.

I get the following to errors logged to the console:

- No valid response from extension script.
- Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by eliykat** [comment]
We're using https://github.com/bitwarden/desktop/issues/1388 to track this issue, please check that thread for further discussion.
