### ISSUE TITLE
Desktop App doesn't follow SAML SSO auth flow

### ISSUE THREAD

**Issue by AdamVB** [bitwarden/desktop#1290]
### Steps To Reproduce

We have Reverseproxies in front of our Bitwarden.

When clients access the Page for the first time they are then redirected to our SSO Service where they login.

After the login a cookie is set that let's the client through the reverseproxy to the bitwarden installation.

(this is based on mod_auth_mellon and SimpleSaml PHP)

Now in the Browser this works fine. But the bitwarden desktop doesn't follow this auth-flow

### Expected Result

What should happen (as it happens in the browser):

->GET bitwarden.example.com 
<-303 sso.example.com, set testcookie 
-> GET sso.example.com
<- 302  sso.example.com/getSamlChallenge...
-> GET sso.example.com/getsamlchallenge
<- 200 set cookie SAMLAuthtoken, redirect with javascript
-> POST sso.example.com/postresponse
<- 303 bitwarden.example.com set mellon-cookie
-> GET bitwarden.example.com --- Page is accessible

End result is that the mellon cookie is set in the browser. 
When presenting this cookie to the reverseproxy it lets us through to bitwarden.

### Actual Result

Bitwarden Desktop app starts with a POST to ```api/accounts/prelogin```

->POST bitwarden.example.com/api/accounts/prelogin
<-303 sso.example.com, set testcookie 
-> GET sso.example.com
<- 303  sso.example.com/getSamlChallenge...
-> GET sso.example.com/getsamlchallenge
<- 200 set cookie SAMLAuthtoken, redirect with javascript

Error:
SyntaxError: Unexpected token < in JSON at position 0
Received API exception: SyntaxError: Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/15871966/152362805-a5a847a6-7ba1-434b-b5a9-86b5e55e1309.png)

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>POST data</title>
    <script type="text/javascript" src="/simplesamlphp/resources/post.js"></script>
    <link 
        type="text/css" rel="stylesheet" href="/simplesamlphp/resources/post.css" />
</head>
<body>

    <noscript>
        <p><strong>Note:</strong> 
        Since your browser does not support JavaScript, 
        you must press the button below once to proceed.</p> 
    </noscript> 

    <form method="post" 
        action="https://bitwarden.tsi-vc.otc-service.com/mellon/postResponse">
    <!-- Need to add this element and call click method, because calling 
    submit() on the form causes failed submission if the form has another 
    element with name or id of submit.
    See: https://developer.mozilla.org/en/DOM/form.submit#Specification -->
    <input type="submit" id="postLoginSubmitButton"/>
<input type="hidden" name="SAMLResponse" value="xxxxxx==" /><input type="hidden" name="RelayState" value="https://bitwarden.tsi-vc.otc-service.com/api/accounts/prelogin" />
        <noscript>
            <button type="submit" class="btn">Submit</button>
        </noscript>
    </form>

</body>
</html>

```
the Bitwarden app does not continue and cannot POST the SAML Response, therefore not receiving the mellon-cookie.

### Additional Context

We have an Enterprise License for Bitwarden, so i also tried it with the Enterprise Single Sign On configuration.

This opens up the browser, which can follow all of the Auth workflow. Then it opens up the bitwarden:// URI,

problem here is, that the mellon-cookie is not transfered over to the bitwarden desktop app, therefore the desktop app is not allowed through the reverseproxy

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.30.0

**Comment by Hinton** [comment]
Some more context. The applications expect to communicate directly with the Bitwarden API, and do not understand HTML responses to json requests.
