### ISSUE TITLE
OTP generation broken on 1.31.0

### ISSUE THREAD

**Issue by belpolaris** [bitwarden/desktop#1309]
### Steps To Reproduce

1. Open bitwarden on Windows
2. Sign in with password
3. Select account to gain OTP for signin
4. No OTP present
5. Check Premium status, BW client states not premium
6. Verify premium status on website
7. Log out, back in to BW
8. OTP is present, but verification code fails authentication
9. Check Android BW client, different code present on screen

### Expected Result

Windows-generated OTP code works

### Actual Result

Android-generated code works, windows-generated code does not.

### Operating System

Windows

### Operating System Version

Win10 19043.1466

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.31.0

**Comment by vmadventure** [comment]
Facing the same issue here. Windows client 1.31.0 reports that my account does not have an active Premium membership, although the Bitwarden website indicates that I am. Unable to view OTP keys within the desktop client, but I can still view them on the latest version of the iOS app. My Windows machine is also Windows 10 with a slightly different build: 19043.1526 .

**Comment by djmixman** [comment]
Same Issue. Unable to see any OTP codes. Using the menu option Edit > Copy TOTP does not work either.


Windows desktop client.
Version 1.31.0
Shell 16.0.7
Renderer 96.0.4664.110
Node 16.9.1
Architecture x64

**Comment by kspearrin** [comment]
We are looking into the problem. For now you can log out and back in to restore you premium status.

**Comment by sfanous** [comment]
Thanks for the workaround @kspearrin. I can confirm that this worked for me.

**Comment by vmadventure** [comment]
Thank you @kspearrin , logging-out of the desktop client and logging back in resolved the issue on my Windows 10 devices.

**Comment by Webxorcist** [comment]
Same issue and solution on the Linux Flatpak image.

**Comment by BirdInFire** [comment]
Same issue on Flatpak (linux) Version

**Comment by dkleehammer** [comment]
System76/Pop OS linux, same issue.

**Comment by kspearrin** [comment]
Please try v1.31.1 that is now available. It should include fixes for this issue.
