### ISSUE TITLE
BItwarden browser extensions stopped working after desktop app update

### ISSUE THREAD

**Issue by dzigner** [bitwarden/desktop#1311]
### Steps To Reproduce

1. Go to 'Start Bitwarden app on desktop and login...'
2. 'Go to browser - I used Chrome and Edge to check - and click on the extension to unlock'
3. It stays on 'Awaiting confirmation from desktop'

### Expected Result

When clicking on browser extension, and trying to log in with biometrics, it should get confirmation from the desktop and unlock.

### Actual Result

The 'Awaiting confirmation from desktop' message box stays as is, even after logging in successfully, and the browser extension does not unlock.

### Screenshots or Videos

![browserloginproblem](https://user-images.githubusercontent.com/1585458/153516222-97fbf7dd-03f9-450d-a57b-b54bfa7e9638.png)
![lockedextension](https://user-images.githubusercontent.com/1585458/153516226-4de7fa7e-60a0-4464-bfc2-2cd67736be78.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.31.0 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by Randrage** [comment]
I also had this bug after the new update. With some tinkering, I discovered a "fix":

1. In the Browser Extension for Bitwarden, go into **Settings**
2. Under **Account** click **Log out** and then **Yes** to confirm
3. Click **Log In** and re-enter your Master Password to login

Future attempts to **Unlock with biometrics** should work now, assuming your Desktop application is still setup correctly.

**Comment by cscharf** [comment]
Hi @dzigner , thank for the report, however this duplicates an existing issue already being worked on by the team, https://github.com/bitwarden/desktop/issues/1310.

**Comment by dzigner** [comment]
@Randrage Sorry, this did not work for me. It gives me error - 
I logged out, then Logged back in with Master Password, it gives me error -
![mstrpwderror](https://user-images.githubusercontent.com/1585458/153678897-bafff372-03ee-4974-a510-3513982761ad.png)
But then, it is logged in with the lock icon underneath.  Then I can unlock with master password - but neither Pin nor fingerprint work.
