### ISSUE TITLE
Window disappears

### ISSUE THREAD

**Issue by gamathers** [bitwarden/desktop#132]
I have Ubuntu 18.04.1 with FireFox 61.0.1 and added BitWarden as a FireFox extension.
When I try to login to BitWarden it asks for my email and master password. I click on the email field and enter ok. But when I click on the master password field or tab to it, the window disappears.

**Comment by Crocmagnon** [comment]
Duplicate of https://github.com/bitwarden/browser/issues/580
Besides, you're posting this issue in the wrong repo. This one's for the desktop app, not the browser extension 🙂

**Comment by gamathers** [comment]
Thanks I'll go to the other thread,
