### ISSUE TITLE
Bitwarden for Windows 1.31.0 doesn't show premium membership

### ISSUE THREAD

**Issue by emilseman** [bitwarden/desktop#1320]
### Steps To Reproduce

1. Go to Bitwarden app for windows
2. Click on Account -> Premium Membership

### Expected Result

I am a premium member, so it should show that
Also premium membership (e.g. OTP codes) should work, but they don't

### Actual Result

Bitwarden windows reports `You are not currently a premium member` (refreshing doesn't help it either)
OTP codes don't work (are not shown in application)

### Screenshots or Videos

Win version -> ![image](https://user-images.githubusercontent.com/9448707/153596725-4b27ccba-852f-414c-a4df-bb61667e1a7d.png)
Web version, same account: ![image](https://user-images.githubusercontent.com/9448707/153597107-08e0616d-cf4e-46f7-8fc7-639905b094e4.png)

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com), Chocolatey

### Build Version

1.31.0

**Comment by iAmSaugata** [comment]
Same here, from the windows app, it is showing purchase premium membership, where as I am already a premium member, this will highly impact as all the two factor authentication stored here. Please fix this as early as possible.

it looks like beta version pushed to production in hurry.

**Comment by kspearrin** [comment]
Please try v1.31.1 that is now available. It should include fixes for this issue.

**Comment by emilseman** [comment]
Thanks, new version fixed it.

**Comment by andreujuanc** [comment]
I just got this. 
![image](https://user-images.githubusercontent.com/360052/158239498-52eaccca-fe71-4473-a0c6-2fc967b36e8e.png)

**Comment by eliykat** [comment]
Hi @andreujuanc, does logging out and back in again fix it? Or manually syncing your vault?
Do you have premium personally or via an organization?

**Comment by andreujuanc** [comment]
Hi @eliykat 
I closed the app and opening it this morning,  Didn't work. Then I saw your email and tried it in this order:

> Or manually syncing your vault?

Didn't fix it.

> Does logging out and back in again fix it?

This worked!

>Do you have premium personally or via an organization?

Personal

**Comment by eliykat** [comment]
Good to hear, thanks. Please let me know if the issue reoccurs.
