### ISSUE TITLE
Unlock with windows hello no longer works on chrome extension

### ISSUE THREAD

**Issue by ratva** [bitwarden/desktop#1326]
### Steps To Reproduce

1. Start with the desktop bitwarden app set to launch on boot.
2. Open a new chrome session
2. Click on the locked bitwarden extension
3. Click "unlock with biometrics"
4. Press okay on the windows security/windows hello pop up when it recognises you

### Expected Result

Extension used to unlock and be usable

### Actual Result

The windows security pop up closes as expected, but the extension freezes on this screen:
![image](https://user-images.githubusercontent.com/10108884/153660347-ab77fbb1-5bc2-4ab5-b40b-0f58d68419bf.png)

### Additional Context

The issue started today. I do not know if there was a new update that broke it.

I've tried logging off the desktop app, reinstalling the extension, disabling and re-enabling the extension integration and likewise for using biometrics.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Extension Version: 1.56.1, desktop app 1.30.0

**Comment by kspearrin** [comment]
Please try v1.31.1 that is now available. It should include fixes for this issue.

**Comment by ratva** [comment]
> Please try v1.31.1 that is now available. It should include fixes for this issue.

Hi there, I've just updated and restarted my machine to try this. I'm still having the same issue with the extension.

The desktop app can unlock via windows hello without issue, but the extension gets stuck on the screenshot I attached previously.
My settings are as follows, if you see something that is wrong:
![image](https://user-images.githubusercontent.com/10108884/153665688-4994e3f6-7e2d-4aa4-b47d-99f1b36a5ff5.png)

And in the browser extension settings I have:
![image](https://user-images.githubusercontent.com/10108884/153665809-48da9860-0998-4c45-8aa8-6cea6efe91d0.png)

**Comment by ratva** [comment]
> Please try v1.31.1 that is now available. It should include fixes for this issue.

Hi there, I've just updated and restarted my machine to try this. I'm still having the same issue with the extension.

The desktop app can unlock via windows hello without issue, but the extension gets stuck on the screenshot I attached previously.
My settings are as follows, if you see something that is wrong:
![image](https://user-images.githubusercontent.com/10108884/153666068-1d2a264a-fe80-47f9-93c8-ac12685d0b57.png)

And in the browser extension settings I have:
![Uploading image.png…]()

**Comment by MGibson1** [comment]
@ratva Sorry for the confusion, can you please try upgrading your browser plugin to the latest as well?

**Comment by Larry-Sussman** [comment]
@ratva Sorry about the trouble here! Our team has worked out and tested a fix, it turns out this issue was specific to the browser extension. We've submitted the update to Google for review on the Chrome web store, it will be **v1.56.3** when released. When it becomes available [here](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb/related?hl=en), can you please try upgrading your browser plugin as well? That should the problem with unlocking with Windows Hello. Hope this helps! 😄

**Comment by ratva** [comment]
> Our team has worked out and tested a fix

@Larry-Sussman  Amazing, thank you - I'll keep checking for the update to hit the store and will post back either way with the results =)
