### ISSUE TITLE
Problem minimising to tray

### ISSUE THREAD

**Issue by keeneye** [bitwarden/desktop#133]
I really like Bitwarden: its a great product. However I can't get the system tray icon to work at all on Windows 10. When the tray icon does appear (occasionally) it doesn't do anything, and sometimes it stops me loading BitWarden altogether. Here is an error message I get when trying to minimise to the tray:
![image](https://user-images.githubusercontent.com/1785742/45205216-692ace00-b279-11e8-8814-2cee930c917f.png)
I do hope this can be fixed as the 'minimise to tray' is a great feature.
Mark

**Comment by kspearrin** [comment]
https://github.com/bitwarden/desktop/issues/111
