### ISSUE TITLE
MacOS: Creating new login in collection is not visible and causes errors in console log

### ISSUE THREAD

**Issue by frode** [bitwarden/desktop#134]
I simply created a new login inside a collection, and expected to see the new login listed in the collection once i clicked save. But the load spinner just stayed forever.

Clicked on "All items", that displayed all the items, and then i navigated back to the collection where I created a new login.

Resulted in 0 items displayed, and errors in the console (Dev Tools):

![screen shot 2018-09-11 at 08 43 44](https://user-images.githubusercontent.com/102189/45342772-377a7580-b59f-11e8-832f-d41afcceacc9.png)

The error listed below now occurs each time i click on any of the collections I got available: 

```
vendor.js:1812 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by kspearrin** [comment]
Should be fixed in next version.

**Comment by frode** [comment]
@kspearrin Thats good! But is the issue closed before the next version is released?
In my case and others, this is still a open issue until its available as fixed in the new version..

**Comment by kspearrin** [comment]
Issues are tracked here for development purposes. Since development for this issue is complete, it is closed.
