### ISSUE TITLE
Forced to use PIN instead of selected Windows Hello

### ISSUE THREAD

**Issue by WoodlandsAndy** [bitwarden/desktop#1342]
### Steps To Reproduce

1. With Bitwarden running in the background, Open Google Chrome on a Dell Windows 10 PC
2. Attempt to open Bitwarden chrome extension

### Expected Result

Expect the program to request a fingerprint scan to access the vault.

### Actual Result

Even thought in the main "Bitwarden program settings" and in the "Chrome extension settings" the option to "open with PIN" are unchecked and "unlock with Biometrics" are checked, Bitwarden requests PIN for security every time I try to log in.  When prompted for a PIN if I select "other options", I can then select "fingerprint" and it works but then every time I try to log-in to the Bitwarden extension, it asks for the PIN again.  All very annoying.  It was all working perfectly until the recent program "upgrade".

### Operating System

Windows

### Operating System Version

10

### Installation method

Microsoft Store

### Build Version

Version 1.31.2 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1  Arch x64

**Comment by eliykat** [comment]
What version of the Chrome extension are you using? We had some issues with biometric unlock which were fixed in the latest patch release (1.56.5). Please make sure you've got the latest extension version.

**Comment by WoodlandsAndy** [comment]
That fixed it. Thanks

Regards

Andy
