### ISSUE TITLE
cmd + w doesn't close the window on macOS

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/desktop#1353]
### Steps To Reproduce

The title says it all.

### Expected Result

cmd + w closes window on macOS - it is standard behaviour.

### Actual Result

cmd + w is inactive 

### Additional Context

This is exactly the same issue as one already fixed in the past:

https://github.com/bitwarden/desktop/issues/714

For some reason it resurfaced now again.

### Operating System

macOS

### Operating System Version

12.2.1

### Installation method

Mac App Store

### Build Version

Version 1.31.3 (2320)

**Comment by nico-zck** [comment]
+1

**Comment by eexit** [comment]
Yes, please, bring this back!

Thanks!

**Comment by cscharf** [comment]
Thanks for the report @kapitainsky , the fix noted did correct the issue previously, however it appears from initial inspection that code remains in-tact and hasn't changed. Will route this to the team to take a look at root cause.

**Comment by kapitainsky** [comment]
> Thanks for the report @kapitainsky , the fix noted did correct the issue previously, however it appears from initial inspection that code remains in-tact and hasn't changed. Will route this to the team to take a look at root cause.

Thank you for looking into it.

I have also tested no Apple shop version on both Monterey and Big Sur and this time cmd+w is missing also here.
