### ISSUE TITLE
can login from app to self hosted environment

### ISSUE THREAD

**Issue by karba78** [bitwarden/desktop#1354]
### Steps To Reproduce

Launch the app
log out if logged in
fill email adress
fill password
click login button
"An error has occured
An unexpected error has occured"
Web browser plugin keeps working fine on same pc. W10. 

### Expected Result

i am expecting Bitwarden to start and log in to my server

### Actual Result

app does not log into server

### Operating System

Windows

### Operating System Version

W10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.31.3

**Comment by karba78** [comment]
Version 1.23.1

**Comment by kspearrin** [comment]
The latest self-hosted server version is 1.46. Please update and try again.

**Comment by Hinton** [comment]
Hi @karba78 , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
