### ISSUE TITLE
the installation seems not to work when the internet is not available or does not respond correctly

### ISSUE THREAD

**Issue by sfonteneau** [bitwarden/desktop#1361]
### Steps To Reproduce

1. launch of the installation with silent argument and no internet acces

### Expected Result

that it works

### Actual Result

crash

### Screenshots or Videos

![154678508-05286183-3593-498c-a50e-202120b53afc](https://user-images.githubusercontent.com/5419492/154687443-c031161c-2ee9-4361-86cd-b901f61a41c3.PNG)

### Additional Context

The workstation is in a vlan where it does not have internet access

### Operating System

Windows

### Operating System Version

10.0.19042.2526

### Installation method

Direct Download (from bitwarden.com), wapt package

### Build Version

1.31.3

**Comment by kspearrin** [comment]
You can download the nsis .7z file from our releases here on GitHub. Place it in the same directory as the installer and it will use the local copy instead of trying to download it.
