### ISSUE TITLE
Uninstalls when upgrading.

### ISSUE THREAD

**Issue by KingBasilisk** [bitwarden/desktop#1363]
### Steps To Reproduce

A la hora de actualizar a la versión 1.31.3 se reinicia la ampliación, cuando intentas abrirlo debe aparecer un error que dice lo siguiente "The item 'Bitwarden.exe' that this shortcurt refers to has been changed or moved, so this shortcurt will no longer work properly" y sucede aun que intente abrir la app desde las apps recientemente usadas

### Expected Result

The application starts as it normally does.

### Actual Result

La aplicacion es borrada del pc

### Screenshots or Videos

![2022-02-18](https://user-images.githubusercontent.com/99997678/154761460-11e36f17-cc5f-4881-ae38-b6d88ec9bde8.png)

### Operating System

Windows

### Operating System Version

Windows 11, based x64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

When trying to upgrade from version 1.31.2 to version 1.31.3

**Comment by eliykat** [comment]
This is a known issue and has been reported in bitwarden/clients#2622. Please see that thread for more information.

The current theory is that it's caused by spaces in your Windows username, but we haven't been able to reproduce it.
