### ISSUE TITLE
Generate Password Opens Behind Main Window

### ISSUE THREAD

**Issue by dembeck** [bitwarden/desktop#1366]
### Steps To Reproduce

1. Set BitWarden to "Always on Top" in the "Window" menu.
2. Go to any saved login, and click edit.
3. Click the _Generate Password_ icon by the _Password_ box.
4. Click _Generate Password_ several more times because I don't think it is responding.
5. Realize that I now have ten _"Overwrite Password"_ confirmation windows centered **behind** the main BitWarden window.

### Expected Result

When changing a login password with the _Generate Password_ icon, the confirmation window should open **centered on top** of the main BitWarden window.

This should happen regardless if BitWarden is set to "Always on Top" or not.

### Actual Result

When changing a login password with the _Generate Password_ icon, the confirmation window opens centered **under** the main BitWarden window.

### Operating System

Windows

### Operating System Version

Windows 11 Enterprise (OS Build 22557.1)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.31.3 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by Hinton** [comment]
Hi @dembeck,

Thanks for reporting this. I've managed to replicate it and have opened a PR which should resolve this issue.

**Comment by Hinton** [comment]
This is now merged, and should be included in the next release.
