### ISSUE TITLE
Can’t log in, login screen renders grey rectangle instead of captcha

### ISSUE THREAD

**Issue by phortuin** [bitwarden/desktop#1388]
### Steps To Reproduce

**Apologies** for the messy bug report, while I was typing, I tried several scenarios and now I'm unable to log in at all. I kept my original notes with strikethrough to give some context to the problem and my progress trying to pinpoint the issue.

~~Prerequisites: you need to be logged in with an account and have a secondary account that you want to add.~~

1. Open Bitwarden Desktop on MacOS ~~(being logged in with primary account)~~
2. ~~Click your account name in the top right and '+ Add account'~~
3. Enter email address
4. Enter password
5. Click Log in

A grey rectangle is rendered below the email/password fields; clicking it doesn’t yield results.

**Note:** I am now also getting the same results after reinstalling the app (via Homebrew) and logging in to a single, Personal Premium account. I currently can not log in to any account with MacOS Bitwarden.

### Expected Result

I expected to either see a 'Credentials incorrect' notice, or move on to the next screen where I can enter my 2FA code. My desired final outcome would be both my accounts being logged in.

### Actual Result

A grey rectangle is rendered, no other user feedback is given (even when I type in a wrong password), and the dialog doesn’t move forward to the 2FA screen.

### Screenshots or Videos

<img width="1062" alt="Screenshot 2022-03-02 at 09 18 11" src="https://user-images.githubusercontent.com/137299/156323371-2dec2157-b3d6-42ee-9432-6a84e7f88a41.png">

### Additional Context

I have a Personal Premium account and a Business Teams account. ~~It seems that this happens for business accounts. The personal account forwards to the 2FA screenm, but the Business account doesn’t, not even after restarting the app. I simply cannot log in with my Business Teams account in the Desktop app.~~ Both accounts seem to get this issue, but I can sometimes log in with my Personal account, but never with my Business account.

This happened:
- being logged in to an account and adding a secondary (via Switch Account), 
- after trying to add a secondary account (which yielded the above results), then logging out from all accounts and signing in to any of my accounts (which again, yielded these results).

~~After I quit and restart Bitwarden, I can log in to my primary (personal) account as expected, but not add a secondary (business) account as the same thing described above happens.~~

### Operating System

macOS

### Operating System Version

12.2.1

### Installation method

Homebrew

### Build Version

Version 1.31.3 (2320)

**Comment by MGibson1** [comment]
Hi, could you navigate to the [captcha prompt hosted by bitwarden](https://vault.bitwarden.com/captcha-connector.html?data=eyJzaXRlS2V5IjoiYmMzOGM4YTItNTMxMS00ZThjLTlkZmMtNDllOTlmNmRmNDE3IiwibG9jYWxlIjoiZW4ifQ%3D%3D&parent=https%253A%252F%252Fvault.bitwarden.com%252F%2523%252F&v=1), directly? Do you still see only a grey box?

What about if you go [directly to hcaptcha](https://newassets.hcaptcha.com/captcha/v1/716b3bf/static/hcaptcha-checkbox.html#id=0l155ps8mcri&host=vault.bitwarden.com&sentry=true&reportapi=https%3A%2F%2Faccounts.hcaptcha.com&recaptchacompat=true&custom=false&tplinks=on&sitekey=bc38c8a2-5311-4e8c-9dfc-49e99f6df417&theme=light)?

Trying to understand where the failure point is.

**Comment by MGibson1** [comment]
Does no inner html exist for the `hcaptch_iframe` element?

Any console errors that might point to failures to load?

**Comment by eliykat** [comment]
Duplicate issue: https://github.com/bitwarden/desktop/issues/1284

**Comment by phortuin** [comment]
The inner HTML for `hcaptcha_iframe` exists, but the iframe that is loaded from there doesn’t seem to get loaded:

```html
<iframe src="https://newassets.hcaptcha.com/captcha/v1/716b3bf/static/hcaptcha-checkbox.html#id=0wc2urmapcd&amp;host=vault.bitwarden.com&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=true&amp;custom=false&amp;tplinks=on&amp;sitekey=bc38c8a2-5311-4e8c-9dfc-49e99f6df417&amp;theme=light" title="widget containing checkbox for hCaptcha security challenge" tabindex="0" frameborder="0" scrolling="no" data-hcaptcha-widget-id="0wc2urmapcd" data-hcaptcha-response="" style="width: 303px; height: 78px; overflow: hidden;"></iframe>
```

**Comment by MGibson1** [comment]
I'm have been totally unsuccessful in reproducing this issue.

Is it intermittent or every time you attempt to solve captcha? Does any part of the captcha load, like is this after you click the checkbox?

If you're available I'd love to chat live on [gitter](https://gitter.im/bitwarden/Lobby) and see about fixing this.

**Comment by codcod** [comment]
Hi, same problem here. The same setup (MacBook M1 + Homebrew) and the same outcome: grey rectangle instead of captcha challenge that prevents from logging in to the desktop app.

Command line output shows nothing:
```
~ ❯ /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
(node:46391) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use Bitwarden --trace-deprecation ... to show where the warning was created)
20:53:02.555 › Checking for update
20:53:03.083 › Update for version 1.31.3 is not available (latest version: 1.31.3, downgrade is disallowed).
<--- Last few GCs --->
[46405:0x108008000]       60 ms: Scavenge 2.8 (4.2) -> 2.4 (4.7) MB, 0.5 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
<--- JS stacktrace --->
```

Workaround is to install the app via App Store (not Homebrew). No problems there.

**Comment by kspearrin** [comment]
Are any of you able to join our gitter chat [here ](https://gitter.im/bitwarden/Lobby) and help us debug this in live chat together? We are still having a hard time reproducing the issue and your help would be appreciated.

https://gitter.im/bitwarden/Lobby

**Comment by OzanBarsal** [comment]
I have this problem as well on a 2021 M1 MBP using brew installation. I've noticed there is one issue that pops up in the developer tools when I click Sign In (when the captcha box first appears basically), attaching a screenshot in case it helps:
<img width="509" alt="Screen Shot 2022-03-10 at 15 36 07" src="https://user-images.githubusercontent.com/3352988/157663693-dd945635-96bb-4c31-8aa1-f48f887ac34d.png">
