### ISSUE TITLE
Microsoft Store version not updated

### ISSUE THREAD

**Issue by ichaushev** [bitwarden/desktop#139]
The Microsoft Store release of Bitwarden is still on version 1.7.0. I see it's been roughly a week since the release of 1.8.0. When is the update expected to come to MS Store and why is it delayed? Are users better off using the exe installer?

**Comment by kspearrin** [comment]
Microsoft denied our update since we have links to the browser extensions, android app, and ios app in the top menu. We will submit another update soon with this removed to see if they will then accept. I'd say you are better off with the regular exe if you want the most recently updates faster.
