### ISSUE TITLE
No access to passwords if Bitwarden server (self hosted) is not accessible (via reverse proxy)

### ISSUE THREAD

**Issue by MichaelHammen** [bitwarden/desktop#1391]
### Steps To Reproduce

1. Shutdown bitwarden server (but leave Reverse Proxy active)
2. Start Bitwarden Client (no matter if Full Client or Browser Addon)
3. Type in Master Password

### Expected Result

Bitwarden should allow access to passwords in "offline mode"

### Actual Result

When I shut down the Bitwarden server (or even just stop the Docker containers), Bitwarden displays the message "Logged out - Your login session has expired." (Bitwarden-screenshot2.jpg).
After entering my password, I get the error message "An error has occurred. .....:" (Bitwarden-screenshot3.jpg) is displayed (the source of the URL of the Bitwarden Web App):

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>`

### Screenshots or Videos

![Bitwarden-screenshot1](https://user-images.githubusercontent.com/100669731/156504787-0e54ecd3-e64d-4e3b-aac2-3a6d6a8e88a2.png)
![Bitwarden-screenshot2](https://user-images.githubusercontent.com/100669731/156504803-c3df49e0-794b-4bb2-91ee-782c11809eb5.png)
![Bitwarden-screenshot3](https://user-images.githubusercontent.com/100669731/156504830-dfec0bc0-4f0c-40b3-a757-aa8c47394aba.png)

### Additional Context

We had two problems, which is why the Bitwarden server was no longer accessible, but the firewall was accessible.
If we then want to access passwords in Bitwarden, we unfortunately can't get to it any more. That is a "no go".

I recreated it with Vaultwarden and Traefik (private), it's basically the same here: If I deactivate the network for the Vaultwarden container, I can no longer access Bitwarden. In this case, the client simply remains "empty" after logging in and the "wheel of death" turns endlessly...

I have already reported this behaviour (Bitwarden, not Vaultwarden) to support. The last response was as following:
I will forward this to our dev team for their consideration. I personally see it as an improvement request.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Client: 1.31.3 (and older Versions), Server Installed:1.44.1 (and older Versions)

**Comment by Hinton** [comment]
This is the expected behavior, the client will log out if it receives a 400, 401 or 403 error. You should be able to configure the reverse proxy to send another status code if the resource is gone.
