### ISSUE TITLE
Search dialogue in Firefox extension drops characters while typing (fast)

### ISSUE THREAD

**Issue by anastrophe** [bitwarden/desktop#1398]
### Steps To Reproduce

1. Go to Firefox browser add-on in toolbar
2. Click in search dialogue (if necessary - normally cursor is in dialogue already)
3. Type in desired search term
4. I am an extremely fast typist. Characters are dropped intermittently as algo attempts to realtime search

### Expected Result

I type in my search term without characters being dropped while I type.

### Actual Result

Start typing e.g. the word "Gargantuan". If I make the slightest pause, perhaps just after the second 'g', sometimes the entire entered text disappears for a fraction of a second, then reappears having skipped the most recent character I typed during the blanking. Other times, I can see the cursor go backwards a character while I'm typing, as if I hit the backspace key. This happens fleetingly, and appears to be the algo seeing a micropause and deciding it should begin 'live' search, which blocks the keyboard input for that fraction of a second.

### Additional Context

I have not yet tested this in other browsers besides Firefox, if needed I'll do so.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H1 19043.1526

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.56.6

**Comment by djsmith85** [comment]
Hi @anastrophe, thank you for the report.

This has already been reported on https://github.com/bitwarden/browser/issues/2371. Please add any details there.

Closing this now, as duplicate.
