### ISSUE TITLE
Windows Store

### ISSUE THREAD

**Issue by Morgy93** [bitwarden/desktop#14]
Any chance to get the app into the Windows Store via the Desktop Bridge?

"Microsoft developed a tool that compiles Electron apps as .appx packages, enabling developers to use some of the goodies found in the new application model."
https://electronjs.org/docs/tutorial/windows-store-guide

https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge

**Comment by kspearrin** [comment]
I'll look into this more.

**Comment by kspearrin** [comment]
I'm now building appx for windows store. We'll plan to publish for stable.
