### ISSUE TITLE
Secure Notes can still be viewed without providing master password when master password re-prompt is enabled 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/desktop#1401]
### Steps To Reproduce

1. Go to desktop client or the web extension
2. Create a secure note 
3. Enable master password re-prompt 
4. Save
5. Search the item and try to view it 

### Expected Result

The expect result should be the same as in the web vault where before you can view the secure note, the master password needs to be entered. After that you can view or edit the note. 

### Actual Result

In the desktop client and web extension the secure note content can be viewed without providing the master password. Master password is only required when trying to edit the note 

### Operating System

Windows, macOS, Linux

### Installation method

Mac App Store

### Build Version

Version 1.30.0 (1935)

**Comment by Hinton** [comment]
Hi,

We're tracking this feature request in the forums, https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737. Please continue the discussion there, the issue will be closed.
