### ISSUE TITLE
Newline characters get stripped from custom fields data

### ISSUE THREAD

**Issue by Kouassi-Goli** [bitwarden/desktop#1402]
### Steps To Reproduce

1. Save an item and create an associated custom field
2. Input multi-line data the custom filed (GPG key, SSH key, JSON...)
3. Save the item.
4. Copy the custom field data.

Here I have created a note with the same JSON data in a custom field.

### Expected Result

The data should be the same (with all new line characters)

### Actual Result

All new line characters get stripped from the data resulting in a weirdly formatted data. This can cause issues with say GPG keys.

### Screenshots or Videos

![Screenshot from 2022-03-14 16-08-23](https://user-images.githubusercontent.com/31928919/158201644-38c7bc6c-3914-4ced-b8a8-89af3271b32a.png)

### Additional Context

The behavior is the same across all applications and all platforms.

### Operating System

Linux

### Operating System Version

Ubuntu 21.10 x64

### Installation method

Snap

### Build Version

Version 1.31.3 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by nellsavedra** [comment]
Same behavior on Android 12 app version 2.17.0 (4526), Firefox extension version 1.57.0 and macOS 12.2.1

**Comment by nodakai** [comment]
FYI https://community.bitwarden.com/t/add-an-additional-multi-line-text-field/2165

**Comment by dwbit** [comment]
Hey everyone, since this is an ongoing discussion and requires a change/enhancement, this issue will be closed and conversation can continue in the Bitwarden Community Forums [Add an additional Multi-Line Textield](https://community.bitwarden.com/t/add-an-additional-multi-line-text-field/2165/11) feature request topic.

**Comment by nodakai** [comment]
Oh my. Then @nellsavedra @Kouassi-Goli please come and vote for the Discourse thread so that our voices are heard. 23 votes for it so far
