### ISSUE TITLE
Can't login on Linux after changine KDF

### ISSUE THREAD

**Issue by alien2003** [bitwarden/desktop#141]
Can't sign in on Linux after changind KDF to 50,000. I tried to rm -rf Bitwarden's data folder. Windows/Android/Firefox/CLI versions work as expected, only Electron Linux app is affected

**Comment by kspearrin** [comment]
Are you using an old version that doesn't support KDF changes? You need version 1.70 or greater.

**Comment by alien2003** [comment]
oh yes... sorry
