### ISSUE TITLE
macOS: Menubar icon can't open window if closed via red close button

### ISSUE THREAD

**Issue by mjswensen** [bitwarden/desktop#143]
On macOS (Mojave 10.14), the tray icon toggles showing and hiding of the Bitwarden window. However, if the window is closed via the red close button in the upper-left corner, there is no way to restore the window as far as I can tell. The app must be quit and re-opened.

Thank you for your time and for all your hard work on Bitwarden!

**Comment by tauren** [comment]
👍 this is definitely annoying. Only way to get the window to show again is to close the app, reopen it, and login again.

**Comment by koraykupe** [comment]
I also have this issue. The system tray icon is useless at this moment.

**Comment by David240** [comment]
The same. High Sierra 10.13.

**Comment by mchonan1996** [comment]
@kspearrin You could probably close this issue, as it has been fixed in the above pull request.
