### ISSUE TITLE
Wrong translation in German Configuration Tab

### ISSUE THREAD

**Issue by myssv** [bitwarden/desktop#1445]
### Steps To Reproduce

1. Go to Datei / Einstellungen
2. Scroll down to EINSTELLUNGEN
and see the next box

### Expected Result

a german text

### Actual Result

other language

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/65643813/159951935-42461c00-be1a-4ce2-8be0-0f95a89a4307.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Microsoft Store

### Build Version

1.32.1

**Comment by djsmith85** [comment]
Hi @myssv thank you for your report.

Our translations are created by our amazing community via [Crowdin](https://crowdin.com/project/bitwarden-desktop). I just checked the [translation](https://crowdin.com/translate/bitwarden-desktop/53/en-de?filter=basic&value=0#q=App%20Se) and indeed a translation from a different language snuck in. I've downvoted the wrong translation and upvoted the correct one (I'm a native German speaker).

I'll keep this open until the next sync with CrowdIn, which I'll likely monitor and merge.

**Comment by djsmith85** [comment]
Confirming that the correct translation was imported via the Crowdin sync through #1451. This will be included in the next release.
