### ISSUE TITLE
An error has occurred with import keepass2.xml.  Ciphers[11]: The field Notes exceeds the maximum encrypted value length of 10000 characters.  

### ISSUE THREAD

**Issue by inthemix94500** [bitwarden/desktop#145]

**Comment by inthemix94500** [comment]
Hi
i have a problém with import keepass2.xml

i have this message perharp what free version is limited in number entries !

An error has occurred.

Ciphers[11]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[17]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[139]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[140]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[143]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[145]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[153]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Best regards

**Comment by tekchip** [comment]
Bump.

Receiving this when trying to import LastPass CSV. Attempted to do this by the instructions here https://help.bitwarden.com/article/import-from-lastpass/ using copy/paste.

Linux Ubuntu Budgie 18.10, Firefox Quantum 62.0.3 (64-bit).

**Comment by kspearrin** [comment]
You'll need to open the import file and locate the offending items at the given indexes in the error message. Either remove the items or reduce the amount of data that is trying to be imported for that item. Then save and try again.

**Comment by pepa65** [comment]
Is it possible to increase the maximum encrypted value length?

**Comment by TheLinuxNinja** [comment]
removing the entry is not an option, as it needs to be stored in the Vault. The entry in my case is a PGP key, so it's >10000 characters. LastPass has no issue with these, which is the problem I run into when trying to import LP vault to BitWarden. Removing the entry from the import file allows the import to succeed, but still unable to add the entry manually using the vault.
