### ISSUE TITLE
Presumably after an I update, I have two installations of Bitwarden

### ISSUE THREAD

**Issue by Simon311** [bitwarden/desktop#1455]
### Steps To Reproduce

Update from version 1.32.0.0 to 1.32.1.0.

### Expected Result

Bitwarden gets updated wherever it was installed

### Actual Result

Two desktop shortcuts, one to original install location (D:\Program Files\Bitwarden in my case) and one to C:\Users\Simon\AppData\Local\Programs\Bitwarden. Both locations have a Bitwarden install, version 1.32.0.0 in the former and version 1.32.1.0 in the latter.

### Operating System

Windows

### Installation method

Other

### Build Version

1.32.1

**Comment by Simon311** [comment]
I would like to know what to do in the situation as well. Should I reinstall to my original install location? Will the next update break it again?

**Comment by Hinton** [comment]
Hi @Simon311,

I posted a reply in the other issue thread, bitwarden/clients#2571. Please uninstall both and re-install it. We've done some work on ensuring the updater will behave better in the future and I believe it should install to the correct location after the next update.

If not feel free to comment here and I'll reopen the ticket, thanks.

**Comment by HookDuke** [comment]
I have noticed this same behavior. What I have done to get is working is when I notice the updates are available, open Bitwarden using "Run as Administrator" and let the update proceed. That behavior won't happen again until the next time an update is released and trying to install. Simply follow that procedure again the next time an update is available.

**Comment by Simon311** [comment]
> Hi @Simon311,
> 
> I posted a reply in the other issue thread, [#1423 (comment)](bitwarden/clients#2571). Please uninstall both and re-install it. We've done some work on ensuring the updater will behave better in the future and I believe it should install to the correct location after the next update.
> 
> If not feel free to comment here and I'll reopen the ticket, thanks.

I am not sure why you guys had to break things. I followed your advice now and the problem with it is that your installer gives me no option to install in the previous location, which was on drive D. What would you recommend to actually install it on drive D?
