### ISSUE TITLE
Not Autofilling On Walmart.com - Mac OS - Firefox, Safari and Chrome

### ISSUE THREAD

**Issue by greenmo99** [bitwarden/desktop#1471]
### Steps To Reproduce

1. Go to 'www.walmart.com'
2. Click on 'Sign In Account'
3. Click on 'Sign In'
4. Try to autofill with 'cmmd+shift+L'
5. Got to Bitwarden extension on toolbar and try to autofill by clicking on 'username' under 'logins'
6. Repeat above on Firefox, Safari and Chrome

### Expected Result

Email address will be autofilled, allowing me to navigate to the password page.

### Actual Result

Nothing happens.

### Additional Context

Bitwarden is working very well on every other site I try, but for some reason www.Walmart.com doesn't work.

### Operating System

macOS

### Operating System Version

11.6.4

### Installation method

Mac App Store

### Build Version

1.32.1

**Comment by dwbit** [comment]
Hi @greenmo99, have you already tried using [custom fields](https://bitwarden.com/help/auto-fill-custom-fields/#using-linked-custom-fields) to solve the issue? You can also provide auto-fill fail information [in this issue](https://github.com/bitwarden/browser/issues/1621), and here is a direct link to the [form](https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform).

You can report any further specific auto-fill fail issues using the Github issue and form above, so I'll close this issue now.
