### ISSUE TITLE
1.32.1 Upgrade Notice on Boot; Failure to Upgrade from 1.31.3

### ISSUE THREAD

**Issue by tlforrester** [bitwarden/desktop#1474]
### Steps To Reproduce

Start Windows, get upgrade notice.  Every time.  Version remains at 1.31.3

### Expected Result

Upgrade to 1.32.1 to complete.

### Actual Result

Apparently the upgrade fails although there is no indication of error.

### Operating System

Windows

### Operating System Version

10

### Installation method

Other

### Build Version

1.31.3

**Comment by Hinton** [comment]
Closed as duplicate of bitwarden/clients#2571
