### ISSUE TITLE
Release builds trigger Content Security Policy errors

### ISSUE THREAD

**Issue by SchnWalter** [bitwarden/desktop#1475]
### Steps To Reproduce

1. Install the latest package`*` from the release page, currently `v1.32.1`
2. Open the developer tools using F12 or the View menu.

`*` I was using the Debian release, but this probably affects all package.

### Expected Result

The developer tools should show no errors.

### Actual Result

There are several CSP errors like this:
```
Content Security Policy of your site blocks the use of 'eval' in JavaScript`
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.
1 directive
Source Location	Directive	Status
vendor.js:36113	script-src	blocked
Learn more: Content Security Policy - Eval
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/2186426/162073022-16931f0f-fb0a-46ff-808d-d11a78d74490.png)

### Additional Context

Those errors exist because `NG_DEV_MODE` is set to `true`. In Angular, that flag should always be `false` in production builds.

I think that with some small changes to the application, that custom webpack build setup could be simplified, and maybe even removed. It's best to avoid custom build setups, it helps avoid issues like this and reduces the maintenance cost in the long run.

P.S. I still haven't decided if I'll stick to Bitwarden, but when I'll do, I'll try to provide some patches for this.

### Operating System

Linux

### Operating System Version

Debian GNU/Linux 11 (bullseye) x86_64

### Installation method

Other

### Build Version

1.32.1

**Comment by Hinton** [comment]
Hi @SchnWalter,

Thanks for letting us know. This has already been fixed in https://github.com/bitwarden/desktop/pull/1408 and will be included in the next release.
