### ISSUE TITLE
MacOS 2 factor not prompting

### ISSUE THREAD

**Issue by JeremyS132** [bitwarden/desktop#149]
I am running MacOS Mojave running Bitwarden 1.9.0. I am running self hosted and currently have 2 factor turned on. The first method is via Yubikey the second is through Google Auth. I am not getting the prompt for 2 factor when logging out and re-logging in. Please note this is not a lock but clicking on Logout under account in Bitwarden. I have forced a sync but I am not getting the prompt for my yubikey or my google auth codes.

**Comment by kspearrin** [comment]
Maybe you clicked "remember me" on a previous 2FA prompt. Try deauthorizing your sessions from web the vault.

**Comment by Hinton** [comment]
Hi @JeremyS132, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
