### ISSUE TITLE
Full search doesn't work

### ISSUE THREAD

**Issue by pepa65** [bitwarden/desktop#151]
According to https://help.bitwarden.com/article/searching-vault/ the latest Bitwarden should have full search, but it's not working on Latest (1.9).

**Comment by kspearrin** [comment]
What about it isn't working? Seems to work fine in my tests.

**Comment by pepa65** [comment]
Well, it doesn't find text in the comments, only in the titles it seems?

**Comment by kspearrin** [comment]
Full text search should include the notes fields.

**Comment by pepa65** [comment]
Maybe since the 1.10 release? I'll try again. The report was against 1.09.0.

**Comment by pepa65** [comment]
Just tried with 1.10.0, created an entry with notes, searched for a string that is in the notes, and it doesn't find it. This is the amd64 deb release downloaded from Github.

**Comment by kspearrin** [comment]
Just testing this on 1.10.0 and it seems to work fine. Create an item with note value of 'pepa65', then did a search for 'pepa65' and it showed up as expected.

**Comment by pepa65** [comment]
Oh, haha! I see what you mean, if you type in the exact content of the notes field, it does find it. I was hoping for more of a substring match, that would be way more useful - feature request then.

**Comment by kspearrin** [comment]
Try `>notes:pepa*`

**Comment by pepa65** [comment]
It works erratically, I think you should look at the code. I tried your syntax `>notes:ap*` and it finds 1 entry while 2 are matching.

**Comment by pepa65** [comment]
It seems you don't care, but apps in this category that cannot be trusted to work well with simple things, are bound to be less trusted. I am just trying to help improve the app, and before properly resolving the issue, you're closing it.

**Comment by kspearrin** [comment]
If you provide proper steps to reproduce an issue, I'll consider reopening the issue.

**Comment by octoxan** [comment]
Okay I added a note to an item `(Some Test)`

Searching for `Some Test` returns zero results because I didn't include the parenthesis. Heck I can't even search for the word `Some` even though it's in the notes because  there's another character next to it. Seems parenthesis always break it.

Now I added 2 new items, `Property Solutions` and `Network Solutions`.

When I search for `Property Solutions`, it should definitely not be returning both results.

**Comment by pepa65** [comment]
Wouldn't it be much easier to allow parts of words to be matched?? And more versatile as well. I would welcome this. (If some people insist on matching whole words, perhaps a configuration option to this effect?)

**Comment by octoxan** [comment]
Download 1Pass, import some entries, do a search. I just want it to work as well as theirs does.

Let's say we have 50 entries, as a business with clients. 25 of them are for Property Solutions and 25 for Network Solutions, when searching explicitly for Network Solutions it should not show all 50 results lol.

Also we have many entries for the same site with the clients name in parenthesis after the site name... and these are only searchable if you include parenthesis in your search.. while other characters do not affect it in this way.

**Comment by skube** [comment]
I find that searching **Notes** within _My Vault_ works. However, strangely searching within an _Organization's Vault_ does not.
