### ISSUE TITLE
"Failed to fetch" since version 1.31.1 - self hostet instance

### ISSUE THREAD

**Issue by Garsem** [bitwarden/desktop#1518]
### Steps To Reproduce

After updating to a newer version than **1.30.0** (1.31.1 etc.) of the Bitwarden desktop application. When I try to log in, only this error message occurs.  'An error has occurred. Failed to fetch'. So you can not log in with the app.
The Bitwarden server runs the latest version of the self-hosted Bitwarden.

### Expected Result

Log-in and use Bitwarden

### Actual Result

Log-in is not possible

### Operating System

Windows, macOS

### Operating System Version

Windows 10, Mac os 12.0 Monterey

### Installation method

Mac App Store, Microsoft Store

### Build Version

1.33.0

**Comment by Hinton** [comment]
Hi @Garsem,

Which server version are you using?

**Comment by Hinton** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. Please reach out to our customer success over at: https://bitwarden.com/contact and they will assist you with troubleshooting this issue further, You can include a link to this issue in the message content.
