### ISSUE TITLE
File -> Settings greyed out on Ubuntu 16.04

### ISSUE THREAD

**Issue by mohamedadaly** [bitwarden/desktop#152]
I tried both the AppImage and Snap versions on Ubuntu 16.04. On both, the File -> Settings (and many other menu options) are greyed out. Some of them work with the hot key (e.g. Ctrl+L to lock the vault), others don't have shortcuts (e.g. Settings). Is there a workaround for this? Thanks ...

**Comment by et304383** [comment]
Experiencing the same issue on Ubuntu 18.04.  Nearly everything is greyed out.

**Comment by Fiech** [comment]
Can confirm on Ubuntu 16.04 LTS _Xenial Xerus_

Every Menu Item concerning the actual Bitwarden functionality is greyed out. All of _File_ and _Account_, as well as _Search Vault_, _Password Generator_, and _Password History_ in the _View_ menu.

Shortcuts (where available) as well as the the buttons at the bottom (+) are working. Very inconvenient as I cannot force sync the vault...

I'm using the current version available via the built-in update routine of Bitwarden desktop and a self hosted Bitwarden docker instance, which I just updated via `./bitwarden.sh updateself` and `./bitwarden.sh update`.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/50
