### ISSUE TITLE
No OTP verfication after log out 

### ISSUE THREAD

**Issue by abd1rahmane** [bitwarden/desktop#1532]
### Steps To Reproduce

1. Open Bitwarden and Login (Email + password)
2. ✅  OTP verification 
3. logged in
4. Log out and close Bitwarden
5. Open Bitwarden and Login (Email + password)
6. ❌ No OTP verification ! (_The problem is here_)
7. logged in

NB: The website works fine .

### Expected Result

- Step number 6 : Ask for **OTP verification.**

### Actual Result

- Step number 6 :  **No OTP verification**.

### Additional Context

Version 1.33.0
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

### Operating System

Linux

### Operating System Version

Ubuntu 20.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

 1.33.0

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
