### ISSUE TITLE
js2c crash on windows

### ISSUE THREAD

**Issue by fls-indinf** [bitwarden/desktop#1533]
### Steps To Reproduce

Start Bitwarden via autostart on windows. Then the crash popped up. 

### Expected Result

no crash

### Actual Result

![image](https://user-images.githubusercontent.com/59866126/171799619-42f152c8-fcf8-4932-9279-88fdb47e1643.png)

### Additional Context

maybe related to https://github.com/bitwarden/desktop/issues/495

### Operating System

Windows

### Installation method

Chocolatey

### Build Version

1.33.0 Node 16.9.1

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
