### ISSUE TITLE
Mac: get code signature error

### ISSUE THREAD

**Issue by Chris53897** [bitwarden/desktop#1534]
### Steps To Reproduce

The updater shows an error

`Error: Could not get code signature for running application
at Server.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar/main.js:18804:36)
at Object.onceWrapper (node:events:513:28)
at Server.emit (node:events:394:28)
at emitListeningNT (node:net:1353:10)
at processTicksAndRejections (node:internal/process/task_queues:82:21)

An upgrade from 1.33.0 to 2022.5.0 looks suspicious. So i cheked this page to verify.

### Expected Result

Correct Update

### Actual Result

Error (s. Above)

### Additional Context

I am not sure if i have the direct download version.

Version 1.33.0
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture arm64

### Operating System

macOS

### Operating System Version

12.4

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

1.33.0

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
