### ISSUE TITLE
Macbook Air M1 app not working correctly

### ISSUE THREAD

**Issue by dev-gbassanini** [bitwarden/desktop#1535]
### Steps To Reproduce

1. Open app (external monitor connected too, not sure if this has some effect on the issue)
2. Even though the app is functional (allows to copy passwords, etc...) the main window is stuck: can't close it, can't resize window, half the search bar is under app title bar and cant bring it in front, there's no minimize or fullscreen button (maybe hidden behind app title bar) only option is to use "hide to menu bar" in order to "minimize it"

### Expected Result

App window working correctly:
Showing all the minimize, fullscreen and close buttons
Search bar showing correctly

### Actual Result

Can barely use the app, can't even get the app build version as the pop up window does not show

### Screenshots or Videos

<img width="803" alt="Screen Shot 2022-06-04 at 14 40 55" src="https://user-images.githubusercontent.com/19476843/172023231-6f3119e8-10a0-4e7b-b181-083d9e6c597f.png">

### Operating System

macOS

### Operating System Version

Monterrey 12.4

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by dev-gbassanini** [comment]
Confirmed, this issue appears when you have an external monitor connected.

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
