### ISSUE TITLE
Prevent application window momentarily being displayed upon startup when 'Start To Tray Icon' is enabled

### ISSUE THREAD

**Issue by monkeyhybrid** [bitwarden/desktop#1537]
### Steps To Reproduce

1. Enable 'Start To Tray Icon' in settings.
2. Exit Bitwarden desktop client.
3. Start Bitwarden desktop client.
4. Observe application window is momentarily displayed before being minimised to system tray icon.

### Expected Result

With 'Start To Tray Icon' enabled, the application window should not be displayed at all when being first opened.

### Actual Result

The application window is momentarily displayed (or at least the window decorations are) before being minimised to system tray icon, albeit only for a very short time (less than a second).

### Operating System

Linux

### Operating System Version

Kubuntu 21.10

### Installation method

Snap

### Build Version

Version 2022.5.1 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by monkeyhybrid** [comment]
I just noticed a previously reported issue, #831, requesting the same fix, but it was closed due to being marked as stale.

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
