### ISSUE TITLE
is version v2022.5.1 the latest stable version or another pre-release?

### ISSUE THREAD

**Issue by suschizu** [bitwarden/desktop#1538]
### Steps To Reproduce

 @vgrassia ... because the App Store download still contains 1.33.0 
I'm asking because the last build was changed to a pre-release after a few days?
Thanks

### Expected Result

**

### Actual Result

**

### Additional Context

**

### Operating System

macOS

### Operating System Version

Big Sur

### Installation method

Homebrew

### Build Version

1.33.0

**Comment by vgrassia** [comment]
Version 2022.5.1 is the latest stable release.  The AppStore assets were submitted today and are awaiting approval by Apple. All future releases can be found in our [clients](https://github.com/bitwarden/clients/releases) repository.

**Comment by suschizu** [comment]
thanks for the information!
