### ISSUE TITLE
bitwarden.com has no CSP

### ISSUE THREAD

**Issue by johngraybosch** [bitwarden/desktop#1539]
### Steps To Reproduce

The bitwarden.com site does not have a content security policy set. This could allow for cross site scripting attack vectors. The main risk would be that the Login button could be rewritten to redirect to a phishing site.

Here is the report from Mozilla Observatory for the main site:

[https://observatory.mozilla.org/analyze/bitwarden.com](https://observatory.mozilla.org/analyze/bitwarden.com)

### Expected Result

The vault.bitwarden.com site has the expected level of security:

[https://observatory.mozilla.org/analyze/vault.bitwarden.com](https://observatory.mozilla.org/analyze/vault.bitwarden.com)

As does the main 1password.com site:

[https://observatory.mozilla.org/analyze/1password.com](https://observatory.mozilla.org/analyze/1password.com)

### Actual Result

Here is the report from Mozilla Observatory for the main site:

[https://observatory.mozilla.org/analyze/bitwarden.com](https://observatory.mozilla.org/analyze/bitwarden.com)

### Screenshots or Videos

I'm also worried about the 15 different trackers that are included on the main website. Without a CSP, they could in theory also become weak spots and attack vectors. Bitwarden's security is then only as good as Reddit's or Quora's.

<img width="791" alt="Screen Shot 2022-06-10 at 4 38 29 PM" src="https://user-images.githubusercontent.com/1764921/173152417-e3a88877-3cf4-4eb5-ac53-27da00d20db0.png">

<img width="814" alt="Screen Shot 2022-06-10 at 4 39 10 PM" src="https://user-images.githubusercontent.com/1764921/173152426-9570521b-f589-4943-9225-a77a7f17e42d.png">

### Operating System

macOS

### Operating System Version

Montery 12.4 Safari 15.5

### Installation method

Other

### Build Version

Main Site

**Comment by Hinton** [comment]
Hi,

This repository is archived. Please create a new issue in https://github.com/bitwarden/clients.
