### ISSUE TITLE
"The name field is required" error when adding new entry to an organizations collection

### ISSUE THREAD

**Issue by NochEinKamel** [bitwarden/desktop#159]
We are running a local installation of bitwarden with an organization and shared collections.

**Steps to reproduce the error:**

1. Open the Mac desktop client
1. Select a shared collection on the left ((Or manually select the organization and a collection in step 4))
1. Click on the +-Button on the bottom
1. Add some information (e.g. just a name)
1. Click the floppy disk icon

**Expected behaviour:**

Entry should be saved and shared with the selected collection.

**Actual behaviour:**

A red error popup appears:

> An error has occurred.
> The Name field is required.

**Comment by kspearrin** [comment]
Sounds like you need to update your server.
