### ISSUE TITLE
Add attachment during item creation

### ISSUE THREAD

**Issue by rafaelalvessa** [bitwarden/desktop#163]
I've noticed that on the desktop, web and Android clients it's not possible to upload attachments while creating a new item. First I need to save it and then edit it in order to be able to add attachments. This happens with all item types. Is there any reason for this, any limitation with the implementation or design?

Creating a new item (no option to add attachments):

![Creating a new item](https://user-images.githubusercontent.com/7062203/48645055-66b4c500-e9dc-11e8-8aaf-2008972dd8e0.png)

Editing an item (option to add attachments available):

![Editing an item](https://user-images.githubusercontent.com/7062203/48645056-66b4c500-e9dc-11e8-81ce-1b8dffc9e389.png)

**Comment by ralvessa** [comment]
If this is going to be implemented, should I open similar tickets for the other clients (web and mobile)?

**Comment by kspearrin** [comment]
This process works like this because we need an item to associate the uploaded attachment to. If the item does not exist yet (assuming you upload the item before the item is actually created), there isn't a way to associate it. We would have to use some other type of temp storage solution.

**Comment by ralvessa** [comment]
I thought about that, but maybe the file could be uploaded without being linked to any item, and then one of these two options would happen:

1. The item is created and the file is linked to it.
2. The item creation is canceled and the file is removed.

**Comment by mmhasse** [comment]
I think the best (and rather standard) solution would be to provide an "apply" button in edit mode (between the "save" and "cancel" buttons). This way I could create the note, then attach an item, without having to leave and re-enter edit mode. Having the apply button would generally be useful, e.g. when editing lengthy notes.

In any case, it would be good user guidance to make the attachments field visible but greyed out from the beginning. As it stands, I was unsure if my premium subscription was even active, because I didn't see any indication of the attachment function.

**Comment by daniwb** [comment]
Having an apply button next to the Entry, would also be a good Workarround.

A solution would be, to remove the externalized upload, just create a list of items to be uploaded. When hitting save, they should be sent with the other information as well.

**Comment by SteganosaurusRex** [comment]
I really hope this feature is added. It's such strange design to have to create an item and then go back to edit mode in order to add an attachment.

Apply button would be great.

**Comment by rdsignr** [comment]
It seems that the issue has not been resolved, and no response has been given by Bitwarden to various solutions suggested by users above. At the very least, in the Add Item dialog, a note should be shown, indicating that the item needs to be saved first, before an attachment can be added.

**Comment by dwbit** [comment]
Hey everyone, since this is a request and not an Issue, I'll be closing it. There is an existing [feature request](https://community.bitwarden.com/t/add-attachment-during-creation/14817) on the Bitwarden Community Forums if you want to add your vote/voice to the request.
