### ISSUE TITLE
MacOS: Switch from Google Analytics to Matamo

### ISSUE THREAD

**Issue by BurungHantu1605** [bitwarden/desktop#165]
Just installed the MacOS app and it tried to connect to Google Analytics. There is a privacy friendly tracking choice: https://matomo.org/ - Easy to setup.

**Comment by Hinton** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
