### ISSUE TITLE
Uexpectedly shows all items

### ISSUE THREAD

**Issue by AlesRuzickaEu** [bitwarden/desktop#167]
Quite often (multiple times a day, usually while resuming work with Bitwarden) i get to situation when I click on some entry and I get both "Favourites" and "All items" to look active and showing all items (even when I did not try to go to different folder).

![image](https://user-images.githubusercontent.com/808041/48903538-17e3b100-ee5c-11e8-9f78-005e62168295.png)

**Comment by kspearrin** [comment]
Should be fixed in next version. Thanks.
