### ISSUE TITLE
Select item, start typing to jump to item does not work as expected

### ISSUE THREAD

**Issue by pedrogarcia** [bitwarden/desktop#173]
On any desktop app that you have on your computer, you can do as following:

1. Select any item in a table
2. Start typing something

The selection will jump to the item that nearest matches what you typed.
You can test it on Windows Explorer.

This does not work on Bitwarden desktop. 
You select an item, start typing, and nothing happens. 

This is frustrating, because the desktop app does not work and behave and feel like a proper desktop app, and it also does not have all the affordances and usefulness of desktop apps in general. This is really frustrating.

**Comment by riptide-dev** [comment]
@pedrogarcia -

Are you using the latest version? I just did it in:

Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

And it worked as expected.

Thanks!
