### ISSUE TITLE
安装过程中出错

### ISSUE THREAD

**Issue by fafnar** [bitwarden/desktop#175]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Bitwarden-Installer-1.11.2_2.exe
  应用程序版本:	1.11.2.0
  应用程序时间戳:	5a6fed7c
  故障模块名称:	nsis7z.dll
  故障模块版本:	15.14.0.0
  故障模块时间戳:	56e2d3d6
  异常代码:	c0000094
  异常偏移:	0003a1c4
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789
![snipaste_2018-12-04_15-04-25](https://user-images.githubusercontent.com/36658790/49424683-50797800-f7d6-11e8-97a2-c294180ffc24.png)

**Comment by fafnar** [comment]
> Does the portal windows app work for you?

便携版运行没有问题。
Portable version runs without problems.

**Comment by kspearrin** [comment]
Try downloading the installer assets manually here:
https://github.com/bitwarden/desktop/releases/download/v1.11.2/bitwarden-1.11.2-x64.nsis.7z

Place it in the same directory as the installer and then run the installer.

**Comment by fafnar** [comment]
@kspearrin 
Thank you, the problem is solved. 谢谢，问题解决了。
