### ISSUE TITLE
Windows: prompt for master password does not indicate it’s for BitWarden

### ISSUE THREAD

**Issue by wixoff** [bitwarden/desktop#176]

**Comment by wixoff** [comment]
I’m using Firefox on Windows 7 with the Bitwarden extension. When starting the browser I get a prompt for the master password, but nothing on that floating dialog box indicates it is for Bitwarden. 

It would be helpful to include the app name, an icon, and also the username, e.g. “[shield] Enter the BitWarden master password for xxx@yyy.zz.”  It might also be helpful to visually associate it with the extension icon. 

I’m not entering my password into an unidentified box.

**Comment by kspearrin** [comment]
That prompt isn’t from Bitwarden.

**Comment by wixoff** [comment]
Well, I cancel out every time so I guess that’s good!
