### ISSUE TITLE
Bitwarden (snap, flatpak) doesn't work with Wayland

### ISSUE THREAD

**Issue by andres-jurado** [bitwarden/desktop#178]
Bitwarden in Snap and Flatpak format doesn't start with Wayland on a fresh install of Ubuntu 18.10 amd64. 
AppImage works fine. On xorg, snap and flatpak have no problem starting.

**Comment by itsjaredbs** [comment]
I am seeing the same behavior under Ubuntu 18.10. Under the standard "Ubuntu" session (with Xorg), Bitwarden launches normally. Under "Ubuntu with Wayland", the Bitwarden snap package never launches.

`snapd` version
```shell
$ snap --version
snap    2.36.3
snapd   2.36.3
series  16
ubuntu  18.10
kernel  4.18.0-12-generic
```

bitwarden snap version
```shell
$ snap list| grep -E 'Name|bitwarden'
Name       Version  Rev    Tracking  Publisher      Notes
bitwarden  1.11.2   15     stable    bitwarden✓     -
```

mutter version
```shell
$ apt-cache show mutter | grep Version
Version: 3.30.2-1~ubuntu18.10.1
Version: 3.30.1-1
```

xorg version
```shell
$ apt-cache show xserver-xorg | grep Version
Version: 1:7.7+19ubuntu8
```

I do not know if this is a bitwarden issue, a Wayland issue, a mutter issue, a GNOME issue, and Ubuntu issue, a Snapcraft and/or Flatpak issue (I haven't tested the Flatpak like @andres-jurado), but I can at least confirm that simply logging out and switching the session is enough to replicate the issue and provide some details.

**Comment by koarlmichael** [comment]
The same problem with the upcoming Debian Buster (10), Gnome 3.30.

**Comment by VigilanteComedian** [comment]
Still a problem in Ubuntu 19.04 Disco with Bitwarden v 1.14. Other snap apps don't seem to show this problem (Discord and Telegram) so I suspect it's specific to the Bitwarden app.

**Comment by VigilanteComedian** [comment]
Reinstalled KDE Neon which is based upon Ubuntu 18.04. The latest respin is on 18.04.3 and now in a Wayland session the Bitwarden snap seems to open just fine - can anyone else confirm on other distros/environments?

**Comment by prometheanfire** [comment]
I just tested the 1.15.2 deb and it still launches within xwayland (exits when xwayland is killed).

**Comment by robertovallone** [comment]
Same problem in Ubuntu 18.04. The only way to launch Bitwarden is through
/snap/bitwarden/current/bitwarden

**Comment by tomodachi** [comment]
I suggest this be closed: 
 launches fine from flatpak in Fedora 35  using gnome-shell as well as sway

**Comment by prometheanfire** [comment]
> I suggest this be closed: launches fine from flatpak in Fedora 35 using gnome-shell as well as sway

Did it launch via the xwayland backend?  that's what this request is trying to avoid.

**Comment by tomodachi** [comment]
It's actually not entirely clear from issue if @andres-jurado  is attempting to run Bitwarden under a Xwayland or Wayland native. 
Since he just states that it "doesn't start with Wayland"

Either way it works BOTH under Wayland and Xwayland

` flatpak run com.bitwarden.desktop`
 Launches the bitwarden application with the application defaults (which result in a Xwayland session)
 this is how Gnome-desktop on Fedora and Sway  would launch bitwarden.

`GDK_BACKEND=wayland flatpak run com.bitwarden.desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`
Launches the bitwarden application  wayland native. 

This was tested on bitwarden 1.3.0

**Comment by prometheanfire** [comment]
sounds like it's good to go then :D

**Comment by eliykat** [comment]
Thanks for  the update @tomodachi, I'll closed this as resolved. If the issue persists, please let me know and I'll reopen.

**Comment by ExNG** [comment]
> `GDK_BACKEND=wayland flatpak run com.bitwarden.desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`

@tomodachi Starting bitwarden with your command exists with `139` and prints:
```
user@pc:~> GDK_BACKEND=wayland flatpak run com.bitwarden.desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote --enable-crashpad
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 08:42:24.019: Failed to load module "canberra-gtk-module"
[2:0309/084224.077218:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[2:0309/084224.087222:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
juser@pc:~> [47:0100/000000.125475:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
```

**Comment by RyanHir** [comment]
> > `GDK_BACKEND=wayland flatpak run com.bitwarden.desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`
> 
> @ tomodachi Starting bitwarden with your command exists with `139` and prints:
> 
> ```
> user@pc:~> GDK_BACKEND=wayland flatpak run com.bitwarden.desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
> [2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote --enable-crashpad
> (node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
> (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
> Gtk-Message: 08:42:24.019: Failed to load module "canberra-gtk-module"
> [2:0309/084224.077218:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [2:0309/084224.087222:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
> juser@pc:~> [47:0100/000000.125475:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
> ```

I am also getting the same results with the Flatpak. When running in XWayland, I am just getting a gray screen, as seen in the attached screenshot (Imagine the cursor in the expected location to open such a menu). ![Screenshot from 2022-03-20 16-28-22](https://user-images.githubusercontent.com/4690732/159186709-6275615e-710b-49f6-970d-b3921ba8bd4f.png)
I do however believe the application is running as the global menu dropdown is partially loading as seen here. 
![Screenshot from 2022-03-20 16-29-20](https://user-images.githubusercontent.com/4690732/159186754-37469c0d-6664-4e71-a082-8af368df7a80.png)

This is on GNOME 41.3 with the NVIDIA 510.54 driver on Arch Linux.
