### ISSUE TITLE
macOS app icon (some dock love)

### ISSUE THREAD

**Issue by TCattd** [bitwarden/desktop#18]
I don't know if i'm the only one, but http://prntscr.com/ihec2z that doesn't look quite well to me.

Look at the size/proportion of Finder, FaceTime, Sublime, iTerm2, Slack, that use the same square like type of icon.

Can we get some less rough one? please :)

It's not urgent of course, but greatly appreciated if it can be considered.

**Comment by kspearrin** [comment]
Seems we just need some padding rather than taking up all the available space for the icon.

**Comment by kspearrin** [comment]
This is fixed in next version. Same size as the slack app.

**Comment by TCattd** [comment]
Thanks Kyle :)

**Comment by kspearrin** [comment]
@TCattd Does it look better now with 0.0.7?

**Comment by TCattd** [comment]
Much better, Kyle http://prntscr.com/ihszyf much better :)
