### ISSUE TITLE
Bitwarden flatpak is outdated

### ISSUE THREAD

**Issue by kallisti5** [bitwarden/desktop#182]
The Flatpak for bitwarden is pretty outdated at 1.7.0.

https://github.com/flathub/com.bitwarden.desktop

Any chance of a bump to 1.11.x?

**Comment by tobstarr** [comment]
Also: I cannot run it as the name is `com.bitwarden` and I am running into this error

```
> flatpak run com.bitwarden
error: Invalid id com.bitwarden: Names must contain at least 2 periods
```

Any help?

**Comment by tobstarr** [comment]
Ah, looks like there is also a `com.bitwarden.desktop` will try this instead.

**Comment by kspearrin** [comment]
We don’t publish a flat pack. This is community managed.

**Comment by kallisti5** [comment]
You leave the community to manage a software application for passwords? Isn't that a massive risk?
