### ISSUE TITLE
Desktop app (Linux, from snap) does not honor proxy settings

### ISSUE THREAD

**Issue by Lalufu** [bitwarden/desktop#187]
Desktop app, installed from snap following the instructions on https://bitwarden.com/.

Using the app on a network that requires an outbound http/https proxy fails to connect to the server, as a direct connection is attempted, which is blocked by the network firewall. ```http_proxy``` and ```https_proxy``` environment variables are set correctly. I've also not found a way to configure a proxy directly in the app.

The same applies to the CLI tools.

**Comment by kspearrin** [comment]
We would likely need to add some options for this I suppose.

**Comment by hlestrat** [comment]
This is not related to an OS (nor snap, package or direct installation), since the problem also exists on Windows app. This is a blocking problem to use the app in production environment.

**Comment by Selmirrrrr** [comment]
Same issue here, I agree with @hlestrat, this is not related to a particular OS (hello Electron) I'm a premium user and cannot use the Windows app on my work laptop because of this...

**Comment by Selmirrrrr** [comment]
Btw, is there a way to sponsor this issue ?

**Comment by rigwild** [comment]
Having the same problem.

One solution would be to use Electron [`session.setProxy`](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig).
I don't know if this can be used dynamically at runtime. A CLI launch command may work.

Temporarily:
 - You can use the [Web vault](https://vault.bitwarden.com/) in your browser.
 - The [Bitwarden CLI](https://github.com/bitwarden/cli) supports environnement variables proxy settings.
 - Use a program to route all app traffic through your proxy transparently (SocksCap64, Proxifier)

That's not ideal though 🤐

**Comment by technicalguru** [comment]
No progress on this? It is open for almost a year. Want to use Bitwarden in my job environment and cannot due to this issue...

**Comment by kspearrin** [comment]
You can launch the application with the `--proxy-server` option. See here for more info: https://electronjs.org/docs/api/chrome-command-line-switches#--proxy-serveraddressport

**Comment by gsemet** [comment]
this option does not support proxy authentication. Please reopen it and support the proxy properly. I know this is annoying, pretty much everybody hates proxy, but life in corporation network is not easy, for the moment, bitwarden cannot be used in this environment except by using browser extension.

**Comment by redno2** [comment]
+1
