### ISSUE TITLE
haveibeenpwned password lookup support

### ISSUE THREAD

**Issue by kallisti5** [bitwarden/desktop#194]
haveibeenpwned now offers an API service to send a cryptographically anonymous hash of a password to see if it has been part of any compromises in the past.

https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#cloudflareprivacyandkanonymity

It would be nice if bitwarden tied into https://haveibeenpwned.com/Passwords allowed (opt-in) to report on site passwords which have been known compromised in the past.

**Comment by kspearrin** [comment]
We already do.

- https://twitter.com/bitwarden_app/status/976822321922039809
- https://blog.bitwarden.com/account-health-reports-for-premium-users-e4accfd9576d
