### ISSUE TITLE
never lock up automatically on ubuntu

### ISSUE THREAD

**Issue by jarod** [bitwarden/desktop#196]
I remember  one or two month ago, when I switch from unlocked bitwarden to other apps it will lock automatically after a few minutes. But with the latest version, it never lock up.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic


$ apt show bitwarden
Package: bitwarden
Version: 1.12.0
Status: install ok installed
Priority: extra
Section: default
Maintainer: 8bit Solutions LLC <hello@bitwarden.com>
Installed-Size: 146 MB
Depends: gconf2, gconf-service, libnotify4, libxtst6, libnss3, libsecret-1-0, libxss1
Homepage: https://bitwarden.com
License: GPL-3.0
Vendor: 8bit Solutions LLC <hello@bitwarden.com>
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: A secure and free password manager for all of your devices.
  A secure and free password manager for all of your devices.
```

**Comment by jarod** [comment]
Oh, you got me. I didn't set the lock option. Because I didn't know there are settings exists. Please view the attached screenshot, the menu is hidden.
![bitwarden](https://user-images.githubusercontent.com/7960/51455587-4f4fda80-1d85-11e9-82eb-964e8a15d340.png)

**Comment by kspearrin** [comment]
Try `Ctrl+Comma` to open settings.

**Comment by jarod** [comment]
I can click on the menu, and the menu item will show up. 
I guess this is an theme issue. Bitwarden used hard code black menu font color, maybe bitwarden should get the menu font color from the system theme setting.

**Comment by kspearrin** [comment]
Maybe. Sounds like a separate issue. I'll close this one now since the original issue is resolved.
