### ISSUE TITLE
TOTP Mismatch

### ISSUE THREAD

**Issue by jajabro1** [bitwarden/desktop#198]
TOTP codes are not matching when using Desktop and Mobile.

When logging on via desktop with the Firefox, Chrome extensions or the Desktop client the TOTP codes do not match up with the TOTP code on the mobile app.

Also, the codes generated by the Extensions or the Dektop apps are incorrect and only the ones generated by mobile apps seem to work.

**Comment by jajabro1** [comment]
Also. I have confirmed that the TOTP generator codes are the same in the account settings.

This happens with any and all TOTP accounts that are syncing across my devices.

**Comment by kspearrin** [comment]
Your system time is likely not correct tone one of the devices.

**Comment by jajabro1** [comment]
> Your system time is likely not correct tone one of the devices.

Oh, interesting I hadnt thought of that. Seems to work find on my desktop at work, but definitley have issues with my main computer at home. 

Ill try adjusting my time there.

Any other ideas on what it could be that I would give a shot adjusting?

Would the NTP my computers sync with cause the issue?

**Comment by ben-galusha** [comment]
I've experienced this issue as well. Bitwarden Desktop seems to rely on the system time for generating TOTP codes (at least on Windows, can't speak for anything else). If the system time is wrong, the code will be wrong. Perhaps Bitwarden should be changed to use NTP for time? It could fall back to the system clock if no network is available.

Would this work, or are there security risks associated with this?

**Comment by mlaterman** [comment]
I'm experiencing this issue on MacOS; I'm running v1.16.6 of the app and getting incorrect codes.
My timezone is set to PST

**Comment by MisterY** [comment]
Previously given suggestion should resolve your issues. If your system time is even 30 seconds apart from the service you are authenticating with, this may cause invalid codes. 
By very definition, [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) is based on time.

**Comment by Brainwasher06** [comment]
Same problem here, seting the time to auto on my computer did fix it
