### ISSUE TITLE
macOS mouse scrolling doesn't work

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/desktop#199]
Scrolling with a mouse on macOS doesn't work, though scrolling with two fingers on the trackpad works flawlessly.

BW 1.12.0
macOS 10.14.2

**Comment by Crocmagnon** [comment]
Still happening on 1.14.0

**Comment by kspearrin** [comment]
Just tested this with my logitech wireless mouse and it seems to scroll just fine.

**Comment by Crocmagnon** [comment]
Do you have Logitech Options installed ? I had it cause issues on Windows with other Electron apps. It's installed on my Mac.

I'll do some other tests tonight.

**Comment by kspearrin** [comment]
> Do you have Logitech Options installed ? 

I do not

**Comment by Crocmagnon** [comment]
Thanks for the insight, I'll try to uninstall Logitech Options and report back here.

For the record, here's the issue I was referring to earlier : https://github.com/microsoft/vscode/issues/56964

**Comment by Crocmagnon** [comment]
I'm unable to reproduce it today. I don't know why I thought I had the issue the other day... I'm closing the issue, I will reopen it in case I can find a way to reproduce it.

Thanks for your time !

**Comment by Crocmagnon** [comment]
I'm unable to reproduce it today. I don't know why I thought I had the issue the other day... I'm closing the issue, I will reopen it in case I can find a way to reproduce it.

Thanks for your time !

**Comment by DinoLeung** [comment]
@Crocmagnon I have problems with Logitech Options scrolling, I think it is related to this issue. See: #296 296
