### ISSUE TITLE
I cannot wait

### ISSUE THREAD

**Issue by starkers** [bitwarden/desktop#2]
I have an issue in that I cannot wait for this.. Big fan of your guys work and getting everyone I know to move to bitwarden.. Thanks!

PS: do you have any tips on things I can do to help me wait?
PPS: there will be a linux desktop client right? I'm happy to package it up for arch if so

-David

**Comment by kspearrin** [comment]
Yes, there will be a linux client. Tips are to use the browser extension instead.
