### ISSUE TITLE
Password copying results in different passwords (MacOS tested)

### ISSUE THREAD

**Issue by bensquire** [bitwarden/desktop#203]
I've noticed that if you use the copy icon, passwords are copied as you'd expect. However if you 'show the password', select and copy it, each character is seperated by a new-line.

Below is an example copy paste from a previously saved "item". It works correctly when creating, but not when viewing a password after creation, I suspect it's related to the colour formatting

```
Mno2@Tr33$5xI7csJiJD

M
n
o
2
@
T
r
3
3
$
5
x
I
7
c
s
J
i
J
D
```

![screenshot 2019-01-28 at 08 57 38](https://user-images.githubusercontent.com/600237/51824679-d8619700-22da-11e9-915f-b5b048184e2c.png)

**Comment by kspearrin** [comment]
Fixed in next version
