### ISSUE TITLE
Windows 10 program crashes when scrolling down to the bottom.

### ISSUE THREAD

**Issue by jacobschellenberg** [bitwarden/desktop#204]
I have uninstalled/reinstalled the program, still crashes. I can still view any other login info- but as soon as I scroll down to whatever that last item is- it just shows a white screen. I have to refresh/close the app for it to come back.

**Comment by jacobschellenberg** [comment]
Figured it out.

It was an item with the URI: https://paycom.com

If I remove the URI, crash stops. I also created a new item called it "a_test" to appear at the top, added the URI, as soon as I saved the Bitwarden view went white. I reloaded the app, it showed for a second then went white.

I went to my Android app, removed the URI, refreshed the desktop app, and it loaded just fine.

**Comment by kspearrin** [comment]
I can reproduce. Thanks.

**Comment by kspearrin** [comment]
It has something to do with this string icon from paycom.com. I posted about it here on StackOverflow, so I am really not sure. https://stackoverflow.com/questions/54470155/why-can-chrome-render-a-png-image-but-firefox-cannot

**Comment by henioStraszny** [comment]
I've had this problem on 1.15.2, I've did uninstalled and installed again and it disappear.

**Comment by rickysyamsi** [comment]
I can not reproduce this with latest Bitwarden Desktop App `version 1.16.6`.

**Comment by kspearrin** [comment]
This issue was fixed in a recent version.
