### ISSUE TITLE
Regex URIs displaying incorrectly

### ISSUE THREAD

**Issue by devsecdan** [bitwarden/desktop#206]
Regex URIs may not display correctly in view mode.

Edit mode:
![uri1](https://user-images.githubusercontent.com/6662937/52260565-6b738000-291e-11e9-8983-e64ac1949fd1.png)

View mode:
![uri2](https://user-images.githubusercontent.com/6662937/52260569-6d3d4380-291e-11e9-9046-9b6c98c74e47.png)

This does not seem to affect the browser extensions.

**Comment by meffect** [comment]
^https://.*google.co.uk.*$
