### ISSUE TITLE
Text dissapearing when adding new item

### ISSUE THREAD

**Issue by karlos455** [bitwarden/desktop#208]
When I add a new item, sometimes when filling the information, all the forms are cleared. 
Sometimes more than once on the same item. 

Maybe this is something due to the refresh/sync time?

This happens on at least 3 different machines.

OS: Windows 10 x64

**Comment by ShirokaiLon** [comment]
Is it similar to this issue https://github.com/bitwarden/browser/issues/847 or something different?

**Comment by karlos455** [comment]
No, this is something different. I can reproduce this by doing the following:

1) add new item
2) fill some (or all) the fields
3) wait (maybe a minute)
4) all fields are cleared

Sometimes this happens faster, meaning I'm adding a new item, and when I get to the "notes" field, all the above gets cleared.
