### ISSUE TITLE
ERR_NAME_NOT_RESOLVED for every url in Linux app

### ISSUE THREAD

**Issue by mc-buckets** [bitwarden/desktop#209]
I am running the desktop app on Ubuntu 18.04. It works fine when I am not connected to a VPN, but when I am connected to a VPN it does not work. I am connected to a VPN 100% of the time when using my computer unless I am testing an issue like this one. 

The UI throws a "failed to fetch" error. In the debug console, every URL is throwing an ERR_NAME_NOT_RESOLVED error. 

The web vault and the Android app both work fine while connected to the same VPN. Additionally, performing an nslookup on api.bitwarden.com also works fine while connected to the VPN.

I am at a loss on how to further debug. Please let me know if I am missing something obvious or if this is a bug. I'd be happy to clone the repo and do manual builds if the solution is simply modifying a config option somewhere. 

This might be related to https://github.com/bitwarden/desktop/issues/187 but I am not 100% sure.

**Comment by karlbateman** [comment]
I'm also permanently connected to a VPN and experienced similar issues. Whilst connected to my VPN I use `bitwarden --no-proxy-server` to launch Bitwarden which works for me.
