### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by pehlm** [bitwarden/desktop#21]
Thank you for your work! I'm on Ubuntu 16.04, having installed the DEB package 0.0.6. I'm on the swedish locale, which is included in Bitwarden app but the GUI is in english and I can't change that. The "File" menu is also just greyed out, there is a settings entry there but I can't click it. I know that the app isn't finished and I wanted to report the problem.
Thank you!

**Comment by kspearrin** [comment]
The disabled menu is a known bug with Electron on Ubuntu 16.04. Unfortunately we can't fix it at this time.

The locale problem is something separate though. Can you open the View > Toggle Developer Tools and run `navigator.language` in the console and let me know what it says?

**Comment by pehlm** [comment]
Running the command outputs: "sv". The GUI is in english though. Is there some dependency missing, which isn't installed at DEB install?

**Comment by kspearrin** [comment]
Whoops. I see the problem. Will be fixed in next version. Thanks.
