### ISSUE TITLE
vault doesn't lock on system sleep in Mac

### ISSUE THREAD

**Issue by ns740** [bitwarden/desktop#210]
macOS 10.14.3 Mojave
Bitwarden 1.12.0
Preferences|Lock Options set to "On System Sleep"

But vault doesn't lock when system sleeps.   

For example, if Bitwarden is running with the vault open,   
then neither:  
1) closing the lid 
2) choosing "sleep" from the apple menu  

cause the vault to lock.  
in both cases (after reauthenticating via touchid) the vault remains unlocked

**Comment by kspearrin** [comment]
I am not able to reproduce, but I am on High Sierra, so not sure if that has anything to do with it.

**Comment by ns740** [comment]
it might.   
i can confirm that the lock (both on idle and on sleep) aren't working on my system.

What *DOES* work are the "timer" locks (1 min, 5 min etc) in both the desktop app and the firefox and safari extensions, as well as the "browser restart" lock options in the firefox and safari extensions.

Not sure if this is related, but if i enable the "Enable Tray Icon" setting, the icon displays in the tray it's just an icon displaying in the tray - it doesn't respond to hover, or click, or right click, and it doesn't change (or badge) if i lock the vault.    (unlike the icon that displays for the browser extensions).

Is there something I can do on my end to help you reproduce the "fail to lock" problem?

**Comment by ns740** [comment]
it might.
I can confirm my MacOS desktop app fails to lock the vault on "on sleep" and also "on idle" (assuming closing the lid for a while is a way to induce idle).

What *DOES* work are the timer options (1min, 5min etc) in the desktop app and also the timer and browser restart options in the safari and firefox extensions.

Not sure if this is related but if i enable the "Enable Tray Icon" setting, an icon does appear in the tray, but it doesn't respond to click or rightclick or hover and it doesn't change (or badge) when the vault locks (unlike the icon displayed by the browser extensions that *DO* respond to clicks and hovers and do show the lock badge when the vault locks).   Not sure if this is supposed to be (not) working like this.

Is there something i can do to help you reproduce the "fail to lock on sleep/idle" problem on MacOS 10.14.3?   Log something or try something?   Please let me know
