### ISSUE TITLE
Windows: No way to access menu bar with keyboard, making it impossible to access with a screen reader

### ISSUE THREAD

**Issue by pitermach** [bitwarden/desktop#213]
I'm using the Bitwarden desktop client on both Mac OS and Windows, along with screen reading software ([NVDA](https://nvaccess.org/)). The screen reader is able to read the main window of the app fine, treating it like a webpage, but the same can't be said for the menu bar.

On Mac OS, this isn't a problem, because the app just integrates with the system menu bar and VoiceOver (the Mac OS Screen Reader) has a keyboard shortcut to focus it. On Windows, screen readers don't display the menus as part of the main window, which wouldn't be a problem except the normal windows keys to focus it don't work. Pressing Alt or F10 doesn't focus the menu, and pressing Alt+letter to drop down a specific menu doesn't work either. This is a serious problem because it literally makes it impossible to access certain sections of the app if you're blind. While some options, like lock or settings have hotkeys, other options that you might want to access like log out or check for updates don't and even if they did you couldn't discover this fact without opening the menus.

Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0

**Comment by kspearrin** [comment]
Thanks for the info. So would the fix here be to just make it possible to focus the menu via a hotkey or something? I think you said `alt` is the standard there?

**Comment by kspearrin** [comment]
Looks to be an issue with Electron. See here: https://github.com/electron/electron/issues/2504

Looks like it might be fixed in an upcoming version, though: https://github.com/electron/electron/pull/15302

**Comment by pitermach** [comment]
Yep, pressing alt to focus the menus would be helpful, as well as pressing Alt with the first letter of a specific menu to open it (IE Alt+F would immediately open the file menu). It's good that  the Electron developers have fixed the issue, as soon as it gets implemented in an Electron release I think it'll be crytical for bitwarden to update to that release. If it wouldn't be too problematic though I think a fix should still be implemented in the next bitwarden release, as I know a few blind BW users apart from myself who'd find it helpful.

Thanks for a fast response!

**Comment by pitermach** [comment]
I just noticed that this appears to be fixed, at least as of Bitwarden 1.16.6, though this could have easily happened earlier whenever the fix landed in Electron. Anyway I'm closing this ticket.
