### ISSUE TITLE
Errors from snap install on Ubuntu....

### ISSUE THREAD

**Issue by frohro** [bitwarden/desktop#215]
I did a sudo snap install bitwarden, and it appears to run okay, but in the terminal window, I get these messages:
** Message: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.227" (uid=1000 pid=8864 comm="/snap/bitwarden/16/bitwarden " label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.24" (uid=1000 pid=2437 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

**Comment by kspearrin** [comment]
Sounds like you need to grant Bitwarden the `password-manager-service` snap interface. More:

https://docs.snapcraft.io/interface-management/6154
https://docs.snapcraft.io/supported-interfaces/7744

**Comment by frohro** [comment]
Thanks kspearrin!  That worked.
Rob

**Comment by zakst** [comment]
Just in case someone finds this. An easier solution is to go to 

1. Go to Ubuntu Software
2. Search for the app throwing the error
3. Click Permissions
4. Turn `ON` Read, add, change, or remove saved passwords

That worked for me

**Comment by joeldjizanne** [comment]
@zakst  It's worked for me to after spent more than 5 hours to fix it
Thanks

**Comment by sparwow** [comment]
@zakst This worked for me.
Thanks!

**Comment by devidy** [comment]
> Apenas no caso de alguém encontrar isso. Uma solução mais fácil é ir para
> 
> 1. Vá para o Ubuntu Software
> 2. Procure o aplicativo que está lançando o erro
> 3. Clique em Permissões
> 4. Ative `ON`Ler, adicionar, alterar ou remover senhas salvas
> 
> Isso funcionou para mim

Thanks

**Comment by devidy** [comment]
> Just in case someone finds this. An easier solution is to go to
> 
> 1. Go to Ubuntu Software
> 2. Search for the app throwing the error
> 3. Click Permissions
> 4. Turn `ON` Read, add, change, or remove saved passwords
> 
> That worked for me

Thanks

**Comment by Thomas-Hartmann** [comment]
@devidy Thank you, that did it for me.

**Comment by brian2303** [comment]
> Just in case someone finds this. An easier solution is to go to
> 
> 1. Go to Ubuntu Software
> 2. Search for the app throwing the error
> 3. Click Permissions
> 4. Turn `ON` Read, add, change, or remove saved passwords
> 
> That worked for me
