### ISSUE TITLE
Autofill not working on applications in the Secure Folder (Samsung devices) 

### ISSUE THREAD

**Issue by LeonardoPantani** [bitwarden/desktop#219]
The autofill function works normally in normal apps, but not in the secure folder (samsung devices), which is a special ambient where applications are "protected".

**Comment by kspearrin** [comment]
I'm not sure. Maybe Samsung disable autofill in that folder?

**Comment by LeonardoPantani** [comment]
In the past I used LastPass, but I decided to switch to BitWarden because I did not like LastPass anymore. The application of LastPass, however, allowed the autocompletion also in the Secure Folder. In practice it shows a "widget" above the application where I can select the fields to fill

![video_20190227_135120](https://user-images.githubusercontent.com/35602340/53491701-53af9780-3a97-11e9-83b0-4c899920e282.gif)

**Comment by mhaluska** [comment]
I added Bitwarden to my Secure folder and then activated Bitwarden autofill there and it works. Can you try this?

**Comment by LeonardoPantani** [comment]
I tried to activate Bitwarden in the Secure Folder and now it works. Thank you!
