### ISSUE TITLE
[Portable version] Unexepected token < in JSON at position 0

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/desktop#225]
Hi,
I'd like to use Bitwarden at work but I can't install web extensions. However my IT departments gave me the Windows portable version.
We connections are filtered by the proxy. I can't access https://bitwarden.com for example.
Is it the reason why I can't log in?
Thank you.

![bitwarden](https://user-images.githubusercontent.com/5938828/53863088-87d00e80-3fe9-11e9-870e-05bea0200ac5.png)

Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

**Comment by kspearrin** [comment]
What does the login request look like under View > Dev Tools > Network?

**Comment by Primokorn** [comment]
@kspearrin I guess it means that the connection is blocked.
![bitwarden2](https://user-images.githubusercontent.com/5938828/53890605-cafda200-4028-11e9-9d96-52026fff5f07.png)

**Comment by kspearrin** [comment]
Yes, looks like your corporate network is blocking Bitwarden's servers. Not sure there is anything we can do about that.
