### ISSUE TITLE
[WINDOWS] tray issue

### ISSUE THREAD

**Issue by Lourys** [bitwarden/desktop#227]
I have downloaded the app from windows store and it doesn't go to the tray when I click on the minimize or close button whereas my settings tell it to do:
![image](https://user-images.githubusercontent.com/16736227/54074281-ed91f400-4290-11e9-8c62-d7868172f327.png)

Another thing (which can help I think):
If I click on Window => Hide to Tray, I got an error like this:  
![image](https://user-images.githubusercontent.com/16736227/54074232-54fb7400-4290-11e9-9fbf-14460a53bf76.png)
After that, if I do this again, the window correctly goes to the tray but I cant open it anymore, I have to kill the process to reopen the app.
I hope you can help me and solve this issue! :)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/111
