### ISSUE TITLE
TS Error 2403 on OpenBSD

### ISSUE THREAD

**Issue by basis0** [bitwarden/desktop#229]
While trying to get Bitwarden Desktop to run on OpenBSD I'm getting a TypeScript error TS2403.  The exact error is:

ERROR in node_modules/sweetalert/typings/sweetalert.d.ts(4,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'swal' must be of type 'typeof import("/home/jmorefield/src/bitwarden/desktop/node_modules/sweetalert/typings/sweetalert")', but here has type 'SweetAlert'.

I had to locally build the desktop-idle dependency and have that working fine, but this seems entirely unrelated.

OpenBSD 6.4
NodeJS v8.12.0
npm 6.4.1

Any ideas?

**Comment by kspearrin** [comment]
Are you trying to build from source or is this running one of the packaged apps?

**Comment by basis0** [comment]
I believe it may be related to https://github.com/t4t5/sweetalert/issues/890, but if anyone has any other ideas I would love to know!

**Comment by basis0** [comment]
I believe it may be related to https://github.com/t4t5/sweetalert/issues/890, but if anyone has any other ideas I would love to know!

**Comment by kspearrin** [comment]
I implemented a workaround to this problem (I opened that issue with sweetalert) so I am not sure why it isn't working for you.

**Comment by ray851107** [comment]
@basis0 I also encountered this problem today. Seems to be related to npm/npm#3497.

**Comment by djsmith85** [comment]
Hi @basis0 as this is an old issue and we switched over to sweetalert2, this issue should be resolved. While I am now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

Regards Daniel
