### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by paul1149** [bitwarden/desktop#23]
I'm on MX-17  Linux (debian 9.3). I move the BW appimage to the /opt directory, where it will be accessible by all users. Then in my ~/.config/bitwarden I changed the data.json file's permissions to "other: none".

Is this a good privacy scheme on a multiuser machine? Are there any other considerations? I'm assuming that in /opt, bitwarden will create a new ~/.config folder for each user in his home folder.

**Comment by kspearrin** [comment]
I am not a Linux user so I am not very knowledgeable about how you should set up your user permissions. Maybe someone else here can help answer that. What I can tell you is that we store all application data in Electron's `userData` path, which is defined here: https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by paul1149** [comment]
The standard program setup is to have a central location for the executable, for universal access. It then writes to the various user profiles, respecting the permissions of each profile, so users can't access each other's data. I would assume that's the case here, and would be surprised if it isn't, but because I'm the one who put the BW executable in the /opt folder, I just wanted to make sure.

**Comment by kspearrin** [comment]
According to Electron's docs it's at `$XDG_CONFIG_HOME` or `~/.config`. It seems to indicate that it would be stored per user.

**Comment by paul1149** [comment]
Yes, it did seem that way. I also wasn't sure about the data file having the standard user profile permissions: other: read. That means, I think, that other users can read it. Of course, they still need the PW to get to the clear data, but I don't know if physical access is a good idea or not. That's why I changed it to "none". Maybe I'm being over concerned.

**Comment by kspearrin** [comment]
It's you're concerned about read permissions for other users on the same machine, feel free to adjust them. The file contains only encrypted sensitive information.
