### ISSUE TITLE
Notes not being saved in 1.14.0 Desktop/Win 8.1

### ISSUE THREAD

**Issue by FrankTT3D** [bitwarden/desktop#230]
After updating to 1.14, I can sync (green success toaster), but in fact notes I entered through the browser extension do not appear in desktop version. When saving notes in desktop, error toaster "Unexpected error occured" pops up.

**Comment by kspearrin** [comment]
Bitwarden cloud server or some other?

**Comment by FrankTT3D** [comment]
This is on Cloud,
Version 1.14.0
Shell 3.0.14
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

Just verified it on other keys - same issue.

**Comment by kspearrin** [comment]
What method of installation? Store, exe, portable?

**Comment by FrankTT3D** [comment]
Exe, had the same issue installing the update from within BW (resolved apparently by admin permission) but I didn't check here so I closed BW, downloaded the exe and installed, which seemed to work fine. After reading #228 reinstalled exe also with admin - no change. Same not issue.

**Comment by kspearrin** [comment]
Have you tried logging out and back in to refresh the auth token?

**Comment by FrankTT3D** [comment]
I restarted several times with no effect, but explicitly logging out and in solved it! Thanks!
