### ISSUE TITLE
Login bug on Windows 10 

### ISSUE THREAD

**Issue by Ghost-Recon131** [bitwarden/desktop#233]
For some reason, Bitwarden will not accept any passwords when I open it then put the laptop to sleep and try to login after waking the laptop up from sleep.Clicking the login button does nothing with or without the correct password. Been happening since updating Bitwarden to V1.14.0. I’ve got this bug on my Windows 10 Pro laptop and PC both on 1809 17763.379. 

Originally posted here: https://community.bitwarden.com/t/cannot-login-bug/5197

**Comment by kspearrin** [comment]
Is this windows store or exe?

**Comment by Ghost-Recon131** [comment]
This is the exe version

**Comment by kspearrin** [comment]
Is this when unlocking or logging in? Can you reliably reproduce it or does it only sometimes happen?

**Comment by Ghost-Recon131** [comment]
It happens when logging in after booting from restart/shutdown. It will happen every time of the right steps were followed as outlined above. It's only been occurring on my Windows 10 PC and laptop but Mac doesn't have this problem.

**Comment by kspearrin** [comment]
so...

1. Open Bitwarden
2. Log out
3. Sleep computer - keep bitwarden app open... ???
4. Wake computer
5. Try to log in

?

**Comment by Ghost-Recon131** [comment]
Not exactly. 
1) Boot up computer
2) Open bitwarden (do not sign in)
3) put computer to sleep 
4) wake computer then login to computer 
5) enter the password to bitwarden 
this will then trigger the bug where clicking login will not do anything

**Comment by kspearrin** [comment]
Ok, just tried those steps and unfortunately did not reproduce the problem.

**Comment by Ghost-Recon131** [comment]
Hm perhaps it may be my antivirus causing the problem
