### ISSUE TITLE
Snap-installed

### ISSUE THREAD

**Issue by detly** [bitwarden/desktop#234]
On Ubuntu 18.04.1. Snapd 2.37.4+18.04.1. Bitwarden 1.14.0 installed via Gnome Software.

When I try to launch Bitwarden from the command line, I see:

    $ bitwarden
    /snap/bitwarden/17/bin/desktop-launch: line 248: [: too many arguments
    $

**Comment by kspearrin** [comment]
I am not sure. It seems to work fine here on my test Ubuntu 18 VM.

**Comment by djsmith85** [comment]
Hi @detly, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
