### ISSUE TITLE
Relaunching Bitwarden while it's running causes the view to lock up

### ISSUE THREAD

**Issue by CSAS-Nicholas-Roberts** [bitwarden/desktop#235]
If you have a hotkey or shortcut to bitwarden.exe and hit it while the program is open or running in the system tray, the window will react, but will cause the view to lockup. However, you can still close it without having to kill the program.

OS: Win 10
BW Version: 1.14.0 (although this problem has been present over the last few versions)
BW Shell: 3.0.14
Renderer: 66.0.3359.181
Node: 10.2.0
Architecture: x64

Steps to recreate...
1. Map a hotkey or shortcut to Bitwarden.exe
2. Open Bitwarden
3. Minimize it to the tray or focus another window
4. Attempt to open it again using the shortcut or hotkey

Workaround

1. Close the program completely by clicking the red x or by right clicking and closing in the status bar.
2. Reopen the program and it should be working normally.

**Comment by CSAS-Nicholas-Roberts** [comment]
Sorry about the open/close. I misclicked.

**Comment by kspearrin** [comment]
> Map a hotkey or shortcut to Bitwarden.exe

How do I do this in Windows?

**Comment by CSAS-Nicholas-Roberts** [comment]
If you right click on the desktop, choose new -> shortcut, and then browse to the Bitwarden.exe, there’s your shortcut. 

If you’ve already created a shortcut, you can right click it -> properties -> shortcut tab -> shortcut key to map a hotkey. 

Some keyboard software, like Logitech, will let you map a program to a specified favorites key on their keyboards by using their software too.

**Comment by kspearrin** [comment]
OK, I have that running but I am not able to reproduce any "lock up" while using the shortcut to launch the Bitwarden.exe, while running in tray or already open.

**Comment by CSAS-Nicholas-Roberts** [comment]
Weird...I was able to reproduce it on Saturday when I posted this, but it's no longer happening. Sorry to waste your time!
