### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by KaiserYang** [bitwarden/desktop#236]
Good afternoon,

Im a student learning about github thing. I wanted to download, open, modify and compile this repo  and I dont know how, I tried to search in the internet but maybe because this is a really noob question I couldnt find an answer. Can someone give some advices please? Im currently using Visual Studio IDE and I have just downloaded node.js
Thank you in advance.

**Comment by kspearrin** [comment]
This might be of help:

https://guides.github.com/

You need to clone the repo, then use the build instructions in the read me.
