### ISSUE TITLE
Tabs not displayed in 'NOTES' field

### ISSUE THREAD

**Issue by alemih** [bitwarden/desktop#238]
When you are in edit mode, everything is displayed correctly
![notes_edit_mode](https://user-images.githubusercontent.com/11029770/55052337-3c95a280-5061-11e9-9b6f-4ba6683ab8f6.PNG)
, but when you just viewing, tab's (tab keys) is not displayed.
![notes_disp_mode](https://user-images.githubusercontent.com/11029770/55052328-2f78b380-5061-11e9-98b6-b7b50c8d6363.PNG)
It appeared after last update from previous version to the
(Version 1.14.0
Shell 3.0.14
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64)

**Comment by alemih** [comment]
And I forgot to mention that in previous versions everything was displayed correctly.

**Comment by kspearrin** [comment]
Should be fixed in next version
