### ISSUE TITLE
Lock settings don't work on macos

### ISSUE THREAD

**Issue by neeilya** [bitwarden/desktop#240]
#### Versions:
Bitwarden version (MacOS): Version 1.14.0
MacOS version: Mojave 10.14.4

#### Problem:
Changing lock options in macos client doesn't have an effect.

For example, I have configured it to lock on system sleep and unlock with PIN:
![image](https://user-images.githubusercontent.com/3954686/55671216-e3621600-588d-11e9-99d9-69baaf67bb97.png)

But after reopening the app it asks for master password:
![image](https://user-images.githubusercontent.com/3954686/55671224-0987b600-588e-11e9-8193-270f32af510e.png)

Reinstalling the app didn't help.

**Comment by kspearrin** [comment]
Is this only a problem with "On system sleep"?

**Comment by neeilya** [comment]
> Is this only a problem with "On system sleep"?

@kspearrin, no, nothing except "Never" option works - it asks for master password immediately after I reopen the app.

**Comment by kspearrin** [comment]
Did you select the option to "Lock with master password on restart" when enabling the PIN?

**Comment by neeilya** [comment]
>Did you select the option to "Lock with master password on restart" when enabling the PIN?

Yes

**Comment by kspearrin** [comment]
Sounds like it’s working as expected then.

**Comment by neeilya** [comment]
What about this case:

![image](https://user-images.githubusercontent.com/3954686/55745762-442d5200-5a38-11e9-941f-97f46810ce88.png)

Is it correct that it asks for password every time I reopen the app?

---

Same goes for minutes intervals:
![image](https://user-images.githubusercontent.com/3954686/55745955-cc135c00-5a38-11e9-91aa-c08328c78f29.png)

After I reopen the app within 10 seconds:
![image](https://user-images.githubusercontent.com/3954686/55745978-d9304b00-5a38-11e9-8356-6384d7d76b74.png)

**Comment by kspearrin** [comment]
Unless you are using "Never" or PIN without "Lock with master password on restart" checked, the app will always lock whenever you restart it.

**Comment by Crocmagnon** [comment]
I guess the confusion here is that "Lock options" applies a timeout when the app is still running. It's not applied when you restart the app.

**Comment by kspearrin** [comment]
Correct. Using a lock option means that sensitive data, such as your encryption key, is only held in memory of the application. So if you restart the app, it is lost and must be provided again.
