### ISSUE TITLE
URL is detected but no login item appears

### ISSUE THREAD

**Issue by Pierrotsaturnien** [bitwarden/desktop#241]
Hi,
I’m using the Bitwarden browser extension for Microsoft Edge and I’m experiencing the following issue.
When I go on a website for which I have created a login item in Bitwarden, the extension shows me purposely that the website is recognised :  a number 1 appears in the extension. But when I open the extension, no matching login appears int the “Current tab” page. Have a look at the attached screenshot.
Even though, the right-click context menu shows the login item and also the auto-fill on page load, words perfectly.
Thanks for your help and kind regards.

![Annotation 2019-04-07 053129](https://user-images.githubusercontent.com/49356675/55678490-fc54e080-58fa-11e9-9743-61ee7702cc5f.jpg)

**Comment by kspearrin** [comment]
The Edge extension is currently affected by several bugs as outlined here:
https://github.com/bitwarden/browser/issues/744

We are waiting for the new Chromium Edge to come out, which should resolve all of these problems.
