### ISSUE TITLE
Ubuntu 18.04: a click on the locked vault window ought to give the master password text field focus

### ISSUE THREAD

**Issue by benklaasen** [bitwarden/desktop#242]
I'm running the BitWarden AppImage `Bitwarden-1.14.0-x86_64.AppImage` on Xubuntu 18.04.2 LTS.

The app starts in the locked mode, as I would expect. 

However a click on the app window doesn't give the master password text entry field focus, nor does a CTRL+TAB. 

Instead, once the app has focus, I need to hit TAB to give the field focus.

**Comment by kspearrin** [comment]
Hmm, this must have something to do with Linux and/or AppImage since both windows and macos give focus when the app is started on the lock screen.

**Comment by benklaasen** [comment]
Interesting! There's no PPA for Linux; perhaps you have a non-AppImage build I can try, in order to exclude AppImage as the source of the no-focus problem?

**Comment by kspearrin** [comment]
See here for options: https://github.com/bitwarden/desktop/releases

**Comment by kholisabdullah** [comment]
On my Lubuntu 18.04, after showing the window, the focus is in the menu bar. Pressing the ESC gives the focus to the password field or search field, rather than hitting the TAB so many times.
