### ISSUE TITLE
Following URL breaks windows application

### ISSUE THREAD

**Issue by jpeizer** [bitwarden/desktop#244]
After looking at it for a while I came to the conclusion that the following URL breaks the UI of the bitwarden windows application.

`https://www.paycomonline.net/v4/ee/web.php/app/login`

Setting this to the URl field will break the UI.

This does not appear to be restricted to a given Windows setup.

**Comment by kspearrin** [comment]
This is a known problem at the moment. It has to do with the broken favicon that paycom uses, which crashes the renderer process in Electron. Should be fixed when we update to Electron 4.

**Comment by nitrix** [comment]
As a temporary work-around, I think you could use the little gear icon and change the URL matching mode to prefix or regex until they update :)

**Comment by kspearrin** [comment]
> As a temporary work-around, I think you could use the little gear icon and change the URL matching mode to prefix or regex until they update :)

Yes, that would stop the application from trying to render the website icon.

**Comment by nitrix** [comment]
I deleted my comment to avoid speculating, but that's very useful @kspearrin. Much appreciated.

**Comment by xtqqczze** [comment]
Perhaps we could temporarily disable website icons by default, as requested in #253? @kspearrin

**Comment by xtqqczze** [comment]
Fixed in [v1.15](https://github.com/bitwarden/desktop/releases/tag/v1.15.2).
