### ISSUE TITLE
windows app login problem

### ISSUE THREAD

**Issue by alexlao26** [bitwarden/desktop#247]
So, I've activated my 2-step verification via email and whenever I log in to windows app, the first thing that I would do is enter my master password, then it asks me for the 2-step verification code. 

While waiting for the code in the email, sometimes, not all the time, the windows app will show a loading circle symbol, then it suddenly reverts back to asking me for the master password without me having been able to type the verification code yet. 

Is this a safety feature or a bug? In the web vault of bitwarden, this doesn't happen.

**Comment by kspearrin** [comment]
Does this only happen after you have recently logged out from another account?

**Comment by alexlao26** [comment]
Yes, I think this only happens whenever I recently logged out and try to log in again in the same account.

**Comment by kspearrin** [comment]
This would be by design then. Whenever you log off, after ~10 seconds of inactivity, the application reloads the process to make sure all memory space is properly cleaned up. This is what you are seeing.

**Comment by alexlao26** [comment]
Just tested it again just now after more than 3 hours of not doing anything. I opened the windows app, then first time I entered the master password, it happened again. I think there's a bug.
