### ISSUE TITLE
Support for manual Autofill for desktop applications ?

### ISSUE THREAD

**Issue by Moxville** [bitwarden/desktop#25]
Hi Kyle,
Any plan to add support for Manual Autofill of credentials for desktop applications like...
ProtonMail IMAP/SMTP Bridge
Veracrypt
Desktop VPN Applications

**Comment by kspearrin** [comment]
Can you explain, what is "manual autofill"?

**Comment by Moxville** [comment]
I have disabled "Enable Auto-fill On Page Load" in browser extension - I'm calling this as auto auto-fill
So every time I use a keyboard shortcut or I click the Login in extension to "Autofill" the credentials - that I call as Manual Autofill. 

The feature I was requesting is, in desktop app by clicking the "Login" or by using "keyboard shortcut for windows" the desktop app can recognize the windows application and autofill the credentials in application login prompt.

**Comment by kspearrin** [comment]
There arn't plans in the near future for autofilling in the desktop app at this time.

**Comment by Moxville** [comment]
thanks for your replies :)
