### ISSUE TITLE
Snap package doesn't open in Ubuntu Bionic

### ISSUE THREAD

**Issue by FMuro** [bitwarden/desktop#250]
Just installed from the snap store. In **doesn't** open in the following cases:

* Clicking on the desktop icon.
* Running `bitwarden` or `snap run bitwarden` from the terminal.
* Running `/snap/bin/bitwarden`.

However `/snap/bitwarden/current/bitwarden` **does** work.

**Comment by kspearrin** [comment]
It seems to work for me on Unbuntu 18 without issue. Any idea what could be different on your installation?

**Comment by FMuro** [comment]
No idea, it's a fresh install (both the operating system and the snap package), I've narrowed the thing to the symlink in `/snap/bin/`there must be something going on with it. It looks like an installation or packaging issue, since otherwise Bitwarden runs from the original file in `/snap/bitwarden/current/`. Have you also tried from a fresh install?

**Comment by VigilanteComedian** [comment]
Tagging #178 as your terminal code `/snap/bitwarden/current/bitwarden` seems to allow the snap to run on Wayland whereas normal entries/commands do not.

**Comment by FMuro** [comment]
I should say I experience this under both X and Wayland.

**Comment by morganatwishpond** [comment]
I'm experiencing this same issue with Disco on Wayland. Haven't tested it on X.

**Comment by focom** [comment]
Yes same issue on 19.04 with Wayland

**Comment by VigilanteComedian** [comment]
https://github.com/bitwarden/desktop/issues/178#issuecomment-520153221

Seems fixed in 18.04.3 but needs further testing.

**Comment by treellama** [comment]
Same issue in 19.10, with X11

**Comment by JackHack96** [comment]
Same here, 19.10 on X11
