### ISSUE TITLE
Select-all should select items; instead selects text

### ISSUE THREAD

**Issue by crispinb** [bitwarden/desktop#252]
Either Edit->Select All or ctrl-A should result in all items being selected. Instead it selects all text on the 'page'.

(Linux client v. 1.14.0)

**Comment by wolfika** [comment]
I can confirm this behavior is the same on the macOS 1.15.2 client. I guess this is just a platform-default button in the menu, since there's no way to select multiple items from the item list in Bitwarden anyway.
