### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Antonio-52** [bitwarden/desktop#254]
Environment:
PC: HP Laptop 15-da0xxx
OS: Windows 10 Home
Bitwarden:
Version 1.12.0
Shell 3.0.13
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

The PC is connected to Internet via WiFi.

1. As soon as I run Bitwarden, a message appears asking if I want to restart to apply an update (1.14).
2. Accept restart
3. Appears an error message warning a Javascript error (see attached file).
![Bitwarden erroreAggiornamento_2019-05-15](https://user-images.githubusercontent.com/46651541/57692717-c3b9cc80-7647-11e9-8539-5baa45f159f6.PNG)
The behaviour is highly reproducible also after a PC reboot.

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/desktop/issues/228
