### ISSUE TITLE
macOS tray icon doesn't switch to Bitwarden app on first click

### ISSUE THREAD

**Issue by eih** [bitwarden/desktop#256]
When enabling tray icon on macOS, and when the window is behind other apps, clicking the tray icon doesn't switch to Bitwarden. You can switch to Bitwarden only on second click. It should switch on first click.

### Recreating the issue
1. Enable tray icon from preferences
2. While Bitwarden app is visible switch to another app
3. Click tray icon once, it won't switch to Bitwarden app
4. Click tray icon again, this time it will switch to Bitwarden app

### Device info and version
Device: MacBook Pro (Retina, 13-inch, Early 2015)
Operating system: macOS Mojave 10.14.5 (18F132)
Bitwarden Desktop app version 1.14.0 (1.14.0)

**Comment by kspearrin** [comment]
On step 3, it minimizes the app for me, which is expected since the app is already open. Is this not what you expect?

**Comment by eih** [comment]
Hi,

When the app is open, but not in the front (i.e. hidden behind another app), I'd expect to be switched to it when I click on the tray icon. But when I click on the tray icon once, nothing happens. Only on second click I can switch to Bitwarden app (i.e. comes forward, above all appication windows). You're right, clicking a third time hides the Bitwarden window, but issue is I have to click the tray icon twice to see the Bitwarden window.

When I look at it now, my bug report was not so clear, sorry. I hope it is now, thanks.

**Comment by mjthompson** [comment]
This is an issue for me too, same symptoms you describe. Quite frustrating.

Device: MacBook Pro (Retina, 13-inch, Early 2015)
OS: macOS Mojave 10.14.6
Bitwarden Version 1.16.6 (1.16.6)
