### ISSUE TITLE
Keyboard shortcuts / hotkeys

### ISSUE THREAD

**Issue by ilya40umov** [bitwarden/desktop#26]
It would be nice to have enough shortcuts supported, so that the user does not need to use a mouse (ideally at all) when working with the app. And as usual there should be a popup with shortcuts under Shift + ?.
I would personally prefer Vim-based shortcuts for navigating the vault items, but I would totally understand if you decided to implement arrow-key-based shortcuts instead.

**Comment by kspearrin** [comment]
Please provide specific examples of shortcuts that are missing. I am not familiar with Vim-based shortcuts.

**Comment by ilya40umov** [comment]
1. Right now there are no shortcuts / hotkeys available in the desktop app (as far as I can tell).
Edit: I actually managed to discover that Tab and Shift+Tab can be used to navigate between items, and Enter can be used to open the selected credentials. However, I would normally expect there to be a menu items that would bring up a popup which would shot all the available shortcuts (as well as Shift+? shortcuts to access this popup from keyboard). 
2. When I wrote Vim-based, I mainly meant using j/k for navigating between credentials as opposed to using arrow keys.
3. Here is an example of keyboard shortcuts available in Google's Inbox: 
![inbox-shortcuts](https://user-images.githubusercontent.com/2254925/36508082-e5e0e506-175b-11e8-9a47-c704ba047b51.png)
E.g. I can use j/k to navigate between threads and n/p to navigate between emails within thread.

So, overall even if you stick to the already available shortcuts (partially visible in menu), I would recommend adding a few extra things like a shortcut for coping login, a shortcut for coping password, a shortcut for show password, a shortcut for opening a website etc. And then to make all them discover-able,  I would add that pop-up.

**Comment by shauser** [comment]
Also desperately needed:
- Cancel (Esc) and Save (Ctrl+Enter) when creating / editing an entry
- Generate password from entry (a variant which uses the current settings to generate the password and automatically stores it without even showing the popup would be even better)
- Focus menu tree (types, folders, ...) and item list (required if you add keyboard navigation)

Bonus points for:
- Ctrl+U to delete the text in front of the cursor (this is a standard feature on Linux for single line text entries and should really exist on all platforms - at least as an option)
- Being able to configure the shortcuts in a config file (support for keyboard layouts which have j/k keys in other places)

**Comment by cr-sh** [comment]
a BASIC feature like this, after 3 years wasted, become a a bug, not an enhancement.

**Comment by aleochoam** [comment]
For anyone that visits this issue, this is already resolved and you can find the documentation here: https://bitwarden.com/help/article/auto-fill-browser/#using-keyboard-shortcuts

**Comment by cr-sh** [comment]
I think that now, anyone who visit this issue, is wondering what, a link about browser extensions auto-fill, is suppose to solve in the missing navigation feature of the desktop app 😉

**Comment by aleochoam** [comment]
> 
> 
> I think that now anyone who visit this issue is wondering what, a link about browser extensions auto-fill, is suppose to solve in the missing navigation feature of the desktop app 😉

You are correct, I came here searching for the extension, did not notice this was the repo for the desktop app

**Comment by fsonntag** [comment]
Yep, can you edit or delete your answer then? :)
