### ISSUE TITLE
Ubuntu snap own self signed certificate 

### ISSUE THREAD

**Issue by trayntab** [bitwarden/desktop#260]
hi guys,
i use bitwarden self hosted on my server with a self signed certificate. i don't want to use it online with letsencrypt or something like that - just local in my network - or with a vpn remote on my devices. i had some issues with the certificate on iOS and MacOS. But after i import the certificate in the ca store on iOS and MacOS i can use bitwarden on it. 
But i have problems on ubuntu. i imported the ca in ubuntus ca store. 
 -copy it to this directory /usr/local/share/ca-certificates
 - sudo update-ca-certificates

but the bitwarden snap doesn't work. 

can you help me please?

ps: i think a better option were if bitwarden get an option "hey you use an self-signed ca - do you want to trust it?" in the program/app.

**Comment by kspearrin** [comment]
How did you generate this self signed cert?

**Comment by trayntab** [comment]
with the bitwarden docker script or do you mean the export? via firefox

best regards

**Comment by kspearrin** [comment]
Did you create the cert yourself or did the installer script?

**Comment by trayntab** [comment]
with the installer script

**Comment by sangdrax8** [comment]
Did anyone ever find a fix for this?  I have tried the snap and the appimage.  I always get a failure to fetch due to inability to verify the cert.  I do have the cert added in Ubuntu, but I have to use a self-signed and it seems to just not verify.

**Comment by trayntab** [comment]
hey sangdrax8, sorry i have no fix for this, at the moment i use only the firefox addon. i found no way to add the cert to the snap program... :(

**Comment by trayntab** [comment]
i found a solution for the snap app.

https://thomas-leister.de/ca-zertifikat-importieren-linux-windows/

#!/bin/bash

### Script installs root.cert.pem to certificate trust store of applications using NSS
### (e.g. Firefox, Thunderbird, Chromium)
### Mozilla uses cert8, Chromium and Chrome use cert9

###
### Requirement: apt install libnss3-tools
###


###
### CA file to install (customize!)
###

certfile="root.cert.pem"
certname="My Root CA"


###
### For cert8 (legacy - DBM)
###

for certDB in $(find ~/ -name "cert8.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
done


###
### For cert9 (SQL)
###

for certDB in $(find ~/ -name "cert9.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
done
