### ISSUE TITLE
JavaScript error occured in main process

### ISSUE THREAD

**Issue by DarylSun** [bitwarden/desktop#265]
![Screenshot (130)](https://user-images.githubusercontent.com/46442682/60122981-e5918d80-9775-11e9-95c6-e7731f8f17dd.png)

I have no idea what this means: should I be worried??

I'm running the latest version of the desktop client on Windows 10 1803.

**Comment by kspearrin** [comment]
Does this happen every time?

**Comment by DarylSun** [comment]
No, it happened only once. If I recall correctly, though, I had opened the settings menu before this.
