### ISSUE TITLE
what should the permissions be on ~/Library/Application Support/Bitwarden ?

### ISSUE THREAD

**Issue by luckman212** [bitwarden/desktop#266]
I was doing a file search in my $HOME directory today on 2 different macOS machines that both have the Bitwarden desktop app installed and I noticed that the permissions were different on
```
$ ls -ld "$HOME/Library/Application Support/Bitwarden"
```
machine A has `755`:
```
drwxr-xr-x  15 luke  staff
```
machine B has `341` (seems weird??):
```
d-wxr----x  13 luke  staff
```

Which is correct?

**Comment by kspearrin** [comment]
You would need `rwx` for whatever user is using the application. Machine A seems more appropriate.

**Comment by luckman212** [comment]
Ok, thanks. Not sure how the perms got set that way on B. Definitely never touched that directory manually.
