### ISSUE TITLE
Context menu on list of entries does not work as expected

### ISSUE THREAD

**Issue by stranljip** [bitwarden/desktop#27]
Platform: macOS 10.13.3
Version: 0.0.7

**Steps to reproduce:**
* Open program and enter master password
* right-click on an entry
* select view or edit

**Observed behavior:**
* context menu is replaced with another context menu (entries: copy, select all)

**Expected behavior:**
* right-click on context menu item opens entry for viewing/editing

**Comment by kspearrin** [comment]
Seemed to happpen to me once, but when i moved the mouse it showed the view page.

**Comment by stranljip** [comment]
Huh - it still happens here every time. If you like, I can show it to you with a remote session?

**Comment by stranljip** [comment]
I just found out that is does only happen with an unfiltered list. If you filter the list of entries, everything works as expected.

**Comment by jareddlc** [comment]
I think I found out how to reproduce. It occurs when an element is highlighted, it will then show the menu (copy, select All)

**Comment by jareddlc** [comment]
![bitwarden](https://user-images.githubusercontent.com/1082238/37489808-09dcbc90-2856-11e8-884c-352c2ac25784.png)

**Comment by stranljip** [comment]
I tried to reproduce this with the current version, no success --> Cannot reproduce
