### ISSUE TITLE
High RAM consumption Desktop application Windows 10

### ISSUE THREAD

**Issue by PlayerCZ** [bitwarden/desktop#272]
Hello,

Are you planning to optimize your password manager?

So what I was looking at takes up a total of about 90-140 MB of RAM

Couldn't this use of RAM be reduced?

Perhaps such a Keepass takes about 20 MB

Thank you.

**Comment by kspearrin** [comment]
We use Electron to build our desktop application, which by itself probably takes up 100mb or more. I don't think there is much room for us to optimize any further.

**Comment by PlayerCZ** [comment]
> Používáme Electron k vybudování naší desktopové aplikace, která sama o sobě pravděpodobně zabírá 100mb nebo více. Nemyslím si, že je pro nás další prostor pro další optimalizaci.

Don't want to do some Lite version yet?

**Comment by SDRPatriot** [comment]
That's not a large amount of memory usage for the functionality of the application.  I honestly don't know how it's actually as low as it seems to be most of the time.

**Comment by juliomaranhao** [comment]
I just made a screenshot of 'process explorer' to compare KeePass 2 (C#) and Bitwarden. The columns about RAM are the lighter ones ending with K (Private Bytes and Working Set, whatever these mean). For me (4GB RAM), 200MB more or less are acceptable. 

I am using one KeePass 2 plugin: KeeAnywhere. Both apps are loaded with the same contents (a lot of entries). Bitwarden CPU usage is very low (~0.3%) at rest. I think it's fair enough.


![ram](https://user-images.githubusercontent.com/791426/74781328-0caa4b80-5280-11ea-9c3c-95cdbc668908.png)

**Comment by maaudet-ca** [comment]
I've just ran into an issue with the BitWarden Windows App that made it use about 10GB of RAM. 

I had it set to lock only on restart, but after about a week without rebooting my computer I've noticed that I had about 70% of RAM usage and 80% of SWAP usage. It didn't show at all in the Task Manager and I had to guess which application was using all that RAM by closing down running applications one by one. When I got to close BitWarden, it asked me to elevate, and then the RAM usage went down to ~35%.

I have 32GB of RAM on my system.

**Comment by cscharf** [comment]
@maaudet-ca , can you tell us what version of the Bitwarden desktop app you're running and what version of OS?

@PlayerCZ, Other than some outliers, generally electron is the bulk of the usage there as it manages the Windows API layer; we use a shared code-base between our web vault, browser extension, CLI and desktop application which electron makes possible on the desktop side (similar to Slack, etc.) Currently there are no plans on the roadmap to build a "Windows native" app (for now).

**Comment by maaudet-ca** [comment]
@cscharf 

Bitwarden
Version 1.20.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

Windows 10 Pro 2004 Update

**Comment by cscharf** [comment]
Thanks, was Bitwarden running an update do you know? We've not had any other reports of a memory leak, etc. but that doesn't mean something didn't get into a wonky state. Please let us know if it happens again; in the meantime can you do a memory diagnostics scan to see if your machine perhaps has some blocked/bad sectors in RAM, perhaps there was a race condition for memory blocks/sectors which allocated those w/o registering (hence not showing up in task manager).

**Comment by maaudet-ca** [comment]
Since it asked me to elevate while closing, it might be related to an update (the version I gave you is the one I had after, I'm not sure what I had before). I've installed the Bitwarden Windows Desktop software from the website, so it's not from the Windows Store.

This is a recent machine and I didn't had issues with the memory diagnostic when I built it (2 weeks ago). I'll try to run another one once I don't need my computer.

**Comment by cscharf** [comment]
Thanks, hopefully it was just a fluke issue with an update routine, please keep an eye on it and if it occurs again feel free to re-open this issue or open a new one.

@PlayerCZ , I am closing this issue for now, thank you for reporting it, however at this time there are no plans to reduce the Windows desktop version's memory footprint explicitly due to the use of electron.
