### ISSUE TITLE
Dim brightness on HDR-enabled display

### ISSUE THREAD

**Issue by OneOkami** [bitwarden/desktop#274]
If running the Windows app on an HDR-capable display on Windows 10 with HDR enabled the application display from the menu bar down is very dim.  It appears the app is not respecting Windows' SDR content appearance settings when within this display context.  Its an issue a lot of apps had early on with Windows HDR display support.

It's something I wouldn't mind looking into myself at some point since I have the means to test and verify a fix.

**Comment by Crocmagnon** [comment]
Wouldn't it be an issue with electron itself ?

**Comment by OneOkami** [comment]
I’ve suspected that being the case but I’m not familiar enough with Electron at this point to know whether this issue is resolvable only at the framework level.  If anyone knows for sure I can instead raise the issue with that project.

**Comment by OneOkami** [comment]
A couple notes:

I found a [recent issue raised with VSCode](https://github.com/Microsoft/vscode/issues/68069) (another Electron-based app) for the same problem.  The correspondence mentions it has since been fixed but there's no detail on how it was done and some people complained they were still experiencing the issue.  I'll be able to test the latest version public version myself later.    

Someone also commented regarding [a lower-level fix](https://github.com/Microsoft/vscode/issues/68069#issuecomment-510839657) 4 days ago but mention they are, as I am in this case, not familiar enough with the code base to implement a fix at this time.

**Comment by OneOkami** [comment]
This appears to be fixed in version 1.15.2.  Looks fine on both an HDR and non-HDR-enabled display.  I'd be curious to know where/what the fix was since the latest version of Visual Studio Code still has the problem unless you specify command argument "--force-color-profile srgb" and it's on Election 4.2.5.  I see a bump from Electon 3.x to 5.x so I'm guessing perhaps somewhere in that range there's a framework-level fix as implied on the VSCode project.

In any case I'll close this issue.
