### ISSUE TITLE
Lag when typing into fields

### ISSUE THREAD

**Issue by AlphaShadows77** [bitwarden/desktop#275]
When I am typing password, there is a lag. It is just a field, so it seams strange to me

**Comment by kspearrin** [comment]
Which password field are you referring to? Does this happen every time?

**Comment by AlphaShadows77** [comment]
Sorry for forgetting information at the beginning of this issue.
It is happen to all fields in the application.
I done some searches and I think that the problem comes from events of the fields but maybe I am wrong.

**Comment by FaserF** [comment]
Happens to me still on the Windows Application
