### ISSUE TITLE
Windows app creates incorrect Verification Code (TOTP)

### ISSUE THREAD

**Issue by Degine** [bitwarden/desktop#276]
Hi,
With a premium membership comes the ability to generate 2FA codes. However, the Windows app generates wrong codes based on the Authenticator key scanned from a QR code withthe iOS app, AND when entering the authenticator key manually in the Windows app. 

Note that the iOS app does produce verification codes that are correct with the same authenticator keys.

Windows app details:
Version 1.14.0
Shell 3.0.14
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64

**Comment by kspearrin** [comment]
Make sure your system time is correct. This will cause invalid codes to generate.
