### ISSUE TITLE
Huge Security Flaw: No 2FA on windows app, Chrome or Edge

### ISSUE THREAD

**Issue by MarkCWEV** [bitwarden/desktop#284]
I have 2FA turned on and am prompted to use it when logging into my bitwarden account on the web, but when I open the windows 10 app or Chrome/Edge extension all I'm required to enter is my master password. This is _massive_ security flaw and makes 2FA useless.

Unless it's fixed ASAP, I'm bailing

**Comment by kspearrin** [comment]
This is because you are only unlocking the application, which you previously logged into. 2FA is only required when logging in, not subsequent unlocks.

It seems you have already discovered the other issues regarding the request for additional levels of 2FA, so I will close this issue now.
