### ISSUE TITLE
Close to tray does not work in macOS and linux

### ISSUE THREAD

**Issue by netvl** [bitwarden/desktop#285]
The "Close to tray" feature implemented in https://github.com/bitwarden/desktop/pull/168 does not work on macOS or Linux.

In macOS, closing the main window does not exit the application (which is good), but it results in a necessity to re-type the master password, which is really unfortunate. It is interesting that clicking the tray icon does result in correct behavior (main window being hidden/showed again, without changing the locked state).

In Linux, closing the main window results in the entire application being closed. Naturally, after restart I have to enter the master password again. Ideally, in Linux with this option enabled should result into the main window being hidden, but the app itself should remain in memory and keep its locked/unlocked state.

**Comment by LanceSandino** [comment]
+1 to this -- I mentioned this here: https://github.com/bitwarden/desktop/issues/283#issuecomment-517110848

but should have probably made a new issue for it :)

**Comment by idiaz97** [comment]
It does not work on windows 10 either

**Comment by Cris70** [comment]
It works here if I choose "Window" => "Hide to Tray" from the menu, but if I close the window using the X button the application is closed instead of hiding into the tray. I would expect it to hide instead, when in the options I have "Enable Tray Icon" selected.
I am on openSUSE Tumbleweed (KDE).

**Comment by netvl** [comment]
Any chance to get this fixed? If not, are contributions accepted? I might have got enough resolution to try and fix it myself, although I never worked with electron before :)

**Comment by sshermz** [comment]
I would like to move to BW on linux, but this is a major usability issue.

It should be trivial to fix as the functionality is already implemented on linux via Window|Hide to Tray.

'Close to Tray Icon' is present in the settings on Windows, but is missing in settings on Linux. So it looks like Linux was partially neglected when this feature was implemented  >_<

**Comment by matte-Rhorn** [comment]
In the version for Windows there is a dedicated toggle button in the settings to manage the application behavior when the close and minimize buttons are clicked. That toggle button allows deciding if it should be minimized to the tray. Such option is missing in the version for Linux.

Would be great if such option 'Close to Tray Icon' button could be implemented also for the platforms other than Windows.

**Comment by Cris70** [comment]
Any news on this?

**Comment by silverscat-3** [comment]
I'm currently attempting to solve this problem; Close to tray works by commenting out the platform conditional branch in `tray.main.ts` (at least on Linux) but I can't found the code that hides that setting. It's too bad, I don't understand how the setting is hidden at the moment.

**Comment by Cris70** [comment]
v1.23 is still exhibiting this behavior.

**Comment by digitalpenguin** [comment]
Any news on when this fix will be in a release?

**Comment by cscharf** [comment]
this will be resolved with https://github.com/bitwarden/jslib/pull/212

**Comment by wwalker** [comment]
For me, on Linux, Bitwarden-1.28.2-x86_64.AppImage, this still doesn't work.

* Open to Tray
* Close to Tray
* Hide to Tray 

All three result in BitWarden is still running, but the window is gone, and it isn't in the tray, and the window manager doesn't know anything about it either.  So I have to go kill the process.

I've given up and created some wrappers around the BitWarden CLI.  Has anyone got good wrappers around the CLI, or been able to use the desktop app?

**Comment by johnhamelink** [comment]
@wwalker I'm using this wrapper with some degree of success https://github.com/mattydebie/bitwarden-rofi

**Comment by wwalker** [comment]
Sweet!  Thank you, @johnhamelink !  I had written mine to use rofi too. But mattydebie's version is much cleaner!

**Comment by Cris70** [comment]
> For me, on Linux, Bitwarden-1.28.2-x86_64.AppImage, this still doesn't work.

I'm using 1.28.1 appimage on openSUSE with KDE and it works.

**Comment by soloturn** [comment]
on gnome this works. one has a right mouse "hide", ans well as a hide button alongside the close button in the title bar should one configure it:

![image](https://user-images.githubusercontent.com/825568/151700366-19ba337c-aa26-4e89-97a6-7c17e7d7ecea.png)

**Comment by MartinX3** [comment]
Arch Linux XFCE4
I use bitwarden since 1.30.0 and close to tray always worked like a charm.

**Comment by cscharf** [comment]
Thanks @MartinX3 and @soloturn ... Are there any users still experiencing this issue on the current version of the desktop client? In the meantime I'm going to close this issue, if it is still a problem please feel free to reopen.
