### ISSUE TITLE
Crash after Update Linux v1.15.2

### ISSUE THREAD

**Issue by Masgalor** [bitwarden/desktop#286]
After updating the AppImage from v1.14.0 to v1.15.2 Bitwarden crashes with the following message.

`[20808:0802/001112.252976:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.`

After that I installed Bitwarden with the provided .deb package which produces the same error.
But here I was able change the permission as mentioned in the error what solved the problem.

**Comment by kspearrin** [comment]
I am not able to reproduce this on Ubuntu. Seems there is a thread with electron about the error here though: https://github.com/electron/electron/issues/17972

**Comment by Masgalor** [comment]
This comment sums it up pretty good: https://github.com/electron/electron/issues/17972#issuecomment-516957971

Electron uses the kernel feature `CLONE_NEWUSER` which is disabled by default on some distros because of security concerns.

I'm on Debian where it is disabled, while your Ubuntu has it enabled.
That's why you can't reproduce it.

Besides of that electron has a fallback mechanism, the mentioned `SUID sandbox helper binary`.
To make use of this binary it needs the permission set `4755` but it is shipped with `0755`.
So in the first place the packaging process should be improved to set the correct permissions.

Otherwise people need to activate the mentioned kernel feature.
`sysctl kernel.unprivileged_userns_clone=1`

**Comment by kspearrin** [comment]
Looks like there is an open bug with our builder library here: https://github.com/electron-userland/electron-builder/issues/3872

I am following it for any updates.

**Comment by vladimiry** [comment]
> I am not able to reproduce this on Ubuntu

Executing `sudo sysctl kernel.unprivileged_userns_clone=0` can help with reproducing the case.

**Comment by vladimiry** [comment]
> Besides of that electron has a fallback mechanism

This fallback mechanism comes with Chromium (SUID sandbox), so Electron uses it as a given thing. Besides that as far as I now this thing won't work for the AppImage case. But hadrcoding `--no-sandbox` argument in AppImage's AppRun script will solve the issue (this approach is already applied for the recent electron-builder versions, but only for the Snap target so far).

**Comment by Gaudon** [comment]
This version is constantly crashing on Windows 10 as well if it's related.

**Comment by IanTheEngineer** [comment]
`--no-sandbox` arg workaround for those that use the Bitwarden Freedesktop tray icon, [edit the `Exec`](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables) line of the `*.desktop` file with a `_space_"--no-sandbox"_space_` after the `AppImage` and before the `%U`

Eg. edit `~/.local/share/applications/appimagekit-bitwarden.desktop`:
```
[Desktop Entry]
Name=Bitwarden
Comment=A secure and free password manager for all of your devices.
Exec="/path/to/Bitwarden-1.15.2-x86_64.AppImage" "--no-sandbox" %U
Terminal=false
Type=Application
Icon=appimagekit-bitwarden
...
```

**Comment by CLechleitner42** [comment]
FYI: We can reproduce the problem on Debian Buster, adding --no-sandbox helps.

**Comment by vctt94** [comment]
I can also reproduce this issue at Debian Buster
