### ISSUE TITLE
Desktop app BItwarden-generated 2FA token wrong format

### ISSUE THREAD

**Issue by Jack15911** [bitwarden/desktop#287]
When the 2FA code is generated and stored within Bitwarden then displayed by the desktop app, the token's format is wrong. The format shows as follow: "123 456," with a space between the third and fourth numbers in a six-digit token. When cut-and-pasted into Reddit, Reddit rejects the format. (Untested on other sites, as this is my only Bitwarden-stored secret.) 

(This does not apply to Firefox extension or iOS - it only applies to the desktop app, and has only been verified on a macOS 10.14.5.)

The workaround is to memorize and manually type the token digits, or to paste and modify the string by removing the space.

**Comment by kspearrin** [comment]
There is a copy button next to the formatted code. Are you using that? This should not include the middle space.

**Comment by Jack15911** [comment]
Probably not. The copy button works properly; Command-C copies the space. Close.
