### ISSUE TITLE
Duplicate programs entry with 1.15.2 update

### ISSUE THREAD

**Issue by Ryanjtombs** [bitwarden/desktop#289]
Since the 1.15.2 update, Bitwarden has a duplicate programs and features entry in Windows.

I've tried uninstalling and reinstalling the program, but the website download is only updated for version 1.14.0. 

Any fix for this? Does anyone know where the registry key should be for the old entry?

![Untitled](https://user-images.githubusercontent.com/53541018/62415205-edb6d580-b61d-11e9-97a2-8cbf5417927a.png)
![Untitled1](https://user-images.githubusercontent.com/53541018/62415206-ef809900-b61d-11e9-9771-7b924aa26401.png)

**Comment by kspearrin** [comment]
The website has been updated to the latest version. Can you just uninstall the old one?

**Comment by vxmn** [comment]
I'm facing the same issue. Both entries point to the same uninstaller in the same directory. If I try to uninstall 1.14.0, it removes the Bitwarden directory in Program Files and removes the entry for 1.15.2. The Entry for 1.14.0 remains and I can not delete this erroneous entry. Saying "Windows cannot find 'C:\Program Files\Bitwarden\Uninstall Bitwarden.exe'. Make sure you typed the name correctly, and then try again."
