### ISSUE TITLE
MacOS: crash on start after updating to 1.15.3

### ISSUE THREAD

**Issue by chilikasha** [bitwarden/desktop#290]
Mac OS 10.14
today updated to 1.15.3 via app store and app crashes on each start.

attached log
[log.txt](https://github.com/bitwarden/desktop/files/3464862/log.txt)

**Comment by kspearrin** [comment]
Does the same issue occur if you use the .dmg version instead of mac app store?

https://github.com/bitwarden/desktop/releases/download/v1.15.2/Bitwarden-1.15.2.dmg

**Comment by shila77** [comment]
Same Problem for me on macOS 10.13.6. Did not check the .dmg.
Also AppStore Version is 1.15.3.

**Comment by kspearrin** [comment]
@shila77 Could you try the dmg please?

**Comment by kspearrin** [comment]
Tracking issue with electron repo here: https://github.com/electron/electron/issues/19626

> Ask users who are encountering this issue to run the app with --disable-gpu to see if that helps, and also open about:gpu in Chrome and report the contents.

**Comment by akapitoha** [comment]
about:gpu contents
[about_gpu.txt](https://github.com/bitwarden/desktop/files/3470636/about_gpu.txt)

**Comment by kspearrin** [comment]
Can you guys please uninstall the version from the mac app store and install the .dmg version:
https://github.com/bitwarden/desktop/releases/download/v1.15.2/Bitwarden-1.15.2.dmg

Then open terminal and execute it with:

```
/Applications/Bitwarden.app/Contents/MacOS/Bitwarden --disable-gpu --enable-logging
```

**Comment by shila77** [comment]
dmg version is working. no crashes.

**Comment by tonysva** [comment]
I received this link from support. 
https://github.com/bitwarden/desktop/releases/download/v1.14.0/Bitwarden-1.14.0.dmg

So I could go back to previous version. Instead of the dealing with the crashing of 1.15.2. 
There’s a problem tho. When you close B/W 1.14.0 there is a problem on restart, it automatically updates to 1.15.1.
I went to ~/Library/Application Support/Cache/update/pending/Bitwarden 1.15.2.zip.
Deleted the Update folder. Now I’m able to use 1.14.0 with no problem. 
- iMac El Capitan 10.11.6 -

**Comment by freefieldpress** [comment]
Thanks for suggesting I use the .dmg approach instead of the app store. That solved the problem. I'm on Mac 10.13.6. Hoping all continues to go well.

**Comment by kspearrin** [comment]
@shila77 @tonysva @freefieldpress @akapitoha 

Could you guys uninstall the dmg version, then reinstall from Mac App Store. If the problem still exists, please try running from terminal with the following command:

```
/Applications/Bitwarden.app/Contents/MacOS/Bitwarden --enable-logging
```

and report the output of the crash.

Also, can you try running with

```
/Applications/Bitwarden.app/Contents/MacOS/Bitwarden --disable-gpu
```

and see if that stops the crash?

**Comment by billwieboldt** [comment]
Both commands return the following with the app store version on macOS 10.13.6:
```
FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
Trace/BPT trap: 5
```

**Comment by kspearrin** [comment]
@billwieboldt Could you provide the output to `about:gpu` in Chrome (if you have that installed).

**Comment by billwieboldt** [comment]
I noticed that request, but unfortunately I don't have Chrome installed. I'm on a 2010 MacBook Pro that has issues with gpu switching which results in kernel panics due to an underrated capacitor. Chrome was one of the worst offenders and really not an option for me on this machine.

Hopefully someone with a more modern and stable setup can report on that front.

**Comment by billwieboldt** [comment]
Managed to install and run Chrome without issue - hopefully this helps. (Deleted previous post as it's no longer relevant).

[about:gpu](https://gist.github.com/billwieboldt/1a48c04047c711124d6b6a1026e3d142/raw/5bf27555f83c3d000397b5b7cb2ed83e89cceee5/Chrome%2520about-gpu.txt) (Raw)

**Comment by kspearrin** [comment]
Thanks @billwieboldt . I reported it here: https://github.com/electron/electron/issues/19626

**Comment by shila77** [comment]
Updated to 1.16.5 App Store version a few minutes ago. Crashes on launch....

Used Version 1.16.4 downloaded for here for the last week, works including Safari extension...

**Comment by babalooza** [comment]
Same here with 1.16.10 from App Store (crash on launch) but dmg version 1.16.6 is working just fine, including Safari extension.

**Comment by maquedexiju** [comment]
Same issue for me with 1.6.10 from AppStore.

I tried with `--disable-gpu --enable-logging` to start, and I get this:

> FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.

**Comment by TheSonicZone** [comment]
Installing the .dmg from this issue, and then allowing it to update, solves all the problems.
