### ISSUE TITLE
Program appears in Windows 10 taskbar when should be in tray

### ISSUE THREAD

**Issue by Vimru** [bitwarden/desktop#291]
Once the vault has been unlocked and locked and then bitwarden minimised to the system tray, if Windows is locked the unlocked, bitwarden appears in the taskbar rather than remaining in the system tray.

If you try to open bitwarden by clicking on the icon in the taskbar, it doesn't open.

**Comment by CyBiS** [comment]
For me Bitwarden minimizes to the system tray but crashes as soon as it is reopenend, no Windows locking/unlocking necessary. Also running Window 10 and latest Bitwarden App version 1.15.2.

**Comment by Vimru** [comment]
Just noticed this issue is now fixed and #293 is related (thanks CyBiS).
