### ISSUE TITLE
devtools/developer console opens on launch

### ISSUE THREAD

**Issue by Kiwi** [bitwarden/desktop#292]
I am trying to [package bitwarden for nixos](https://github.com/NixOS/nixpkgs/pull/65764) and am [having this problem](https://github.com/NixOS/nixpkgs/issues/65889)

To reiterate here; the problem is that when I launch bitwarden desktop it opens the developer tools window pane by default. (the one that F12 toggles) I don't know if this is normal, a bug in bitwarden, or a bug in my package attempt? Is this intended behavior? I'd like to get this merged into nixpkgs but not knowing if it's intended, a bitwarden bug, or a bug in packaging which I need to fix is holding it back.

Could anyone confirm whether this is normal, and if it's my packaging, know what I might need to do to fix?

Thanks! I really like bitwarden. Great work everyone!

**Comment by kspearrin** [comment]
No, this is not expected. The dev tools should only open by default on doing dev builds. `i.e. npm run electron`.

**Comment by Kiwi** [comment]
Thank you! That was what I needed to know. I have figured out a way to get it to work now. Hopefully will get it cleaned up and submitted soon!
