### ISSUE TITLE
v1.15.2 Crashing on Windows 10

### ISSUE THREAD

**Issue by Gaudon** [bitwarden/desktop#293]
![image](https://user-images.githubusercontent.com/1593839/62474462-844dd880-b77d-11e9-9e0b-3c27aa719d24.png)

This version of the application is constantly crashing on desktop (windows 10).

**Comment by kspearrin** [comment]
How did you capture this screenshot if it is crashing?

**Comment by Gaudon** [comment]
> 
> 
> How did you capture this screenshot if it is crashing?

It crashes after a period of time, or after being minimized to the taskbar (I'm not sure what causes it to crash). I'm able to use it and copy a password or 2 before it crashes. It briefly freezes upon being restored and then crashes. I'll check the event viewer for more information.

**Comment by kspearrin** [comment]
Are you using close/minimize to tray icon?

**Comment by Gaudon** [comment]
> 
> 
> Are you using close/minimize to tray icon?

That's correct, I am.

Faulting application name: Bitwarden.exe, version: 1.15.2.0, time stamp: 0x5d369450
Faulting module name: Bitwarden.exe, version: 1.15.2.0, time stamp: 0x5d369450
Exception code: 0xc000041d
Fault offset: 0x0000000000ba9bec
Faulting process id: 0x26e4
Faulting application start time: 0x01d54b9f2439a4d4
Faulting application path: C:\Program Files\Bitwarden\Bitwarden.exe
Faulting module path: C:\Program Files\Bitwarden\Bitwarden.exe
Report Id: d26add3b-5099-4553-8309-ccdc6c5e03d7
Faulting package full name: 
Faulting package-relative application ID: 

Windows simple says "APP CRASH - NOT RESPONDING"

**Comment by kspearrin** [comment]
This is a known bug in latest version. It should be fixed in the next version. The workaround is to disable those settings, OR enable the `Enable Tray Icon` setting.

**Comment by Gaudon** [comment]
> 
> 
> This is a known bug in latest version. It should be fixed in the next version. The workaround is to disable the tray settings, OR enable the `Enable Tray Icon` setting.

Will give it a shot, thanks.
