### ISSUE TITLE
New collection not pushed to desktop client

### ISSUE THREAD

**Issue by vxmn** [bitwarden/desktop#294]
I added a new collection to an organization without any other collections. While the newly created item showed up in the desktop client without manually refreshing, the available collections did not seem to be synced. There was not "Collections" entry on the sidebar and the actual collection did not show up. When clicking on "Collections" in the login entry I created in the browser, it did not show any assigned collections. After syncing manually, the collection showed up as expected.

Are collections not being pushed to the desktop client automatically while login entries are?

**Comment by vxmn** [comment]
Maybe this is related to how user permissions are handled like in [this issue](https://github.com/bitwarden/server/issues/536)?

**Comment by kspearrin** [comment]
Yes, collection updates are live synced at the moment. They will get synced on the slower timed sync which occurs a few times per day or on manual refresh or restart of the client.
