### ISSUE TITLE
Mouse scroll wheel won't work when the vault is locked

### ISSUE THREAD

**Issue by DinoLeung** [bitwarden/desktop#296]
OS: macOS 10.14.6
Bitwarden version: 1.15.2

Here's how I recreate it:
1. start the bitwarden app
1. go to settings
1. set lock options to `1 minute`
1. wait until it is locked
1. once it is locked, go to Exposé then select bitwarden
1. might need to switch back and forth to create the issue
1. at this point, the mouse scrolling wheel (mx master in my case) not work even in other applications
1. the mouse will go back to normal once the vault is unlocked

**Comment by kspearrin** [comment]
> go to Exposé then select bitwarden

Is this another language? Any idea what that is in English?

**Comment by DinoLeung** [comment]
@kspearrin oh sorry, I think it's called mission control now. https://en.m.wikipedia.org/wiki/Mission_Control_(macOS)

**Comment by kainzjoh** [comment]
Having the same issue with MacOS Version 10.14.6 (18G2022) and Bitwarden Version 1.16.6 (1.16.6)
You don't need to go to Exposé, just leave the Application in the Background (select any other Window or Application) and wait for Bitwarden to Lock the Vault - Mouse Wheel stops working.

**Comment by asimen1** [comment]
Same here with, also with Logitech MX Master 3

**Comment by pkrasnicki** [comment]
I have the same issue. It occurs only when I have LogiOptions software installed.
macOS version 11.2.3
Bitwarden version 1.25.1
LogiOptions version 8.36.76

**Comment by joshbuckley182** [comment]
Looks like it might be related to https://github.com/bitwarden/desktop/issues/738#issuecomment-832762876

I'm having the same issue but with the gesture button on my MX Master. Works if bitwarden isn't running, or if it is and the vault is unlocked.

**Comment by xLinkOut** [comment]
Same issue. When Bitwarden is running, all the gesture/side buttons on MX Master 2S are broken, even the scroll wheel is unresponsive or scroll in the opposite direction (like check/uncheck natural scroll in System Preferences->Mouse).

- macOS Big Sur 11.4
- Bitwarden 1.27.1 (531)
- Logi Options 8.54.147
- MX Firmware 12.01

**Comment by eliykat** [comment]
This issue is being tracked in #298 and has been fixed in v1.28.0, which was just released. (Although it can take a week or so to go through app store approval.)
