### ISSUE TITLE
Can't save new date because of a server-side issue 

### ISSUE THREAD

**Issue by cig0** [bitwarden/desktop#297]
Hi,

Right now as of **Sat, 10th August, 10:43 PM GMT -3** I can't save new data into my Bitwarden vault (using either the local app or the web interface) because there is an outage of the service, preventing me from both saving the actual entry on which I spent a several minutes adding data, and also from accessing my vault through the web interface: 

<img width="1022" alt="Screen Shot 2019-08-10 at 22 40 35" src="https://user-images.githubusercontent.com/394089/62828550-14e24980-bbc0-11e9-819f-682a19d3d43b.png">

I really like Bitwarden (I'm a paid subscriber in fact), but the obstinacy of the developers in not allowing us to save information while off-line is really, **really** frustrating at times.

**Comment by kspearrin** [comment]
Issues should now be resolved. Can you try refreshing?
