### ISSUE TITLE
minimize or close twice on Win10 crashes

### ISSUE THREAD

**Issue by tomschlintz** [bitwarden/desktop#299]
Bitwarden 1.15.2, on Windows 10, with minimize to tray and close to tray enabled - if you open and either minimize or close twice (even w/o logging in), it closes, disappears from the tray, requiring restart and re-logging in.
![snip](https://user-images.githubusercontent.com/49277797/63141085-63be2380-bfb2-11e9-8c0d-60e1c1586912.JPG)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/293
