### ISSUE TITLE
"Hide To Tray" on Windows 10 crashes when clicking tray icon, but not if right clicking "Show / Hide"

### ISSUE THREAD

**Issue by JamesMowery** [bitwarden/desktop#300]
I'm running the latest version of Windows 10. When using the Window > Minimize To Tray option, the app crashes when I attempt to left click on the tray icon to bring back up the Bitwarden window. 

**However**, if I right click on the tray icon and use "Show / Hide" option, it works fine.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/293
