### ISSUE TITLE
Android - Master Password doesn't work in app.

### ISSUE THREAD

**Issue by brigcmccoy** [bitwarden/desktop#304]
When using the app on Android, I get "An error has occurred. Invalid Master Password. Try again." Master Password works fine with the Windows 10 app, Windows 10 (Chrome) web browser, and Chrome web browser on Android. (Latest versions of both web browsers.

...brig

**Comment by kspearrin** [comment]
This repository is for the desktop app. It sounds like you have a problem with the mobile app.

**Comment by djsmith85** [comment]
Hi @brigcmccoy, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
