### ISSUE TITLE
Windows 10 OS | Hide to Tray crash

### ISSUE THREAD

**Issue by MrDiabolical** [bitwarden/desktop#305]
When using the desktop application, Hide to Tray function works up till you need to reopen it. After that it shows the application for a few seconds then closes without a windows crash report.

Device Info and Version:
Windows 10 OS Build 18362.356
Bitwarden version 1.15.2

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/293
