### ISSUE TITLE
Windows 7 x64 Uncaught Exception Error: EBADF

### ISSUE THREAD

**Issue by Rfosu2k2** [bitwarden/desktop#306]
![Bitwarden_error](https://user-images.githubusercontent.com/5554308/65302537-586d9300-db30-11e9-87bf-ffa12a1a7fb3.jpg)

Error happened when launching desktop program on Windows 7 x64 from the start menu.
Version 1.15.2
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

**Comment by kspearrin** [comment]
Does this happen every time you launch? Maybe try clearing the appdata folder for Bitwarden?

**Comment by rfosu2k2** [comment]
This is the first time I have experienced the error.  I will clear out the appdata folder for Bitwarden as suggested.

**Comment by rfosu2k2** [comment]
It worked for the first time after clearing appdata, then I checked an updated to 1.16.x.  I was also able to open the application 1 more time.  Upon attempting to open today I received this error, and even emptying appdata again does not allow application to open at all.  A repeat of this error is all that populates.  Will uninstall/reinstall and update here with any new information.

![image](https://user-images.githubusercontent.com/5554308/65380322-02aefd00-dc8e-11e9-8df0-cf43a4fd48d2.png)

**Comment by Rfosu2k2** [comment]
Many updates since this issue.  closing.
