### ISSUE TITLE
Windows Store Version has update check enabled

### ISSUE THREAD

**Issue by MarcelWie** [bitwarden/desktop#307]
It seems that the automatic Update feature is enabled in the Windows Store Version of Bitwarden. I'm using 1.15.2 and it's currently trying to update itself which leads to a loop as he's not able to do so. 

Version 1.15.2
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

**Comment by kspearrin** [comment]
Thanks. I discovered this last night. Should be fixed next version.
