### ISSUE TITLE
Provide deb repository or PPA for easier install/update on Debian/Ubuntu Linux 

### ISSUE THREAD

**Issue by MurzNN** [bitwarden/desktop#308]
Bitwarden already build deb files for use Bitwarden as native app on Debian/Ubuntu Linux, instead of sandboxed via snap or appimage. 
But the problem is that users must update it manually via tracking, downloading and installing new deb file. 

Will be good to implement auto-update deb packages via providing deb-repository or PPA archive with fresh version of Birwarden app (and cli tool to).

Here https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted is manual how to build auto-updated PPA via Launchpad recipe

**Comment by kspearrin** [comment]
We've been tracking this feature request here:
https://community.bitwarden.com/t/provide-software-repositories-for-linux-packages/101
