### ISSUE TITLE
Icon not showing correctly on Arch Linux

### ISSUE THREAD

**Issue by Kirpal** [bitwarden/desktop#31]
It shows the correct icon in the app menu, but in the menubar it shows a placeholder icon. Running the latest AppImage on Archlinux

![image](https://user-images.githubusercontent.com/18384371/36517987-9a051d4a-1752-11e8-9e12-5ab7f0a43507.png)

**Comment by cj-sv** [comment]
Confirmed here as well. On Ubuntu 17.10 GNOME Shell 3.26.2.

![screenshot from 2018-02-24 12-35-47](https://user-images.githubusercontent.com/11567756/36625693-55bbc21a-195f-11e8-8c38-987f63036018.png)

![screenshot from 2018-02-24 12-36-10](https://user-images.githubusercontent.com/11567756/36625695-62203a0e-195f-11e8-8b86-18b8cc38e7d8.png)

**Comment by kspearrin** [comment]
Possible fix in the next update. Looks like there was a bug in our packaging library, but not sure if this is the fix or not... https://github.com/electron-userland/electron-builder/releases/tag/v20.1.1

**Comment by kspearrin** [comment]
Update to latest and let me know if it is fixed please.

**Comment by cj-sv** [comment]
Nice, it's fixed.

![screenshot from 2018-02-25 13-33-35](https://user-images.githubusercontent.com/11567756/36638452-8968fc00-1a30-11e8-86b1-c383ffd33267.png)

**Comment by Kirpal** [comment]
Same for me
