### ISSUE TITLE
Cannot login due to update never ends (Linux - v.1.16.4)

### ISSUE THREAD

**Issue by Timmy93** [bitwarden/desktop#311]
## Environment:
**OS**: Linux Mint 19.2 - Cinnamon Edition
**Bitwarden version**: AppImage - 1.16.4

## What happen?

After the credential are inserted (Bitwarden disconnected) and the login button is pressed, the login button start loading for a couple of minutes and at the end it come back normally.
The login is impossible

## How to reproduce:

- Be sure to be connect behind a Firewall and a _Proxy that is blocking the connection to the update server_
- Disconnect from your Bitwarden account
- Reopen Bitwarden desktop
- Insert your credential
- Press Login

####Note

Under the same system and connection it is still possible to connect using the website or the browser (Firefox) addon.

Here is the message that I receive from the command line when I run the AppImage:
```
[12:49:26.857] [info] Checking for update
[12:51:36.871] [error] Error: Error: net::ERR_CONNECTION_TIMED_OUT
(node:3569) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_TIMED_OUT
(node:3569) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kspearrin** [comment]
Can you open the developer tools under View menu and see what the network requests look like?

**Comment by bugterix** [comment]
You can find the solution over here:
https://github.com/bitwarden/desktop/issues/286
--no sandbox for the .desktop-File helps

**Comment by Timmy93** [comment]
@bugterix Thank you for your comment but manually changing the _.desktop_ file is actually only a workaround, not a real solution.

@kspearrin As you can see from the attached screenshot the request times out due to firewall/proxy settings.

![Schermata del 2019-09-25 17-57-35](https://user-images.githubusercontent.com/10899430/65688159-e8e52f80-e06a-11e9-929b-065c83589f17.png)
![Schermata del 2019-09-25 17-57-13](https://user-images.githubusercontent.com/10899430/65688160-e8e52f80-e06a-11e9-8b80-334d8e6410a2.png)
