### ISSUE TITLE
Safari 11 extension

### ISSUE THREAD

**Issue by jawsoftware** [bitwarden/desktop#319]
El Capitan 10.11.6, Safari 11.1.2, Bitwarden 1.16.6
The Bitwarden Safari app extension doesn't work; the icon is shown on the Safari toolbar, but clicking on it does absolutely nothing (apart visual feedback of click).

**Comment by kspearrin** [comment]
I'm not sure Safari app extensions would work with El Capitan. Do you use other Safari App Extensions installed from the Mac App Store?

**Comment by jawsoftware** [comment]
I didn't found the standard .safariext on site, so I checked in the application bundle and found the app extension; double-clicking on it installed it on Safari (it is present in Safari Preferences and it appears in the Safari toolbar (so I deduce Safari app extensions are supported by Safari 11.1.2), but clicking on the icon in the toolbar doesn't show any menu.

**Comment by jawsoftware** [comment]
I can confirm that Safari App Extensions do work on Safari 11. I just tried installing Keep Everything from the Mac App Store and it is fully functional.
