### ISSUE TITLE
Desktop app 1.16.7 fails to launch on macOS 10.15 Catalina (integrity verification)

### ISSUE THREAD

**Issue by CFKevinRef** [bitwarden/desktop#320]
This app was installed from the Mac App Store. OS version is macOS Catalina 10.15 Beta (19A578c).

* Launch from Applications, Launchpad, etc (not Safari extension)
* An error alert pops up:

>“.LTZ2PFU5D6.com.bitwarden.desktop.CIY2N9” can’t be opened because its integrity cannot be verified.
>This software needs to be updated. Contact the developer for more information.
>Bitwarden created this file today at 9:53 AM.
* click “Move to Trash” or “Cancel”
* Another alert appears:
>A JavaScript error occurred in the main process
>Uncaught Exception:
>Error: >dlopen(/var/folders/wx/0c8xf6l51kv5d82b6p486d700000gn/T/com.bitwarden.desktop/.LTZ2PFU5D6.com.bitwarden.desktop.CIY2N9, 1): no suitable image found.  Did find:
	>/var/folders/wx/0c8xf6l51kv5d82b6p486d700000gn/T/com.bitwarden.desktop/.LTZ2PFU5D6.com.bitwarden.desktop.CIY2N9: code signature in (/var/folders/wx/0c8xf6l51kv5d82b6p486d700000gn/T/com.bitwarden.desktop/.LTZ2PFU5D6.com.bitwarden.desktop.CIY2N9) not valid for use in process using Library Validation: library load disallowed by system policy
	/var/folders/wx/0c8xf6l51kv5d82b6p486d700000gn/T/com.bitwarden.desktop/.LTZ2PFU5D6.com.bitwarden.desktop.CIY2N9: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:164:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/node_modules/desktop-idle/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:839:30)

* App never launches

Looks like this may be related to new code signing requirements for sandboxed apps: electron/electron#19342

**Comment by semireg** [comment]
Also seeing this on an Electron app I manage. Commenting to subscribe and offer assistance as I work around the issue.

**Comment by kspearrin** [comment]
@semireg Please let me know if you figure this out. I'll do the same.

**Comment by Zegorax** [comment]
I've just updated to Catalina. The problem is occurring to me as well. Is there any beta / fix yet ?

**Comment by Ezzahhh** [comment]
Going to Security & Privacy and allowing the app manually does not solve the issue. When the app is opened it will continue the error and the option to allow will again appear in the settings.

**Comment by kspearrin** [comment]
I submitted 1.16.8 to the app store for review. It contains a possible fix, but I am not sure. I will report back when it goes live.

**Comment by semireg** [comment]
It's driving me crazy because my MAS build keeps getting rejected by Apple with this exact screenshot. Strangely, I can cleanly deliver a non-MAS build with hardenedRuntime and it works flawlessly on Catalina. If I keep hardenedRuntime disabled on the MAS build I can run my /mas-dev builds with no issue on 10.14.6. When I enable hardenedRuntime on the MAS build, my /mas-dev builds fail with code signing issues.

I'm using `"electron-builder": "^21.2.0"`

Also see this thread https://github.com/electron-userland/electron-builder/issues/4040#issuecomment-539225300

**Comment by 2pockets** [comment]
I'm not a developer but this might be useful. I'm running the old Mac OS 10.11.6 and had a stable Bitwarden with 1.16.6.   I loaded 1.16.7 and it won't open. Crashes every time. It produces an error report at each failure. I can share the report if it would be useful.

**Comment by GauthierPLM** [comment]
I saw a similar issue with Firefox in the early days of Catalina beta. It was a notarization issue: the .app was signed as well as the main executable, but the updated was not. At every launch, the updater was started but being not signed, it was killed by MacOS.

As Electron apps are often multi-process and use helpers executables, the issue might come from one of them which is not properly signed. Discord had the exact same issue as BitWarden but fixed it.

**Comment by kspearrin** [comment]
Well, my update didn't work. Apple rejected it with the same error as @CFKevinRef posted originally here for Catalina. I tired the suggested fix from https://github.com/electron/electron/issues/19342 , by adding `"asarUnpack": "*.node"` for the build from electron-builder, but that didn't seem to help.

![image](https://user-images.githubusercontent.com/1190944/66393240-0639c800-e9a0-11e9-8df4-325fbde14c56.png)

**Comment by porcherie** [comment]
> Well, my update didn't work. Apple rejected it with the same error as @CFKevinRef posted originally here for Catalina. I tired the suggested fix from [electron/electron#19342](https://github.com/electron/electron/issues/19342) , by adding `"asarUnpack": "*.node"` for the build from electron-builder, but that didn't seem to help.
> 
> ![image](https://user-images.githubusercontent.com/1190944/66393240-0639c800-e9a0-11e9-8df4-325fbde14c56.png)

Is the version downloadable from the website working? Or is affected as well??

**Comment by kspearrin** [comment]
@semireg I have hardened runtime disabled for our mas builds here. Do you think that is the issue?

**Comment by kspearrin** [comment]
With Bitwarden here, the stacktrace is pointing to:

> at Object. (/Applications/Bitwarden.app/Contents/Resources/app.asar/node_modules/desktop-idle/index.js:1:21)

`desktop-idle` is a node module that we use for detection idle timeouts on the desktop. It requires a native binary, so maybe that has something to do with it.

https://github.com/bithavoc/node-desktop-idle

**Comment by kspearrin** [comment]
Submitted 1.16.9 with hardened runtime enabled for the mac app store build. Let's see what happens.

**Comment by kspearrin** [comment]
Unfortunately 1.16.9 with hardened runtime still failed review with Apple. Same error:

![image](https://user-images.githubusercontent.com/1190944/66447787-57d46800-ea1d-11e9-9944-86164e7be788.png)

I am out of ideas at this point.

**Comment by semireg** [comment]
@kspearrin, can you post your package.json mas/mac sections showing entitlements and settings, and also the contents of the entitlement files? I really think this has to do with a bug in electron-builder... assuming you're using it.

**Comment by kspearrin** [comment]
@semireg See

https://github.com/bitwarden/desktop/blob/master/package.json#L63
https://github.com/bitwarden/desktop/blob/master/package.json#L151
and 
https://github.com/bitwarden/desktop/blob/master/resources/entitlements.mas.plist
https://github.com/bitwarden/desktop/blob/master/resources/entitlements.mas.inherit.plist

**Comment by semireg** [comment]
Looks about the same as mine. I've got a help request out to @develar to see if my theory of codesigning with binary entitlements is causing problems. We'll see... he hasn't responded yet. He's a busy guy and I bet this kind of thing is high stress. I mean, it is for us... so... 😉

**Comment by kspearrin** [comment]
@semireg Have you been able to reproduce the issue at all with mas-dev builds? I don't know any other way of testing possible fixes other than submit it to Apple and hope it works.

**Comment by semireg** [comment]
I’m in the same boat. I have no way to reproduce the error they are seeing because my mas-dev builds fail to launch do to code signing issues.

**Comment by kspearrin** [comment]
@semireg My mas-dev builds work just fine. It's just the mas build doesn't work.

**Comment by kspearrin** [comment]
I should also mention that I am on macOS Mojave, which this error is not present. I am going to upgrade to Catalina tonight and see if anything changes with me running the mas-dev build.

**Comment by kspearrin** [comment]
I just finished installing Catalina and I can still run the mas-dev builds without issue.

**Comment by kspearrin** [comment]
@semireg Would it work some way if we just did the code signing manually?

**Comment by rodalpho** [comment]
In the meantime, users can get the MacOS desktop app to work by signing it themselves. This same fix applies to every Electron app Catalina broke. You will need Xcode installed to do it.

```sudo xattr -cr /Applications/Bitwarden.app
sudo codesign --force --deep --sign - /Applications/Bitwarden.app```

**Comment by josias-r** [comment]
I only get the problem with the app store version. So my preferred fallback is installing the version from [bitwarden.com](https://bitwarden.com/)

**Comment by rodalpho** [comment]
That works too. I prefer to  fix the appstore version so it'll work for now, and then when Kyle fixes the problem and pushes an update it will automatically be installed.

**Comment by semireg** [comment]
I'm waiting for MAS review. If approved I'll post my writeup. If it fails, I continue banging my head against the wall.

Out of curiosity, what's the output of this on your mac, mas and mac-dev builds?

```
codesign --display --entitlements :- ./release/*/*.app
```

**Comment by kspearrin** [comment]
@semireg 

mac:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
</dict>
</plist>
```

mas-dev:

```
bplist00?

_ com.apple.application-identifier_#com.apple.developer.team-identifier_com.apple.security.app-sandbox_%com.apple.security.application-groups_6com.apple.security.cs.allow-unsigned-executable-memory_0com.apple.security.cs.disable-library-validation_1com.apple.security.files.user-selected.read-write_!com.apple.security.network.client_ LTZ2PFU5D6.com.bitwarden.desktopZLTZ2PFU5D6	?				       <b???Ko???????
```

mas:

```
bplist00?

_ com.apple.application-identifier_#com.apple.developer.team-identifier_com.apple.security.app-sandbox_%com.apple.security.application-groups_6com.apple.security.cs.allow-unsigned-executable-memory_0com.apple.security.cs.disable-library-validation_1com.apple.security.files.user-selected.read-write_!com.apple.security.network.client_ LTZ2PFU5D6.com.bitwarden.desktopZLTZ2PFU5D6	?				       <b???Ko????????
```

**Comment by semireg** [comment]
I can't find any documentation that says it's good/bad to codesign with binary encoded entitlements, but my hunch (pending MAS review) is that this broke with Catalina. My "fix" is to convert the plist to xml, resign and notarize. It's worth noting that electron-builder only does this (encoded binary plist) if the sandbox entitlement is true. That's why your Mac build looks like normal XML, but your mas/mas-dev builds are outputting the binary plist. If you redirect the output of that command using `> entitlements.temp` and run `file entitlements.temp` it'll say it's a binary plist. You can then use `plutil -convert xml1 entitlements.temp` to convert (in place). Again, if I get good news I'll post my full process. I don't want to send anyone on a wild chase for nothing.

**Comment by kspearrin** [comment]
@semireg Looking forward to hearing if that works or not. Is there a reason why you think that is the issue?

**Comment by semireg** [comment]
Only because my mas-dev builds fail to launch (latest Mojave) until I re-sign them with the XML version of the entitlement. Crash reporter says the failure to launch is related to code signing. AppStoreConnect accepts both builds and the error we are both seeing at review time indicated that entitlements aren’t loaded properly.

**Comment by kspearrin** [comment]
The only thing that makes me think that might not be the case is that my mas-dev builds do work, as in.

**Comment by semireg** [comment]
Agreed. We are two data points. Check this issue for others https://github.com/electron-userland/electron-builder/issues/4040#issuecomment-539225300

Especially the user who said that their entitlements were “corrupt” (before we identified as binary plist).

**Comment by semireg** [comment]
Still rejected with similar error.

**Comment by paradeiser** [comment]
The current MAS version (1.16.7) also crashes on app launch on 
OS X 10.11.6 and
macOS 10.12.6

(is there a way to get the Safari extension unsing the .dmg 1.16.6 version, which works fine?)

Thanks!

**Comment by kspearrin** [comment]
@semireg Yes, I am following. I'm playing with a few things myself now based on your findings.

**Comment by kspearrin** [comment]
v1.16.10 was finally accepted by Apple and should now be available in the Mac App Store. Can anyone confirm that it is working? If you are using the .dmg, you should probably uninstall the first before trying.

**Comment by Ezzahhh** [comment]
I am on macOS 10.15 Catalina and it appears to be working fine for me!

**Comment by kocour** [comment]
Confirmed 1.16.10 from App Store work just fine on Catalina

**Comment by CFKevinRef** [comment]
Excellent! 1.16.10 fixes the issue for me as well (Catalina). Waiting on some feedback about Mojave per @kspearrin's request.

**Comment by 2pockets** [comment]
I was just in the App store and 1.16.10 BitWarden wouldn't download. The error message "A server with the specified hostname could not be found."
<img width="426" alt="Screen Shot 2019-10-16 at 10 18 55 AM" src="https://user-images.githubusercontent.com/56288034/66943661-80052d80-f000-11e9-9f71-9c8067d1623f.png">

**Comment by kspearrin** [comment]
@2pockets That sounds like an app store connectivity issue. Can you download any apps?

**Comment by kocour** [comment]
@2pockets That is general appstore issue for sure, I was’nt able to update my Xcode today with same error

**Comment by 2pockets** [comment]
Not sure what's up with the App store. On Bitwarden's page it didn't give me an Apple login. It gave me the error message.  So, I logged in to the store by downloading a different app. Then I was able to download BitWarden. Thanks for the tip.

**Comment by 2pockets** [comment]
1.16.10 BitWarden does not work on OS 10.11.6.  Crashes before open as 1.16.7 did. I'll be interested to see what the oldest OS it is stable on.

**Comment by Zegorax** [comment]
I'm on the latest Catalina version and have no problems now with the AppStore version.

**Comment by josias-r** [comment]
it works for me too on catalina 🥳

**Comment by kellray** [comment]
Hey all. Today, I simply overwrote the app (same version 1.16.6) and it is working just fine in Catalina.

**Comment by ymacora** [comment]
Woraround  for node js. It may work for other applications as well
curl "https://nodejs.org/dist/v12.13.0/node-v12.13.0.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"

**Comment by 2pockets** [comment]
Bitwarden 1.16.11 & extension 1.42.1 work on Mac OS 10.13.6 with Safari 13.0.3. The extension function and fills passwords. So far, the only thing it doesn’t do is show a number of login matches over the extension icon in the Safari toolbar like it does in Firefox.
