### ISSUE TITLE
Windows Store install fails to start if not installed on primary hard drive

### ISSUE THREAD

**Issue by TranquilMarmot** [bitwarden/desktop#323]
I have two drives on my Windows 10 machine; `C:` and `D:`. By default, I have the Microsoft Store install apps to `D:`

When trying to start Bitwarden installed from the Microsoft store it gives me the following error:
![bitwarden-error](https://user-images.githubusercontent.com/504259/66281296-95938e00-e86f-11e9-8fae-db0fc0e1de0d.PNG)

To fix this, I had to go to Settings -> Apps -> Bitwarden and then select "Move" and move it to my main drive, `C:`. The app then starts normally.

It seems like the app should be agnostic to where it's installed.

**Comment by kspearrin** [comment]
Is there any user data at .../AppData/Roaming/Bitwarden ?

**Comment by TranquilMarmot** [comment]
No, the folder didn't even exist and I tried to create it (and a fake `data.json` and `data.json.303227609` file) and it gave the same error

**Comment by kspearrin** [comment]
The next update will require that the app be installed on `C:` drive.
