### ISSUE TITLE
Support macOS 10.11 for Safari 11 extension

### ISSUE THREAD

**Issue by jawsoftware** [bitwarden/desktop#325]
*(Sorry, I don't know if there is another method to reopen an erroneously closed issue)*

El Capitan 10.11.6, Safari 11.1.2, Bitwarden 1.16.6
The Bitwarden Safari app extension doesn't work; the icon is shown on the Safari toolbar, but clicking on it does absolutely nothing (apart visual feedback of click).

*kspearrin commented Oct 3, 2019*
I'm not sure Safari app extensions would work with El Capitan. Do you use other Safari App Extensions installed from the Mac App Store?

*(at this point the issue was closed as I replied too late)*

*jawsoftware commented Oct 7, 2019*
I can confirm that Safari App Extensions do work on Safari 11. I just tried installing Keep Everything from the Mac App Store and it is fully functional. 
I didn't found the standard .safariext on site, so I checked in the application bundle and found the app extension; double-clicking on it installed it on Safari (it is present in Safari Preferences and it appears in the Safari toolbar (so I deduce Safari app extensions are supported by Safari 11.1.2), but clicking on the icon in the toolbar doesn't show any menu.
As an alternative, is there any chance to download the classic .safariext for this version of Safari? I know you did it, but I cannot find it.

**Comment by kspearrin** [comment]
Once we get the desktop working correctly in the app store I will circle back and see if we can get support for macOS 10.11 and up.

**Comment by jawsoftware** [comment]
Ok. thanks.
The desktop app downloaded from site does work well, btw (except for the extension).

**Comment by kspearrin** [comment]
Can you try this dev build and see if it works? https://cdn.bitwarden.net/misc/Bitwarden-1.16.11.dmg

**Comment by jimwins** [comment]
The Safari extension shows up with the dev build, but does not work. The Command-\ shortcut doesn't do anything, nor does the toolbar button.

(Less important is that the icon on the toolbar button appears to be mis-positioned/sized.)
![Screen Shot 2019-10-17 at 11 09 24 AM](https://user-images.githubusercontent.com/329264/67035560-bdd08780-f0ce-11e9-9f35-ae9e3294e4fa.png)

**Comment by kspearrin** [comment]
@jimwins This is on macOS 10.11?

**Comment by jimwins** [comment]
Yes, macOS 10.11.6, Safari 11.1.2

**Comment by kspearrin** [comment]
Can you see if there are any crash logs generated?

Have a look in ~/Library/Logs/DiagnosticReports. To show the Library folder in Finder hit command+J and tick the box with the label that says Show Library Folder. Or use the Terminal to navigate there. The name of the Bitwarden app extension is called "safari", so look for any reports listed like safari_{DATE}_{DEVICE}.crash

**Comment by jimwins** [comment]
No crash logs. If I follow what happens when pressing Command-\ in the debugger, it shows that safari.extensions.dispatchMessage('bitwarden', msg) is getting called but nothing happens. The debugging just says it is returning undefined. (Not sure how to see what, if anything, is happening when the toolbar button is pressed.)

**Comment by kspearrin** [comment]
I am not sure I will be able to figure out what is going on here without being able to debug the safari extension on 10.11, which I don't have. Do you happen to have X-Code and know how to use it?

**Comment by jimwins** [comment]
I'll have to install Xcode on this machine and would only call myself minimally competent at using it, but I can dig in.

**Comment by kspearrin** [comment]
You can hop in our dev chat here and I can try to help walk you through the steps to debug:
https://gitter.im/bitwarden/Lobby

**Comment by jimwins** [comment]
Sure, but it may take a few days before I've had time to get Xcode downloaded and get back to this.

**Comment by jawsoftware** [comment]
I confirm that dev build behaves the same: the bw icon is shown in Safari, and clicking on it does nothing.
I have XCode installed if it can help.

**Comment by kspearrin** [comment]
@jawsoftware Can you pull the browser repo and try to open and build the xcode project in https://github.com/bitwarden/browser/tree/master/src/safari

**Comment by jawsoftware** [comment]
Uhm, I downloaded the zip file, but cannot open in XCode: "incompatible project version." (My XCode version on 10.11 is 8.2.1.

**Comment by kspearrin** [comment]
Hmm, yea, that makes sense. I don't think you can do dev work on newer project formats.

Honestly, I am not sure what we can do to troubleshoot further at this point.

**Comment by 2pockets** [comment]
It would be interesting to find out the oldest OS that the extension works with. 
Has anyone tried it on: Sierra/10.12.6, High Sierra/10.13.6, or Mojave/10.14.6?

**Comment by Hinton** [comment]
Closing this issue since we've had a proper release in the App Store for a while with a Safari extension for 14+.

**Comment by 2pockets** [comment]
Oscar,

How about a link to the post so I know what you are talking about. Haven’t used 10.11 for a long time.

**Comment by Hinton** [comment]
https://github.com/bitwarden/browser/issues/1696
