### ISSUE TITLE
Bitwarden of Microsoft Store version cannot run.

### ISSUE THREAD

**Issue by fxzxmicah** [bitwarden/desktop#329]
![image](https://user-images.githubusercontent.com/48860358/66837074-fe2bea80-ef94-11e9-9b44-2c31bf15cc41.png)
Win32 version can run normally.

**Comment by kspearrin** [comment]
Are you running any anti virus?

**Comment by fxzxmicah** [comment]
Just Windows Defender @kspearrin

**Comment by kspearrin** [comment]
I just tested this on my Windows 10 desktop from the Windows Store and it works fine, so it would seem to be specific to your device. I am not sure what it could be at the moment.

**Comment by fxzxmicah** [comment]
oh, I didn't notice before, here's the same example as my error (#323). He said that the software can't be installed outside the C disk. @kspearrin

**Comment by kspearrin** [comment]
Your error appears to be a bit different. Are you installing the app outside of C: ?

**Comment by fxzxmicah** [comment]
Yeah, I install it in D:. I found that many uwp apps will prompt that this app can only be installed on C: when installing, so if this app does not support installation in a location other than C:, please set the Microsoft store to only allow installation on C: to avoid unnecessary trouble. If this is a bug, please fix it in time. @kspearrin

**Comment by kspearrin** [comment]
I'll research if there is a way for me to add such warning.

**Comment by kspearrin** [comment]
Found this setting when configuring the app for the store:

![image](https://user-images.githubusercontent.com/1190944/66923627-277d6280-eff7-11e9-9f62-d2283585ffb3.png)


I assume this is what you are referring to. It will be part of the next update. Thanks.

**Comment by fxzxmicah** [comment]
> Yeah, I install it in D:. I found that many uwp apps will prompt that this app can only be installed on C: when installing, so if this app does not support installation in a location other than C:, please set the Microsoft store to only allow installation on C: to avoid unnecessary trouble. If this is a bug, please fix it in time. @kspearrin

@kspearrin Hello, have you fixed the problem mentioned in this issue? Although you can limit where users can install, I think it would be better if users could choose where to install, as I mentioned here. 
> If this is a bug, please fix it in time.

What do you think?
