### ISSUE TITLE
Update starts Bitwarden twice by default

### ISSUE THREAD

**Issue by Thalonius** [bitwarden/desktop#33]
This behaviour was noticed twice now using the Windows version:
1) When a new update is available you get notified and it closes bitwarden (works fine)
2) At the end of the setup Bitwarden automatically starts in it's updated version AND the installer has the option to "Start Bitwarden" checked by default.
So when you click "Finish" in the installer it starts another instance of Bitwarden (now open twice).

Kind regards,
Thalon

**Comment by kspearrin** [comment]
I noticed this too. I reported it to the author of the packaging tool we use: https://github.com/electron-userland/electron-builder/issues/2619

**Comment by kspearrin** [comment]
I patched this by making the app a "single instance" app. So the updater will just re-focus the already open app.
