### ISSUE TITLE
Bitwarden Snap freezes after typing single character

### ISSUE THREAD

**Issue by Vimru** [bitwarden/desktop#330]
I have installed bitwarden with snap (`snap install bitwarden`). When running bitwarden, it launches with two error messages:

```
Gtk-Message: 19:42:42.459: Failed to load module "pk-gtk-module"
Gtk-Message: 19:42:42.460: Failed to load module "pk-gtk-module"
```

When I type a single character in the email or password input fields, the entire window freezes.

```
$ snap --version
snap    2.41-1.fc30
snapd   2.41-1.fc30
series  16
fedora  30
kernel  5.3.5-200.fc30.x86_64
```

**Comment by kspearrin** [comment]
I am not able to reproduce this on Ubuntu 18 with snap 2.42 and Bitwarden 1.16.6. I don't have a fedora box to test on, unfortunately.

**Comment by Igetin** [comment]
I have the same issue with bitwarden 1.16.6.

```
$ snap version
snap    2.42.2-1.fc30
snapd   2.42.2-1.fc30
series  16
fedora  30
kernel  5.3.15-200.fc30.x86_64
```

**Comment by m-kuhn** [comment]
Confirmed here

The AppImage from [the download page](https://bitwarden.com/#download) runs fine

```
snap version
snap    2.42.2-1.fc31
snapd   2.42.2-1.fc31
series  16
fedora  31
kernel  5.4.10-200.fc31.x86_64
```

**Comment by limepixl** [comment]
Happens on Ubuntu 19.10 as well. The AppImage works perfectly fine.

**Comment by m-kuhn** [comment]
Any link to other issues or an upstream bug report?
