### ISSUE TITLE
Extra Entry in "Programs and Features" on Windows after update

### ISSUE THREAD

**Issue by giodestone** [bitwarden/desktop#332]
This issue is similar to #289 - The new update overrides the new files but doesn't remove the old version reference in "Programs and Features" and adds a new program entry, i.e. the entry for the old version remains.

When pressing uninstall on the older version windows just displays an error that says, among other things "...may have already been uninstalled...".

**Comment by sfkpmr** [comment]
Experiencing the same problem on Windows 10.
