### ISSUE TITLE
index.html missing in build directory

### ISSUE THREAD

**Issue by lpknv** [bitwarden/desktop#335]
Once running the commands `npm install` and `npm run electron` the `index.html` file is missing and an error is showing up in the application.

I fixed it by simply creating the `index.html` file in the `build` directory.

See the error in the browser console below.

I hope it helps.

![bitwarden-missing-file](https://user-images.githubusercontent.com/46848124/67166302-6a8c5c80-f38e-11e9-9700-c1d048f522fc.PNG)

**Comment by kspearrin** [comment]
This is expected. Just let the build finish and it will reload once the renderer finishes building.

**Comment by lpknv** [comment]
oh. okay. thank you for the quick response!
I guess the issue can be closed.

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________
