### ISSUE TITLE
BitWarden Close Automatically on MacOS Mojave 10.14.3

### ISSUE THREAD

**Issue by jefrydco** [bitwarden/desktop#336]
Hi, recently I installed BitWarden on Mac Mojave 10.14.3. When I opened it, it suddenly closed automatically. An error window appears with this error trace:

[BitWarden Log Trace.txt](https://github.com/bitwarden/desktop/files/3748505/BitWarden.Log.Trace.txt)

**Comment by kspearrin** [comment]
Does the dmg version from the website work?

**Comment by jefrydco** [comment]
Nice, it's worked! Thanks
