### ISSUE TITLE
Bug: Switching macOS from light to dark (and vice versa) while app is open has no effect on the app!

### ISSUE THREAD

**Issue by thearnav** [bitwarden/desktop#343]
It appears that the app only checks for system theme (light/dark) on launch, and stays the way it opens (light/dark) even after the system theme is changed.

**Comment by aterenin** [comment]
Same issue here, on both the desktop app and browser extension.

**Comment by Hinton** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
