### ISSUE TITLE
Certain menu entries for Bitwarden snap is not working properly.

### ISSUE THREAD

**Issue by mgunt** [bitwarden/desktop#344]
I am using Kubuntu 19.10 and I installed the snap package for Bitwarden. When I logged intot Bitwarden, the application works as epxected, but some menu entires in the menu bar are greyed out and cannot be accessed. What can I do to fix this [issue?]

For some reason, I am having trouble posting a screenshot.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/50 . This is a known electron issue
