### ISSUE TITLE
AppImage doesn't launch, nothing happens when clicked.

### ISSUE THREAD

**Issue by ioogithub** [bitwarden/desktop#345]
I am a new user trying to run Bitwarden on Debian Buster. I downloaded the AppImage but when I click on it, nothing happens. I do see this error logged:

FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that tmp/.mount_Bitwar6JkWbK/chrome-sandbox is owned by root and has mode 4755.

Not sure how to proceed with this. I can't set those permissions because it is an AppImage and it temporarily creates those folders then exits with the error.

I have several other AppImages that run as expected.

I am using the latest version downloaded from the website.

**Comment by hiddenimages** [comment]
I have experienced this same issue with Bitwarden's appimage as well as several others (and I'm also on Debian Buster).  Bitwarden had sent me this link for information:

> I'm sorry to see you are having this issue. It sounds like you are encountering this open bug in one of the libraries we are using, we are following closely for a fix to be made and then we will act on it. You can follow here: https://github.com/bitwarden/desktop/issues/286

It seems from this linked thread that the problem only affects certain distros.

From some of the posts in that thread I used the following workaround:  modifying the .desktop file Exec line to Exec="/path/to/Bitwarden-1.15.2-x86_64.AppImage" "--no-sandbox" %U
This workaround also worked for other appimages that were also not working.  Unfortunately I do not have enough knowledge of any repercussions to running no-sandbox.

The appimage for version 1.14 was still working fine, except that each time I would run it, the appimage would auto-update to the latest version which did not work.

I mostly use the extension for Firefox, so I do not run the appimage too often.  When I do, I've been going with this --no-sandbox workaround for now.   Until I hear of any other fix.

-S

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
