### ISSUE TITLE
"Failed to fetch" errors on desktop app

### ISSUE THREAD

**Issue by Vince972** [bitwarden/desktop#348]
Hello,

System = Xubuntu 18.04
Bitwarden version =
Version 1.16.6
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

Problem = When I'm connected to a VPN, I can't log in. Works fine when the VPN is off.
No problem which browser extension (Firefox).

Same problem here : https://www.reddit.com/r/Bitwarden/comments/ap9iyr/failed_to_fetch_errors_on_desktop_app/

Thanks for this great app.

Vincent

**Comment by kspearrin** [comment]
Open the developer tools under the "View" menu option. Then go to the "Network" tab. Do you see the outgoing network request?

**Comment by Vince972** [comment]
Yes there were outgoing network requests. That's strange, it's working today...
