### ISSUE TITLE
MacOS app was unhardened?

### ISSUE THREAD

**Issue by think222** [bitwarden/desktop#349]
In [this hardening commit](https://github.com/bitwarden/desktop/commit/2e16d7c02c4c28214e3e04a7262926cbdb326427), it appears some insecure entitlements were enabled, rather than disabled.

The following entitlements were set to `true`, but should really be set to `false`:
```
com.apple.security.cs.allow-unsigned-executable-memory
com.apple.security.cs.disable-library-validation
```

Here is a quote from the [Apple documentation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-unsigned-executable-memory):
>**Important**
Including this entitlement exposes your app to common vulnerabilities in memory-unsafe code languages. Carefully consider whether your app needs this exception.

**Comment by kspearrin** [comment]
These entitlements were required for electron at the time.

**Comment by think222** [comment]
Are they currently required? If not, I'd gladly make a PR fixing this.

**Comment by kspearrin** [comment]
As far as I know, yes.

**Comment by think222** [comment]
I see, that is unfortunate. If you know of an electron tracking issue for this, be sure to let me know!
