### ISSUE TITLE
Clipboard data is not marked as concealed on macOS

### ISSUE THREAD

**Issue by MXfive** [bitwarden/desktop#350]
When copying a password to the clipboard on macOS, `org.nspasteboard.ConcealedType` should be set.  This informs the OS and other applications that the contents is sensitive.  Applications such as Alfred that can store clipboard history respect this flag and don't save copied passwords.

I've not looked into the aspects of how this works, but from this PR for another password manager, it looks like it works based of of content mine types: https://github.com/keepassxreboot/keepassxc/pull/1202/files

**Comment by kspearrin** [comment]
Duplicate bitwarden/clients#2633 ?

**Comment by MXfive** [comment]
Aha yes, I the keywords I searched for didn't bring up that issue.
