### ISSUE TITLE
Unable to see saved data on Windows Desktop Application

### ISSUE THREAD

**Issue by siddharthmohta** [bitwarden/desktop#354]
I am unable to see saved data on Windows Desktop Application
On web and browser add-on data looks is fine.

Version 1.16.6
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

**Comment by kspearrin** [comment]
Need more information and reproduction steps.

**Comment by djsmith85** [comment]
Hi @siddharthmohta, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
