### ISSUE TITLE
Unable to logout from Windows Desktop Application

### ISSUE THREAD

**Issue by siddharthmohta** [bitwarden/desktop#355]
I am unable to logout using "Logout" option from "Account" menu.

Version 1.16.6
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

**Comment by kspearrin** [comment]
Why not? What happens?

**Comment by djsmith85** [comment]
Hi @siddharthmohta , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
