### ISSUE TITLE
Paypal auto-fill fails

### ISSUE THREAD

**Issue by networkproblemsolver** [bitwarden/desktop#357]
If I copy the email and password manually and paste using CTRL-V I can log into Paypal.  But if I use the "auto-fill" then it asks for a code on the "enter email" screen.

**Comment by kspearrin** [comment]
The desktop app does not autofill. Are you referring to the browser extension. If so, this is fixed in next version.

**Comment by networkproblemsolver** [comment]
Hey, thanks for the reply.  You were right, I was referring to the "browser extension."  I've solved my problem, though, I no longer do auto-fill with anything (I had auto-fill change my router password without me realizing).  Now I just "click to populate."  Funny how something I thought was an absolute requirement is now something I avoid.  Love BitWarden, keep up the great work, you are a hero in this realm.
