### ISSUE TITLE
MacOS Desktop App Crashes when trying to attach 4th attachment to secure note

### ISSUE THREAD

**Issue by meichthys** [bitwarden/desktop#360]
When trying to attach every 4th attachment to a secure note the desktop app crashes. If i restart the app i can add 3 more attachments and then the 4th attachment crashes the application again.

I'm on Bitwarden Desktop Version 1.16.6 
I'm running OSX 10.15.2

I'd rather not submit the entire OSX crash report publicly, but below are some details that may help track things down:

```

Process:               Bitwarden [37237]
Path:                  /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
Identifier:            com.bitwarden.desktop
Version:               1.16.6 (1.16.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bitwarden [37237]

...

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [37237]
```

**Comment by kspearrin** [comment]
I am not able to reproduce. Are you using the `dmg` or AppStore version of the app?

**Comment by meichthys** [comment]
Hi @kspearrin,
I'm using the dmg version.

**Comment by kspearrin** [comment]
@meichthys , That's what I was using as well. Weird. Does this happen only on a particular item or any item you create in your vault?

**Comment by meichthys** [comment]
@kspearrin  It seems to be any item. I'll test again when i get home and reboot my mac.

**Comment by meichthys** [comment]
@kspearrin It still seems to happen. Just tested it on a new secure note.

On a side note, i find it a little strange that i can't attach documents to a new secure note until after i save it for the first time and then click 'edit'.

Let me know if there's any other information i can provide to help track down the issue.

**Comment by meichthys** [comment]
It used to happen on the 4th attachment, but now it seems to be more random. I can attach up to 6 before it crashes.

I'll try to re-download the app to see if it still happens with a new downloaded dmg app.
