### ISSUE TITLE
password history option from menu bar doesn't list history

### ISSUE THREAD

**Issue by dhrp** [bitwarden/desktop#362]
I looked for the password history, and found that in the Mac OS Desktop app under 'view' there is an option 'password history'. But no matter how I try to find password history it says "There are no passwords to list." 

This surprised me because I knew that this item has a password history.

Turns out that for the same item I can click on the little link "Password history: 1" in the bottom of the detail page, and it does show it. So it must be a bug with the item in the menu bar. Attached screenshot summarises it all.

Thanks for a great tool!!

![Screenshot 2020-01-10 09 47 35](https://user-images.githubusercontent.com/2017300/72139057-599c2780-338e-11ea-8636-d7ef6b5a879e.png)

**Comment by kspearrin** [comment]
This is the password history for the password
Generator, not the item you are viewing.

**Comment by araujoantonio** [comment]
So, there isn't an history for the item?
