### ISSUE TITLE
Windows installer not working behind corporate firewall

### ISSUE THREAD

**Issue by jmborer** [bitwarden/desktop#370]
After downloading and launching the Bitwarden installer exe, it starts and the progress bar moves, then it claims that it was successfully installed, but no: nothing in C:\Program Files\Bitwarden except the un-installer and nowhere a log file that may help identifying the issue. We are behind a corporate proxy that requires NTLM and checks for viruses in binary files. When the files are more than a few MB then it is two step download. 

[edit] in \AppData\Local\bitwarden-updater there is package.7z but its size is only 11 KB

**Comment by kspearrin** [comment]
You can download the `.7z` dependency manually from here: https://github.com/bitwarden/desktop/releases

Then place it in the same directory as the installer. It will use the local `.7z` instead of trying to download it.

**Comment by jmborer** [comment]
Nice trick. It works. Should be added to the documentation.
