### ISSUE TITLE
Localization issue: Missing plural form

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/desktop#374]
There is missing plural form in your string. Text like "text(s)" looks bad. In many languages translators need to have one, few (2-4) and also many form.

See grammar rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

https://github.com/bitwarden/desktop/blob/337f4ad98700c254951ac44b0ab677685192f2f5/src/locales/en/messages.json#L1101

**Comment by mKoonrad** [comment]
@bitwarden-bot Issue still present

**Comment by mKoonrad** [comment]
@dwbit You don't understand issue. I can't prepare good translation with (s) end. You should use plural forms (one, few, many, other form) to prepare good translation. And I can't get any help on Crowdin with any reported issues. I never got any answer there about any reported issue.

**Comment by dwbit** [comment]
Thanks for clarification. We're going through the unresolved issues on Crowdin, so if you don't have anything pending, feel free to post on Crowdin and I'll follow up there.

**Comment by mKoonrad** [comment]
@dwbit Ok. Please look on all unresolved issues on Crowdin. You can find all issues there.
