### ISSUE TITLE
Premium membership not accepted

### ISSUE THREAD

**Issue by yakuraku** [bitwarden/desktop#380]
I have a self-hosted bitwarden instance with a premium-subscription for OTP. Had to reinstall my mac (Catalina) and so Bitwarden. Now after login in the Bitwarden-App / Chrome / Safari, the Premium Membership is not recognised. I use the same email for local and online bitwarden. I'd appreciate if you could fix  this fast, since I'm not able to login into my Google-Account and some other services where I use OTP!!!!!

Screenshot attached. Click on the refresh/reload button does not change anything.
![Screenshot 2020-02-10 at 06 50 11](https://user-images.githubusercontent.com/31287535/74124292-06f29d00-4bd2-11ea-8f6b-a1dae6b0edef.png)

Edit: iPhone is now also affected, so you basically logged me out of my accounts!

**Comment by vincentsalucci** [comment]
Have you contacted customer support about your issue? 
It not, please reach out at https://bitwarden.com/contact/
