### ISSUE TITLE
Encryption keys and private keys stored on disk

### ISSUE THREAD

**Issue by g-arjones** [bitwarden/desktop#381]
Hello @kspearrin, I was doing some research before starting using Bitwarden to manage my passwords and stumbled upon this article: https://medium.com/@davis.a.brandon/bitwarden-doesnt-care-about-security-59e2ef87870a which mentions this issue: https://github.com/bitwarden/browser/issues/485. 

This obviously raised some eyebrows and made me investigate a little further what Bitwarden was actually keeping on disk. I am using macOS Catalina 10.15 and in Bitwarden's Application Support folder (~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden) there is a data.json file that contains the encrypted vault items but also an `encKey`, an `encPrivateKey` a `keyHash` and a `securityStamp` in json format. Could you please elucidate what all these are? Is the encryption key I found in `data.json` the one mentioned in the issues I previously referred to and that could be used to decrypt the vault?

Thank you.

**Comment by kspearrin** [comment]
@g-arjones What you find stored in the data.json file are encrypted versions of your keys. We do not store raw keys to disk. The article you linked was due to a vulnerability that was patched many years ago.
