### ISSUE TITLE
No warning when leaving edit mode with pending changes

### ISSUE THREAD

**Issue by Hakun1n** [bitwarden/desktop#384]
Hi, 

I really think there should be "confirmation" when you change something (especially password!) and click elsewhere without clicking either "Save" or "Cancel". Right now you just automatically lose the changes and if it is the password you just changed by using the generator you're doomed...

More detailed what happened to me:
- I went to one of the pages and wanted to change my password, user settings, change password
- I've opened by Desktop Bitwarden app, found my stored credentials, went to EDIT mode
- Clicked the "Generate password" so the pwd generator popped up
- Clicked the "Regenerate password" till i got password with matching requirements (needs to start with letter in this particular case) 
- Then i hit the "copy password" and clicked the "tick" mark to close the pwd generator (my new PWD is in clipboard)
- /// So at this point i have the record in EDIT mode WITH the pwd already stored but NOT saved yet
- I switched to my browser and pasted the new pwd into the page and SAVED the change on the web. Now i have confirmation that the pwd was changed successfully.
- I went back to Bitwarden and clicked on **other** record in vault while the first record was still in edit-mode (forgot to click the "Save" button first)
- The changes i did were lost so do the new 20+ random char password i just used. Now i have no idea what that password was and i have to use the password reset function. 

Luckily it was a common page where i could reset via email. But there are specific pages (like online banking) which will simply not allow you to reset password over mail and you have to either call the support (limited availability) or visit their branch office. So this sucks a lot...

So please add a warning popup when something gets changed (at least the password!). Something like "You have unsaved changes in the record". Do you want "Save changes X Discard changes X Cancel" where the third one just gets you back to edit mode.

Few extra comments:
- Yes there is the "password history" function (forgot to use it in my case and did the reset) so in theory you can find the PWD there but if you don't realize immediately that you did not saved the new password and generate few more of them there is no way of finding the right one (as you will most probably get locked after several failed attempts)
- I did not "hit" the save right after closing the pwd generator because at that point the pwd was not yet changed on the page. There are situations when the new pwd is not accepted because requirements are not met (like the length is too long, invalid characters, etc...) or maybe page load failure. So first i want confirmation about pwd change then i am saving the new record in BW
- "Remember to click the Save" is a nice "best practice" but time to time you can just do an accident mouse-click while grabbing your mouse. Murphy's Law says you will definitely click at the exact moment where the cursor is on another record...

Hope the explanation makes sense :]

Thanks!

Alex

**Comment by kspearrin** [comment]
The next version of the desktop app will include a warning when navigating away from an add/edit page with unsaved changes.
