### ISSUE TITLE
Username auto-fill does not work on epicgames.com

### ISSUE THREAD

**Issue by GauthierPLM** [bitwarden/desktop#387]
Steps to reproduce:

- Create an epicgames.com account;
- Save the credentials in BitWarden with defaults fields (username & passwords fields);
- Go on login page;
- From the extension, click on the website name to auto-fill the credentials;
- The password is filled but not the username.

Browser: Firefox Nightly 75.0a1 (2020-02-20) (64 bits)
Extension: Version 1.42.2

This issue is here for few months at least.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1029

**Comment by GauthierPLM** [comment]
My bad, wrong repository to report this issue. I'll create it again in the extension repository.

Edit: you closed the issue faster than I could. Sorry for the inconvenience.
