### ISSUE TITLE
Data loss of unsaved changes after Bitwarden auto-locks

### ISSUE THREAD

**Issue by sfgeorge** [bitwarden/desktop#389]
Context: Under `Lock Options`, I have Bitwarden Desktop set to lock my vault after 5 minutes.

What I did:
* I created 3 custom hidden fields, and left the Item in edit mode.
* I then switched to another application for 30 minutes, causing my 5 minute auto-lock timeout to engage.
* When I returned to Bitwarden, the 3 custom hidden fields were not there.

I realize now that I would have been safer to have explicitly saved changes and closed the related Item before switching back to another application.  But I believe it is unexpected behavior that there be loss of data.

I recognize that may be a difficult one, because neither of these 2 options sound great:
1. After the auto-lock timeout, prevent the vault from being locked until the User has confirmed whether they want to commit unsaved changes. 👎  Bad - because the vault may remain open indefinitely if the User walked away from their computer.  This could make the vault more likely to be compromised.
2. After the auto-lock timeout, auto-save unsaved changes. 👎  Semi-bad - because it's possible the User has made modifications that they don't intend to save.  I realize that it's not appropriate for Bitwarden to try to guess whether the unsaved changes are wanted or not.

I wonder if one of these other things might be acceptable - but I know this is starting to sound like a feature request:
3. In the event of unsaved changes when the vault is locked, save any unsaved changes to Items as new 'Draft' Items.
4. In Preferences, provide the User an option to explicitly chose that unsaved changes be either 1.) saved or 2.) discarded when the vault is locked.

----
This issue is similar but _not the same_ as #384. 
> The next version of the desktop app will include a warning when navigating away from an add/edit page with unsaved changes.

... This would not prevent my data loss, as I never navigated away from the edit page; I stayed on it, and the time-out locked & discarded unsaved changes.

**Comment by kspearrin** [comment]
I think #4 is probably the only possible solution.

**Comment by sfgeorge** [comment]
Thank you @kspearrin.  I'll open a proper feature request thread on the community forum in that case. Feel free to close this Issue if that's correct.
