### ISSUE TITLE
Client sends out of date Firefox version user agent (to Duo)

### ISSUE THREAD

**Issue by ispcolohost** [bitwarden/desktop#399]
The MacOS Bitwarden client appears to use the following user agent:

"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"

If the two step login integration is enabled with Duo, and the Duo organization has a policy of not allowing out of date software, this causes the login to fail because Firefox 67 is out of date.

It would probably be preferable to have the Bitwarden client use a proprietary user agent, and then have an option to self configure a user agent for situations where that is needed.  For example, Duo will allow an unknown user agent access if that's not otherwise disallowed, and it's far more likely for an organization to disallow out of date known software versus disallowing all but known software.  If the organization policy disallows both out of date software and unknown software, then the user can revert to filling in a user agent that matches a known-current browser.

**Comment by kspearrin** [comment]
We set this generic user agent so that third party services that receive requests from the app (ex. HaveIBeenPwned) cannot build context about our users. I have bumped it to Firefox 74 for next release.
