### ISSUE TITLE
Bitwarden Desktop catches CTRL+Shift+L

### ISSUE THREAD

**Issue by tetafro** [bitwarden/desktop#402]
Biwraden Info:
```
Version 1.17.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64
```

OS: Linux Mint 19.1 Tessa

Bitwarden installed using snap.

I'm not sure when the last update happend, since it's performed automatically, but today I discovered that the hotkey CTRL+SHIFT+L which I use in another app, now globally grabbed by Bitwarden. When I press it, it brings Bitwarden window in front. If Bitwarden is closed, everything works as before - I can use this hotkey.

Is there any way to change this behavior?

**Comment by kspearrin** [comment]
Should be fixed in next release. Will hotfix soon.
