### ISSUE TITLE
New global shortcut `Cmd+Shift+G` breaks shortcuts in other applications …

### ISSUE THREAD

**Issue by fooness** [bitwarden/desktop#405]
The newly introduces global shortcut `Cmd+Shift+G` breaks the behavior of other applications. This should never have been merged as a globald and non-deactivatable shortcut …

See also: https://github.com/bitwarden/desktop/pull/351

**Comment by NZAU1984** [comment]
I also have this problem on Mac. `Cmd+Shift+G` is used in many apps, including Finder, to go to a specific folder. Very annoying to have Bitwarden taking the focus!

**Comment by kspearrin** [comment]
Shortcut is removed next version coming soon.
