### ISSUE TITLE
Deleting folder does not delete cards within

### ISSUE THREAD

**Issue by ariffjeff** [bitwarden/desktop#410]
While you can delete a folder, doing so will fail to delete all the cards within as well. This has caused a problem for me since there are many cards that I want to delete simultaneously. The only way I can see to do this is to manually go into edit mode for each card and then delete them, which takes 4 user actions per card (very time consuming). Selecting and deleting multiple cards on the browser platform appears to be possible, but not on desktop.

**Comment by kspearrin** [comment]
This is the expected functionality. You can hulk delete items with 1 action using the web vault multi select options.

**Comment by ariffjeff** [comment]
Thanks. I just expected the a functionality like this to be consistent across platforms.
