### ISSUE TITLE
App crashes when deleting an item or folder

### ISSUE THREAD

**Issue by yurtsiv** [bitwarden/desktop#411]
When I click the delete button on an item or folder the app crashes.

Here's the error:

```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

The app is running on Manjaro Linux, Gnome 3.34.4 and was installed via `snap`.

**Comment by arekkusu** [comment]
+1 Can confirm, **unable** to remove entry: application crashes and entry is not removed. Reproducible.

* Environment: Linux/AMD64, Ubuntu 20.04
  * Using ZFS-on-root, with dataset for `snap` folder (meaning mounted separated), unsure if relevant
* Bitwarden installed using software store / snap:

```
Name               Version                     Rev   Tracking       Publisher   Notes
bitwarden          1.17.2                      24    latest/stable  bitwarden✓  -
```
* Issue: Application crashes / closes suddenly after deleting (login) entry. On next launch the entry is not removed
* Reproduce: Create a new entry and delete it (or delete existing entry).
* Note: Deletion works for me using the Firefox extension. Issue seem specific to desktop / SNAP.

Issue happens consistently on my system but have not tested on fresh Ubuntu 20.04 default install. There is a possibility some factor (ZFS and `snap` being it's own mountpoint) are involved.

Journalctl log entry from starting the app to the crash. Not everything might be relevant:
https://gist.github.com/arekkusu/a57dce18f6e24312ec63cd2e228c6aa3

Most relevant is just before the crash:

```
May 10 10:49:11 <HOSTNAME> bitwarden[933425]: Could not load a pixbuf from icon theme.
                                          This may indicate that pixbuf loaders or the mime database could not be found.
May 10 10:49:11 <HOSTNAME> bitwarden_bitwarden.desktop[933425]: **
May 10 10:49:11 <HOSTNAME> bitwarden_bitwarden.desktop[933425]: Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/bitwarden/24/data-dir/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

Interestingly, another snap on the system , Spotify also has log entry related to pixbuf (it does not crash through). Issue seem related to that library.

```
May 10 10:50:35 <HOSTNAME> spotify[164629]: Cannot open pixbuf loader module file '/home/alexandre/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory
                                        
                                        This likely means that your installation is broken.
                                        Try running the command
                                          gdk-pixbuf-query-loaders > /home/alexandre/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache
                                        to make things work again for the time being.
```

Let me know if you need more detail / bug log and if you can reproduce. Thanks.

**Comment by kyle-marshall** [comment]
Hello, I also encountered this issue with Bitwarden 1.26.5 from the snap store on Ubuntu 20.04.2 LTS. This was resolved for me by removing the snap store version and downloading/using the .AppImage from the Bitwarden website (also version 1.26.5).

**Comment by ppd** [comment]
Can confirm for the snap with version/revision `1.27.1 2021-07-07 (52)` on Ubuntu 21.04.
Also crashes when exporting passwords.

**Comment by Hinton** [comment]
This seems to be a known issue caused by the png loader going missing during an update 😖[1].

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/159 suggests running the following commands to refresh it
```
sudo update-mime-database /usr/share/mime
sudo /usr/lib/arm-linux-gnueabihf/gdk-pixbuf/gdk-pixbuf-query-loaders --update-cache
```

[1] https://bugs.launchpad.net/ubuntu/+source/debconf/+bug/1627564
