### ISSUE TITLE
Chinese translation slips

### ISSUE THREAD

**Issue by nomanous** [bitwarden/desktop#413]
The options "password" and "passphrase" in password generator should be translated to two different Chinese words "密码" and "口令" instead of both "密码".
Also in the generator, "minimum numbers" and "minimum special" should be translated to "最少数字字符数" and "最少符号字符数" respectively.
The slips appear on the chrome plugin too.

![image](https://user-images.githubusercontent.com/22901252/77030299-19ce6d80-69d9-11ea-926a-bc4d733ba6eb.png)

**Comment by kspearrin** [comment]
Please see https://help.bitwarden.com/article/localization/
