### ISSUE TITLE
Unable to install Bitwarden on x64 Windows

### ISSUE THREAD

**Issue by bkralik** [bitwarden/desktop#414]
![obrazek](https://user-images.githubusercontent.com/5994847/77044619-09f65f80-69c0-11ea-8cb3-941baae2afb2.png)
![obrazek](https://user-images.githubusercontent.com/5994847/77044658-15e22180-69c0-11ea-885c-02c9647ed6ea.png)

But my internet connectivity seems allright, I can download that file easilly with broswer/wget/other tools...

My firewall is off and I use just windows defender (not any other AV)

**Comment by kspearrin** [comment]
Try downloading the x64 .7z file from here https://github.com/bitwarden/desktop/releases

Then place it in the same directory as the installer and run the installer again. It should use the local file instead of trying to download it

**Comment by djsmith85** [comment]
Hi @bkralik did the workaround @kspearrin mentioned work? If so, could you please close this issue.

**Comment by bkralik** [comment]
Sorry, I totally forgot about this. I am not sure what was happening, but installation works fine now. Closing...
