### ISSUE TITLE
Creating a Note and switching views kills the note

### ISSUE THREAD

**Issue by echolock** [bitwarden/desktop#415]
I created a note, and didn't save it (didn't know I had to), and then switched from Secure Notes to All Items and it destroyed the note and changed the Edit view to a login item edit view instead.

I would suggest either:
- auto-saving the note OR at least keeping it open in the edit area
- if the user quits the app, bring up a warning that they will lose the current note/item that is being edited

**Comment by kspearrin** [comment]
It should have prompted you to save before navigating away.

**Comment by echolock** [comment]
No, it definitely doesn't. Not for me anyway.

**Comment by vincentsalucci** [comment]
@echolock - thank for the report! Can you please answer the following questions:
- What operating system and version are you using?
- What version of the desktop application are you using?

**Comment by echolock** [comment]
- What operating system and version are you using? Windows 10 Pro 64bit (v
1909) and also Mac OS High Sierra 10.13.6
-
- What version of the desktop application are you using?  *Bitwarden 1.17.1
*

**Comment by vincentsalucci** [comment]
@echolock Thanks for the updates - I've been able to successfully replicate the issue and should have some fixes done soon &trade;
