### ISSUE TITLE
Account > Premium Membership wrongly tells me I'm not a Premium Member

### ISSUE THREAD

**Issue by mackaaij** [bitwarden/desktop#418]
I get this string: "You are not currently a premium member."
https://crowdin.com/translate/bitwarden-desktop/53/en-nl#2094

It's used in this file:
https://github.com/bitwarden/desktop/blob/21e32542192a45d4c203d9091e563434456f07c9/src/app/accounts/premium.component.html

When I click the button to buy Premium, my vault opens without the banner "You have premium access" from this string:
https://crowdin.com/translate/bitwarden-web/58/en-nl#2913

If I navigate to Organisations, Bitwarden wrongly informs me I'm not a member of any organisation. 

After clicking around a bit, Bitwarden shows me the organisation and the Premium banner re-appears.

Let me know if you need more info for reproduction.

**Comment by kspearrin** [comment]
Do you have a premium membership subscription or are you only a member of an org that gives you premium access?

**Comment by mackaaij** [comment]
Via an organisation (Family).

**Comment by zugl** [comment]
I'm also with the same problem. Member of an organization with enterprise subscription.

**Comment by zeten30** [comment]
Same problem on my side. We have company organization / premium access.

**Comment by zeten30** [comment]
![Screenshot from 2020-10-20 10-16-09](https://user-images.githubusercontent.com/1825873/96561016-52ac2900-12bf-11eb-94e5-f3cf949ffc47.png)
![Screenshot from 2020-10-20 10-15-38](https://user-images.githubusercontent.com/1825873/96561029-56d84680-12bf-11eb-9332-32f714eb67ac.png)

**Comment by aravindhp** [comment]
I am facing the same issue. I am part of a company organization with premium access.

**Comment by cscharf** [comment]
Thanks, this is definitely on our radar to get this buttoned up consistently across all of our clients.

**Comment by saimonmoore** [comment]
I just bought a premium membership and the linux desktop client still believes I do not. I've re-logged in umpteen times already. Not sure what else I need to do :(

**Comment by saimonmoore** [comment]
Update: By forcing a full-logout and relogging in it fixed it. Still not nice.

**Comment by jamesonp** [comment]
Same issue.  Premium via organization, shows on the web version but does not show premium in the Chrome extension.

**Comment by cscharf** [comment]
This will be resolved in the upcoming release.

**Comment by jamesonp** [comment]
> This will be resolved in the upcoming release.

Thank you

**Comment by Hinton** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by kaliavarun** [comment]
I had the same issue. Logging out and logging back fixed it.
