### ISSUE TITLE
Desktop client unusable if DNS not operating

### ISSUE THREAD

**Issue by jjeffery** [bitwarden/desktop#426]
If you start the BitWarden desktop client on a computer with a functioning network, but DNS unavailable, the desktop client will show an "in progress" animation and is not usable.

This was important to me because I needed the password to the local router/firewall applicance but could not access it because BitWarden was (presumably) trying to figure out if it needed an update or not, or maybe it was synchronizing its data.

I would suggest that BitWarden would be more useful in these scenarios if it permitted access to the locally-stored data while these network operations were in progress.

![image](https://user-images.githubusercontent.com/458924/78194782-6ded4d80-74c1-11ea-869f-dd39a3c5155c.png)

**Comment by kspearrin** [comment]
@vincentsalucci  Can you test pulling the plug and unlocking the app?
