### ISSUE TITLE
No prompt to unlock after restart

### ISSUE THREAD

**Issue by zahroc** [bitwarden/desktop#428]
Windows 10 1909 Build 18363.720
Bitwarden Desktop v1.17.2 / Shell 6.1.7 / Renderer 76.0.3809.146 / Node 12.4.0 / Architecture x64

When having Bitwarden start with Windows, I from the taskbar and it does not display the prompt to unlock. Some menu items are available such as File/Quit.

If I quit the program and rerun Bitwarden, it works every time.

**Comment by Skrapshak** [comment]
Hey zahroc,

I can understand your frustration. I find it curious that Bitwarden doesn't have an in-app setting to 'Start with Windows' like other password managers that I've used personally and for work. 

On to your issue. Do you happen to have "Start To Tray Icon" enabled in Settings?

<img width="369" alt="StartToTrayIcon" src="https://user-images.githubusercontent.com/30083755/83212866-85d5fc00-a115-11ea-9c99-6dcc6c325fd0.PNG">

If so, you might want to try and disabling that.

If you don't have that enabled, I hope that you get a solution soon.

**Comment by zahroc** [comment]
I do have that set with BW starting from the STARTUP Folder at boot. I will disable that setting and give it a try. unfortunately I can not reproduce 100% of the time.
