### ISSUE TITLE
i can't remove and login..

### ISSUE THREAD

**Issue by KOKOLALAMA** [bitwarden/desktop#435]
同時顯示1.16.6跟1.17.2，
移除會留下1.16.6，

i can't remove 1.16.6

https://imgur.com/jOp8ri2.jpg

https://imgur.com/SVOkimG.jpg

程式安裝後，明明輸入信箱，
卻被要求輸入信箱。

i can't login 1.17.2

https://imgur.com/ApLyGNu.jpg

**Comment by sevensixseven** [comment]
No worries, you can use this remove the unwanted "Apps & features" entry. You will want to save the code below as a (.reg) file and then run it.

`Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{173a9bac-6f0d-50c4-8202-4744c69d091a}]`

**Comment by KOKOLALAMA** [comment]
my email can login firefox-addones and web.
However, the PC client cannot be logged .

**Comment by djsmith85** [comment]
Hi @KOKOLALAMA, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
