### ISSUE TITLE
Unlock with pin does't work 

### ISSUE THREAD

**Issue by Fabioah** [bitwarden/desktop#436]
I am not able to use the "unlock with pin" option since even if it's enabled and after it asked me to enter my pin,it does nothing. I had this problem both in Ubuntu 19.10 using latest deb package (can't remember version) and in Ubuntu 20.04 using latest snap. Vault is set to lock on reboot but in fact it locks every time I close the app.
Tell me if I should provide further infos / logs

**Comment by fascox** [comment]
Make sure you have not selected the option to require your master password along with your pin.

**Comment by JuanVqz** [comment]
I was thinking the same as @Fabioah but after following your instructions it works.

I tried it with iOS app Version: 2.4.2 (68)
Thank you for your work
