### ISSUE TITLE
Deleting an entry generates Yes/No popup that's unreadable. 

### ISSUE THREAD

**Issue by ivnvitx** [bitwarden/desktop#440]
It's happening in Linux's snap version, happening with any language.

**Comment by tabelro** [comment]
Having the same issue on Linux's snap version
![bug](https://user-images.githubusercontent.com/22519605/81189345-cf8d6400-8ff9-11ea-9082-2ebef59dd167.jpg)

**Comment by n30phyte** [comment]
Still having the same problem.

**Comment by Hinton** [comment]
Hi,

This issue seems to be a duplicate of bitwarden/clients#2628, there are some potential work-arounds mentioned on the snaps forums, but unfortunately we haven't stumbled upon this ourselves yet.

Going to close this to avoid duplicates.
