### ISSUE TITLE
Make bitwarden-desktop availible through the NPM registry

### ISSUE THREAD

**Issue by TheMageKing** [bitwarden/desktop#441]
This is technically a 'feature', but it is a technical feature that really belongs here.

I noticed that this app is designed to be built and installed via NPM, however, it's not actually on the NPM registry.  I think you should make it available through NPM, as bitwarden-cli is.

The reason I ask is because I am looking at packaging this for the Debian repositories, and while a handy tool exists for turning npm packaging into debian packaging (npm2deb), it currently requires that the npm package be available on the registry.  Although I am trying to patch npm2deb to work on a locally downloaded file, I am left wondering why bitwarden isn't simply added to the NPM registry.  Is there some underlying technical reason?

Thanks for your time.

**Comment by kspearrin** [comment]
I don't think I have ever installed a GUI desktop application through NPM. Is this something that is possible/normal to do?

**Comment by TheMageKing** [comment]
I found this
https://www.npmjs.com/package/npm-gui

It seems to be a GUI npm package manager that can be installed via npm.
But I don't think it's an electron app: it runs in the browser.  However,
from browsing the NPM docs, I think it's fine.
The only referred to limits are naming guidelines and ensuring that `npm
install` works: thus, I think its totally reasonable to expect that this is
possible.
However, I could be wrong, and I never managed to find an electron app that
installs via NPM.  And the second line of your guide, `npm run electron`,
might break it.

But I am hardly a javascript developer.

**Comment by kspearrin** [comment]
We don't plan to distribute the desktop app over NPM at this time.
