### ISSUE TITLE
Unable to upgrade outdated bitwarden snap on Ubuntu

### ISSUE THREAD

**Issue by kvdb** [bitwarden/desktop#444]
As a bitwarden user on Ubuntu 20.04 (upgraded 18.04), I'm unable to upgrade to a more recent version of bitwarden. Not sure if this an issue with bitwarden or Ubuntu...

1. Observe old version installed currently.
```
$ snap list | grep bitw
bitwarden             1.12.0                      16    latest/stable    bitwarden*    -
bw                    1.9.1                       15    latest/stable    bitwarden*    -
```

Try upgrading, seems no upgrade is available...
```
$ snap refresh
All snaps up to date.
```

I expected to get the latest version available as seen here: https://github.com/bitwarden/desktop/releases

**Comment by kspearrin** [comment]
This seems like a snap issue to me. I do not know why it would report that there are no updates for you.

**Comment by djsmith85** [comment]
Hi @kvdb, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
