### ISSUE TITLE
Default option for clear clipboard is 'Never'

### ISSUE THREAD

**Issue by saurabhs** [bitwarden/desktop#447]
This issue exists on Android app too.

The default clear clipboard setting should be time based by default (say, 30s) and let the user to set it to 'Never'. 

This covers lot of users who doesn't review the default settings (and in case of clear clipoard, hidden in Settings > Options).

**Comment by kspearrin** [comment]
We don't want to modify a user's clipboard without their consent, which is why it is set to "Never" by default.

**Comment by saurabhs** [comment]
KeepassXC does it, so I though that was norm. Alternative can be (atleast on Android) to move the Clear Clipbaord to Settings, since its hidden in Setting > Option.

**Comment by saurabhs** [comment]
since there's no reply in last 7 days, closing the issue, disappointingly
