### ISSUE TITLE
Ubuntu SNAP: App won't start if cant' read ~/Documents

### ISSUE THREAD

**Issue by arekkusu** [bitwarden/desktop#448]
Snap package version of Bitwarden won't start if there is an "issue" with ~/Documents permission.

I figured out this was because on my system ~/Documents was a symlink to /mnt/DATA/documents/. This is a separate mount (ZFS datasets actually). It has permission for my user but of course SNAP can imposes some restriction.

* Environment: Linux/AMD64, Ubuntu 20.04, using following SNAP (from software store):

```
Name               Version                     Rev   Tracking       Publisher   Notes
bitwarden          1.17.2                      24    latest/stable  bitwarden✓  -
```

Note: Running `bitwarden` from terminal did not return anything, system log did point to the issue:

```
May 09 20:56:20 <HOSTNAME> kernel: audit: type=1400 audit(1589025380.744:73): apparmor="DENIED" operation="rmdir" profile="snap.spotify.spotify" name="/mnt/DATA/documents/" pid=138847 comm="rmdir" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0
```

Note the Bitwarden [Snap permission (screenshot)](https://user-images.githubusercontent.com/3620344/81489461-8f0b4000-92b0-11ea-950c-8ec1c9310795.png). I tried disabling "Access file in your home folder"

Question / Expectation:

* Why does Bitwarden SNAP need access to ~/Documents / home folder (outside of dedicated snap folder) ?
* Any way for this to not fail or at least not "silently"?
  * I am not sure if that an issue that need handling on SNAP side.

**Comment by andreasmjg** [comment]
I think I also had this issue. Wouldn't start, didn't give any error. I did `snap remove bitwarden` and went into my `~/snap/bitwarden/` folder and removed a file called "current".

I then re-installed via `snap install bitwarden` and it now works again.

**Comment by mod-john** [comment]
I also have the same issue with the logs showing this reason:

audit: type=1400 audit(1634780384.021:412): apparmor="DENIED" operation="rmdir" profile="snap.bitwarden.bitwarden" name="/media/windows/Users/modjohn/modjohn@gmail.com/Documents/" pid=60203 comm="rmdir" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0

I have a dual boot system and I symbolic link my ~/Documents to a folder in a mounted local NTFS volume,
