### ISSUE TITLE
URI Port not shown

### ISSUE THREAD

**Issue by coussej** [bitwarden/desktop#449]
When a bitwarden entry has a port in the URI, the port is not shown in the app. During editing it looks like:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/9944663/81814867-8ffad680-9529-11ea-8ec0-70fa663317c6.png">

When viewing it looks like:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/9944663/81814887-98531180-9529-11ea-9e04-e3f4bed5dcb8.png">

We notices this because we use the URI fields also for the information they contain, not only to link them to a website for browser autocomplete.

**Comment by ToGitOrNotToGit** [comment]
I don't know why BW truncates all URI as they do. Not sure the design decision here. I find it to be a bad UX. I would love to see full un-truncated URI data when not in Edit mode. URI labels and reordering would be nice while we're at it!
