### ISSUE TITLE
Windows desktop 1.17.2 - An error has occurred. An unexpected error has occurred.

### ISSUE THREAD

**Issue by milnak** [bitwarden/desktop#452]
This was working previously, so I'm not sure what happened.

Now when I try to log in with the desktop app, I get the message shown in the subject.

The developer network tab shows:

status.bitwarden.com -  response: {"status":406,"error":"Not Acceptable"}

Can someone assist?

**Comment by milnak** [comment]
(The chredge extension is working fine)

**Comment by kspearrin** [comment]
We had some downtime earlier which likely caused this problem. Should be resolved now.

**Comment by milnak** [comment]
@kspearrin thanks. Can that error be improved?
