### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by klzig** [bitwarden/desktop#453]
Suddenly I'm unable to sync or save a new login entry.

On two different Windows 10 machines I get an "unable to sync" error when syncing and "An error has occurred. Unexpected token < in JSON at position 0" when saving a new entry.  Both messages appear briefly in popups.

On Android 9 I don't see an error when I sync but the app crashes when a new entry is saved and the entry is lost.

On Windows I'm running:
Version 1.17.2
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by jwarner112** [comment]
Also dealing with this as of a few minutes ago. Backend server must be having a problem -- I had hoped there'd be a "save local, catch up later" way to do this so I can still make an account, though.

**Comment by jwarner112** [comment]
Update: [they're aware of it](https://twitter.com/Bitwarden/status/1124047755771621381), it's being caused by [an Azure outage](https://status.azure.com/en-us/status).

**Comment by kspearrin** [comment]
This should be resolved now. We had some downtime earlier which likely caused this problem.
