### ISSUE TITLE
Windows 10 Desktop app Window doesn't show up after upgrade.

### ISSUE THREAD

**Issue by jwhang627** [bitwarden/desktop#461]
After I upgraded (and later reinstalled) to the latest version, the desktop window to the app doesn't show up.

**Comment by clayadams5226** [comment]
@jwhang627 Can you provide more information / steps to reproduce.

**Comment by jwhang627** [comment]
For better quality: https://streamable.com/5fe1ob

![recreation](https://user-images.githubusercontent.com/14305330/84429970-a494c200-abee-11ea-854f-187d849466f8.gif)

**Comment by clayadams5226** [comment]
Thanks. It looks like it may be opening off-screen. That's a pretty common, and annoying, thing that happens with a lot of Windows 10 apps. Can you see if these steps work?

https://www.technipages.com/bring-off-screen-window-back-onto-screen

**Comment by jwhang627** [comment]
It works! Thank you for the tip.
