### ISSUE TITLE
Desktop app not deleting items

### ISSUE THREAD

**Issue by Razer0123** [bitwarden/desktop#464]
Using latest Mac app, if I try to delete an item nothing happens. Logging to the vault via browser and deleting from there works though

**Comment by cscharf** [comment]
Can you list the desktop build/version number you have installed and your macOS version? Are you using the cloud, self-hosted, official Bitwarden server or an alternative, etc.?

**Comment by Razer0123** [comment]
Hello, it is latest version v1.18.0

Self hosted using this add-on for Home Assistant

https://github.com/hassio-addons/addon-bitwarden

**Comment by kspearrin** [comment]
This is the official Bitwarden repo. Please contact the maintainers of community-created Bitwarden_RS, who maintain that addon for Hassio.
