### ISSUE TITLE
Disabling "Enable Tray Icon" doesn't remove old tray icon

### ISSUE THREAD

**Issue by uwueviee** [bitwarden/desktop#467]
## Describe the Bug
When unchecking the "Enable Tray Icon" option, Bitwarden will not remove the old tray icon, allowing for duplication.

## Steps To Reproduce
1. Enable the tray icon option
2. Disable the tray icon option
3. Notice the tray icon is still there
4. Repeat steps 1 and 2 for duplication

## Expected Result
The tray icon is removed

## Actual Result
The tray icon stays and isn't removed

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/15057172/85212950-07d8cf80-b326-11ea-9ada-975edc1cfee1.png)
[Link to video](https://streamable.com/4d5qpf)

## Environment

- Operating system: GNOME Shell 3.36.3 on Arch Linux with AppIndicator/KStatusNotifierItem Version 33
- Build Version: 1.18.0

**Comment by clayadams5226** [comment]
This looks to be a known issue in Electron 
https://github.com/electron/electron/issues/17622

**Comment by clayadams5226** [comment]
Work around has been created to resolve the duplicate tray issue.
https://github.com/bitwarden/jslib/pull/227
