### ISSUE TITLE
Automatic installation of version 1.19.0 failing, unable to retain version 1.18.0

### ISSUE THREAD

**Issue by michaelharrod** [bitwarden/desktop#473]
## Describe the Bug

Windows client is attempting to install an update, but on completion, Bitwarden is not installed.

## Steps To Reproduce

1. Start Windows 1.18.0 version.
2. Wait until prompted that version 1.19.0 version is available.
3. Exit the app.
4. Complete the installation.
5. Try to start the updated app - shortcut points to application that no longer exists.

## Expected Result

Installation successful and version 1.19.0 is running.

## Actual Result

Version 1.19.0 is not installed, and version 1.18.0 has been removed.

## Environment

- Operating system: Windows 10
- Build Version 1.18.0

## Additional Context

If I return bitwarden.com and download the windows installer, I get version 1.18.0. Install that, it starts OK, then I am warned about the 1.19.0 installation and the loop starts again. Help!

**Comment by kspearrin** [comment]
The website download link is now updated.

**Comment by michaelharrod** [comment]
Thank you. It still seemed to automatically notify of 1.19.0 being available and uninstall 1.18.0, but then didn't install 1.19.0.

Nonetheless, I have manually downloaded and installed 1.19.0 and am up and runing again.
