### ISSUE TITLE
Vault Automatically Locks After Changing Theme

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/desktop#478]
### **Describe the Bug**
Vault automatically locks after changing theme of the desktop application

### **Steps To Reproduce**
1. Open Bitwarden Desktop App
2. Change the theme 

### Expected Result 
Theme changes without locking vault

### **Actual Result**
Vault gets locked automatically.

### **Environment**
Operating System: Windows 10 
Version 1.19.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by MattTheDev** [comment]
@vachan-maker Thanks for the issue. This is actually by design - theme components are loaded on load of the app, and to load the new theme we actually do a refresh of the UI. On refresh, memory is wiped, and the natural flow of how things happen .. you're then presented with a locked vault.
