### ISSUE TITLE
Sometimes login autofill in firefox/ios does not work

### ISSUE THREAD

**Issue by AlexVKNG** [bitwarden/desktop#482]
I use regular firefox on an iphone, latest update, 6s plus.

When I try to use bitwarden to autofill login/password on any website, I input master password, tap an existing login in the vault and nothing happens, login/pass fields remain empty.
I need to do everything again (exactly the same steps) and only then my login/pass will be autofilled.

Tried with a few different websites - exactly the same. And after some more testing I couldn't pinpoint when it happens. Just sometimes. It feels like it usually happens when I spend some time not using firefox in other apps and just generally after some real life time it happens.
Never happened once in ios Safari btw.

**Comment by vachan-maker** [comment]
I have heard some complaints regarding the autofill in the iOS app. So you are not alone.
