### ISSUE TITLE
where to insert our own baseURL?

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/desktop#485]
Hi again,

I thought the logical place to insert our own baseURL for our own server would be [here](https://github.com/bitwarden/desktop/blob/84af4ee48f2e22770376aecf27613dc65ab1d137/tsconfig.json#L12)

I tried replacing the . with my own URL (I've tried with and without the https) but when I then run npm run build it fails.

Is there another place where I should insert my own? I know that users can just go to Settings and change it there but that's not very practical with older members of the family that aren't very computer literate.

Thanks

**Comment by pdarcos** [comment]
Anyone know where to set our self-deployed server URL?

**Comment by pdarcos** [comment]
Sorry to bug you @kspearrin but can you point me to the right file I need to change?

I figured this would be an easy change but I can't find where vault.bitwarden.com is hardcoded.

Thanks

**Comment by kspearrin** [comment]
default URLS are set in jslib/services/api.service.ts and jslib/services/environment.service.ts

**Comment by pdarcos** [comment]
Thanks @kspearrin 

FYI your ubuntu app no longer builds after you updated jslib last night.
