### ISSUE TITLE
JavaScript error on startup 

### ISSUE THREAD

**Issue by Ncrypt3dit** [bitwarden/desktop#488]
The following error has been popping up recently every time I start Bitwarden on a Win7 x64 Machine. 
Bitwarden starts up and works with no issue that I can see during normal operation.

https://i.imgur.com/jkTxqvG.png

## Steps To Reproduce

Just doing a fresh start of BitWarden after  a reboot.

## Screenshots or Videos

https://i.imgur.com/jkTxqvG.png

## Environment

- Operating system: Windows 7 x64
- Browser: N/A Desktop App Issue
- Build Version: 1.19.0 https://i.imgur.com/V6RObYl.png

**Comment by cscharf** [comment]
Notes in regards to electron-store known issues with file locking on Windows through asar. There may need to be a different access pattern created to fully avoid this, but as long as the application functions after the error we should be okay (for now):

see:
* https://github.com/sindresorhus/electron-store/issues/31
* https://github.com/sindresorhus/electron-store/issues/30
* https://github.com/electron-userland/electron-json-storage/issues/116#issuecomment-441579273

**Comment by Kozzren** [comment]
I am also having this same error, but i unfortunately cannot use the program on the latest release. 1.19 works but 1.20 does not.

**Comment by zimmermanj42** [comment]
Same error for me on Windows 7 x64.  I can downgrade to 1.19 which works fine, but the auto-update is constantly putting me to 1.20 after one use.  Going to have to use the portable version for now I suppose.

**Comment by zimmermanj42** [comment]
Sorry, had two tabs open and commented on the wrong thread.  No, it is not this error for me, but the other you linked to.
