### ISSUE TITLE
Lock Now option is greyed out in system tray

### ISSUE THREAD

**Issue by MiltenPlescott** [bitwarden/desktop#493]
## Describe the Bug

After closing and reopening Bitwarden desktop app Lock Now option in system tray context menu is greyed out even though the desktop vault is unlocked.

## Steps To Reproduce

1. Enable tray icon in settings
2. Click on system tray icon &#8594; Lock Now option is available
3. Close Bitwarden desktop app (either using close button or system tray &#8594; exit)
4. Start Bitwarden app again
5. Unlock vault
6. Lock Now option in system tray is greyed out and unclickable
7. Go to Settings &#8594; Disable, then Enable system tray icon
8. Lock Now option is no longer greyed out

## Expected Result

Lock Now option in system tray works even after restarting Bitwarden desktop app.

## Actual Result

Lock Now is greyed out after Bitwarden restart.

## Screenshots or Videos

![bitwarden_system_tray_bug](https://user-images.githubusercontent.com/30568667/88805065-fe594780-d1ae-11ea-946d-5f742c5663d8.jpeg)

## Environment

- Operating System: KDE neon 5.19
- KDE Plasma Version: 5.19.4
- KDE Frameworks Version: 5.72.0
- Qt Version: 5.14.2
- Kernel Version: 5.4.0-42-generic

### Bitwarden
- Version 1.19.0
- Shell 6.1.7
- Renderer 76.0.3809.146
- Node 12.4.0
- Architecture x64

**Comment by MGibson1** [comment]
This appears to be an upstream issue with electron, see electron/electron#14941, as left click-to-show is also not working but always popping up the context menu.

As a partial workaround we can force the context menu update by resetting it rather than changing the underlying object as we do now.

Working on a PR for this.
