### ISSUE TITLE
Current touchIdConsentMessage is not meaningful.

### ISSUE THREAD

**Issue by accolon** [bitwarden/desktop#496]
## Describe the Bug

On macOS, the English Touch ID prompt reads:

> "Bitwarden" is trying to Verify for Bitwarden..
> Touch ID or enter your password to allow this.

As you can see, there are several issues with the current _touchIdConsentMessage_ string:
- capital V in "Verify"
- the unnecessary additional period
- the text makes no sense

I suggest using something like the following as _touchIdConsentMessage_:

> unlock the vault

## Steps To Reproduce

Enable Touch ID on macOS, restart Bitwarden Desktop.

## Environment

- Operating system: macOS Catalina
- Build Version (go to "Settings" → "About"): 1.20.0

<img width="556" alt="Screenshot 2020-07-29 at 18 32 29" src="https://user-images.githubusercontent.com/126886/88894658-80497f00-d248-11ea-8168-28f082d2c285.png">

**Comment by cwille97** [comment]
I'm working on a fix for this

**Comment by cscharf** [comment]
Resolved with #578 , thanks @cwille97
