### ISSUE TITLE
File menu disabled on Ubuntu 16.04

### ISSUE THREAD

**Issue by pehlm** [bitwarden/desktop#50]
Thanks for the stable 1.0 version. Anything new on the menu issue on Ubuntu 16.04? https://github.com/electron/electron/issues/11891.

**Comment by kspearrin** [comment]
Any news will come from the linked issue. So no news.

**Comment by NerdHarder615** [comment]
Are there any updates on this issue? Or anything that can be done to help troubleshoot this issue?

**Comment by kspearrin** [comment]
As mentioned previously, this is an Electron issue. There isn't anything we can do until they fix the problem. The issue is linked above.

**Comment by kspearrin** [comment]
Not fixed.

**Comment by pehlm** [comment]
Seems to work on 18.04, at least, upgraded to 1.10.

**Comment by et304383** [comment]
@pehlm no idea how this is workign for you.  I'm fully updated via apt and have Bitwarden 1.10.0 installed and the menu still isn't working for me.

**Comment by Fiech** [comment]
@et304383 On Ubuntu 18.04 with KDE5, it works for me as well, but not on my other machine with Ubuntu 16.04 with Unity.

**Comment by et304383** [comment]
Ahh!  I'm using Unity (I hate Gnome).  So this isn't an Ubuntu issue as much as it's probably a Unity issue.

**Comment by pehlm** [comment]
Earlier it didn't work for 18.04 but now it does (18.04 use Gnome). If you are using 16.04, it does not seem to work though. If it is because of Unity, I don't know. Likely not.

**Comment by pwyde** [comment]
Still an issue with snap package on the following system:
OS: KDE Neon (Ubuntu 18.04 base)
Architecture x64
Snap version: 1.11.2

**Comment by leggettc18** [comment]
This is also an issue for me on Solus Budgie with the Snap version 1.12.0 Rev 16. I'm using a self hosted Bitwarden server and the Global Menu widget on Solus Budgie if that matters.

**Comment by GLaDTheresCake** [comment]
Issue here too, KDE NEON on Arch with latest version from the AUR (1.14.0). Only seems to happen when the global menu is pinned to a bar (which adds the context menu of the application to outside the application window). When I remove this global menu bar, and the context menu is attached to the application, the buttons are no longer greyed out.

**Comment by FrankySnow** [comment]
Same issue with :
- Kubuntu 18.04 
- Plasma 5.12.7
- Bitwarden 1.14.0
- Shell 3.0.14
- Renderer 66.0.3359.181
- Node 10.2.0
- Architecture x64 
but only when the global menu is enabled (I had to disable it in order to use Bitwarden). What is unclear for me is : if this is an electron-related issue, why don't I see this behavior with all of the other electron apps ?

**Comment by akhfa** [comment]
> but only when the global menu is enabled (I had to disable it in order to use Bitwarden). What is unclear for me is : if this is an electron-related issue, why don't I see this behavior with all of the other electron apps ?

This is true. Thank you. I disabled global menu, and the issue is gone. 

I like the global menu, but need to disabled it when I need to access bitwarden desktop apps menu

**Comment by Sparsa** [comment]
I am facing the same issue in KDE 5.16.4 with global menu enabled, the settings are all grayed out, on Appimage, even if I install it from AUR. But if I install it using flatpak it works, because flatpak apps don't use global menul.

**Comment by Sparsa** [comment]
Any, news on this issue, I am still facing the same for the recent AppImage 1.16.2, KDE 5.16 Manjaro

**Comment by Sparsa** [comment]
> Same issue with :
> 
>     * Kubuntu 18.04
> 
>     * Plasma 5.12.7
> 
>     * Bitwarden 1.14.0
> 
>     * Shell 3.0.14
> 
>     * Renderer 66.0.3359.181
> 
>     * Node 10.2.0
> 
>     * Architecture x64
> 
> 
> but only when the global menu is enabled (I had to disable it in order to use Bitwarden). What is unclear for me is : if this is an electron-related issue, why don't I see this behavior with all of the other electron apps ?

Hey, are you still facing this issue?

**Comment by Sparsa** [comment]
I am using KDE 5.16.5 and still facing the issue. Can anyone provide a solution to this problem?

**Comment by Sparsa** [comment]
Just want to know any way to fix this, I am facing this issue for long time now, is it related to some version of electron?

**Comment by NovaViper** [comment]
Oh guys! I think there is a solution! On KDE 5.20, if you use the Global Menu applet, it doesn't grey out any of the entries. It seems to be specific to that Applet, as I've tried it with another one called AppMenu and it was greyed out.
