### ISSUE TITLE
A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by Goldfinger44** [bitwarden/desktop#502]
## Describe the Bug
The following error has been occurs when I start Bitwarden on PC (Win7 x64).
After I click "OK" Bitwarden does not start.

Error: Nie można odnaleźć określnego modułu.
It means - The specified module could not be found.

## Steps To Reproduce
Run Bitwarden right after installing version 1.20.0

## Actual Result
Inability to use the program.

## Screenshots or Videos
![2020-08-02 150319](https://user-images.githubusercontent.com/69112558/89124596-8eadca00-d4d8-11ea-9920-5ccb1f86a32c.jpg)
![2020-08-02 152314](https://user-images.githubusercontent.com/69112558/89124614-a5ecb780-d4d8-11ea-90c2-f8d4560a522c.jpg)

## Environment

- Operating system: Windows 7 Professional x64 
- Build Version 6.1 (compilation 7601: Service Pack1)
- Bitwarden 1.20.0

**Comment by tgreer-bw** [comment]
We have a fix coming soon. Workarounds and all the details here:

https://github.com/bitwarden/desktop/issues/495
