### ISSUE TITLE
Ver 1.20 throws up JavaScript error and will not open

### ISSUE THREAD

**Issue by Ncrypt3dit** [bitwarden/desktop#503]
## Describe the Bug

Bitwarden throws up an error on startup and window will not show up, even though 2x Bitwarden.exe processes are running when checking Task Manager Win7 x64

## Steps To Reproduce

Just ran a fresh and upgraded install of Ver 1.20 on Win7 x64 system. 
Ver 1.19 runs fine with the issue (https://github.com/bitwarden/desktop/issues/488) I previously posted.

## Expected Result

Bitwarden Desktop login window to show up nor the system taskbar icon.

## Actual Result

No Bitwarden Desktop login window showing up nor the system taskbar icon.

## Screenshots or Videos

https://i.imgur.com/xrxbFSw.png

## Environment

- Operating system: Windows 7 x64
- Build Version: 1.20 Can't do as requested since Bitwarden does not open.

**Comment by gate1975mlm** [comment]
It's a known issue and already being worked on.

**Comment by cscharf** [comment]
@Ncrypt3dit , please update to the latest 1.20.1 build for Windows and you should be good to go. The issue has been resolved.

**Comment by Ncrypt3dit** [comment]
> @Ncrypt3dit , please update to the latest 1.20.1 build for Windows and you should be good to go. The issue has been resolved.

Awesome. Thank you.
