### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by nicedevil007** [bitwarden/desktop#504]
Heya, just want to ask if there is a solution (Group Policy f.e.) to disable Update notifications.
In my network not everybody is allowed to install software and then they start to cry: "I can't do the update that bitwarden is asking me for" :)

Maybe someone got a solution for that, small config file, a GPO template, anything like that?

**Comment by Greenderella** [comment]
Hi! At the moment there is no way to disable in-app automatic updating but the feature request is already on our backlog for these exact scenario on Enterprise users. 

What we suggest as a workaround is to use some version that do not have no auto-update at all, for Windows systems would be the Portable App for Flash Drives, you can find that version here: https://bitwarden.com/#download clicking on → more desktop installation options

**Comment by cscharf** [comment]
@nicedevil007 , sorry, just saw this, you can use an environment variable, `ELECTRON_NO_UPDATER=1`

ref: https://github.com/bitwarden/jslib/blob/master/src/electron/updater.main.ts#L38
