### ISSUE TITLE
1.20.1 Update not installed

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/desktop#505]
## Describe the Bug
1.20.1 Update not installed

1.20.1 Update not installed after selecting Check for Updates or agreeing to Restart Bitwarden to install 1.20.1 Update. Nothing happens.
## Steps To Reproduce

1. Launch Bitwarden 1.20.0 macOS client
2. Select menu item > Check for Updates
3. Select ‘Yes' when prompted: "Update Available An update was found. Do you want to download it now?"

OR
3. Select ‘Restart’ when prompted by dialog, "Version 1.20.1 is ready to install. You must restart the application to complete the installation. Do you want to restart and update now?"
## Expected Result

Install and relaunch Bitwarden with updated version 1.20.1 
## Actual Result
Nothing, app does not relaunch and remains version 1.20.0

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
macOS 10.15.16
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]
1.20.0
![Screen Shot 2020-08-04 at 9 56 02 AM](https://user-images.githubusercontent.com/68088552/89323281-49a1a900-d63a-11ea-8bb6-91c11426e17c.png)
![Screen Shot 2020-08-04 at 10 04 50 AM](https://user-images.githubusercontent.com/68088552/89323283-4a3a3f80-d63a-11ea-9c7e-0d2ae76a5b46.png)

**Comment by ToGitOrNotToGit** [comment]
Or is this similar related to issue #504 ?

**Comment by cscharf** [comment]
I don't believe this is a similar issue. The new version is available for manual download, not sure why your instance isn't updating. Can you try re-installing?

**Comment by djsmith85** [comment]
Hi @ToGitOrNotToGit , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
