### ISSUE TITLE
Refresh causes white screen to appear instead of the dark theme/nord theme page. 

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/desktop#509]
## Describe the Bug

When refreshing the application, the light theme screen suddenly kicks in even if the theme is set to dark/nord.

## Steps To Reproduce
_Set Nord theme or Dark theme_
1. Login 
2. Press Ctr+Shift+R
Also occurs when changing the theme

## Expected Result
Display that particular page in the respective theme.

## Actual Result

White screen appears with loading animation

## Environment

- Operating system: Windows 10
-Latest build

**Comment by clayadams5226** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/509
