### ISSUE TITLE
Unlock does not work without logout

### ISSUE THREAD

**Issue by stekreis** [bitwarden/desktop#512]
After locking the vault, I get correctly prompted to type in the Master password. However, I can't unlock the vault without logging out.

## Steps To Reproduce

1. Log in to Bitwarden Client
2. Click on "File" > "Lock Now"
3. Type in Master password
4. Click "Unlock"

## Expected Result
Vault unlocked

## Actual Result
Error Message:
_An error has occured.
Invalid Master password_

5. Click "Log out", confirm
6. Type in Master password
7. Click "Log in"
8. Success

## Environment

Manjaro Linux 5.7.9-1
Build Version 1.20.1
(same behavior on coworker's Windows 10 machine)

## Additional Info

Have searched but did not find this as an existing report.

**Comment by tgreer-bw** [comment]
If you're self hosting official Bitwarden, you'll need to update your server to v1.36+.

If you're using bitwarden_rs, this issue is still outstanding.
