### ISSUE TITLE
Ubuntu desktop Client : Failed to fetch

### ISSUE THREAD

**Issue by nemonein** [bitwarden/desktop#514]
## Environment

- Operating system: Server - On Premise / Ubuntu server 18.04 /Docker
- Build Version (go to "Settings" → "About"): The latest one

## Additional Context

**TL;DR**
Ubuntu Desktop Client does not connect to On premise server.
Google chrome browser on Ubuntu Desktop, Android Device and iOS(iPad) device work fine.

---

I've installed on premise server on Ubuntu server 18.04 following the [official instruction](https://bitwarden.com/help/article/install-on-premise/).
I'll use Bitwarden only internally, so I chose self-signed SSL certificate.
The hostname of Ubuntu Server is 'vbox-u18-server', and I made possible to connect it by this name(https://vbox-u18-server).

```
$ sudo ./bitwarden.sh install
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): vbox-u18-server 	

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.36.1: Pulling from bitwarden/setup
Digest: sha256:5b2c43b46c03da54aecc6d19098b0574b5fb205f0cd3046019725925cadfdf29
Status: Image is up to date for bitwarden/setup:1.36.1
docker.io/bitwarden/setup:1.36.1

(!) Enter your installation id (get at https://bitwarden.com/host): my id

(!) Enter your installation key: my key

(!) Do you have a SSL certificate to use? (y/n): n

(!) Do you want to generate a self-signed SSL certificate? (y/n): y

Generating self signed SSL certificate.
Generating a RSA private key
........................................++++
...............++++
writing new private key to '/bitwarden/ssl/self/vbox-u18-serve/private.key'
-----
Generating key for IdentityServer.
Generating a RSA private key
............................................++++
....................++++
writing new private key to 'identity.key'
-----

!!!!!!!!!! WARNING !!!!!!!!!!
You are using an untrusted SSL certificate. This certificate will not be 
trusted by Bitwarden client applications. You must add this certificate to 
the trusted store on each device or else you will receive errors when trying 
to connect to your installation.

Building nginx config.
Building docker environment files.
Building docker environment override files.
Building FIDO U2F app id.
Building docker-compose.yml.

Installation complete
```

And then, I copied the certificate(~/bwdata/ssl/self/vbox-u18-server/certificate.crt) to the desktop.
```
sudo cp certificate.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates
```

However, the Desktop client refuse to connect to the server(Failed to fetch).
For Ubuntu Desktop client, I've tried Deb version as well as AppImage version, both of them do not work at all.

I also copied(installed) the certificate to Android phone(Galaxy S9), and [iPad](https://medium.com/collaborne-engineering/self-signed-certificates-in-ios-apps-ff489bf8b96e), and both of the devices work without any problem.

What did I miss?

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by LoSaMe** [comment]
I got the same error. Any suggestions?
