### ISSUE TITLE
Usability/accessibility: hard to see "X" button in search field

### ISSUE THREAD

**Issue by timmay7** [bitwarden/desktop#518]
When searching, the "X" button to clear the input field is not very visible, and blends in too much. Increasing the contrast would solve the issue. Please see the attached screenshot.
![visibility](https://user-images.githubusercontent.com/4268981/90082096-cb8d7400-dcc3-11ea-8f48-b8489cba0eda.png)

**Comment by kspearrin** [comment]
This is provided by the browser, and unfortunately I have found not way to properly style it.

**Comment by timmay7** [comment]
> This is provided by the rendering engine (Chromium), and unfortunately, I have found no way to properly style it.

In that case, my next suggestion would be to make the input background white, and the magnifying glass and text dark. Then everything will contrast with each other.

**Comment by dylanjan313** [comment]
Styling this element seems possible, see here: https://jsfiddle.net/19codwf5/2/
