### ISSUE TITLE
Mac OS Desktop App Locking when clicking "X"

### ISSUE THREAD

**Issue by WorldIRC** [bitwarden/desktop#519]
## Describe the Bug

Clicking "X" on the MacOS Desktop app, immediately locks the vault, even if the app still remains open.  Unless quitting the app completely, simply clicking "X" should not immediately lock the vault. 

## Steps To Reproduce

How can we reproduce the behavior:  Click X on the Mac OS desktop app

## Expected Result

App should still remain unlocked, unless Vault Rule exists to specify otherwise.  X should simply be to close the window, but not lock the vault.  Perhaps a new rule should be added that X can lock the vault, if desired.

## Actual Result

A clear and concise description of what is happening. 

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina] Mac OS 10.15.6
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10] 1.20.1

**Comment by cscharf** [comment]
Thank you for posting this however closing it now. Please see: https://github.com/bitwarden/desktop/issues/419
