### ISSUE TITLE
Pressing @ in edit view opens form for new entry

### ISSUE THREAD

**Issue by stranljip** [bitwarden/desktop#52]
I try to add a user name containing an `@` sign to an existing entry. Upon pressing `@` the entry I am editing is closed and a blank form for a new entry is displayed. This does not happen while editing a new entry.
macOS 10.13.3
Bitwarden Desktop 1.0.1

**Comment by kspearrin** [comment]
There are `Alt` hotkeys for creating new items of different types (see File -> New Item). I am guessing one of these conflicts with some international keyboards?

**Comment by stranljip** [comment]
You are right - the shortcut for new login is `Alt` - L which is exactly the location for the `@` on the German layout of all Mac Keyboards (https://support.apple.com/de-de/HT201794).
Great! :-) So I assume it is up to you to change the shortcut?

**Comment by kspearrin** [comment]
I moved them to `Ctrl + Shift + Letter` for next release.
