### ISSUE TITLE
.appimage does not create a desktop shortcut

### ISSUE THREAD

**Issue by kaushalyap** [bitwarden/desktop#522]
## Describe the Bug

When appimage file executed for the first time it should automatically create desktop icon.

## Steps To Reproduce

1. Download app image file
2. `chmod +x *.appimage`
3. `./*.appimage`

## Expected Result

Initial execution of app image should create a desktop shortcut.

## Actual Result

No creation of desktop shortcut after initial .appimage execution. Have to manually create a desktop short (downloading icons).
Most annoying after a update have to change the .desktop file path since the new .appimage have different version number.

## Environment

- Operating system:Linux
- Build Version :

Version 1.20.1
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

## Additional Context

See https://github.com/AppImage/awesome-appimage#desktop-integration in order to how to integrate appimage with desktop.

If not give us [an official flatpak distribution on flathub.org](https://github.com/bitwarden/desktop/issues/188)

And thanks a lot for creating Bitwarden!

https://github.com/bitwarden/desktop/issues/188

**Comment by 3ter** [comment]
Did you check out the (not too complex way) [Joplin is dealing with this feature](https://github.com/laurent22/joplin/blob/dev/Joplin_install_and_update.sh)?

They "support all Desktops that have support for the freedesktop standard".
