### ISSUE TITLE
Installed and portable build 1.20.1 unable to start on Windows 7 x64

### ISSUE THREAD

**Issue by kkovaletp** [bitwarden/desktop#526]
## Describe the Bug

I’ve installed Bitwarden desktop 1.20.1 onto my Windows 7 x64 workstation for 1st time. When I try to run it, I see that the window appear on the skreen for few miliseconds and it closed, so actually it couldn’t be started. I’ve tried to reboot after installation, downloaded portable version of same build - result is the same.

Also I’ve tried to find some logs: searched in Windows event log; ProgramData; profile’s AppData - nothing.

## Steps To Reproduce

1. Install Bitwarden desktop 1.20.1 onto Windows 7 x64 (or download portable)
2. Run it
3. It shows a window for few milliseconds and closed

## Expected Result

Application is opened on Login screen

## Actual Result

It shows a window for few milliseconds and closed

## Screenshots or Videos

n/a for screenshots; no video, as I don't see much value in addition to this text

## Environment

- Operating system: Windows 7 x64 with all updates, not requiring extended support subscription
- Build Version 1.20.1

## Additional Context

I'm not sure what additional info could help - ask me)
like...
There is TinnyWall firewall installed, but app exe file is explicitly allowed for TCP/UDP traffic
Default keyboard and system language is Russian (cp_1251)
There is a topic on community: [https://community.bitwarden.com/t/bitwarden-desktop-couldnt-be-started-on-windows-7/14042](https://community.bitwarden.com/t/bitwarden-desktop-couldnt-be-started-on-windows-7/14042)
Tried to find some logs, but didn't

**Comment by Hygens** [comment]
My tip is to use portable version 1.19.0. Here I use Windows 7 Pro(Latest updates) and work normaly.

**Comment by kkovaletp** [comment]
@Hygens, thanks for the tip, but where to get that version? I see only latest one on official download page

**Comment by Hygens** [comment]
https://github.com/bitwarden/desktop/releases/tag/v1.19.0

**Comment by kkovaletp** [comment]
Thanks @Hygens , I've downloaded and installed 1.19.0 and it works (at last it starts and asks for creds), but is auto-updated to 1.20.1 and after restart doesn't start anymore.
So, this is confirmation for me that there is a bug in 1.20.1 and it is not something with my OS
I have workaround now to use portable 1.19.0, which doesn't auto-update, but please fix the bug, so that I could use latest version

**Comment by Hygens** [comment]
@kkovaletp I do not think that exists some priority for that issue because Windows 7 is dead for Microsoft Support for example. It's more productive for you migrate for Windows 10 because more and more programs continue evolve and not work more on Windows 7 no so only bitwarden. This is mine single opinion! I too use Windows 7 but short I will migrate for Windows 10. I'm bitwarden user as you.

**Comment by kkovaletp** [comment]
I don't plan to migrate to Win10 in short period of time, as:
- all my programs work fine and Bitwarden is 1st found one
- Win10 has known issues with privacy
- Win10 is much less stable and has poor quality comparing with Win7, as MS updates released for Win10 in uncontrolled by users way and regularly introduce new critical bugs (MS has changed the way how they test updates: now only basic testing is done before release and then most testing is performed by individual users, when they forced to install them onto their PCs)
