### ISSUE TITLE
MacOS: Unable to drag window from rightmost pane.

### ISSUE THREAD

**Issue by jacobpledger** [bitwarden/desktop#528]
## Describe the Bug
Using the desktop app on MacOS, if I go to move the window, I cannot initiate a drag from the top of the rightmost pane - where an actual entry would appear when selected. Additionally it is hard to grab the window from the middle pane because the search box is right at the top. This leaves the only safe space to drag the window from as the top of the rightmost pane, and this throws me off constantly. Previously, when the app had a title bar this was not an issue.

## Steps To Reproduce
On MacOS (probably any OS, but I haven't checked), launch the desktop app and login, then attempt to drag the window around the screen by grabbing the top of the window in each of its 3 vertical sections.

## Expected Result
You should be able to move the window around by grabbing anywhere along the top of the window, possibly other unpopulated areas too. For example, the lock screen of the desktop app can be moved by grabbing anywhere in the window.

## Actual Result
The window cannot be moved from the rightmost pane (entry view), and is difficult to grab from the top of the middle pane (list view of all logins)

## Environment

Mac OS Catalina
- Build Version 1.20.1

**Comment by addisonbeck** [comment]
Currently, this is a consequence of the intended design. I agree that there should be more draggable space, but getting there is going to require a bit of a redesign. See the attached pull request for some more detail.

I'd suggest making this a feature request on our [community forum](https://community.bitwarden.com/) if you'd still like to see it implemented in the future. We use the forum to gauge overall interest in larger changes like this one. Thanks!
