### ISSUE TITLE
The new updated font in password field is not easy to read

### ISSUE THREAD

**Issue by grande-mephistopheles** [bitwarden/desktop#530]
## Describe the Bug
The new updated font in password field is barely discernible. It looks like a thin monospace font which is very difficult to read in app, especially in the browser addon which itself is a small app. 

## Steps To Reproduce
Use the generate password feature in the app to see the result

## Expected Result
The font should be easy to the eyes

## Actual Result
I've attached some screenshots for better explanation

## Screenshots or Videos
![bw_desktop-login](https://user-images.githubusercontent.com/58479925/92307451-37db5a80-ef86-11ea-9ebc-54a05d86fc5e.jpg)
![bw_desktop-pgpp](https://user-images.githubusercontent.com/58479925/92307452-390c8780-ef86-11ea-9aa8-38a9a312b3dd.jpg)
![bw_desktop-pgpw](https://user-images.githubusercontent.com/58479925/92307454-39a51e00-ef86-11ea-8dfd-6be4cfb4b0ca.jpg)
![bw_firefox-pgpp](https://user-images.githubusercontent.com/58479925/92307455-3ad64b00-ef86-11ea-80c4-5ef148a5ebc8.jpg)
![bw_firefox-pgpw](https://user-images.githubusercontent.com/58479925/92307458-3b6ee180-ef86-11ea-995b-ca294f81146f.jpg)

## Environment

- Operating system: Linux Mint 20

- Build Version : (Flatpak/FlatHub)
Version 1.20.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by Greenderella** [comment]
Hi grande-mephistopheles,

We appreciate your feedback. This has been added to our recommendation list for consideration.

We ask that any future feedback be directed to our official feedback forum on our Community Forums: https://community.bitwarden.com/

Have a nice week.

**Comment by grande-mephistopheles** [comment]
> We ask that any future feedback be directed to our official feedback forum on our Community Forums: https://community.bitwarden.com/

Great, I'll do that. Thank you for an amazing service.
