### ISSUE TITLE
Login Fail after Vault Lock (Windows 10 app)

### ISSUE THREAD

**Issue by robobio** [bitwarden/desktop#532]
## Bug Description

I am hosting BW on a local machine and I have never experienced the issue I am about to describe. I have installed the BW app in a fresh Windows 10 installation and the first login to my vault was successful. After locking the vault, though, I was unable to reenter it. A message keeps appearing stating that my Master Password is wrong, although it is clearly not. However, I am only able to login to my vault after clicking the log-out button and then re-entiring the Master Password for the new login. For now, I have managed to bypass the problem by using the setting which logs me out after timeout instead of locking the vault. 

## Steps To Reproduce

1. Open the BW app on Windows 10
2. Login to your BW account
3. Close BW, or lock the vault
4. Try to reenter your vault by entering the Master Password

## Expected Result

The expected outcome of the above steps would be to simply reenter the vault.

## Actual Result

What actually happens is that an error appears stating that the Master Password is incorrect.

## Screenshot

![BW_error](https://user-images.githubusercontent.com/70844077/92324918-70426d80-f046-11ea-9b8d-c0d1edf663f0.jpg)

## Environment

- Operating system: Windows 10
- Build Version: 1.20.1

**Comment by kspearrin** [comment]
What version are you hosting? Try upadting.

**Comment by robobio** [comment]
I am hosting the latest version of bitwarden_rs on the docker of a Synology NAS (https://github.com/dani-garcia/bitwarden_rs). I might need to contact that github in case you cannot help. It is weird though, because I did not change anything in the actual BW build I host. I only formatted my PC and had a fresh windows 10 installation. The BW app on my phone works pretty fine as usual. I lock the vault and then unlock it with my Master Password and everything is as it is supposed to be. Same holds true for the BW app in a Windows 10 laptop that I have; all works fine. It only started creating this issue after I freshly installed windows to my desktop.  Do you have anything in mind?

**Comment by kspearrin** [comment]
Please contact the bitwarden_rs people. The problem is there.
