### ISSUE TITLE
White flash when opening and loading, even though dark theme was selected

### ISSUE THREAD

**Issue by Weisbrja** [bitwarden/desktop#533]
## Describe the Bug

There is a white flash when the Bitwarden Desktop App opens and loads (see Screenshot).

## Steps To Reproduce

1. Open Desktop App
2. Log in
3. Select dark/nordic theme
4. Close Desktop App
5. Open Desktop App and look at loading screen
 
## Expected Result

I expect the app to have a dark background, even when its loading.

## Actual Result

The App has a white/gray background and flashes the user (see Screenshot).

## Screenshots or Videos

![Screenshot from 2020-09-07 23-19-39](https://user-images.githubusercontent.com/65398029/92417068-af64e180-f160-11ea-83a9-5813e9eab4d5.png)

## Environment

- Operating system: Arch Linux
- Build Version:
  - Version 1.20.1
  - Shell 9.2.1
  - Renderer 83.0.4103.122
  - Node 12.14.1
  - Architecture x64

**Comment by vachan-maker** [comment]
I have also reported this issue  #509 . Is there a way to merge these two issues?

**Comment by kspearrin** [comment]
Duplicate
