### ISSUE TITLE
When bitwarden is open in the background, shortcuts needing space are broken in Figma and Adobe Illustrator.

### ISSUE THREAD

**Issue by nimbling** [bitwarden/desktop#542]
## Describe the Bug
When bitwarden is open in the background, shortcuts needing space are broken in Figma and Adobe Illustrator.

## Steps To Reproduce
Have bitwarden open on the "enter master password" screen

Open Adobe Illustrator, or Figma, try to use a pan or zoom shortcut involving the spacebar.

## Expected Result
That shortcut to work.

## Actual Result
Shortcuts involving keeping space pressed are broken.

## Screenshots or Videos
this would just be a fruitless mouse movement video.

## Environment

Mac OS Catalina 10.15.6
Bitwarden 1.22.1

**Comment by KevoM** [comment]
I just went crazy this past couple of days (uninstalling softwares and rebooting) to finally discover this bug. So glad someone open this thread to confirm.
Hopefully waiting for a solution.
