### ISSUE TITLE
on OSX, pressing CMD+W logs off, system default behaviour is closing the window.

### ISSUE THREAD

**Issue by nimbling** [bitwarden/desktop#543]
## Describe the Bug
pressing CMD+W in bitwarden logs off,
OSX default behaviour is just closing the window

## Steps To Reproduce
press cmd+w

## Expected Result
Window to close as if I had clicked the status bar icon, not logging off

## Actual Result
Bitwarden logs off, requiring me to log in when opening the window again

Mac OS Catalina
Bitwarden 1.22.1

**Comment by clayadams5226** [comment]
Pressing cmd+w closes the application, which in turn locks your vault. This seems to be working as designed until I'm not understanding the issue.

**Comment by nimbling** [comment]
On OSX, cmd+w is not supposed to close an application. That's what cmd+Q is for.
It only closes the window, as headless applications are just that on OSX: headless, they're still fully active.

I get the desired behavior when clicking the bitwarden status bar icon, but visually, there's no difference.

So perhaps this is a feature request? to "do not also lock application when closing window" functionally that state already exists, I'm just unable to get there using the most convenient shortcut at the moment. Clicking the status bar icons is not how I close any other window, but it's what I need to do to keep bitwarden active and hidden from view.

Thanks for having a look!
