### ISSUE TITLE
Bitwarden does not stick to taskbar in Windows after each update

### ISSUE THREAD

**Issue by anhoutwi** [bitwarden/desktop#544]
## Describe the Bug
Every time Bitwarden updates the icon in the Windows taskbar disappears.

## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by Adams880** [comment]
Also have had this issue for a while, every time it updates all shortcuts in Windows break

**Comment by djohsson** [comment]
I have the same issue on Windows 10

**Comment by cscharf** [comment]
We are unable to reproduce this issue and there is no sufficient information to attempt further troubleshooting. If anyone is actively still having this issue some additional detail would be necessary:

* OS Version, build #, etc.
* Prior and Current Bitwarden version (updating from X to Y)
* How are the shortcuts "broken" (underlying/linked file no longer on disk, icon is missing, icon is gone, etc.)?
* What version did this start happening or did you notice it happening?
* Any other detail/info you can provide, such as the location the Bitwarden shortcut is pointing to and location/path a new shortcut points to, etc.

**Comment by pilcherd** [comment]
I just emailed this this morning.

Repro: 
- Install the desktop application https://vault.bitwarden.com/download/?app=desktop&platform=windows
- Run the application from the Start Menu
- Log in etc.
- Right click on Windows 10 Taskbar and select "pin to taskbar"
- Enjoy
- Run the software one day and get an update notification
- Install.  (I just had this happen this morning - closed the app and it update)
- Icon is removed (unpinned) from the Taskbar

Issue: Have to re-pin after every upgrade.

**Comment by pilcherd** [comment]
> We are unable to reproduce this issue and there is no sufficient information to attempt further troubleshooting. If anyone is actively still having this issue some additional detail would be necessary:
> 
> * OS Version, build #, etc.
19042.630 (current Windows 10)
> * Prior and Current Bitwarden version (updating from X to Y)
Current is 1.23.0.  It updated last week too I think.  This is every current upgrade.
> * How are the shortcuts "broken" (underlying/linked file no longer on disk, icon is missing, icon is gone, etc.)?
Taskbar icons that were pinned are unpinned.
> * What version did this start happening or did you notice it happening?
I only started using Bitwarden around 4 months ago.. been every upgrade since then.
> * Any other detail/info you can provide, such as the location the Bitwarden shortcut is pointing to and location/path a new shortcut points to, etc.
See repro above.

**Comment by mfkl** [comment]
Can repro as well (for at least 1 year), happens on every update (or almost).

**Comment by cscharf** [comment]
Thanks @pilcherd & @mfkl , it looks like this is a known issue it seems which would be resolved by a pending PR for electron-builder: https://github.com/electron-userland/electron-builder/issues/2514. It doesn't look like any of the suggested workaround would be a proper solution for Bitwarden at the moment so we'll keep an eye open on this for when it's finally merged, etc.
