### ISSUE TITLE
Windows client crashes when domain doesn't exist anymore

### ISSUE THREAD

**Issue by module0x90** [bitwarden/desktop#545]
## Describe the Bug
I recently changed my domain for my self-hosted BW install and the old domain doesn't resolve anymore. My Windows Desktop client was still pointing at it and now everytime I start the BW client it crashes with "Error" and cannot be used.

## Steps To Reproduce
Remove your self-hosted domain from DNS that it returns NXDOMAIN.

## Expected Result
Error message or just fall back to the local cache.

## Actual Result
Crash, application is closed and cannot be used at all.

## Environment
Windows 10.
BW client version 1.19 (but updated after deleting the profile and installing 1.22.1)

**Comment by Greenderella** [comment]
Hi @module0x90 

Will you first try uninstalling the app, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

After the installation you should be able to configure the new domain and log in normally.

**Comment by module0x90** [comment]
Hi Alex,

done that, just that I renamed the old data directory for some reason - the client wasn't running anyway.
All working again.Thanks a million for this wonderful app.
Regards

Tom
September 17, 2020 11:51 AM, "Alex" <notifications@github.com (mailto:notifications@github.com?to=%22Alex%22%20<notifications@github.com>)> wrote:
	Hi @module0x90 (https://github.com/module0x90)

	Will you first try uninstalling the app, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/ (https://help.bitwarden.com/article/where-is-data-stored-computer/)

	After the installation you should be able to configure the new domain and log in normally.
