### ISSUE TITLE
Unable to log in with SSO on Linux - browser does not redirect to application

### ISSUE THREAD

**Issue by rkujawa** [bitwarden/desktop#551]
## Describe the Bug

I am evaluating enterprise subscription. SSO is a crucial feature. 

## Steps To Reproduce

1. Run Linux Bitwarden Desktop AppImage.
2. Click on "Enterprise Single Sign-On"
3. When browser opens, authenticate to SSO.
4. See blank page, and notice that nothing happens in the Bitwarden app.

## Expected Result

Being logged in to Bitwarden Desktop with SSO.

## Actual Result

Not logged in, but stuck with seemingly empty web browser page pointing to `https://identity.bitwarden.com/Account/ExternalCallback` .

## Screenshots or Videos

The page is not actually empty, it contains the following HTML:
```
<html>
<head>
    <meta http-equiv="refresh" content="0;url=/connect/authorize/callback?client_id=desktop&amp;redirect_uri=bitwarden%3A%2F%2Fsso-callback&amp;response_type=code&amp;scope=api%20offline_access&amp;state=XXXXXX&amp;code_challenge=XXXXXXXXX&amp;code_challenge_method=S256&amp;response_mode=query&amp;domain_hint=XXXXXXX" data-url="/connect/authorize/callback?client_id=desktop&amp;redirect_uri=bitwarden%3A%2F%2Fsso-callback&amp;response_type=code&amp;scope=api%20offline_access&amp;state=XXXXXXXX&amp;code_challenge=XXXXXXXXX&amp;code_challenge_method=S256&amp;response_mode=query&amp;domain_hint=XXXXX">
    <script>
        window.location.href = document.querySelector("meta[http-equiv=refresh]").getAttribute("data-url");
    </script>
</head>
<body>
    <p>You are now being returned to the application. Once complete, you may close this tab.</p>
</body>
</html>
```

## Environment

- Operating system: Linux (Fedora 32)
- Build Version (go to "Settings" → "About"): 1.22.1

## Additional Context

It seems that the whole process actually worked, it's just the redirection to Bitwarden app at the end that failed.

**Comment by cscharf** [comment]
@rkujawa , assuming this is also with `Fedora 32, default shipped browser (firefox-80.0.1-2.fc32.x86_64). It's a normal GUI session with GNOME.` as mentioned in the CLI issue?

On the blank page, are there any console errors being reported or debug output?

**Comment by rkujawa** [comment]
@cscharf Yes, this is also Fedora 32 and Firefox 80.

There are two errors in console on the blank page:
```
Cookie “idsrv.external” has been rejected because it is already expired. ExternalCallback
```

```
Prevented navigation to “https://identity.bitwarden.com/connect/authorize/callback?client_id=desktop&redirect_uri=bitwarden%3A%2F%2Fsso-callback&response_type=code&scope=api%20offline_access&state=XXXXXX&code_challenge=XXXXX&code_challenge_method=S256&response_mode=query&domain_hint=linker-cloud” due to an unknown protocol.
```

I suppose the second message is the real issue here.

**Comment by cscharf** [comment]
Ah ha, thanks! see: https://www.fxsitecompat.dev/en-CA/docs/2020/navigation-to-unknown-protocol-will-be-blocked/

So apparently we need to rethink our redirect page.

**Comment by cscharf** [comment]
@rkujawa , so I've reviewed the WebKit and Mozilla bugs and patches related to that error and checks and I'm struggling to figure out how/why it would specify an `unknown protocol` for `https://` vs. something like `bitwarden://` which *is* used by a redirect but should have been registered by the latest AppImage. (but that is not the redirect URL it's complaining about in the error above).

If you look at the console network trace, which stage are you seeing that in the request chain?

**Comment by rkujawa** [comment]
If I understand the trace correctly, the `Prevented navigation` error appears due to request to:

```
https://identity.bitwarden.com/connect/authorize/callback?client_id=desktop&redirect_uri=bitwarden%3A%2F%2Fsso-callback&response_type=code&scope=api%20offline_access&state=XXXXXX&code_challenge=XXXXXX&code_challenge_method=S256&response_mode=query&domain_hint=XXXXX
```

Which causes 302 redirect to:
```
bitwarden://sso-callback?code=XXXXXX&scope=api%20offline_access&state=XXXXXX
```

**Comment by cscharf** [comment]
Okay, I'm going to go out on a limb and assume then that the AppImage when run on Fedora hasn't registered the `bitwarden://` protocol to handle the callback in the SSO process from the browser and Firefox is simply blocking it (as expected). We're working on reproduction and will look further into it. Thanks @rkujawa!

**Comment by cscharf** [comment]
ref: https://github.com/electron-userland/electron-builder/issues/4035#issuecomment-621131126
