### ISSUE TITLE
Bitwarden won't autofill Safari pinned pages MacOS Catalina 10.15.6 Safari 14.0

### ISSUE THREAD

**Issue by rbowdel** [bitwarden/desktop#553]
## Describe the Bug 
MacOS Catalina 10.15.6 - Safari Version 14.0
Any pinned page in Safari will not autofill. Bitwarden gives the following error message - "Unable to auto-fill the selected item on this page. Copy and paste the information instead."

## Steps To Reproduce
Pin any page in Safari. Try to autofill pinned page with Bitwarden Safari extension.

## Expected Result
Error message - "Unable to auto-fill the selected item on this page. Copy and paste the information instead."## Screenshots or Videos

## Environment
MacOS Catalina 10.15.6 - Safari Version 14.0

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1018
