### ISSUE TITLE
Portable Version Gets Installed on New Update Notifications

### ISSUE THREAD

**Issue by Velgus** [bitwarden/desktop#562]
## Describe the Bug

I run the portable version of BitWarden. 

Whenever a new update comes and the auto-updater triggers, it installs a version which appears in "Add or remove programs" to my system (even if I choose the option to delay the update through the dialog that pops up).

## Steps To Reproduce

1. Download and use an outdated portable version Bitwarden.
2. Wait for auto-update dialog to appear and choose to cancel out of it.
3. Check "Add or remove programs" in Windows to see that Bitwarden now has an installation entry

## Expected Result

Portable Bitwarden is never "installed" in a manner which would appear in the "Add or remove programs" menu.

## Actual Result

Portable Bitwarden gets "installed".

## Environment

- Operating system: Windows 10
- Build Version: 2004 (OS Build 19041.508)

## Additional Context

This could also be worked around if there were an option to disable the update checker in the settings.

This has been happening since I started using Bitwarden (which has been over a year), but I don't know if it's always been like this.

**Comment by kspearrin** [comment]
The portable version should never be doing auto-updates. I cannot seem to reproduce the issue.

**Comment by Velgus** [comment]
This was my mistake.

I use the scoop package manager, which almost always prefers the portable versions of apps due tot he way it works, but it looks like whoever set up the Bitwarden JSON chose to extract the MSI file instead.

My apologies.
