### ISSUE TITLE
Unsaved changes warning not prompting after generating new password (Windows)

### ISSUE THREAD

**Issue by staffa** [bitwarden/desktop#563]
## Describe the Bug

The "Unsaved Changes" warning pop-up box that was implemented in the release following #384 fails to pop-up under certain circumstances. Specifically, under very similar circumstances to the original poster: When generating a new password for an existing login, you can click away and not receive the prompt, thus losing the login (with the acknowledgement of password history).

## Steps To Reproduce

1. Open and unlock the desktop client.
2. Edit an existing login (I used a dummy test login just in case)
3. Click the regenerate password button and hit yes at the prompt.
(Optional: copy to clipboard -- does not make a difference in my testing)
4. Select by hitting the check mark.
(Optional: can view the password by clicking the eye, check its pwndedness, click into the password field, etc. no change in final behavior)
5. Click another login item

## Expected Result

Should receive the "Unsaved changes" warning, as the password has been changed when entered onto the page.

## Actual Result

It switches to the selected login item and the changes made are lost. (Again, I acknowledge the existence of the password history feature.)

## Environment

- Operating system: Windows 10, Version 1909, build 18363.1082
- Build Version: 1.22.2

## Additional Context

I've not personally reviewed the code, but I expect what might be happening is the trigger for the internal "changed, be ready to warn" state is based on detecting user textual input into the fields, and that the auto population by the generator doesn't trip the trigger. 
Thanks for an otherwise great product!

**Comment by eliykat** [comment]
There is a newer issue reporting this defect, please refer to #761 for further discussion. Closing this as a duplicate.
