### ISSUE TITLE
Desktop macOS app does not start on Apple Silicon HW

### ISSUE THREAD

**Issue by peteger** [bitwarden/desktop#567]
## Describe the Bug

Bitwarden (v 1.22.2 (400)) running on macOS (Big Sur B9) with Apple Silicon (Apple DTK HW kit with A12Z chip) is unable to start. Just a blank white screen is displayed. Menu is however accessible (with disabled items) and app does not seem to crash. Browser extensions work fine.

## Steps To Reproduce

1. Start Bitwarden on Apple DTK
2. White screen is displayed, app is not starting

## Screenshots or Videos

<img width="843" alt="Snímek obrazovky 2020-10-06 v 10 47 14" src="https://user-images.githubusercontent.com/7255554/95179713-4dc87f00-07c1-11eb-856f-a39ea3c45a5a.png">

## Environment

- Operating system: Mac OS Big Sur B9
- Build Version: 1.22.2 (400)

**Comment by peteger** [comment]
This seems to be related to this issue in electron:
https://github.com/electron/electron/issues/24319

**Comment by flying-sausages** [comment]
MAS version runs fine in Rosetta 2
<img width="820" alt="image" src="https://user-images.githubusercontent.com/23618693/102299428-3b05bf80-3f53-11eb-87a7-a0e55ae3e0b6.png">

**Comment by clayadams5226** [comment]
I haven't seen this exact issue. When I attempted to run Bitwarden I was prompted by apple to install Rosetta 2 and the app ran without issue. 

@peteger are you still having issues? Can you try to run the following command in terminal and see if it resolves it?

/usr/sbin/softwareupdate --install-rosetta

**Comment by peteger** [comment]
Yes, the issue remains the same after installing Roseta 2 and launching the MAS version. However as this is happening on Apple DTK with A12Z Silicon chip and in the meantime, M1 chip was released (which seems to run fine from previous reports), I suggest closing the issue.

**Comment by cryptnotehq** [comment]
Please reopen. I have macOS Big Sur 11.2 and a built-in i5 processor. White screen, can't do anything. I can just access the menu bar at the top. Same exact issue here.

**Comment by juabara** [comment]
I'm facing the same thing with Bitwarden version 1.25.1 (518)

**Comment by Kfelts** [comment]
I'm also facing this issue. I have an M1 chip and this only seems to happen when I add a new repository. The screen goes white like the above screenshot and I can only get it back by forcing a shutdown.

**Comment by pjuhas** [comment]
1.27.1 running natively.

**Comment by BeyondEvil** [comment]
Same issue here.

**Comment by PixsaOJ** [comment]
Same on Linux/Ubuntu
```
OS: Pop!_OS 21.04 x86_64
CPU: Intel i5-8300H (8) @
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
DE: GNOME
WM: Mutter
Kernel: 5.11.0-7620-generic
```

Using latest and greatest drivers.

I get just blank black screen and top menubar.
