### ISSUE TITLE
When the program is locked, it cannot be unlocked with the master password.

### ISSUE THREAD

**Issue by quziyou** [bitwarden/desktop#573]
## Describe the Bug

When the program is locked, it cannot be unlocked with the master password.

## Steps To Reproduce
1. Go to 'File'
2. Click on 'Lock now'
3. type in your master password.
4. Click on 'Unlock'

## Expected Result
Unlock the program and enter the main menu of the program

## Actual Result
Program tip: invalid master password

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/24522808/96445655-daa01d80-1242-11eb-8ada-3e7c6e46edc3.png)

## Environment
- Operating system:  Windows 10
- Build Version: 1.22.2

## Additional Context
if the program is locked, you must log out and then type in your master password and log in the program.

**Comment by Greenderella** [comment]
I'm unable to reproduce this issue with  Windows 10 Version 1909 and Bitwarden 1.22.2

Will you first try uninstalling the app, removing any leftover data, powering off your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by quziyou** [comment]
Thank you for your reply.
I re-installed the app according to your recommendation, but the issue still remains in my system(Windows 10 Version 2004).
In fact, I tried it on Debian (Version 10.6), and I had the same problem.
By the way, I'm connected to my own bitwarden server, is this the cause of this issue?

**Comment by tgreer-bw** [comment]
If you're on Bitwarden_rs, they may not have patched this issue yet, as the Desktop clients require Bitwarden server v1.36 or higher to support unlocking due to some new API requirements.

If your server is running less than 1.36, try updating and see how it performs.

**Comment by quziyou** [comment]
Ok, got it. My server is running on Bitwarden_rs.
Thanks for your help!

**Comment by quziyou** [comment]
Version 1.22.0 does not have this issue.
