### ISSUE TITLE
lost extension for safari

### ISSUE THREAD

**Issue by kiltum** [bitwarden/desktop#574]
No more safari extension?

OS x catalina, latest bitwarden. 

No safari extension. From web site by clicking to link "for extension" - downloading full copy of bitwarden

in bitwarden app no button/link "install extension"

**Comment by Greenderella** [comment]
Hi @kiltum,

The new Safari extension is now packaged with the Bitwarden Desktop App. You can download the latest app here:
https://vault.bitwarden.com/download/?app=desktop&platform=macos

You can also use the App Store version. Be sure to run the application once. If the extension still does not appear, it may just need to be enabled. In Safari, check under Preferences > Extensions.

**Comment by kiltum** [comment]
Sure, i try all what i can find ;) no any sign of extension. and no any sign how no install

https://ibb.co/BqwhPBG

**Comment by tgreer-bw** [comment]
The desktop app automatically installs the extension. Once you install the desktop app, go to Safari and enable the Bitwarden extension and you're set!

**Comment by kiltum** [comment]
Did you see screenshot? I told you that app do nothing at all :) I even reinstall them from AppStore and from brew - nothing changes :)

**Comment by cscharf** [comment]
That is really bizarre @kiltum , but I do see the screen shot you provided and notice there is no extension listed in Safari settings.

What version of Safari are you running?
Have you tried rebooting your mac?
Have you tried force-quit of Safari, open Bitwarden app, log in, etc., then re-open Safari and checking Preferences --> Extensions?
Have you tried rebooting your mac again? (lol)

**Comment by kiltum** [comment]
It's Catalina latest version. I even reboot my book :) nothing changes. 

So I really need button "reinstall" :) I will try to look inside bitwarden app, may be I will find bitwarden.xyz (don't remember correctly extension)

**Comment by cscharf** [comment]
I've never seen that happen outside of doing local development. At most I've had to "clear out" my Safari local data, force-quit, restart, force-quit, restart, then launch debugger from x-code to get my local dev extension to load up, however the extension is installed with the desktop app, there just must be something where Safari on your machine is not seeing the extension or blocking it. Really strange. I also can't seem to find anything useful doing a web search on this front.

**Comment by rnsc** [comment]
@kiltum  I had this happen to me on Catalina, after the latest Safari update, however, just re-downloading the dmg from the Bitwarden website and replacing my current copy was sufficient to restore the Safari extension.

**Comment by Hinton** [comment]
We no longer supports browser extension outside the App Store. If you are still encountering issues feel free to re-open this.
