### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/desktop#576]
## Describe the Bug

I recieved a JS error when I launched Bitwarden. I cannot reproduce this issue now. I did have another application open called **Joplin** which is an open source note taking app that I think also uses electron. Maybe its because of that. I don't know.

## Steps To Reproduce

1. Open Bitwarden

## Screenshots or Videos

![bitCapture](https://user-images.githubusercontent.com/65799568/97478440-f60fd480-1976-11eb-8c7e-4416576d1187.PNG)

## Environment

- Operating system: Windows 10 2004
- Build Version 1.22.2

**Comment by tgreer-bw** [comment]
You may need to install the C++ distributable libraries [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) - can you give that a shot?

**Comment by cscharf** [comment]
Hi @vachan-maker , if you're running an anti-virus that could have done it, but just being on Windows in general it's a pretty hostile computing environment when it comes to file locks, etc. There are several threads that go on for ages debating around this exact error between electron, electron-storage, etc. where node.js fs module hits this occasionally/intermittently on Windows. It _may_ have had something to do with Joplin running, but then it _may_ not have; really depends which way the wind is blowing sometimes with Windows.

I think you're fine, if it starts popping up consistently or far more frequently please let us know.

**Comment by vachan-maker** [comment]
@cscharf @tgreer-bw 
I haven't installed this on my computer, will do it if I face this issue again. 
Joplin I think crashed before opening Bitwarden and I really couldn't close joplin, things did get a little slow.  Maybe it's because of that. 
I didn't see the error today. I suppose everything is working normally.
Thanks very much for the support.

**Comment by cscharf** [comment]
Thanks @vachan-maker , I'll close this for now, if it continues happening please feel free to re-open and we can look into it further; that error really is and explicitly is around file-access and from what I was able to dig up on the internet, seems to be only on Windows with node.js's FS module and surrounding atomic writes during startup of electron.
