### ISSUE TITLE
Bitwarden desktop (macos Catalina) don't start if there is package.json file at user directory

### ISSUE THREAD

**Issue by ivanddiaz** [bitwarden/desktop#586]
## Describe the Bug
If a void {} pakage.json is present on user directory the application fail to start.

## Steps To Reproduce

1. Open Terminal app
2. run: echo '{}' > ~/package.json
3. start Bitwarden
4. Bitwarden fail to start

## Expected Result
Bitwarden start 

## Actual Result
Birwarden circle keeps spinning forever

## Screenshots or Videos
![Bug](https://user-images.githubusercontent.com/69656309/99000938-080d7d80-2508-11eb-97e0-419e5b19e928.png)

## Environment
- Operating system: Mac OS Catalina
- Build Version: 1.22.2

## Additional Context
Thank you

**Comment by ivanddiaz** [comment]
### 
![Bug](https://user-images.githubusercontent.com/69656309/99001109-4c991900-2508-11eb-896e-67fe0ec94dcb.png)

**Comment by KaiTiggy** [comment]
I have this issue as well with the latest Mac App Store version (1.24.1 (509)) running Catalina 10.15.7. Had the following package.json (leftover from web development tasks) at my user directory and the app just kept spinning on a fresh install. 

```json
{
  "dependencies": {
    "jest": "^26.4.2"
  }
}
```
Deleting the file fixes the issue.
