### ISSUE TITLE
no (search) focus after login using Windows Hello 

### ISSUE THREAD

**Issue by winkler-winsen** [bitwarden/desktop#589]
## Describe the Bug

After login using Windows Hello (e.g. fingerprint sensor), the Bitwarden app does not get focus back.

Focus on search field would be appreciated. This can help users work quickly after Helo without using mouse.

If you don't use Windows Hello and login with Master-Password, the app keeps focus and you can start typing into search field.

## Steps To Reproduce

Starting Windows Bitwarden app, using Windows Hello (e.g. fingerprint sensor). The Bitwarden app looses focus. Keyboard input is not available in Bitwarden window until selecting it (mouse or Alt+Tab).

## Expected Result

If you don't use Windows Hello and login with Master-Password, the app keeps focus and you can start typing into search field.

## Actual Result

Lost focus after Windows Hello.

## Screenshots or Videos

N/A

## Environment

Windows 10 Pro 64 Bit 1909 (# 18363.1198)

Bitwarden Windows app (Windows Store)
- Version 1.22.2
- Shell 6.1.7
- Renderer 76.0.3809.146
- Node 12.4.0
- Architecture x64

**Comment by SergeantConfused** [comment]
Hi there,

I've tested this using Windows Hello with a fingerprint and it's working as intended.
When the vault gets unlocked, the focus is on the search bar and you can start typing.
Can you please uninstall your Bitwarden desktop application, restart, and install the .exe from our homepage https://bitwarden.com/download/ and let us know if that helps?

My system:
Windows 10 Pro 2004 19041.610
Bitwarden Desktop 1.22.2 (.exe, not Windows Store.)

All the best,

**Comment by winkler-winsen** [comment]
Hi @SergeantConfused ,

thanks for quick reply.

I uninstalled 1.22.2 Windows Store Version and installed latest from https://bitwarden.com/download/ 

Tested Version (Download from https://bitwarden.com/download/)
Version 1.23.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

Same behaviour as 1.22.2 from Windows Store. After login with Windows Hello (fingerprint), the Bitwarden App lost focus. So I cannot enter someting into search until I click with mouse on window or use Alt+Tab.

Regards
Lars

**Comment by SergeantConfused** [comment]
Thank you for your update. We'll proceed with this internally.

**Comment by winkler-winsen** [comment]
I checked the behaviour when locking (Ctrl + L) and unlocking an already started Bitwarden app.

When I want to unlock the app with click on unlock with Windows Hello, I use fingerprint sensor and after this, the focus stays on the Bitwarden app and I can start typing into seach bar.

The same bahaviour is, when starting the Bitwarden app and cancel automaticallcy opened Windows Hello window. When I then click manually on unlock with Windows Hello button, the focus stays on Bitwarden app and I can start typing into search bar.

Maybe it's for some reason interesting: The Windows Hello window position differs when starting Bitwarden app to unlocking Tresor. After starting the App, the Windows Hello overlay is in the top left desktop (x, y = 0, 0) postion. But when unlocking tresor, the Windows Hello overlay is right in the middle of the Bitwarden app, even if I moved the position before.

My conclusion is: There must be a difference in calling the Windows Hello function, because it differs on application startup and the click on "ulock with Windows Hello" button.

Version 1.23.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

Regards 
Lars

**Comment by winkler-winsen** [comment]
Tested now under Windows 10 64 bit 20H2 (#19042.685) (before was 1909)

Bug still exists.

**Comment by winkler-winsen** [comment]
Bug still exists in 

Version 1.24.1
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by denisbrodbeck** [comment]
I've got the same behavior: no focus on search field after unlocking with Windows Hello (using Windows Hello PIN)

@SergeantConfused Here are my observations:
If I start a fresh `bitwarden` instance with *Windows Hello*: focus is in search field
If the same `bitwarden` instance gets locked (`ctrl + L`) and then gets unlocked via *Windows Hello*: focus is *not* in search field
This behavior stays the same until I quit `bitwarden` and start it afresh.

```text
Version		1.24.6
Shell		6.1.7
Renderer	76.0.3809.146
Node		12.4.0
Architecture	x64

Edition		Windows 10 Pro
Version		20H2
Installed on	‎04.‎06.‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by winkler-winsen** [comment]
> @SergeantConfused Here are my observations:
> If I start a fresh `bitwarden` instance with _Windows Hello_: focus is in search field
> If the same `bitwarden` instance gets locked (`ctrl + L`) and then gets unlocked via _Windows Hello_: focus is _not_ in search field
> This behavior stays the same until I quit `bitwarden` and start it afresh.

Funny it is. My behaviour is vice versa. No search focus after new instance and search focus after unlock existing instance with Hello.

I use Hello via fingerprint reader without PIN.

**Comment by omniproc** [comment]
Can confirm. No search focus after initial unlock (new instance). Focus works fine when manually locking and later on unlocking with Hello. I guess it has to do with the application focus: when manually locked a user has to manually click "unlock with Windows Hello" to start the unlock process and thus the user manually sets focus on the application before the Hello dialog pops up. At initial startup this is not the case: the Hello dialog will open without any interaction with the application by the user. That seems to make the difference.
If I cancel the Windows Hello dialog that pops up at application start and then click the "unlock with Windows Hello" button in the new instance search focus will work as expected.

Tested on Version 1.24.6 x64 (Node 12.4.0)

**Comment by omniproc** [comment]
Seems to be fixed in 1.25.0

**Comment by winkler-winsen** [comment]
@SergeantConfused @omniproc Can confirm issue is solved. Tested with Microsoft Store version.

Issue can be closed successfully.

Version 1.25.0
Shell 11.1.1
Renderer 87.0.4280.88
Node 12.18.3
Architecture ia32

**Comment by SergeantConfused** [comment]
Thank you all very much for your cooperation with this!

**Comment by keypunch** [comment]
Issue still exists in:
Version 1.28.2
Shell 11.4.5
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

Looks like the person who had it work was ia32 not x64 which is what most have had issues with.

I use Windows Hello pin unlock. Search field doesn't focus, and "ctrl-f" doesn't focus to search field either.

**Comment by omniproc** [comment]
@keypunch 

negative. I'm on x64 as well and it works fine for me (Is anyone seriously using ia32 these days?).

Version 1.28.2
Shell 11.4.5
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

Edition	Windows 10 Pro
Version	21H1
Installed on	‎01/‎08/‎2021
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by keypunch** [comment]
@omniproc 
It was the user that confirmed it to be working winkler-winsen that was using ia32. Missed the fact that you were on x64.

**Comment by keypunch** [comment]
Can confirm issue still exists after re-install of both Windows store version, and exe. This sounds like a fun bug.
