### ISSUE TITLE
Bitwarden Desktop Application Bug

### ISSUE THREAD

**Issue by tjthao** [bitwarden/desktop#592]
## Describe the Bug
Hello,

While in the Desktop Application when I click on a drop down menu in any of the “Types”, the drop down menu will either be located above the application and I cannot select anything. As well as if I double click on the drop down menu the Application will just turn white. If you click around the area the drop down menus will still show but you cannot see any information you have listed. Closing Bitwarden application and signing back in is only way to resolve or if Bitwarden self locks due to Timeout. Upon resigning in the error won’t happen.

## Steps To Reproduce

- Open Bitwarden desktop application
- Select any option on left hand side under "Types"
- Click the "+" Symbol or "Add Item" 
- Select Drop down menu

## Expected Result

Drop down menu will be off the Application, or if double clicking Desktop Application will not be readable.

## Screenshots or Videos
For some reason I cannot add photo, see photos on attached link. 
https://community.bitwarden.com/t/bug-report/15555 
## Environment

-HyperV Windows 10 Pro

**Comment by martin3x** [comment]
I installed the windows 10 client today.
I'm experimenting a similar issue. When clicking on drop boxes, the client goes blank, but I can go back by maximizing or resizing the client. Also happened once the dropbox moves to the top of the blank client window.
