### ISSUE TITLE
Secure note label misaligned with note icon

### ISSUE THREAD

**Issue by gprst** [bitwarden/desktop#599]
## Steps To Reproduce

Go to the Secure Notes menu of your vault.

## Expected Result

The name of the note should be vertically aligned with the note icon, as for the web extension.

## Actual Result

The name of the note is misaligned with the note icon (slightly upward).

## Screenshots or Videos

![misaligned](https://user-images.githubusercontent.com/32643653/100368777-4a54b580-3004-11eb-8d08-b832487011c4.png)

## Environment

- Operating systems: Windows 10
- Build Version : 1.22.2

**Comment by djsmith85** [comment]
Closing this, as it was solved with https://github.com/bitwarden/desktop/pull/870

Thank you again @gryffs for your work in this.
