### ISSUE TITLE
Editing Base URL in data.json prevents all other URLs from being saved and used in the Desktop client.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#606]
## Describe the Bug
If you edit the Base URL in data.json file to change the environment for the desktop client, you cannot edit any other URLs in that file. If you try to change the Base URL and the Icons URL, only the base URL would be reflected in the Desktop client, and it would not show icons on the vault login items.

## Steps To Reproduce
1. Edit the data.json file for desktop client.
2. Add a new local Base URL and add the Bitwarden Icons URL (icons.bitwarden.net).
3. Save the file.
4. Open the Bitwarden desktop client, log out, click on Settings, and check what you see.

## Expected Result
To see the Base URL and the Icons URL you've set.

## Actual Result
You'll see only the Base URL you've set. The Icons URL would be empty.

## Screenshots or Videos
N/A.

## Environment

- Operating system: Windows 10 Pro
- Build Version (go to "Settings" → "About"):
Version 1.23.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

## Additional Context
This relates to when there is a need to deploy the desktop client pre-configured to connect to a local Bitwarden server while using the cloud Icons (favicons) server.

Edit: Added additional context.

**Comment by djsmith85** [comment]
This should be fixed with https://github.com/bitwarden/jslib/pull/628 and will be included in the next release.

**Comment by eliykat** [comment]
Closing per @djsmith85's comment.
