### ISSUE TITLE
"Loading..." error when logging into on-premises instance via SSO with private certificate (ERR_CERT_COMMON_NAME_INVALID)

### ISSUE THREAD

**Issue by kdblocher** [bitwarden/desktop#612]
## Describe the Bug

After logging in via SSO to an on-premises Bitwarden instance with a private certificate, the app hangs on "Loading...".
The following error message appears in Dev Tools:
vendor.js:131151 POST https://<elided>/identity/connect/token net::ERR_CERT_COMMON_NAME_INVALID

The vault loads fine in Firefox and Chrome.

## Steps To Reproduce

1. Sign in via Enterprise SSO

## Expected Result

See vault landing page

## Actual Result

Loading... plus loading spinner

## Environment

- Operating system: Windows 10
- Build Version (go to "Settings" → "About"): 1.23.1
- Log:
vendor.js:131151 POST https://<elided>/identity/connect/token net::ERR_CERT_COMMON_NAME_INVALID
(anonymous) @ vendor.js:131151
nativeFetch @ api.service.ts:1094
fetch @ api.service.ts:1090
(anonymous) @ api.service.ts:181
(anonymous) @ userKeyResponse.ts:12
ZoneAwarePromise @ vendor.js:130946
567.api_service_awaiter @ userKeyResponse.ts:12
postIdentityToken @ api.service.ts:172
(anonymous) @ auth.service.ts:303
fulfilled @ tokenRequest.ts:76
push.ZoneDelegate.invoke @ vendor.js:130419
onInvoke @ vendor.js:28582
push.ZoneDelegate.invoke @ vendor.js:130418
push.Zone.run @ vendor.js:130176
(anonymous) @ vendor.js:130924
push.ZoneDelegate.invokeTask @ vendor.js:130454
onInvokeTask @ vendor.js:28570
push.ZoneDelegate.invokeTask @ vendor.js:130453
push.Zone.runTask @ vendor.js:130221
drainMicroTaskQueue @ vendor.js:130634
Promise.then (async)
scheduleMicroTask @ vendor.js:130617
push.ZoneDelegate.scheduleTask @ vendor.js:130443
onScheduleTask @ vendor.js:130327
push.ZoneDelegate.scheduleTask @ vendor.js:130433
push.Zone.scheduleTask @ vendor.js:130264
push.Zone.scheduleMicroTask @ vendor.js:130284
scheduleResolveOrReject @ vendor.js:130914
ZoneAwarePromise.then @ vendor.js:131060
(anonymous) @ vendor.js:78075
innerSubscribe @ vendor.js:65666
push.SwitchMapSubscriber._innerSub @ vendor.js:142680
push.SwitchMapSubscriber._next @ vendor.js:142670
push.Subscriber.next @ vendor.js:55084
push.SwitchMapSubscriber.notifyNext @ vendor.js:142702
push.SimpleInnerSubscriber._next @ vendor.js:65589
push.Subscriber.next @ vendor.js:55084
(anonymous) @ vendor.js:87900
innerSubscribe @ vendor.js:65666
push.SwitchMapSubscriber._innerSub @ vendor.js:142680
push.SwitchMapSubscriber._next @ vendor.js:142670
push.Subscriber.next @ vendor.js:55084
(anonymous) @ vendor.js:87900
push.Observable._trySubscribe @ vendor.js:55377
push.Observable.subscribe @ vendor.js:55363
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.MergeMapOperator.call @ vendor.js:87802
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
innerSubscribe @ vendor.js:65664
push.SwitchMapSubscriber._innerSub @ vendor.js:142680
push.SwitchMapSubscriber._next @ vendor.js:142670
push.Subscriber.next @ vendor.js:55084
push.TapSubscriber._next @ vendor.js:142781
push.Subscriber.next @ vendor.js:55084
(anonymous) @ vendor.js:87900
push.Observable._trySubscribe @ vendor.js:55377
push.Observable.subscribe @ vendor.js:55363
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.MapOperator.call @ vendor.js:75414
push.Observable.subscribe @ vendor.js:55358
push.MergeMapOperator.call @ vendor.js:87802
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.FilterOperator.call @ vendor.js:87973
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.SwitchMapOperator.call @ vendor.js:142648
push.Observable.subscribe @ vendor.js:55358
push.MapOperator.call @ vendor.js:75414
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.MapOperator.call @ vendor.js:75414
push.Observable.subscribe @ vendor.js:55358
push.DoOperator.call @ vendor.js:142748
push.Observable.subscribe @ vendor.js:55358
push.FinallyOperator.call @ vendor.js:48848
push.Observable.subscribe @ vendor.js:55358
push.CatchOperator.call @ vendor.js:48613
push.Observable.subscribe @ vendor.js:55358
innerSubscribe @ vendor.js:65664
push.SwitchMapSubscriber._innerSub @ vendor.js:142680
push.SwitchMapSubscriber._next @ vendor.js:142670
push.Subscriber.next @ vendor.js:55084
push.MapSubscriber._next @ vendor.js:75437
push.Subscriber.next @ vendor.js:55084
push.FilterSubscriber._next @ vendor.js:87996
push.Subscriber.next @ vendor.js:55084
push.Subject.next @ vendor.js:75074
push.BehaviorSubject.next @ vendor.js:142614
push.Router.setTransition @ vendor.js:53102
push.Router.scheduleNavigation @ vendor.js:53403
push.Router.navigateByUrl @ vendor.js:53285
push.Router.navigate @ vendor.js:53317
(anonymous) @ app.component.ts:198
(anonymous) @ password-generator-history.component.ts:14
ZoneAwarePromise @ vendor.js:130946
567.app_component_awaiter @ password-generator-history.component.ts:14
(anonymous) @ app.component.ts:117
push.ZoneDelegate.invoke @ vendor.js:130419
onInvoke @ vendor.js:28582
push.ZoneDelegate.invoke @ vendor.js:130418
push.Zone.run @ vendor.js:130176
push.NgZone.run @ vendor.js:28477
(anonymous) @ app.component.ts:117
(anonymous) @ password-generator-history.component.ts:14
ZoneAwarePromise @ vendor.js:130946
567.app_component_awaiter @ password-generator-history.component.ts:14
(anonymous) @ app.component.ts:116
(anonymous) @ broadcaster.service.ts:15
send @ broadcaster.service.ts:14
sendMessage @ electronRendererMessaging.service.ts:22
(anonymous) @ electronRendererMessaging.service.ts:11
(anonymous) @ electronPlatformUtils.service.ts:226
ZoneAwarePromise @ vendor.js:130946
567.electronRendererMessaging_service_awaiter @ electronPlatformUtils.service.ts:226
(anonymous) @ electronRendererMessaging.service.ts:9
emit @ events.js:200
onMessage @ C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_1.23.1.0_x64__h4e712dmw3xyy\app\resources\electron.asar\renderer\init.js:42
Show 110 more frames

## Additional Context

My machine has the intermediate and root certificate authorities (from a private CA) trusted in both the personal and machine store. The certificate is trusted when the vault is loaded from the web portal and browser plugin.

**Comment by cscharf** [comment]
Is there a different domain/URL that you're being redirected to that's slightly different than normal after the SSO flow? Perhaps a different in environment setups between URL and internalURL for Identity, etc.? Something that would mismatch the `cn` you have set in your cert?

**Comment by clayadams5226** [comment]
Hi @kdblocher, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by kdblocher** [comment]
Hi @clayadams5226 -

I discovered the source of the issue.
1) The internal CA certificate chain needs to be trusted by the client device. (Obviously)
2) The server certificate issued for Bitwarden needs a Subject Alternative Name (SAN). I had neglected for some reason to add this. Without it, the plugin was failing to trust the issued certificate (for API calls, it seems) and failed during login.

**Comment by cscharf** [comment]
Awesome, thank you for the update Kyle!
