### ISSUE TITLE
Feature Request: Two-Factor for unlock

### ISSUE THREAD

**Issue by basbebe** [bitwarden/desktop#620]
I would really much like a feature to be able to set a second factor for unlocking my vault (be it desktop, mobile or Browser) with a second factor.

I know this is already there to log in but I would like to also use this when the vault is just locked because logging out might be not the best option when e.g. offline.

Pass uses PGP (which can be put on a Smartcard / Yubikey), KeepassXC offers OTP/Challenge-Response (e.g. Yubikey). I find both solution good and I think they would add to the security of the vault.

In case of Yubikey there is support for NFC and Lightning / USB-C via the Yubikey SDKs.

**Comment by SergeantConfused** [comment]
Hi there,

Please note that feature requests are submitted on our feature request page here: https://community.bitwarden.com/c/feature-requests/5
I recommend checking this: https://community.bitwarden.com/t/unlock-bitwarden-with-yubikey-2fa-instead-of-not-in-addition-to-password/13224 out.

I hope this helps. Please let me know if you have any questions.

All the best,

**Comment by basbebe** [comment]
Sorry, I wasn't aware of that!
