### ISSUE TITLE
Windows Hello credential prompt is not centered on the app

### ISSUE THREAD

**Issue by sylveon** [bitwarden/desktop#641]
## Describe the Bug

When using Windows Hello unlocking, the window will always show up at coordinate `(0, 0)` which can be on an entirely different monitor than the one Bitwarden is running on. This can be very confusing for the user since they do not expect the Windows Hello to open on a monitor they're not currently observing.

## Steps To Reproduce

1. Enable Windows Hello unlock
2. Lock Bitwarden
3. Click on "Unlock with Windows Hello"

## Expected Result

The credential prompt shows up in the middle of the Bitwarden app window.

## Actual Result

The credential prompt shows up at coordinate `(0, 0)`, possibly a different monitor than the one Bitwarden is opened on.

## Screenshots or Videos

Actual: 
![image](https://user-images.githubusercontent.com/6440374/104240887-c8411480-542a-11eb-92df-0f7e43bbb1a0.png)

Expected:
![image](https://user-images.githubusercontent.com/6440374/104240908-d0994f80-542a-11eb-8b83-e1e383c5795b.png)

## Environment

- Operating system: Windows 10 20H2
- Build Version: 1.23.1

## Additional Context

This is caused by the app not calling the credential prompt through `IUserConsentVerifierInterop::RequestVerificationForWindowAsync` (it's currently using `UserConsentVerifier::RequestVerificationAsync`).

Calling the suggested method instead will also make the credential prompt a child of the Bitwarden app window, preventing any interaction with the app until the prompt is answered (currently, you can literally exit the app while the prompt is still there and the app process + prompt will linger until cancelled by the user).

**Comment by vision2003** [comment]
I've also noticed this before and can confirm it's also happening on my computer.

**Comment by clayadams5226** [comment]
Hey @sylveon, Moving the application window seems to in many cases "resolve" the position for the next prompt. Unfortunately, the suggested APIs are not easily accessible for us currently since NodeRT does not support it. Can you give this a try and let me know if it's a viable workaround for you?

**Comment by sylveon** [comment]
For my use case, not really, because my typical use pattern is opening the app, getting the credentials I need, and then completely closing the app.

I've investigated contributing the fix and realized NodeRT doesn't support it too. Ended up filling https://github.com/NodeRT/NodeRT/issues/151, but the project seems dead and hasn't had any commit since 2019. I could write a npm module allowing access to these interfaces and replace NodeRT in a PR, would that be acceptable?

**Comment by vision2003** [comment]
The trick @clayadams5226 mentioned does indeed seem to work for me, but only when unlocking Bitwarden desktop client. It doesn't work when unlocking from Chrome extension though. What could be done here, this is really annoying.

**Comment by vision2003** [comment]
Any news on this, the issue still seems to be there?

**Comment by sylveon** [comment]
Something in Windows must have changed to do this association automatically because it now works correctly for me with the Bitwarden desktop client

**Comment by vision2003** [comment]
Hm, weird, it's still the same on my end and I'm updated to the latest version of Windows. Did you do anything special/different to make it work?

**Comment by sylveon** [comment]
Nope. Is your Bitwarden desktop client up to date as well? I get mine through the Windows Store so it might have automatically updated.

**Comment by vision2003** [comment]
Yeah, I'm on 1.25.1.

I think the issue is that I'm getting unlock prompt before the main Bitwarden window is open, because I have Bitwarden on auto-start when Windows starts (it starts in the background and minimizes to tray). If I start Bitwarden separately, it does indeed center the unlock prompt.
