### ISSUE TITLE
Acronis Ransomware Detection

### ISSUE THREAD

**Issue by Sutphinwb** [bitwarden/desktop#644]
## Describe the Bug
I've an application on Windows 10 that I use for backup called Acronis True Image 2021.  When Bitwarden starts up, the ransomware detection that is part of the application warns of possible ransomware injection.  This is probably because Bitwarden is encrypting the key file (which is what it is supposed to do).

Not sure what can be done.  Also am addressing the issue with Acronis (but that doesn't mean Bitwarden shouldn't look at it!).

Any ideas appreciated.

Thanks

## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by cscharf** [comment]
Thanks @Sutphinwb , we'll see if we can't follow up with Acronis, while I'm closing this particular issue (as there are some false positives from certain malware/antivirus apps in regards to Bitwarden) if you could provide the detailed detection log, or at least the interesting bits around Bitwarden that would be great. Much appreciated!
