### ISSUE TITLE
Minimize upon startup

### ISSUE THREAD

**Issue by lalicatala** [bitwarden/desktop#646]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by SergeantConfused** [comment]
Hi there,

Can you clarify what seems to be the issue, please?


Thank you in advance,

**Comment by clayadams5226** [comment]
Hey @lalicatala, sorry to hear you're having issues. This should be resolved in the latest version of the desktop application (1.24) releasing later this week. Once you get it installed you should just need to enable "Minimize on startup" from your Bitwarden Preferences and you should be all set. Please let us know if this resolves your issue.

**Comment by clayadams5226** [comment]
I believe this issue has been resolved with the latest release. Closing this as resolved.

**Comment by lalicatala** [comment]
Clayton,

sorry, your fix did not work

**Comment by kennymc-c** [comment]
I also noticed that the Mac App does not start minimized at system startup or user login, despite having the start in menubar option enabled in preferences. Only when I start the app manually, it starts minimized.

macOS 11.1 & 11.2
MAS App Version 1.24.5 (513)
