### ISSUE TITLE
Windows desktop client does not sync automatically with changes done through web vault.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#647]
## Describe the Bug
If you add a new item to your vault through the web vault, the desktop client does not sync automatically and show the new item.

## Steps To Reproduce
1. Log into your web vault.
2. Add a new Login item to your vault and call it VaultSyncTest.
3. Open your desktop client.

## Expected Result
To see VaultSyncTest within a few seconds.

## Actual Result
VaultSyncTest did not appear within 10 minutes. Manually syncing helped.

## Screenshots or Videos
N/A.
## Environment

- Operating system: Windows 10 Pro 19041.508.
- Build Version: 1.23.1.

## Additional Context
Please note that adding an item through the desktop client synced immediately with the web vault. I refreshed the web vault by clicking on Tools and then back on My Vault.

**Comment by kylekurz** [comment]
This bug exists on the macOS client as well and is worse than this initial report exposes. If you `Purge Vault` on the web, the logins are never removed locally until the next manual sync or timeout of the login. This is a pretty big security hole if you think you've been compromised, as purged items remain accessible on active sessions long after they should be deleted.

**Comment by c4539** [comment]
I think this issue is on the server, so all clients are affected.
