### ISSUE TITLE
Windows desktop app - missing "Enable Browser Integration" checkbox

### ISSUE THREAD

**Issue by willfliaw** [bitwarden/desktop#651]
## Describe the Bug

As described in [here](https://bitwarden.com/help/article/biometrics/), specifically in the _Enable Biometric Unlock for Browser Extensions_ section, there should be, for both macOS and Windows, a checkbox through which one may enable Bitwarden-browser integration. Nonetheless, this checkbox seems to be non-existent, at least in the Windows desktop app (installed though either the Standard Installer or the Windows Store).

## Steps To Reproduce

1. Install Bitwarden on Windows 10 through the Standard Installer/Windows Store.
2. Navigate to Settings (File → Settings).

## Expected Result

Existent Enable Browser Integration checkbox.

## Actual Result

Non-existent Enable Browser Integration checkbox.

## Environment

- Operating system: Windows 10.
- Build Version (go to "Settings" → "About"): Version 1.23.1; Shell 6.1.7; Renderer 76.0.3809.146; Node 12.4.0; Architecture x64.

## Additional Context

Bug persists even if the "Unlock with Windows Hello" checkbox is checked.

**Comment by clayadams5226** [comment]
Hey @willfliaw the desktop app (1.22.0) hasn't officially been released yet to the store. That will be coming later this week.
