### ISSUE TITLE
Can't enable Biometric Unlock for Browser Extension

### ISSUE THREAD

**Issue by jambonneau** [bitwarden/desktop#652]
I'm using a Mac M1, trying to enable biometric unlock in my Chrome extension (everything is up to date, Bitwarden app, Bitwarden browser extension, Chrome browser) following this : https://bitwarden.com/help/article/biometrics/#enable-biometric-unlock-for-browser-extensions. I can't see the the Enable Browser Integration checkbox in the desktop App. May be the Mac M1 is not supported yet ?

## Steps To Reproduce

Using a Mac M1

1. Go to Desktop App, navigate to Settings (Bitwarden → Preferences).
2. Can't find the "Enable Browser Integration checkbox"

## Expected Result

Expected Result : Find the "Enable Browser Integration checkbox" to click on it

## Actual Result

No "Enable Browser Integration checkbox" checkbox 

## Environment

- Operating system: Mac M1 [Mac OS Big Sur 11.1]
- Build Version Desktop App : Version 1.23.1 (1.23.1)
- Build Version Browser Extension : Version 1.47.1
- Chrome : Version 88.0.4324.96 (Build officiel) (arm64)

**Comment by Leworoe** [comment]
This is a really new feature for the browser extension. You can wait until it is updated in the chrome webstore or you update it yourself: [https://github.com/bitwarden/browser/releases/tag/v1.48.0](https://github.com/bitwarden/browser/releases/tag/v1.48.0)

**Comment by jambonneau** [comment]
OK ! Thanks :)
