### ISSUE TITLE
can not read in offline (no internet) mode

### ISSUE THREAD

**Issue by nefedov** [bitwarden/desktop#66]
I test desktop Linux: Bitwarden-1.0.5-amd64.deb
When I try to open bitwarden without internet connection it failed: [Failed to fetch]
after I switch on connection - it connects (so user and password are correct)
If I open it and switch off network - it works on reading. 
How I can read bitwarden without the Internet?

**Comment by kspearrin** [comment]
You need to be already logged in prior to going offline. Unlocking will work offline.

**Comment by Crocmagnon** [comment]
Note that you must not log out but only lock the vault in order to still be able to access it. Closing the apps causes a vault lock for me (macOS).
