### ISSUE TITLE
Global Menu on Plasma, Items Grey'd out (Not selectable)

### ISSUE THREAD

**Issue by gbcox** [bitwarden/desktop#663]
using:  bitwarden-1.24.1-1.x86_64

When using the global menu widget in KDE Plasma, many items are no longer selectable, they are grey'd out.  For example, the only item that is available in the "File" menu is "Quit".  Most importantly, you can't go into Setup.  Many other functions are also unavailable, such as sync, export and password functions.  If I turn off global menus and relaunch, the menu appears on the window and all functions are available.  Functions should be available when using global menus.
```

          /:-------------:\          gbcox@charon 
       :-------------------::        ------------ 
     :-----------/shhOHbmp---:\      OS: Fedora 33 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Kernel: 5.10.9-201.fc33.x86_64 
  :-----------sMMMMNMNMP.    ---:    Uptime: 2 hours, 6 mins 
 :-----------:MMMdP-------    ---\   Packages: 4311 (rpm) 
,------------:MMMd--------    ---:   Shell: bash 5.0.17 
:------------:MMMd-------    .---:   Resolution: 1920x1080 
:----    oNMMMMMMMMMNho     .----:   DE: Plasma 5.20.5 
:--     .+shhhMMMmhhy++   .------/   WM: KWin 
:-    -------:MMMd--------------:    WM Theme: breeze 
:-   --------/MMMd-------------;     Theme: Breeze [Plasma], Adwaita [GTK2] 
:-    ------/hMMMy------------:      Icons: breeze [Plasma], breeze [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Terminal: konsole 
:---:sdNMMMMNds:------------:        CPU: AMD FX-8350 (8) @ 1.853GHz 
:------:://:-------------::          GPU: AMD ATI Radeon HD 7850 / R7 265 / R9 270 1024SP 
:---------------------://            Memory: 6160MiB / 32003MiB 
```

**Comment by pizzadude** [comment]
Workaround:

env ELECTRON_FORCE_WINDOW_MENU_BAR=1 ./Bitwarden-1.24.1-x86_64.AppImage

**Comment by gbcox** [comment]
Thanks, that workaround makes it so it doesn't use global menus at all, and just the local window menu... so at least now I can access settings, etc. - but doesn't electron support global menus?  I thought it did?  I found an article that said that "Title Bar Style" needed to be set to native... but don't see how to do that... https://www.reddit.com/r/kde/comments/aiafsr/global_menu_dont_work_only_in_one_specific/

**Comment by gbcox** [comment]
Appears problem is resolved for X11 KDE, but in Wayland global menu doesn't appear at all.  The circumvention mentioned works to get the menu to appear in the local window however as a temporary workaround.
