### ISSUE TITLE
No bugs to report, just a question for the developers...

### ISSUE THREAD

**Issue by hollow-frenk** [bitwarden/desktop#664]
Hi, I made a mac os 11 style icon and I would like to know what else to change besides icon.icns and icon.iconset, thanks for any reply.

**Comment by flying-sausages** [comment]
I think if you'd clone the repo, make the changes and make a PR you'd get more in-depth feedback

**Comment by hollow-frenk** [comment]
I think so too, but I wanted to do a good job on the first try.  (which then you have to see if it is accepted ...)

**Comment by flying-sausages** [comment]
PRs go back and forward a lot. Chance is you will still have to make some suggestions, but this way it's clear what' been done. PRs with direct no discussion merges are rare :p

**Comment by hollow-frenk** [comment]
Okay then I'm only changing icns and iconset when I'm around, then I see what happens.
