### ISSUE TITLE
Error while enabling browser integration.

### ISSUE THREAD

**Issue by Diiaablo95** [bitwarden/desktop#665]
## Describe the Bug

I am not able to turn on browser integration from the latest version of the app (1.24.1). I get an error message, shown in the screenshot section below.

## Steps To Reproduce

1. Open the desktop app
2. Go to settings
3. Try to check **Enable browser integration**

## Expected Result

I guess the browser integration should be turned on?

## Actual Result

See screenshot below.

## Screenshots or Videos

![](https://imgpile.com/images/7GPuPS.png)

## Environment

- Operating system: Mac OS Big Sur
- Build Version: 11.1

**Comment by crazybadger** [comment]
I've updated this morning with the same error message.  What's different with the App Store version?

**Comment by Diiaablo95** [comment]
I guess it is a matter of certificates (?) But the App Store version is stuck at version 1.23.0 which is 2 months old.

**Comment by XantherBanter** [comment]
Mac Store version just got updated to 1.24.1. I tried enabling browser integration on the Mac Store app, with no success. I am using MacBook Air M1 if that helps.

1. On Firefox 84.0.2, it says browser integration is not enabled.
2. On Safari 14.0.2, it asks for confirmation from the desktop. No notification or a prompt in the desktop app.

**Comment by cho-m** [comment]
I see the same thing as XantherBanter

On Firefox, I see a console error for:
```
ExtensionError: No such native application com.8bit.bitwarden ExtensionUtils.jsm:58:5
```

It looks like Desktop app is supposed to create this file at https://github.com/bitwarden/desktop/blob/ee1ea1a887c0e7c182d194dc9b240c675c283b57/src/main/nativeMessaging.main.ts#L86-L88

The JSON file does not exist in that location for me.

On MAS Bitwarden Desktop app, when I click the `Enable browser integration`, I do see a console error for Apple's Sandbox blocking a file write:
```
Sandbox: Bitwarden(3264) deny(1) file-write-create /private/tmp/app.bitwarden
Violation:       deny(1) file-write-create /private/tmp/app.bitwarden
Process:         Bitwarden [3264]
Path:            ???
Load Address:    0
Identifier:      ???
Version:         ??? (???)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
```

**Comment by cho-m** [comment]
Digging a little further, I think MAS version is lacking necessary entitlements to write outside sandbox.
```zsh
❯ codesign -d --entitlements :- /Applications/Bitwarden.app | xmllint --format -
Executable=/Applications/Bitwarden.app/Contents/MacOS/Bitwarden
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.application-identifier</key>
    <string>LTZ2PFU5D6.com.bitwarden.desktop</string>
    <key>com.apple.developer.team-identifier</key>
    <string>LTZ2PFU5D6</string>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>LTZ2PFU5D6.com.bitwarden.desktop</string>
    </array>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
  </dict>
</plist>
```

Based on another app I have that writes to the same directory, I see the following extra entitlements may be needed:
```
    <key>com.apple.security.temporary-exception.files.home-relative-path.read-write</key>
    <array>
      <string>/Library/Application Support/Google/Chrome/NativeMessagingHosts/</string>
      <string>/Library/Application Support/Mozilla/NativeMessagingHosts/</string>
    </array>
```

Hopefully someone more familiar with MAS build can take a further look.

**Comment by devployment** [comment]
Same problem here. Current App Store App (1.24.1). Browser integration enabled in app. Running on Intel MacBook Pro, Big Sur.

**Comment by kennymc-c** [comment]
Same problem with me on an Intel MacBook Air with Safari, Chrome and Firefox. According to #666 there seems to be problems with the Windows version as well

**Comment by JosiahMendes** [comment]
I see the same behaviour mentioned by cho-m on an Intel MacBook Pro.

When clicking the `Enable Browser Integration`, there's a console error. 
```
Sandbox: Bitwarden(6539) deny(1) file-write-create /private/tmp/app.bitwarden
Violation:       deny(1) file-write-create /private/tmp/app.bitwarden
Process:         Bitwarden [6539]
Path:            /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
Load Address:    0x103d99000
Identifier:      com.bitwarden.desktop
Version:         509 (1.24.1)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
User ID:         501
```

**Comment by henrik242** [comment]
The Bitwarden team seems to be aware of this issue: https://community.bitwarden.com/t/new-browser-extension-not-working-with-biometric-login/16902/17

**Comment by cscharf** [comment]
Yes, we have a PR done already w/ another on the way for Edge on macOS. The Mac AppStore version will be the only version supported because of the way Apple sandboxes app permissions and how native messaging would work, essentially the DMG version (outside of MAS) won't allow us to address the native messaging application consistently as it gets appended with a run-time sandboxed path, which the AppStore version does not (same bits, same signature, same old Apple). We are looking into alternatives (similar but different issues with Windows Store but opposite scenario).

**Comment by Duckbilled** [comment]
Does "Remove Biometrics Unlock from Firefox" in the release notes of the browser update mean we won't see biometrics in FX?

**Comment by cscharf** [comment]
> Does "Remove Biometrics Unlock from Firefox" in the release notes of the browser update mean we won't see biometrics in FX?

Yes, please see: https://github.com/bitwarden/browser/issues/1548#issuecomment-767027871

**Comment by cscharf** [comment]
> @cscharf have you considered compiling a separate version of the extension for Firefox which would have the new permission enabled? Similar to what 1password is doing where they have two types of browser extensions.

I wouldn't "not" consider it, if that double negative helps, lol. Our extension is a Firefox Recommended extension and requires additional review/scrutiny (which is awesome) it also means publishing a duplicate/sibling extension creates both some build/deployment complexity for us, additional footprint for publishing, and will raise some eyebrows at Mozilla I'm sure; on top of all of that possibly causing confusion with our customers/users, etc. 

Hopefully we can push Mozilla to incorporate a fix for the upstream issue regarding the optional permission we need and then we can re-include this for FF in the near future w/o any hacky workarounds. At the end of the day we recognize users of certain browsers choose those browsers more often because they value (security, privacy, lack of monkey-business, etc.) or specific user experiences/expectations. We've been avoiding hacks for Mozilla for some time while we plan an overhaul to our browser extension architecture/design so it works across browsers better (and in FF private mode as well as Chrome's upcoming beta version which will cause pain for all password managers, including us). We simply have to balance that out with short vs. long-term goals.

Thanks and sorry for the rant 😉

**Comment by szlend** [comment]
Fair enough. 1password doesn’t even publish their browser integration extension on the store, but that has its own set of problems. I agree that Mozilla implementing this is the way to go, it’s just the question of how much of a priority this is for them.

**Comment by orangesunny** [comment]
> > @cscharf have you considered compiling a separate version of the extension for Firefox which would have the new permission enabled? Similar to what 1password is doing where they have two types of browser extensions.
> 
> I wouldn't "not" consider it, if that double negative helps, lol. Our extension is a Firefox Recommended extension and requires additional review/scrutiny (which is awesome) it also means publishing a duplicate/sibling extension creates both some build/deployment complexity for us, additional footprint for publishing, and will raise some eyebrows at Mozilla I'm sure; on top of all of that possibly causing confusion with our customers/users, etc.
> 
> Hopefully we can push Mozilla to incorporate a fix for the upstream issue regarding the optional permission we need and then we can re-include this for FF in the near future w/o any hacky workarounds. At the end of the day we recognize users of certain browsers choose those browsers more often because they value (security, privacy, lack of monkey-business, etc.) or specific user experiences/expectations. We've been avoiding hacks for Mozilla for some time while we plan an overhaul to our browser extension architecture/design so it works across browsers better (and in FF private mode as well as Chrome's upcoming beta version which will cause pain for all password managers, including us). We simply have to balance that out with short vs. long-term goals.
> 
> Thanks and sorry for the rant 😉

Thanks for the explanation; it’s not a rant :)

Stay the official publication way. It’s longer, but worth the way and waiting!

**Comment by cscharf** [comment]
Hi @Diiaablo95 , this should be resolved with the latest desktop MAS version + latest browser extension version. You may need to exit and reload your browser (or force an extension reload) in order to get it working again. Please feel free to re-open if this is not the case.

**Comment by crazybadger** [comment]
What versions should it be working?  I've got 1.24.5 (513) on the Desktop and 1.48.1 on Chrome and it's not working.  Server is up to date on 1.39.0.  Thanks

**Comment by Nelluk** [comment]
Sorry to re-open, but my problem seems related. Exiting and reloading the browser did not work, but uninstalling and reinstalling the Chrome extension did. It finally got beyond the extension warning that I did not have browser integration enabled, but now it is stuck saying it is waiting on confirmation from the desktop app.

The desktop vault is the latest MAS version, is open and unlocked. The first time I clicked the 'unlocked with biometrics' box in the extension settings it popped up a permissions window, which I authorized, and then nothing happens. The checkbox is still empty, and whenever I click it now I get the 'Waiting on confirmation' error. I've tried quitting and relaunching the desktop app, and disabling/re-enabling browser integration there.

**Comment by cscharf** [comment]
> 1.24.5 (513) on the Desktop and 1.48.1 on Chrome

That should do it, yes.

> now I get the 'Waiting on confirmation' error. I've tried quitting and relaunching the desktop app, and disabling/re-enabling browser integration there.

We have identified a scenario that was found by @tgreer-bw where he had to also enabled "allow access to file URLs" in Chrome:
![image](https://user-images.githubusercontent.com/3904944/106034361-d2a51480-60a0-11eb-8154-e784562d6dc6.png)

Please check that setting and see if that alleviates the issue. You may need to reload the extension/browser again afterwards to get it working fully.

**Comment by crazybadger** [comment]
I think I've got it working now, but what a faff!  It's also not a great first attempt as I still have to hit a button to enable biometrics and then another to select the login.  Surely it can work better than that, and simply ask for my fingerprint and then autofill the password?  Ideally, I don't even want to unlock the vault, or at least it can be unlocked, the password-auto-filled, and then locked again.

**Comment by vassyz** [comment]
I got the latest versions and I'm still getting `Browser integration is not enabled` on Brave.

**Comment by Nelluk** [comment]
> We have identified a scenario that was found by @tgreer-bw where he had to also enabled "allow access to file URLs" in Chrome:
> ![image](https://user-images.githubusercontent.com/3904944/106034361-d2a51480-60a0-11eb-8154-e784562d6dc6.png)
> 
> Please check that setting and see if that alleviates the issue. You may need to reload the extension/browser again afterwards to get it working fully.

Same behavior as before. I removed the extension. Reinstalled it. Enabled "allow access to file URLs". Logged in to my fault. Quit the desktop app, reopened it. I got the permissions request window when clicking 'Unlock with biometrics' in the extension once again, which I allowed, but now I am back to the previous state of it just telling me it is waiting for desktop verification.

**Comment by Nelluk** [comment]
> I got the latest versions and I'm still getting `Browser integration is not enabled` on Brave.

Try completely uninstalling and re-installing the extension. I could not get past that message until doing that in Chrome.

**Comment by vassyz** [comment]
Only worked by uninstalling and allowing access to file URLs before logging in. Now I'm stuck at this step: `Awaiting confirmation from desktop. Please confirm using biometrics in the Bitwarden Desktop application to enable biometrics for browser.`

I'm not getting any notifications from the desktop app on MacOS.

**Comment by cscharf** [comment]
> I'm not getting any notifications from the desktop app on MacOS.

@vassyz , please uncheck "allow browser integration" checkbox in desktop settings and check it again, that should "jiggle the handle" so to speak in this scenario. We're still polishing up some of these fun things that we've been finding since launching as Apple still has not given any way to beta test macOS MAS apps.

**Comment by vassyz** [comment]
@cscharf Tried that, I'm still not getting the notification.

**Comment by michaelmlin** [comment]
I'm having the same issue where I've downloaded the mac appstore version of bitwarden desktop app v1.24.5.

1. Enabled browser integration (for biometrics)
2. Enabled chrome extension to "Unlock with biometrics" (Chrome Version 88.0.4324.192)
3. Not getting the desktop notification to confirm this enabled chrome browser extension for biometric
