### ISSUE TITLE
Browser integration not working on MS Store app (version 1.24.1)

### ISSUE THREAD

**Issue by rabader** [bitwarden/desktop#666]
## Describe the Bug

Browser integration not working on the Microsoft Store version of Desktop app.

## Steps To Reproduce

1. Download MS store version of desktop app.
2. Click box to 'Enable browser integration' in this desktop app.
3. Open browser extension (in Firefox/Chrome) and try to click the box to 'Unlock with biometrics'.

## Expected Result

Expected 'Windows Hello' pop-up to log in with biometrics.

## Actual Result

Got a message in the extension saying 'Browser integration not enabled'.

## Environment

- Operating system: Windows 10
- Desktop Build Version: 1.24.1
- Browser Extension Build Version: 1.48.0

**Comment by kennymc-c** [comment]
Same problem on macOS: https://community.bitwarden.com/t/touch-id-support-for-macos/568/158

**Comment by henrik242** [comment]
It looks like the Bitwarden team is aware of this issue: https://community.bitwarden.com/t/new-browser-extension-not-working-with-biometric-login/16902/17

**Comment by cscharf** [comment]
Will be released soon; however ultimately the Windows Store version won't be supported until we can figure out a workaround for the necessary permissions to make this work.
