### ISSUE TITLE
Notes field is not searched in desktop client v1.24.1 (Windows 10, MacOS)

### ISSUE THREAD

**Issue by fredekr** [bitwarden/desktop#669]
## Describe the Bug

The search bar no longer searches the NOTES field in entries.

## Steps To Reproduce

1. Enter some test in the notes field of an entry.
2. Use the search bar to search for that text.
3. The entry is not found.

## Expected Result

The search bar should also search the notes field, and those entries should be shown in the item list.

## Actual Result

Text in the notes field appears to no longer be searched; items with matching test in the notes field are not found.

## Environment

Windows 10, Mac OS Catalina
Version 1.24.1

## Additional Context

In version 1.23.1, this worked fine. The Firefox extension still searches the notes field as well.

**Comment by emorinaj** [comment]
I have this problem also.
In general Wildcard Search doesn't work anymore after this update

**Comment by fredekr** [comment]
Appears to be fixed as of 1.24.4.
