### ISSUE TITLE
Windows 10 Desktop

### ISSUE THREAD

**Issue by goran69z** [bitwarden/desktop#670]
## Steps To Reproduce

I have been using desktop version for some time. Got a new computer and after an update of Bitwarden on the new computer it just after lunching freezes. I manage to type first two letters of username and that's it, freeze. Must go to to task manager to turn off. Reinstalled from site and from Microsoft store, Nothing. Extensions work simply fine. It's just desktop. Any ideas?

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by Greenderella** [comment]
Hi @goran69z, will you first try uninstalling the app, removing any leftover data, resetting your device and re-installing? Does this issue still persist?

Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues. Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by goran69z** [comment]
Thank you so much for your input Alex. I did contact Bitwarden staff through email and one of your kind colleagues gave me link here on Github for version 1.23.1 which works fine. No issues whatsoever. I will wait through 1.25 or 1.24.2. because even with leftover data cleaned I just have a freeze of the screen after I input 5 letters of username. Possibly It's me or my machine. I am a happy camper even with 1.23.1. @bitwarden service and support is just phenomenal.

**Comment by goran69z** [comment]
Hello

matter was resolved with version 1.24.4. Thank you.
