### ISSUE TITLE
Bitwarden Desktop (Windows) 1.24.1 triggers Acronis Active Protection

### ISSUE THREAD

**Issue by MTEXX** [bitwarden/desktop#674]
## Describe the Bug

After in-app-upgrade to version 1.24.1 of Bitwarden Desktop (Windows) Acronis Active Protection got triggered every time Bitwarden Desktop starts.

## Steps To Reproduce

1. Start Bitwarden Desktop (Windows) via search or shortcut
 
## Expected Result

No message from Acronis or any other AV should be displayed.

## Actual Result

Acronis Active Protection got triggered.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/3194660/105687896-486e7c00-5ef9-11eb-921a-371a683f91eb.png)

## Environment

- Operating system: Microsoft Windows 10 Prof. 20H2 (Build 19042.746)
- Build Version: 1.24.1

## Additional Context

The affected file is `C:\Users\%username%\AppData\Roaming\Bitwarden\data.json`

Tested on multiple computers (domain joined and private), all installed with AAP got triggered.

**Comment by kspearrin** [comment]
This is a false positive. Likely because that file contains encrypted From your vault. The AV thinks that is random ware for some reason. Please try reporting it to the vendor. We will do the same.
