### ISSUE TITLE
[Linux] 1.24.3 is broken

### ISSUE THREAD

**Issue by pizzadude** [bitwarden/desktop#684]
Tried with snap and AppImage.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'browser-hrtime'

**Comment by lnx00** [comment]
Same thing on Windows:
https://i.imgur.com/1E7otnX.png

**Comment by m-p-3** [comment]
Looks like they pushed a new version but might have retracted it just at the time it was installing, so it's missing some files that are no longer available to download..

**Comment by kspearrin** [comment]
Please reinstall v1.24.4. The download link on our website is updated. Sorry for the problem.
