### ISSUE TITLE
Windows 10 Desktop App Hanging Frequently

### ISSUE THREAD

**Issue by nathan-denyer** [bitwarden/desktop#686]
## Describe the Bug

The Windows 10 Desktop app downloaded from bitwarden.com freezes every 5-10 seconds for about 1 second.
The Windows store version does not display this behavior.

## Steps To Reproduce

Use any text field to type text for 5 to 10 seconds.
There should be a point where the application hangs and stops accepting input.

## Expected Result

There is no freezing.

## Actual Result

The application hangs for about a second frequently.

## Screenshots or Videos

Notice how the typing stops randomly, I was still typing however the application was frozen.

https://user-images.githubusercontent.com/19481006/105792094-02df9c80-5f55-11eb-8cf9-eb261e42002b.mp4

## Environment

Windows 10 20H2
Bitwarden.exe version 1.24.4
Bitwarden UWP version 1.24.1

## Additional Context

I was able to reproduce this on two different machines running Windows 10. 
The UWP version is completely free of this freezing.

**Comment by harrydimitriou** [comment]
Not much to add unfortunately but I'm facing the exact same issue with  1.25.1 .
