### ISSUE TITLE
Chocolatey install script is failing

### ISSUE THREAD

**Issue by fiasko** [bitwarden/desktop#688]
## Describe the Bug

Chocolatey install script is failing and prevents the update or Installation of Bitwarden 1.24.4

## Steps To Reproduce

Try to install or update Bitwarden with chocolatey

## Expected Result

Latest Bitwarden is installed correctly

## Actual Result

ERROR: At C:\ProgramData\chocolatey\lib\bitwarden\tools\chocolateyinstall.ps1:4 char:20
+ ... um = 'File 'D:\a\desktop\desktop\dist\chocoloatey\Bitwarden-Installer ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'D:\a\desktop\desktop\dist\chocoloatey\Bitwarden-Installer-1.24.4.exe' doesn't' in expression or statement.

At C:\ProgramData\chocolatey\lib\bitwarden\tools\chocolateyinstall.ps1:13 char:22
+ silentArgs = '/S'
+ ~
The string is missing the terminator: '.
The upgrade of bitwarden was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\bitwarden\tools\chocolateyinstall.ps1'.

## Environment

Windows 10

## Additional Context

Looks like the chocolateyinstall.ps1 contains an error message in the checksum field, which corrupts the script syntax.

**Comment by kspearrin** [comment]
@joseph-flinn

**Comment by joseph-flinn** [comment]
@fiasko Thanks for submitting this bug. Release 1.24.5 has the fix, has been pushed to Chocolatey, and is currently being reviewed by the Chocolatey moderators.
