### ISSUE TITLE
Unable to upload attachment

### ISSUE THREAD

**Issue by mattico** [bitwarden/desktop#69]
Windows 10 x64

Just installed the app and tried to create a Secure Note and attach a small file (~80KB). I'm a premium user. After hitting the save icon, the button spins for a while, then there's a notification that an error occurred. I'm not behind a proxy or VPN or anything like that. Let me know if I can give you any more information to help debug.

**Comment by kspearrin** [comment]
This is the same problem as https://github.com/bitwarden/web/issues/186

It is a problem in core. It is intermittent. We're still trying to track it down.

**Comment by kspearrin** [comment]
Also, it should be cleared up now. Try again.

**Comment by mattico** [comment]
Ah, okay. It did work when I uploaded it using the web interface. Since you already have somewhere to track the issue, I'll close this one.

**Comment by kspearrin** [comment]
Please reply to one of these issues if you notice it happening again. Since the problem is intermittent I need to know when it is occurring so that I can capture some vital info from the database regarding the problem.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/core/issues/230
