### ISSUE TITLE
Export save: unencrypted csv message for type json

### ISSUE THREAD

**Issue by mmattel** [bitwarden/desktop#696]
## Describe the Bug

After upgrading to  version 1.24.6, I get the warning message when exporting the safe, that csv is not encrypted but json has been selected.

## Steps To Reproduce

Export the safe

## Expected Result

Error message should be either selective to the type of format, or both formats should be noted in the message.

## Actual Result

Confusing error message, because json selected but hint to csv

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/3321281/105972524-00cc2980-608c-11eb-8c9c-dc231d6b5266.png)

## Environment

W10x64 Pro (DE)

## Additional Info

`Csv` --> `csv`

**Comment by clayadams5226** [comment]
Hey @mmattel great catch! This actually looks like an issue with the translation of the app. When viewed in English the message simply says "unencrypted" and doesn't specify the export type.

**Comment by djsmith85** [comment]
Hey @mmattel I removed the file format from the german translation at https://crowdin.com/translate/bitwarden-desktop/53/en-de#3196 and I'm currently waiting for approval thru a proofreader.

**Comment by mmattel** [comment]
@djsmith85 thanks, I have read the proposal and it looks good to me. Hopefully the proofreader commits soon.

**Comment by tgreer-bw** [comment]
👍 approved.

**Comment by djsmith85** [comment]
Thanks @tgreer-bw, that was quick.

**Comment by djsmith85** [comment]
@mmattel The issue can be closed, as the newest release contains the corrected translation.
