### ISSUE TITLE
Add auto update check option

### ISSUE THREAD

**Issue by jpele-tis** [bitwarden/desktop#697]
Hello,
Please add an option to disable auto update check, SDT users will thank you.

Regards.

**Comment by Greenderella** [comment]
Hi @jpele-tis, you can use an environment variable, ELECTRON_NO_UPDATER=1

ref: https://github.com/bitwarden/jslib/blob/master/src/electron/updater.main.ts#L38

**Comment by jpele-tis** [comment]
> Hi @jpele-tis, you can use an environment variable, ELECTRON_NO_UPDATER=1
> 
> ref: https://github.com/bitwarden/jslib/blob/master/src/electron/updater.main.ts#L38

I never saw such method, can you provide me a configuration process ?

Can you consider implementing an option parameter in the user profile, or in the installation folder ? Like a new option in the `data.json` file.

```
{
    "disableUpdateCheck": true, 
}
```

**Comment by cscharf** [comment]
Hi @jpele-tis , there are a few [open requests from the community](https://community.bitwarden.com/search?q=auto%20update%20category%3A5) for this enhancement, please feel free to add some detail, color or upvote one of those to help promote your ask here. It's not unreasonable but something we have to prioritize with other things, etc OR may give someone in the community the opportunity to submit a PR for.

This issue will now be closed, thanks again for your feedback!

**Comment by jpele-tis** [comment]
> Hi @jpele-tis , there are a few [open requests from the community](https://community.bitwarden.com/search?q=auto%20update%20category%3A5) for this enhancement, please feel free to add some detail, color or upvote one of those to help promote your ask here. It's not unreasonable but something we have to prioritize with other things, etc OR may give someone in the community the opportunity to submit a PR for.
> 
> This issue will now be closed, thanks again for your feedback!

Ok, we will switch to the portable version for now, thanks for your replies
