### ISSUE TITLE
cant unlock vault in Windows desktop App

### ISSUE THREAD

**Issue by istdaslol** [bitwarden/desktop#699]
Since a few weeks, when i try to log into my vault, self hosted, i get en error that my master-password is wrong, but it isnt. i have to sign out and in to get it working. It also happens on my browser extension but only in Vivaldi on Windows, not on Vivaldi MacOS.

**Comment by Greenderella** [comment]
You will want to check your server version. If you are not using the latest version, you will want to update. Before you perform an update, please make sure you have a backup, clone or full copy of the bwdata directory. Once you are ready to update, you can follow the update procedure here: https://bitwarden.com/help/article/updating-on-premise

**Comment by istdaslol** [comment]
![image](https://user-images.githubusercontent.com/13665441/106215133-91138700-61d0-11eb-9b1b-508e24724820.png)

@Greenderella i did as you said but it did not help. And as I said, it works fine on other divises or some Browser

**Comment by istdaslol** [comment]
@Greenderella i did an updateself and than an update, do get yesterdays version but still the same issue.
But as is said, id does work on MacOS but the Windows Appstore version and Browserextensions on Windows dont

**Comment by Greenderella** [comment]
Are you running Bitwarden or any other alternative solution (namely bitwarden_rs) in your self-host environment?

**Comment by istdaslol** [comment]
![image](https://user-images.githubusercontent.com/13665441/106264800-6ce29500-6226-11eb-96b1-353f6bfb09a1.png)
@Greenderella no, it should be the normal version

**Comment by istdaslol** [comment]
ok it randomly startet working again
