### ISSUE TITLE
conflict with Alfred's snippets if bitwarden keeps at background on Mac

### ISSUE THREAD

**Issue by Hsin-Liou** [bitwarden/desktop#700]
## Describe the Bug
First I thought its Alfred's problem, so I go to its forum to seek help. 
Here is the [post](https://www.alfredforum.com/topic/16518-snippets-being-blocked-anywhere-if-there-is-an-app-preventing-itmaybe-the-description-not-accelerate/?tab=comments#comment-84599) where you can know what happened in detail.

Although it doesn't cause bitwarden working wrong, it seems the way how  bitwarden is using the API of secure input is over.
## Steps To Reproduce

1. Keeps bitwarden at the background
2. lock bitwarden
3. Wait a while.

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by andfinally** [comment]
I get the same issue. When Bitwarden Desktop is in the background and locked, Alfred Snippets (text replacement feature) stops working. Alfred shows this message, which incorrectly identifies the last program you focused as the cause.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/1647564/109382668-c8fa1100-78d9-11eb-8559-c0990f2d4e84.png">

As soon as I unlock or exit Bitwarden, the message goes away and snippets work again.

**Comment by eliykat** [comment]
This appears to be the same issue as #298. This issue will be closed so that we can track it in one central location. Please refer to that thread for further discussion.
