### ISSUE TITLE
Start automatically on login doesn't work on AppImage package

### ISSUE THREAD

**Issue by carobinario** [bitwarden/desktop#701]
## Steps To Reproduce

1. Download 

1. Download Bitwarden-1.24.6-x86_64.AppImage, then sudo chmod u+x it
2. Launch Bitwarden-1.24.6-x86_64.AppImage
2. Click on ''File / settings"
3. Scroll down to "options"
4. Click on ''Start automatically on login"
5. Click on "Close"

## Expected Result

Bitwarden start in system tray at reboot.

## Actual Result

I have to manually launch Bitwarden-1.24.6-x86_64.AppImage every time I login in my desktop.

## Screenshots or Videos

![Screenshot_20210131_123607](https://user-images.githubusercontent.com/16922051/106382609-f8902900-63c0-11eb-9c28-5849b90be12a.png)

## Environment

- Operating system: Operating System: Fedora 33, KDE Plasma Version: 5.20.5, KDE Frameworks Version: 5.78.0, Qt Version: 5.15.2, Kernel Version: 5.10.10-200.fc33.x86_64, OS Type: 64-bit, Processors: 4 × Intel® Core™ i5-6600 CPU @ 3.30GHz
Memory: 15.3 GiB of RAM, Graphics Processor: Mesa Intel® HD Graphics 530
- Build Version: 1.24.6

## Additional Context

This issue is not present if I install .rpm package (Bitwarden-1.24.6-x86_64.rpm).

**Comment by CepheidVariable** [comment]
I'm able to replicate this behavior on my environment as well:

- Operating System: Manjaro Linux
- KDE Plasma Version: 5.22.5
- KDE Frameworks Version: 5.87.0
- Qt Version: 5.15.2
- Kernel Version: 5.13.19-2-MANJARO (64-bit)
- Graphics Platform: X11
- Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
- Memory: 31.3 GiB of RAM
- Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
