### ISSUE TITLE
Plain text passwords are exported with read permissions for everyone

### ISSUE THREAD

**Issue by vonas** [bitwarden/desktop#705]
## Describe the Bug

An exported JSON or CSV file containing all of the vault's passwords is saved with read permissions for everyone, i.e. the user, his group and others.

## Steps To Reproduce

Export your vault.
https://bitwarden.com/help/article/export-your-data/#from-the-desktop-app

## Expected Result

I expected the file to have only read and write permissions for the me, the user (octal 600).

## Actual Result

The file has read permissions for everyone, and write permissions only for me (octal 644).

## Screenshots or Videos

```
user@desktop> ll
drwxr-xr-x 2 user user   4096  3. Feb 15:00 .
drwxr-xr-x 6 user user   4096  3. Feb 15:00 ..
-rw-r--r-- 1 user user  12345  3. Feb 15:00 bitwarden_export_20210203150000.json
```

### Operating System
Manjaro Linux 20.2.1 Nibia

### Bitwarden
Version 1.23.1
Shell 9.4.1
Renderer 83.0.4103.122
Node 12.14.1
Architecture x64

## Additional Context

KeePassXC saves the encrypted `.kdbx` database with 600 permissions, so I would expect a plain-text file containing my unencrypted passwords to have this permission level too.

**Comment by Greenderella** [comment]
Hi @vonas, permissions are not exported, they can either be manually implemented for each account or with groups: https://bitwarden.com/help/article/how-to-manage-collections/

**Comment by vonas** [comment]
I'm not sure how Linux file permissions relate to in-app collections. Perhaps there is a misunderstanding.

**Comment by cscharf** [comment]
Hi @vonas , it looks like there was a simple misunderstanding. Thanks Alex, this pertains to saving the exported CSV/file to disk with the appropriate permissions on-disk in Linux.

This is something we can look into, thanks Jonas!

**Comment by MGibson1** [comment]
Those two PR I just merged in should correct this. This is a good addition @vonas, thank you!
