### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by ArtexJay** [bitwarden/desktop#71]
I am unable to install bitwarden on window10, it gives out an error stating that I must reconnect to the internet, even though I am connected to the internet and it is fully working
![sdada](https://user-images.githubusercontent.com/32932497/37449564-1cd30dd6-2801-11e8-8003-e60923a7a9a2.PNG)

**Comment by kspearrin** [comment]
Do you have firewalls blocking access to certain endpoints or anything like that?

**Comment by ArtexJay** [comment]
I do not think so, i use the default windows firewall with it's default settings.

**Comment by ArtexJay** [comment]
I ended up downloading the package manually, then there was an update for bitwarden which then properly installed it.

**Comment by kspearrin** [comment]
Thanks for the update. Not sure why it didnt work to begin with.
