### ISSUE TITLE
Share to Collection option missing in Mac desktop client

### ISSUE THREAD

**Issue by tauren** [bitwarden/desktop#712]
## Describe the Bug

Share to collection option is missing in Mac desktop client.

## Steps To Reproduce

1. Right click onto an item
2. Options do not include share

## Expected Result

Share option would be available like in the web client

## Actual Result

No share option

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/282084/107012552-04c40f80-674e-11eb-83af-15fab6bb3b34.png)

## Environment

- Operating system: Mac Big Sur on M1 Mac
- Build Version: 1.24.1 (509)

## Additional Context

There is a comment from 2018 in #156 that says this feature is coming in the next version. I'm assuming the feature landed a while ago, but I don't know for sure since I'm only starting to use Collections now. If this is a feature that hasn't been implemented, then apologies for submitting a feature request. But it seems like it is a bug, possibly a regression.

**Comment by Greenderella** [comment]
Hi @tauren, at the moment on desktop apps it's only possible to share an item into a collection using the **Clone** function. Once this new cloned item has been assigned into the desired collection, the old item can be deleted from your personal vault to avoid any confusion.

**Comment by cscharf** [comment]
You can also share to a collection via the Desktop app by:

1. Edit the item
2. Click the share button at the bottom, next to the delete button
3. Choose which Org + Collection/s you wish to share with (or alter which are shared with)
4. Save

The option is not available via context menu at the moment.

**Comment by tauren** [comment]
Thank you for the workarounds! I was considering upgrading to a Family account specifically for the Organization and sharing features. But only really use the desktop, mobile, and chrome plugins apps and it would be very cumbersome to have to login to the web to maintain collections.

I highly recommend that you make any Premium and Pro features easy to find and use across all apps. Make sure your paying customers have no reason to complain. ;-)
