### ISSUE TITLE
cmd + w doesn't close the window on macOS

### ISSUE THREAD

**Issue by jonohewitt** [bitwarden/desktop#714]
## Describe the Bug

cmd + w doesn't close the window on macOS

## Steps To Reproduce

1. Open Bitwarden
2. Press cmd + w

## Expected Result

The window should close but the application should not quit

## Actual Result

No effect

## Screenshots or Videos

<img width="500" alt="Screenshot 2021-02-06 at 16 51 27" src="https://user-images.githubusercontent.com/47791294/107123025-90978200-689b-11eb-80dd-8d6d715bd6dc.png">

## Environment

- MacOS Big Sur 11.2
- Build Version 1.24.5 (513)

## Additional Context

Appears to have started since adding new settings options in relation to  #419

**Comment by ffeu** [comment]
Hi, just wanted to point that this works in Catalina 10.15.7. So it must be **Big Sur** specific.

**Comment by CarlAndersson** [comment]
Hi, I'm on Catalina 10.15.7 and cmd+w does **not** work for me.
I'm using the same settings as @jonohewitt but otherwise a fresh install of the app.

**Comment by cho-m** [comment]
I commented on a duplicate issue https://github.com/bitwarden/desktop/issues/802#issuecomment-805477418 that there is an implemented behavior difference between DMG (via Brew/homepage) and MAS versions.

Images showing difference in menu options copied from that post:
| DMG Menu | MAS Menu |
|---|---|
| <img alt="dmg-menu" width="282" src="https://user-images.githubusercontent.com/20700669/112254115-45ec8200-8c1d-11eb-969f-372a9e34ef15.png">	| <img alt="mas-menu" width="278" src="https://user-images.githubusercontent.com/20700669/112254242-81874c00-8c1d-11eb-9792-c68d3b0b9ceb.png"> |

The fix may be simply removing the MAS-check, but I am not sure if there is an easy way to locally build/test the MAS version.
Possible diff (for [bitwarden/jslib](https://github.com/bitwarden/jslib)):
```diff
diff --git a/src/electron/baseMenu.ts b/src/electron/baseMenu.ts
index de08e4d..2523e63 100644
--- a/src/electron/baseMenu.ts
+++ b/src/electron/baseMenu.ts
@@ -9,8 +9,6 @@ import {
 import { I18nService } from '../abstractions/i18n.service';
 import { WindowMain } from './window.main';

-import { isMacAppStore } from './utils';
-
 export class BaseMenu {
     protected editMenuItemOptions: MenuItemConstructorOptions;
     protected viewSubMenuItemOptions: MenuItemConstructorOptions[];
@@ -143,7 +141,7 @@ export class BaseMenu {
                 },
                 {
                     label: this.i18nService.t('close'),
-                    role: isMacAppStore() ? 'quit' : 'close',
+                    role: 'close',
                 },
             ];
         }
```

**Comment by cscharf** [comment]
Okay, so funny story @cho-m , that change was implemented back then because Apple originally rejected the app from the app store because it used the `close` action instead of `quit`... it was the original submission review and perhaps we can just assume they put a rookie on the new app review duty or what, but Kyle had to change that in order to get the app approved (which definitely doesn't make any sense).

Either way, we can change it and we're open to it being change back to remove the conditional and just leave it as `close` for the `role` assignment for that menu item. We'll find out one way or the other on MAS store review whether they reject it again for the same reason (which would definitely leave us scratching our heads at this point).

**Comment by kapitainsky** [comment]
quick question - has it been already taken care of? Or you require PR to move it forward?

I have tried no MAS version and it supports both ⌘Q for application and ⌘W for window so based on @cscharf  description it seems like some Apple approver mistake indeed.

**Comment by cscharf** [comment]
> quick question - has it been already taken care of? Or you require PR to move it forward?

It requires a PR, either from the community or when one of our engineers has an opportunity to do so.

**Comment by kapitainsky** [comment]
ta. Will try to create one over Easter then. It is small but annoying bug on macOS.
