### ISSUE TITLE
Windows Version fails to continue slide down page for remaining items in list

### ISSUE THREAD

**Issue by GJB85641** [bitwarden/desktop#726]
## Steps To Reproduce

4. Click on '...'

## Environment

Windows 10, build 21313 rs
Version 1.2.4.6 Shell 6.1.7

**Comment by Hinton** [comment]
Hi @GJB85641, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
