### ISSUE TITLE
syncronization problems on app

### ISSUE THREAD

**Issue by alhandra** [bitwarden/desktop#737]
## Describe the Bug

Summary: If an entry is left selected on the bitwarden windows app, after manual sync, the entry is NOT updated.

Repro:
1 - on the bitwarden windows app the password entry for a site is selected
2 - accessing directly to a site via user and password collected on the app
3 - A password is updated on the site, and the browser bitwarden plugin correctly offers to update it
4 - Manual Sync is issued bitwarden plugin 
5 - manual sync is issued on the windows app 
6 - the entry on the APP is not updated

workaround is select another password entry (example site2) on the windows app and then search for the original entry
I would expect the password to be in sync in both apps.

## Actual Result
Incorrect password is shown on the windows app

## Environment
Windows 10
Edge browser

**Comment by Greenderella** [comment]
Hi @alhandra,

You may just need to manually sync your vault, go to Settings > Sync > SYNC VAULT NOW. If the vault still does not appear to sync, please log out and re-login. 

There are a number of unique factors that can affect the synchronization, from network issues, other extensions, VPN's, Ad-blockers, network configurations among many others. At the moment the multiple extensions and platforms that I've tried sync live as intended, but we will definitely will keep an eye on it!

**Comment by alhandra** [comment]
[repro.pdf](https://github.com/bitwarden/desktop/files/6050676/repro.pdf)

Hi,
issue happens when accessing bitwarden via site.
It's a GUI problem on the windows app.

See details on the pdf I have just attached.

Regards,

**Comment by mmoya** [comment]
I think the same as @c4539 that it's a server problem. I'm affected on Linux as well.

See #647 and bitwarden/browser#1539.
