### ISSUE TITLE
Fix: Convert Mac OS desktop application to ARM-Based application. 

### ISSUE THREAD

**Issue by sivin-git** [bitwarden/desktop#742]
## Describe the issue

Please convert the Mac OS desktop application from Intel-based to an Arm-based application.

<img width="504" alt="Screenshot 2021-03-02 at 9 39 30 AM" src="https://user-images.githubusercontent.com/64252451/109595803-322c8f00-7b3b-11eb-97e3-35fa3c94effb.png">

**Comment by luximus-hunter** [comment]
BitWarden runs on electron. I think its waiting for that to update, but correct me if im wrong

**Comment by cscharf** [comment]
The Electron 11 update is done, next release (🤞🏻  next week) will have it (recently finished regression testing). Full regression is going on this week to include other items for the release as well.... That will version of Electron will support Apple M1 silicone, however we still have to update our build pipeline, etc. which is **_not_** done; but it's on our DevOps roadmap to tackle very soon. In the meantime closing this ticket as we track requests, features and updates like this through the [Bitwarden Community Forums](https://community.bitwarden.com).
