### ISSUE TITLE
desktop app visualization problem

### ISSUE THREAD

**Issue by fearlessfara** [bitwarden/desktop#744]
I think the following image is self-explainatory, there seems to be a visualization problem with the SSO sign-in buttons... maybe the text is simply too long to be contained in the button? (not a big issue, but i think this can be easily fixed). Sorry for the screenshot language (italian), haven't checked if the problem is present in other languages.
By the way I'm using the current latest version of the desktop app.
<img width="1062" alt="Schermata 2021-03-02 alle 17 25 47" src="https://user-images.githubusercontent.com/7695285/109680219-96bc0e00-7b7c-11eb-8759-96ec6775b9af.png">

**Comment by luximus-hunter** [comment]
Its most likely a problem with the Italian language set.

![image](https://user-images.githubusercontent.com/49814847/109778719-71271700-7c05-11eb-8085-166322cf7174.png)

**Comment by cscharf** [comment]
Ah yes, this is a button scale/wrapping issue and has been opened already as bitwarden/clients#2620 . Closing this one as a duplicate, thanks!
