### ISSUE TITLE
macOS 11.2.1 Intel: browser integration enabled in app but can't be enabled in browser 

### ISSUE THREAD

**Issue by Jens-Oldenburg** [bitwarden/desktop#745]
1. Go to 'desktop app / preferences'
2. Check 'Enable browser integration' is enabled
3. Open browser extension
4. Go to 'Options' 
5. Check 'Enable auto-fill on page load' is enabled
4. Go to 'Settings'
5. Click on 'Unlock with biometrics'

## Expected Result
'Unlock with biometrics' can be checked

## Actual Result
cannot set 'Unlock with biometrics', get the message 'Browser integration is not enabled'

## Environment
- Hardware: MacBook Pro 2017 (Intel)
- OS: macOS Big Sur, Version 11.2.1
- Desktop app: Version 1.24.5
- Browser extension: Version 1.48.1
- Browser: Microsoft Edge Version 88.0.705.81
- Browser: Google Chrome Version 89.0.4389.72

## Additional Context
works on my MacBook Air M1 with same OS and browser versions

## Screenshots or Videos
![Extensions 2021-03-03 09-59-53](https://user-images.githubusercontent.com/56303262/109780888-b51b1b80-7c07-11eb-9679-1cb34a1fd600.png)
![Monosnap 2021-03-03 09-53-20](https://user-images.githubusercontent.com/56303262/109780893-b64c4880-7c07-11eb-821f-778a628ec1b6.png)
![About This Mac 2021-03-03 09-38-28](https://user-images.githubusercontent.com/56303262/109780895-b6e4df00-7c07-11eb-9df7-45f7010b89f8.png)
![Chrome-Edge 2021-03-03 09-33-33](https://user-images.githubusercontent.com/56303262/109780899-b77d7580-7c07-11eb-9400-924ede315733.png)
![Bitwarden 2021-03-03 09-32-23](https://user-images.githubusercontent.com/56303262/109780900-b77d7580-7c07-11eb-8c1a-ac70c4bba120.png)

**Comment by sso-bitwarden** [comment]
Hi Jens,

Just want to make sure you install the desktop app from Mac Store.
Could you please try this: 
- Close Chrome
- Toggle the "Enable browser integration" option: Disable it. Close the settings, then enable it again.
- Start chrome and try to enable the biometrics option.

**Comment by Jens-Oldenburg** [comment]
Oh yeah, this way helped:
![Bitwarden-Chrome 2021-03-04 09-03-45](https://user-images.githubusercontent.com/56303262/109931069-a9435e00-7cc8-11eb-9e56-d18c4c94697c.png)

Thank you very much for this quick solution. :-)
