### ISSUE TITLE
Add Login banner doesn't come up for workday sites

### ISSUE THREAD

**Issue by sajid-a** [bitwarden/desktop#753]
I setup an account for a workday site.
I generated a password using BitWarden and created an account. 

However. the banner for add login didn't come up.
And I have setup clear clipboard in 10 seconds option.

So, this means that I have to now do a forgot password, do a password reset and save the password manually.

**Comment by sajid-a** [comment]
Example site: https://tieto.wd3.myworkdayjobs.com/en-US/Tieto_Careers_External_Site/login

**Comment by cscharf** [comment]
Thanks for reporting this issue. This is a known issue that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this post: https://github.com/bitwarden/browser/issues/1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
