### ISSUE TITLE
Linux: Snap variant takes much longer to open than the Flatpak variant

### ISSUE THREAD

**Issue by thatLeaflet** [bitwarden/desktop#754]
## Describe the Bug

On Ubuntu 20.10 running on a Ryzen 5600x and a Samsung SSD, it takes about 7 seconds for the snap variant to open after clicking on it. On Pop!_OS 20.10 running on that same computer, it would take around 1 second for the Flatpak variant to open. (I find this strange because my snap IDE takes less than a second to start loading).

## Steps To Reproduce

1. Download Bitwarden from the store on Ubuntu
2. Wait for it to be finished installing.
3. Opening it for the first time will take a while, and so will all subsequent loadings will take around 7 seconds

## Expected Result

The Bitwarden snap will open quickly, around a second (same speed as Flatpak).

## Actual Result

The Bitwarden Snap takes about 7 seconds to load

## Environment

For the Snap: Ubuntu 20.10 on Ryzen 5600x on Samsung SSD

For Flatpak: Pop!_OS 20.10 on Ryzen 5600x and Samsung SSD

## Additional Context

Has always been the case, not dependent on any sort of system version, would likely occur on previous versions of Ubuntu as well.

**Comment by AI-ien** [comment]
This is not Bitwarden related. Any app opens significantly slower as snap package.

**Comment by clayadams5226** [comment]
Hey @thatLeaflet, as mentioned above, snap package are by their very nature slower to unpack. Additionally, the Flatpak variant isn't maintained by Bitwarden.
