### ISSUE TITLE
App Store Installed Bitwarden Infinite Load Loop On Startup

### ISSUE THREAD

**Issue by koalazub** [bitwarden/desktop#760]
## App Store Installed Bitwarden Infinite Load Loop On Startup

I'm unable to load Bitwarden for MacOS(App Store version). I get a loading screen that conveys a loading screen indefinitely. 

## Steps To Reproduce

1. Go to Bitwarden installed via Mac App Store
2. Click on Installation
3. Finish install 
4. Bitwarden

## Expected Result

Bitwarden to load functionally

## Actual Result

Infinite loop on load

## Screenshots or Videos

https://user-images.githubusercontent.com/7111524/110477641-f3926800-812a-11eb-83d3-996ca0291bf2.mov

## Environment
  System Version:	macOS 11.3 (20E5196f)
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by rcmcsweeney** [comment]
Deleting an old package.json file in the User folder resolved this issue for me.

**Comment by koalazub** [comment]
@rcmcsweeney would it be possible to elaborate on this? Where did you find the User folder?

I thought you meant `Users/`

**Comment by rcmcsweeney** [comment]
In my case, it was in "/Users/Ryan", so drill down one more level from "Users/".

**Comment by koalazub** [comment]
Yeah right. That's really bizarre, but I'll take a look. Thanks again

**Comment by koalazub** [comment]
Ok can confirm. Deleting `package.json` from `Users/<User>` alleviates the infinite load loop issue. I don't think this should be closed as it's still a pertinent issue. 

Thanks @rcmcsweeney for the help

**Comment by gmagno** [comment]
Hey, I'm hitting this very same issue, running on my Linux machine:

```
                   -`                    **@****
                  .o+`                   -----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Inspiron 7560
               `+oooooo:                 Kernel: 5.11.10-hardened1-1-hardened
               -+oooooo+:                Uptime: 1 hour, 24 mins
             `/:-:++oooo+:               Packages: 1185 (pacman)
            `/++++/+++++++:              Shell: bash 5.1.4
           `/++++++++++++++:             Resolution: 2560x1440
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       CPU: Intel i7-7500U (4) @ 2.000GHz
     /ossssssss/        +ssssooo/-       GPU: NVIDIA GeForce 940MX
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel HD Graphics 620
  `+sso+:-`                 `.-/+oso:    Memory: 9322MiB / 15808MiB
 `++:.                           `-/+/
 .`                                 `/


```

Bitwarden version:
```
aur/bitwarden 1.25.1-1 (+69 4.27) (Installed)    Bitwarden Desktop Application
```

I don't see the mentioned `package.json` anywhere in my system, any more tips?
Help would be much appreciated.

**Comment by koalazub** [comment]
I'm not sure where else it could be except for some default location for your applications...

**Comment by gmagno** [comment]
@koalazub no problem mate, thanks for caring.

It seems to be fixed now with a new version of the aur package:
```
aur/bitwarden 1.25.1-2 (+73 7.54) (Installed)
    Bitwarden Desktop Application
```

It's all sorted from my/Linux perspective.

**Comment by koalazub** [comment]
@gmagno no stress. Really glad it somehow resolved itself and cheers for sharing the update on the Linux perspective!
