### ISSUE TITLE
unsaved changes prompt not triggered when user does autoregeneration of a password field

### ISSUE THREAD

**Issue by JCDuclare** [bitwarden/desktop#761]
Normally, when the user tries to leave the edit process of e.g. a login object the desktop app will create a prompt with a warning for unsaved changes. This does not happen if the user triggers an autoregeneration of a password field and then leaves the object.

## Steps To Reproduce

1. Trigger the 'Generate Password' on a field while editing an item
2. Switch to a different item

## Expected Result

'Unsaved Changes' warning is triggered and the user has to confirm to leave and discard the changes

## Actual Result

Changes are instantly lost and the user has been given no warning

## Screenshots or Videos
![h1wBiJMhOL](https://user-images.githubusercontent.com/61692820/110482344-e0f73f00-80e8-11eb-9c3c-7adec7d0e948.gif)

## Environment

- Windows 10 1909 18363.1379
- Bitwarden Version 1.24.6
- Shell 6.1.7
- Renderer 76.0.3809.146
- Node 12.4.0
- Architecture x64

**Comment by gryffs** [comment]
Thanks @JCDuclare for the opened issue, the video was handy. I can replicate this on my mac system as well. My first assumption is that there is an event that triggers when the view is actually edited but in this instance the generate password button does not cause that event to get triggered. I'll look into this issues.

**Comment by eliykat** [comment]
@gryffs This would be a good candidate for a PR if you'd like to tackle it!

**Comment by gryffs** [comment]
This issue is also mentioned here: #563
