### ISSUE TITLE
MacOS accents popup not showing up when the app is locked

### ISSUE THREAD

**Issue by emmanuelvr** [bitwarden/desktop#770]
## Describe the Bug

I use a Mac Mini with the Apple M1 Chip and I use a lot of accents when writing in my native language (Spanish). I use the accent's popup that MacOS offers when you long press a key: 
![image](https://user-images.githubusercontent.com/22592466/110939256-20997300-8303-11eb-8ef7-1320cf475eac.png)

The problem is, I use the Bitwarden desktop app and I noticed that after a while with the app open, that accent's popup won't show up anymore. Right when I open it, it works normally. But after a while, when it's locked and awaiting for my PIN, when I long press a key, it's repeated instead of showing the accents popup. So when trying to write `á`, I get `aaaa2` instead.
It took me a while to figure out it was the Bitwarden desktop app, because it made no sense to me. I thought it had to do with the operating system or my keyboard's settings, but as soon as I fully close the app the keyboard goes back to normal.

I'm not exactly sure of the steps to reproduce the issue but these are the settings I use:
Vault lock wait time: 1 minute
After that time passes, the app is locked and it's unlocked with a PIN.

## Steps To Reproduce

1. Open the Bitwarden Desktop app
2. Set the vault lock wait time to 1 minute
3. Set a PIN
4. Lock the app and wait a few minutes. I couldn't measure how long it takes for it to stop working but you'll be able to notice after a while. Seems to be while the app is locked.

## Expected Result

I expect that I can keep using my accent's popup when writing.

## Actual Result

I end up with the keys being repeated instead of showing the accents when corresponding.

## Screenshots or Videos

It happened to me today and I forgot to record it, but I'll make sure to make it happen again during the day so you can see that the app is open and the popup doesn't show up and how it starts working again when I close it.

## Environment

MacOS Big Sur 11.2.1
Mac Mini with Apple M1 Chip
Bitwarden Versión 1.24.6 (515)

**Comment by emmanuelvr** [comment]
https://user-images.githubusercontent.com/22592466/110968410-7d0d8a00-8325-11eb-87e3-40c9926e18e9.mov

Notice how I click on the Bitwarden app, and close it with "Command + Q" and then the issue is gone. Hope my notes are useful!

**Comment by vpiryns** [comment]
Had the same issue today, was forced to set Bitwarden locking on restart so I can have my popup. Not really safe...

**Comment by emmanuelvr** [comment]
Interesting, I didn't know that that would solve it. I guess I can make sure it's closed when I'm away from the computer. You're right though, it's not really safe, I love the immediate lock. Thanks for your comment!

**Comment by thomaspoignant** [comment]
FYI, I have the exact same problem with a macbook Intel

**Comment by emmanuelvr** [comment]
I noticed it also happens with the Safari extension enabled and locked. I had to uninstall it from Safari. It works ok on Microsoft Edge, Google Chrome and Brave

**Comment by joshbuckley182** [comment]
Looks like it might be related to https://github.com/bitwarden/desktop/issues/738#issuecomment-832762876

**Comment by emmanuelvr** [comment]
I checked out the updates to the issue linked above by @joshbuckley182 and noticed that there was a PR merged to solve a similar issue and I think that it was already deployed, but I have the latest version 1.27.1 (531) and my issue is still happening.

**Comment by eliykat** [comment]
Unfortunately PR #970 didn't make this release, it'll be in the next release. I assume the most recent commenter on that PR is building from source.

That said, I'll ask our QA team to confirm that #970 solved this issue as well, so that we're not waiting until the next release to find out otherwise.

**Comment by eliykat** [comment]
Update: we've confirmed that #970 solves this issue.

**Comment by emmanuelvr** [comment]
Thank you for confirming @eliykat, have a nice week!
