### ISSUE TITLE
Bitwarden portable 1.25.0 for Windows -> not starting

### ISSUE THREAD

**Issue by cybermcm** [bitwarden/desktop#771]
## Describe the Bug

Bitwarden-Portable-1.25.0.exe doesn't start on Windows.
Tried a clean start without existing data, exe starts (taskmanager) and closes. No error message, no log file

## Steps To Reproduce

start portable exe file

## Expected Result

programm starts

## Actual Result

nothing, programm doesn't start

## Screenshots or Videos

nothing available

## Environment

Microsoft Windows [Version 10.0.19042.867], latest updates
Bitwarden-Portable-1.25.0.exe

## Additional Context

also reported in the community forum

**Comment by Scoty43** [comment]
I have the same issues. No start, no error.

**Comment by ozzii** [comment]
I have the same issues. No start, no error.

**Comment by zaonie** [comment]
Same issues.  No start, no error.

**Comment by cscharf** [comment]
We're currently looking into this. Thanks!

**Comment by cybermcm** [comment]
just tested 1.25.1 -> working again
thx
