### ISSUE TITLE
safari crashes when Bitwarden extension running and you cmd+c 

### ISSUE THREAD

**Issue by williammueller** [bitwarden/desktop#774]
## Describe the Bug

When Bitwarden extension is installed and you cmd+c safari crashes.

## Steps To Reproduce

cmd+c on any site with Bitwarden extension running in safari and vault unlocked 

## Environment

MacOS 11.2.3
Safari 14.0.3
Bitwarden version 1.25.0

**Comment by Hinton** [comment]
Hi @williammueller,

Would you mind posting the crash log? It should automatically appear shortly after safari crashes and they can also be manually access using the console, https://support.apple.com/guide/console/reports-cnsl664be99a/mac.

Also are you using a Intel or M1 mac?

Thanks.

**Comment by Clickbaitcake** [comment]
This seems very similar to this bug: https://github.com/bitwarden/desktop/issues/887

**Comment by Clickbaitcake** [comment]
> Hi @williammueller,
> 
> Would you mind posting the crash report? It should automatically appear shortly after safari crashes and they can also be manually access using the console, https://support.apple.com/guide/console/reports-cnsl664be99a/mac.
> 
> Also are you using a Intel or M1 mac?
> 
> Thanks.

Please see https://github.com/bitwarden/desktop/issues/887 for similar

**Comment by Hinton** [comment]
@williammueller Going to close this as my hope is the Safari 14.1 release has fixed the issue. If it still persists even after updating to macOS 11.3 feel free to reopen the issue with some additional information.
