### ISSUE TITLE
French localisation string error

### ISSUE THREAD

**Issue by Hermocrates** [bitwarden/desktop#775]
## Describe the bug

in the file `resources/app.asar` there is a localisation error in a string.
From line 67199, the sentence should be:
```
Un indice de mot de passe maÃ®tre peut vous aider Ã  vous rappeler votre mot de passe en cas d'oubli."
```
It is the only correct french syntax.

## Expected result
```
  "masterPassHintDesc": {
    "message": "Un indice de mot de passe maÃ®tre peut vous aider Ã  vous rappeler votre mot de passe en cas d'oubli."
  },
```
## Actual result
```
  "masterPassHintDesc": {
    "message": "Un indice de mot de passe maÃ®tre peut vous aider Ã  vous rappeler de votre mot de passe en cas d'oubli."
  },
```

## Environment

- Operating system: GNU/Linux Ubuntu 20.04
- Build Version 1.25.0

**Comment by tgreer-bw** [comment]
Thanks for reporting this!

You can make changes directly via our Crowdin project here:

https://crowdin.com/project/bitwarden-desktop
