### ISSUE TITLE
1.25.0 breaks Safari Extension for macOS Catalina

### ISSUE THREAD

**Issue by eduardomarossi** [bitwarden/desktop#776]
## Describe the Bug

Updated to 1.25.0 and Bitwarden Extension stopped working on Safari.
Tried clean reinstall of Bitwarden, but still nothing.
Downgraded to 1.24.6 and Extension is working again.

## Steps To Reproduce

1. Update to 1.25.0 on Catalina
2. Try to use Bitwarden Extension on Safari

## Expected Result

Being able to use Bitwarden on Safari

## Actual Result

Bitwarden is missing on Safari, missing on Extension Panel on Settings.

## Environment

- Operating system: Mac OS Catalina
- Build Version (go to "Settings" → "About"): 10.15.6

**Comment by tadinski** [comment]
Same on BigSur 11.2
Safari Version 14.0.3
Apple Silicon

**Comment by AronDerenyi** [comment]
I have the same issue here: https://github.com/bitwarden/browser/issues/1696

**Comment by macemmek** [comment]
Same on High Sierra 10.13.6
Safari Version 13.1.2

**Comment by abuchanan920** [comment]
Same here on Catalina
 I can confirm that I removed the brew version and re-installed the one from the App Store, but I still don't get the extension back.

**Comment by SkulduggeryOne** [comment]
Here too. Catalina 10.15.7
Safari 14.03.
The extension has disappeared and no longer appears in the Safari extensions.
Update please!!!

**Comment by cpaschold** [comment]
Bitwarden Extension (1.49.0) still here but constantly crashing Safari.
I'm on BigSur 11.2.3, Safari 14.0.3, Apple Silicon

**Comment by keiwando** [comment]
I am also experiencing this issue with
macOS 10.14.4 and 10.15.6
Safari 12.1 and 13.1.2

(Not experiencing crashes but the extension is gone - even after a clean install from the App store)

**Comment by eduardomarossi** [comment]
Upgraded to Safari 14+ and sure enough, it's working again as intended.

Thank you @Hinton . 

Should I close this issue?

**Comment by Hinton** [comment]
@eduardomarossi Please do, we have a couple of other issues tracking this.

**Comment by eduardomarossi** [comment]
Thanks!
