### ISSUE TITLE
Favicons don't show up when specifying custom server "https://vault.bitwarden.com"

### ISSUE THREAD

**Issue by zipsonic** [bitwarden/desktop#777]
## Describe the Bug

Website Favicons do not show up when specifying that the custom server is https://vault.bitwarden.com

## Steps To Reproduce

1. Click File > Lock Now > Log Out. Click Log Out when asked to verify.
2. Click the Gear icon on top left.
3. Type https://vault.bitwarden.com in the "Server URL" box.
4. Click the Floppy Disk Save button
5. Login with bitwarden login information.

## Expected Result

Website Favicons should show next to saved accounts.

## Actual Result

Generic Globes show next to every saved account.

## Environment

- Operating system: Windows 10
- Build Version (go to "Settings" → "About"): 1.25.0

## Additional Context

This really isn't a big deal, but could be an indicator of another problem. This was found when I migrated from a hosted bitwarden server to premium membership on bitwarden.com. I'd only ever had a custom server URL on the desktop app, so I thought I had to put the vault.bitwarden.com information in there. I don't remember if it was ever there before. I have found that if I remove the custom server URL entirely, it will logon fine and the favicons return. I just think this could be an indicator of another underlying problem and thought I should share.

**Comment by djsmith85** [comment]
@zipsonic This is just due how icons are retrieved using self-hosted vs cloud. For self-hosted the icon-service is reachable via `https://someserver.tld/icons` and for cloud it is accessed via `https://icons.bitwarden.net`.

Closing now as no issues here.
