### ISSUE TITLE
Bitwarden 1.25.0 breaks biometrics in Chrome & Brave browser extensions in MacOS Catalina

### ISSUE THREAD

**Issue by kenbolton** [bitwarden/desktop#782]
## Describe the Bug

Upgraded through the App Store to Bitwarden.app 1.25.0 running Mac OS Catalina 10.15.7. Previous version browser extensions in Chrome and Brave worked with biometrics. New version, the browser extensions ask for the already running app to be running. Have reinstalled both app and all extensions. Still no love.

## Steps To Reproduce

1. Upgrade to Bitwarden 1.25.0 in MacOS Catalina from the App Store
2. Enable biometrics in Bitwarden.app
3. Toggle the "Unlock with biometrics" checkbox in the browser extension version 1.49.0
4. Be told to start Bitwarden.app

## Expected Result

With Bitwarden.app running, previous version permitted biometrics.

## Actual Result

No love!

## Environment

- Operating system:  Mac OS Catalina
- Build Version (go to "Settings" → "About"): 1.25.0

**Comment by mahoneylarry** [comment]
+1.
I have the exact same behavior.  Same Bitwarden version and MacOS Catalina also.

**Comment by Nelluk** [comment]
I've never been able to get browser integration working since the feature release in January and have assumed there was some known bug that would get fixed soon.
- Remove Bitwarden Chrome extension
- Open BitWarden Mac App Store app. Enable browser integration
- Install Chrome Extension
- Enable File URLs (previously mentioned as a possible fix)
- Click Unlock with Biometrics in the plugin settings

The first time I do this after a new plugin installation it asks for permissions, which I grant. When I go back in to check, the checkbox is still blank. Now when I check it, it says "Browser integration not enabled".

**Comment by Hinton** [comment]
@kenbolton would you mind verifying that the file `~/Library/ApplicationSupport/Google/Chr
ome/NativeMessagingHosts/com.8bit.bitwarden.json` exists?
And also paste the content of it?

Additionally could you screenshot your extension page in Chrome and Brave? I'm interested in the ID of the bitwarden extension.
Example:
<img width="405" alt="Screenshot 2021-03-18 at 19 23 07" src="https://user-images.githubusercontent.com/137855/111677576-a3e52800-881f-11eb-8112-3db366c1328c.png">

**Comment by kenbolton** [comment]
> @kenbolton would you mind verifying that the file `~/Library/ApplicationSupport/Google/Chrome/NativeMessagingHosts/com.8bit.bitwarden.json` exists?

Exists!

> And also paste the content of it?
```
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "/Applications/Bitwarden.app/Contents/MacOS/Bitwarden",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://nngceckbapebfimnlniiiahkandclblb/",
    "chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/",
    "chrome-extension://ccnckbpmaceehanjmeomladnmlffdjgn/"
  ]
}
```

> Additionally could you screenshot your extension page in Chrome and Brave? I'm interested in the ID of the bitwarden extension.

<img width="398" alt="Screen Shot 2021-03-18 at 14 48 56" src="https://user-images.githubusercontent.com/28277/111680947-21497200-87f9-11eb-8528-9e25bc945aa9.png">

**Comment by Hinton** [comment]
Hmm, everything looks good.

@kenbolton If you are willing to assist a bit further, could you close Chrome and start it using the following command in the terminal: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging -vvv`.
Then try and and enable biometrics. And paste the output from the terminal afterwards. Hopefully that should give me a hint of what might be going on.

**Comment by kenbolton** [comment]
```
~ ❯❯❯ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging -vvv
Service path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + id
requested connection to  bitwarden /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
Connecting client on Unix Socket : /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden


######
error:  Error: connect ENOENT /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden'
}
error Error: connect ENOENT /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden'
}
connection closed bitwarden /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden Infinity tries remaining of Infinity
disconnected from world
<Buffer >
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt32LE (internal/buffer.js:211:5)
    at processData (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:20196:46)
    at Socket.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:20228:17)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at onEofChunk (_stream_readable.js:533:5)
    at readableAddChunk (_stream_readable.js:251:5)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:229:12) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
requested connection to  bitwarden /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
Connecting client on Unix Socket : /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden


######
error:  Error: connect ENOENT /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden'
}
error Error: connect ENOENT /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden'
}
connection closed bitwarden /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden Infinity tries remaining of Infinity
disconnected from world
[71058:775:0318/151249.131718:ERROR:event_router.cc(714)] Event dispatched while shutting down extensions browser client.
[71058:775:0318/151249.132055:ERROR:event_router.cc(714)] Event dispatched while shutting down extensions browser client.
```

**Comment by Hinton** [comment]
@kenbolton Seems like it can't connect to the desktop application (as expected).

Could you do a final test by starting the Bitwarden desktop application (close any currently running before) using `/Applications/Bitwarden.app/Contents/MacOS/Bitwarden` from the terminal, then try and unlock from Chrome and paste the terminal output.

**Comment by kenbolton** [comment]
Happy to keep helping.

```
~ ❯❯❯ /Applications/Bitwarden.app/Contents/MacOS/Bitwarden
(node:74771) DeprecationWarning: file property is deprecated and will be removed in v5.
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
(node:74771) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
starting server on  /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
starting TLS server false
starting server as Unix || Windows Socket
server error Error: listen EACCES: permission denied /Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1458:5)
    at Server.startServer (/Applications/Bitwarden.app/Contents/Resources/app.asar/node_modules/node-ipc/dao/socketServer.js:311:21)
    at FSReqCallback.oncomplete (fs.js:160:23) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden',
  port: -1
}
```

**Comment by Hinton** [comment]
Hmm, interesting. @kenbolton could you check if there is a file at `/Users/ken/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden` and attempt to delete it before restarting the desktop application (with terminal and check if the error is gone)

**Comment by kenbolton** [comment]
@Hinton: There is no `tmp` folder in `Data`. 

```
~/L/C/c/Data ❯❯❯ ls -lath
total 0
drwx------+  5 ken  staff   160B Mar 18 15:14 ..
drwx------+ 10 ken  staff   320B Mar 13 00:22 .
drwx------+ 30 ken  staff   960B Mar  1 16:45 Library
drwx------+  3 ken  staff    96B Mar  1 16:45 Documents
lrwxr-xr-x   1 ken  staff    19B Mar  1 16:45 Desktop -> ../../../../Desktop
lrwxr-xr-x   1 ken  staff    21B Mar  1 16:45 Downloads -> ../../../../Downloads
lrwxr-xr-x   1 ken  staff    20B Mar  1 16:45 Pictures -> ../../../../Pictures
lrwxr-xr-x   1 ken  staff    17B Mar  1 16:45 Music -> ../../../../Music
lrwxr-xr-x   1 ken  staff    18B Mar  1 16:45 Movies -> ../../../../Movies
lrwxr-xr-x   1 ken  staff    31B Mar  1 16:45 .CFUserTextEncoding -> ../../../../.CFUserTextEncoding
```

Deleted the `Data` folder, restarted Bitwarden.app, still no `tmp` directory.

**Comment by Hinton** [comment]
@kenbolton Could you try to create a tmp folder?

**Comment by BeyondEvil** [comment]
Just installed 1.25.1 (518) and had to manually create the `tmp` directory to get Biotmetrics working.
