### ISSUE TITLE
Windows application unresponsive on startup

### ISSUE THREAD

**Issue by Teun-Bond3D** [bitwarden/desktop#794]
## Describe the Bug
Desktop application starts on Windows startup, but is unresponsive. All menus, search bars, buttons are not responding when clicked.

## Steps To Reproduce
- Restart PC
- Login to windows user account.

## Expected Result
- Application should be started on the background (only icon in system tray)
- After showing the application all UI elements should be responsive

## Actual Result
- Application window is visible on startup
- UI elements are unresponsive
- Closing the application and restarting it usually helps.

## Screenshots or Videos
NA

## Environment
- Operating system: Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version (go to "Settings" → "About"): Version 1.25.0
  - Shell 11.1.1
  - Renderer 87.0.4280.88
  - Node 12.18.3
  -Architecture x64
- Possibly relevant settings:
![image](https://user-images.githubusercontent.com/63105550/111590317-3d7feb80-87c6-11eb-8249-636ad272d097.png)

- Version of the edge browser extension (might be relevant as I use biometrics for login):
![image](https://user-images.githubusercontent.com/63105550/111590419-5dafaa80-87c6-11eb-9ab2-d41590e0e34a.png)

## Additional Context
NA

**Comment by cscharf** [comment]
Hi @Teun-Bond3D , please try updating to version 1.25.1 which should resolve this issue and let us know.

**Comment by Teun-Bond3D** [comment]
Ok, seems to work now. I will close the issue and reopen if necessary.
