### ISSUE TITLE
LastPass import did not import TOTP seeds

### ISSUE THREAD

**Issue by MarkAtwood** [bitwarden/desktop#795]
<
## Describe the Bug

The LastPass Authenticator does OATH TOTP, kept in sync via a customer's lastpass account.  The lastpass dump and import to BitWardden did not bring in the OATH data for verification codes.

## Steps To Reproduce

1. Setup a Lastpass account
2. Install Lastpass authenticator mobile app
3. Setup a TOTP verification code entry in the authenticator
4. Link the Lastpass authenticator to the lastpass account
5. Do a Lastpass data export
6. Import the Lastpass data into bitwarden
7. The verification code is not filled in for the account corresponding to the TOTP entry in Lastpass.

## Expected Result

The OATH TOTP verification codes should be configured if they were configured in LastPass and LastPass Authenticator.

## Actual Result

The OATH TOTP verification codes that were configured in LastPass and LastPass Authenticator do not .

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by cscharf** [comment]
Hi @MarkAtwood , thank you for the report! I don't see that we have a mapping currently for LP's TOTP seed values on import, are those included in the export? If so, could you please provide an example (redacted) row(s) from that export file by chance? I have an ask out to the team internally to try to get something scoped out but figured you may have the info more readily available.
