### ISSUE TITLE
Browser integration/Biometric not working (Chrome/MacOS)

### ISSUE THREAD

**Issue by Nelluk** [bitwarden/desktop#797]
I have never been able to get the browser integration between the Chrome plugin and the desktop app working.

## Environment

Mac App Store version 1.25.0
Plugin version 1.49.1
Chrome version 90.0.4430.19 (beta channel)
MacOS 11.2.1 (Big Sur)

## Steps to Reproduce

- Log in to desktop app
- Click "enable browser integration" in settings
- Install fresh copy of plugin from Chrome store and log in
- (optionally, enable 'Allow Access to File URLs' from extension options. Doesn't make a difference either way but has been mentioned before as a fix for similar issues)
- Settings > Unlock with Biometrics
- Click 'allow' on permissions popup:

![image](https://user-images.githubusercontent.com/2545428/111700186-6d071600-880f-11eb-904e-4bcfca547154.png)

- Open extension, which now requires logging in again
- Go to settings. Unlock with biometrics has reverted to unchecked. 
- Check box
- Get presented with *Browser integration is not enabled* error

![image](https://user-images.githubusercontent.com/2545428/111700300-9627a680-880f-11eb-9c05-9c5b651a9326.png)

**Comment by tgreer-bw** [comment]
Make sure "access file urls" is enabled in the extension permissions as well.

**Comment by Nelluk** [comment]
> Make sure "access file urls" is enabled in the extension permissions as well.

I've tried it both ways, with that option enabled multiple times. Doesn't seem to make a difference.

**Comment by ToGitOrNotToGit** [comment]
Same in Brave with + w/o 'access file urls' enabled.

(After fingerprint phrase validation)
WITH Enable browser integration _enabled_

Bitwarden extension in Brave says,
"Biometrics not enabled
Browser biometrics requires desktop biometric to be enabled in the settings first.
Ok”

AND

Bitwarden app store app says,
"Biometrics not enabled
Browser biometrics requires desktop biometrics to be enabled in the settings first.
Cancel”

Brave Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)
Bitwarden macOS Version 1.25.0 (516)

**Comment by Hinton** [comment]
I've opened a PR which should fix this issue.

In the meantime manually creating the `tmp` directory inside `~/Library/Containers/com.bitwarden.desktop/Data` should resolve the issue.

**Comment by Nelluk** [comment]
> I've opened a PR which should fix this issue.
> 
> In the meantime manually creating the `tmp` directory inside `~/Library/Containers/com.bitwarden.desktop/Data` should resolve the issue.

It doesn't - I was monitoring that issue from the prior day because I assumed it was related to my issue, so I tried that solution during one of my attempts. `Data/tmp` exists.

**Comment by Hinton** [comment]
@Nelluk would you be willing to do the same troubleshooting steps as in the other issue?

- Copy of `com.8bit.bitwarden.json` and screenshot of extension page, https://github.com/bitwarden/desktop/issues/782#issuecomment-802184707 
- Chrome logs https://github.com/bitwarden/desktop/issues/782#issuecomment-802207924
- Desktop logs https://github.com/bitwarden/desktop/issues/782#issuecomment-802228463

**Comment by Nelluk** [comment]
@Hinton 
`~/Library/ApplicationSupport/Google/Chrome Beta/NativeMessagingHosts/com.8bit.bitwarden.json` does **not** exist (I assume Chrome Beta is the relevant directory, although I also checked Chrome)

At this point I switched my testing to Chrome standard release track (89.0.4389.90). Installed the extension, logged in, enabled secure file URLs, logged in again.

Now `~/Library/ApplicationSupport/Google/Chrome/NativeMessagingHosts/com.8bit.bitwarden.json` does exist, with contents:

```
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "/Applications/Bitwarden.app/Contents/MacOS/Bitwarden",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://nngceckbapebfimnlniiiahkandclblb/",
    "chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/",
    "chrome-extension://ccnckbpmaceehanjmeomladnmlffdjgn/"
  ]
}
```

Now the flow still fails, but in a different way. 

First I get a notice that the desktop app is blocking the request:

![image](https://user-images.githubusercontent.com/2545428/111881951-4b319e80-8989-11eb-8ea8-1c3367f65368.png)

When I go to the desktop app I am told that browser integration is disabled:

![image](https://user-images.githubusercontent.com/2545428/111881966-5b497e00-8989-11eb-88fb-1ea88bf19080.png)

But it is enabled:

![image](https://user-images.githubusercontent.com/2545428/111881976-63a1b900-8989-11eb-9351-e8de2765f93a.png)


I've tried disabling it, closing the settings, then re-enabling it, but it makes no difference.

Chrome logs:

```
dispatching event to  bitwarden /Users/cbsteven/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden  :  message , {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    command: 'setupEncryption',
    publicKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9i/dGFLyMtCemhCRo8Y+Ypk/5xLdEiYSFa7xgBO9NQW1q+7gStKUPonoCOYbjNmLt4uUidwrLVxtINgjAhH4B6kgSfgX1ry3i5nEG3ZwytJW+f8unEJ1/KVcPewyGOKhDyhlPavsKnesGdtYJLY4/p9l/mIyjIaUDH3AJU91ASkeRWcBO1Q2dFCgQuKEFscgforZmmhagHaAXgdyg+VtDyTJXqB/HYSF8tl69LoShSpYXSP5gmEkEebieqvV5EnyqMY0OIzgsn/4iLCRyKhhJJwQzEKPqKezOA6hbMh+HQ8Jav1HBtQyGUEDN7ThkgIPd2Bkzpe7+MLmDmCWNpn+QIDAQAB',
    userId: '552ab762-94e1-4bde-80b1-acb400e44771',
    timestamp: 1616265411066
  }
}
## received events ##
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  command: 'setupEncryption',
  sharedSecret: 'hjhBE2S5ZZs847ZBPSVq0CDhyQGK5DVlGfMcqCiegf+fH7uoMcSYVX+tyY1gxA2TL+2ZqM8uoLdlfalyoYOxM/a3at2zsuWHqzOAO0IrQF7JnesPkFbGBUpiDjy0KiK1GfGb5Lu6ld0NJcPrHWgUhU7hG21NKP1jF1EOWJYbCRAgT45U/xNJKhhYra/xbg2HrcJthG628Vu8vkaPerYvh4baRoF+Z+BNDvNr1niqUApLIwZJPPNqTWY66AVSavHYVuSQKtkasNkXTFLvyO0Yd/vGi37T7yTiJ7GfsSpyByKkHkqI08LwnfhGPZVuqWMVaoQ2iEM3+VIidHvWn3cmUA=='
}
## received events ##
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  command: 'setupEncryption',
  sharedSecret: 'hjhBE2S5ZZs847ZBPSVq0CDhyQGK5DVlGfMcqCiegf+fH7uoMcSYVX+tyY1gxA2TL+2ZqM8uoLdlfalyoYOxM/a3at2zsuWHqzOAO0IrQF7JnesPkFbGBUpiDjy0KiK1GfGb5Lu6ld0NJcPrHWgUhU7hG21NKP1jF1EOWJYbCRAgT45U/xNJKhhYra/xbg2HrcJthG628Vu8vkaPerYvh4baRoF+Z+BNDvNr1niqUApLIwZJPPNqTWY66AVSavHYVuSQKtkasNkXTFLvyO0Yd/vGi37T7yTiJ7GfsSpyByKkHkqI08LwnfhGPZVuqWMVaoQ2iEM3+VIidHvWn3cmUA=='
}
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  command: 'setupEncryption',
  sharedSecret: 'hjhBE2S5ZZs847ZBPSVq0CDhyQGK5DVlGfMcqCiegf+fH7uoMcSYVX+tyY1gxA2TL+2ZqM8uoLdlfalyoYOxM/a3at2zsuWHqzOAO0IrQF7JnesPkFbGBUpiDjy0KiK1GfGb5Lu6ld0NJcPrHWgUhU7hG21NKP1jF1EOWJYbCRAgT45U/xNJKhhYra/xbg2HrcJthG628Vu8vkaPerYvh4baRoF+Z+BNDvNr1niqUApLIwZJPPNqTWY66AVSavHYVuSQKtkasNkXTFLvyO0Yd/vGi37T7yTiJ7GfsSpyByKkHkqI08LwnfhGPZVuqWMVaoQ2iEM3+VIidHvWn3cmUA=='
}
<Buffer bb 01 00 00 7b 22 61 70 70 49 64 22 3a 22 64 35 39 64 35 38 31 66 2d 32 35 34 64 2d 34 36 62 39 2d 38 61 61 61 2d 32 63 66 39 66 30 31 34 35 61 35 34 ... 397 more bytes>
dispatching event to  bitwarden /Users/cbsteven/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden  :  message , {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.INyGEfyh6IIWh2jpdxAREg==|YAjRAUlDQZonFiY5Nxcavtmsw8tg5G/j5jJHxE4visVI5I7I0gtO4xAr/EV6A0uwD4eC551vTzouYhfM6jfxEQ==|ryZWqPqgPYjDuNro8a9VpiJPvudn0GlSnpfcpw9MB9M=',
    encryptionType: 2,
    data: 'YAjRAUlDQZonFiY5Nxcavtmsw8tg5G/j5jJHxE4visVI5I7I0gtO4xAr/EV6A0uwD4eC551vTzouYhfM6jfxEQ==',
    iv: 'INyGEfyh6IIWh2jpdxAREg==',
    mac: 'ryZWqPqgPYjDuNro8a9VpiJPvudn0GlSnpfcpw9MB9M='
  }
}
## received events ##
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.x8fNgDlfUXO3o0yjPtzA6w==|htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz|UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc=',
    encryptionType: 2,
    data: 'htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz',
    iv: 'x8fNgDlfUXO3o0yjPtzA6w==',
    mac: 'UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc='
  }
}
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.x8fNgDlfUXO3o0yjPtzA6w==|htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz|UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc=',
    encryptionType: 2,
    data: 'htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz',
    iv: 'x8fNgDlfUXO3o0yjPtzA6w==',
    mac: 'UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc='
  }
}
## received events ##
detected event message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.x8fNgDlfUXO3o0yjPtzA6w==|htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz|UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc=',
    encryptionType: 2,
    data: 'htnEgsM29luNh4gKsttxEp0y3KGj64tvnhEOrF964BUGWfbp20APiUaZRicUnS5YMI/QRRgQuINACXE5tYFnL/hUtJB0umUrWK8aLg/nQ/+1CQB6zPW4poR5y/3wa1Cz',
    iv: 'x8fNgDlfUXO3o0yjPtzA6w==',
    mac: 'UkIja8eb3ueDQqt2+j2Po3lmd4SSsYYU6Cx84fJQxgc='
  }
}

```

on the BitWarden side:

```
/Applications/Bitwarden.app/Contents/MacOS/Bitwarden
(node:21520) DeprecationWarning: file property is deprecated and will be removed in v5.
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /Users/cbsteven/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden
(node:21520) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
starting server on  /Users/cbsteven/Library/Containers/com.bitwarden.desktop/Data/tmp/app.bitwarden 
starting TLS server false
starting server as Unix || Windows Socket
## socket connection to server detected ##
received event of :  message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    command: 'setupEncryption',
    publicKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsEjFLP0ysty6es4i6HjQifixrr6BftO0pKUqVbTRo14UKOn30HWXUXyFiliqsXeClqLRbHIZCxEtDHLBlaqiWc7me3v7MM4ZIdA55sdQV9A3GVExiHOb74FQaFKlh2zKfCA4CjFxix07e0vOI47YBXXployLdapv0IX4KqSFyDLvni7wtFmqnLlibWK3GCfZbMwsNBQ/SlhbCsw0CkfPu2RQCSbKx3wvTcCxWjj3pzVjTIofUioeTQR8Vh0JPYKhJgWrc1eACzUqOUwx7O7K1Lw/f3ncTWoYC+9wxDDz0T5SCoLgqablQOiWeTW3/BNPNgCPetAG6ukXK72+Krud8wIDAQAB',
    userId: '552ab762-94e1-4bde-80b1-acb400e44771',
    timestamp: 1616265535548
  }
}
dispatching event to socket  :  message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  command: 'setupEncryption',
  sharedSecret: 'pLemCBG4DsMvFBXS7KdxjZ+ko6jeUe7dlR7SiGtPK1jqyNnHkkV9yCU5mWVJJIBlCDBAdd72ciK5biVcjwPeBViIhY7mHecXF8hA2umD1DCmqgSpNCua9uQ6ksaMcup3CaaTszHBQeF0Oj3tqmsTm6JhP4Vddawyc2oNDt7QjZKN6gAK5nq82I+k8Xur4nUBNdOJSYmPXDtA3EVkPWid5WDGByZ4KK7kaAqr+yyUH8A4sxkTjDlff6FxLrAsG9LU4CHPbF0EfO1UFyRQiiQH5LASIjUS93KN25t5koSBk4i4cnzg6XTwrgGcwWARW9RCmPXrGz/mDXtKCAAhCkhNIQ=='
}
received event of :  message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.CU+kzF4+pnM7xkV5JMdZuQ==|XZcUb02RF0dFIfyZpQ3Zz4xE/iLNxVdLUoM+RolBUp6REz8JCD8/miZHV8O0rzSZfiLrXUfmfEGFGh8zWkSSlw==|oMeS/0Z1byFQp+m53KYZYu1xhMUpwVxRfXXex6RX93w=',
    encryptionType: 2,
    data: 'XZcUb02RF0dFIfyZpQ3Zz4xE/iLNxVdLUoM+RolBUp6REz8JCD8/miZHV8O0rzSZfiLrXUfmfEGFGh8zWkSSlw==',
    iv: 'CU+kzF4+pnM7xkV5JMdZuQ==',
    mac: 'oMeS/0Z1byFQp+m53KYZYu1xhMUpwVxRfXXex6RX93w='
  }
}
dispatching event to socket  :  message {
  appId: 'd59d581f-254d-46b9-8aaa-2cf9f0145a54',
  message: {
    encryptedString: '2.lRViLRQG/ZYEmsBAAzW1Zg==|tBBe8t6PwPXoiGW9tMuDMnEXIEAZFP6vBxuEq/NJxJw47KfONsat0LV9QgzI8NqMkCTYhFxdY5m3d/xRHN2GZovRDadt/oiJTMh4vQc/LXGFDx+AzDqVKm+LuEKARXPh|iasw/dTRhxtVTkijrj7YW3XU19bqN8bM30q/JIe9e0Q=',
    encryptionType: 2,
    data: 'tBBe8t6PwPXoiGW9tMuDMnEXIEAZFP6vBxuEq/NJxJw47KfONsat0LV9QgzI8NqMkCTYhFxdY5m3d/xRHN2GZovRDadt/oiJTMh4vQc/LXGFDx+AzDqVKm+LuEKARXPh',
    iv: 'lRViLRQG/ZYEmsBAAzW1Zg==',
    mac: 'iasw/dTRhxtVTkijrj7YW3XU19bqN8bM30q/JIe9e0Q='
  }
}

```


Let me know if you want separate logs of the failure with Chrome Beta, which seems like a different type of failure since that json file does not get created.

**Comment by Hinton** [comment]
@Nelluk My apologies, I missed that you are using Chrome Beta. That would explain why things weren't working correctly.

The error message you got while using regular Chrome is due to `Touch ID` not being enabled in the desktop application.
![image](https://user-images.githubusercontent.com/137855/111890274-27ea0c00-89e8-11eb-8d43-0867483a8d02.png)

Toggling that should get regular Chrome working, since the logs indicate they can successfully communicate with each other.

Getting Chrome Beta working should also be relatively simple, but requires that you manually copy the `~/Library/ApplicationSupport/Google/Chrome/NativeMessagingHosts/com.8bit.bitwarden.json` file to `~/Library/ApplicationSupport/Google/Chrome Beta/NativeMessagingHosts/com.8bit.bitwarden.json`.

Let me know if this solves it.

**Comment by Nelluk** [comment]
That did the trick on both counts. Thanks!
