### ISSUE TITLE
Small program icon not shown in W10 taskbar

### ISSUE THREAD

**Issue by jeroenslemmer** [bitwarden/desktop#799]
## Describe the Bug
Small program icon is not shown in W10 taskbar for the running or pinned Bitwarden program. In stead a 'blank page' icon is shown in the taskbar. If the taskbar is set to show normal program icons, the Bitwarden icon is shown. Happened after update to version 1.25.1

## Steps To Reproduce

1. Update executable to **Version 1.25.1**
2. Set the taskbar small icons to **on**
3. Start the Bitwarden app from de W10 Start 
4. Pin the Bitwarden app to the taskbar

## Expected Result
The normal Bitwarden (blue-white shield) icon should show up at the taskbar

## Actual Result
A 'blank page' icon is showing at the the taskbar.

## Screenshots or Videos
![2021-03-19 08_55_29-](https://user-images.githubusercontent.com/6870547/111802777-ace10280-88ce-11eb-8f2a-00398122a530.png)

## Environment

- Operating system: Windows 10
- Installation method: Update from download at https://bitwarden.com/download/
- Build Version (go to "Settings" → "About"): 1.25.1

**Comment by o-l-a-v** [comment]
I have what I think is a related problem. I've pinned BitWarden to taskbar. When I open BitWarden, all is good. When I close BitWarden, after some seconds the icon itself disappears, leaving a transparent tile. If I open BitWarden again, the icon comes back. But now BitWarden has been unpinned from the taskbar. So when I close BitWarden again, the icon disappear.

* Windows 10 20H2 on a Dell XPS 15 7590, running 2x external monitors Dell U2412m. Scaling on all screens set to 125%. Taskbar icons size is set to normal, so not small like for OP.
*BitWarden from Microsoft Store.
* I've tried reinstalling BitWarden, used Geek Uninstaller to nuke it away. Made no difference.

**Comment by Nihal247** [comment]
Hi @jeroenslemmer and thank you for your patience.

Please right click on the Bitwarden app in the taskbar, go to '**Bitwarden**'

![Screenshot (1042)_LI](https://user-images.githubusercontent.com/80682093/124579071-6eb32300-de6c-11eb-92c5-de3888517c07.jpg)

 and right click on it, then click on '**Properties*,

![Screenshot (1043)_LI](https://user-images.githubusercontent.com/80682093/124579506-cc476f80-de6c-11eb-88d5-453c7d548103.jpg)

 click on '**Change Icon**',

![Screenshot (1044)_LI](https://user-images.githubusercontent.com/80682093/124579802-19c3dc80-de6d-11eb-9181-73175aeb4747.jpg)

and now select the Bitwarden Logo,

![Screenshot (1046)_LI](https://user-images.githubusercontent.com/80682093/124580127-74f5cf00-de6d-11eb-9bae-414d2b767177.jpg)

Then Click on **Ok**, **Apply**, Ok. Then relaunch Bitwarden.
Your problem would be hopefully resolved now.

Thank you in advanced
