### ISSUE TITLE
Secure Input is acquired by BitWarden on MacOS and never released

### ISSUE THREAD

**Issue by andr984g** [bitwarden/desktop#805]
## Describe the Bug
SecureInput is sometimes never released after being acquired by BitWarden (1.25.1), which means that Macro-software (in my case [Espanso](https://espanso.org)) doesn't work. I have found that SecureInput is consistently released again when the BitWarden desktop client is opened.

## Steps To Reproduce
1. Install BitWarden desktop client and web-app extension from the App Store
2. Since it's the easiest way I know to check if SecureInput is acquired: Install Espanso ([guide](https://espanso.org/install/mac/)).
3. Use the BitWarden app extension "for a while" and keep an eye on the Espanso icon (it is not generally the very first time you log into a website that Espanso stops working. For me, it usually happens after about half an hour of use; I have not been able to determine the exact triggers.)
4. For info on what has happened to SecureInput, you can run `espanso log` in the terminal. The information about which apps have acquired SecureInput seems to not always be directly correct.

## Expected Result
SecureInput will be acquired by Safari/BitWarden (so the Espanso icon will be greyed out) _while a password is entered_, and then released.

## Actual Result
SecureInput is sometimes never released, and the Espanso icon will stay greyed out. When the BitWarden desktop app is opened from the menu bar, SecureInput is released.

## Screenshots or Videos
![BitwardenSecureInput](https://user-images.githubusercontent.com/58516599/112057540-b5993900-8b59-11eb-9064-aa57d1459e9a.png)
A screenshot from the Espanso log. Note that it says that it is 'loginwindow' (a native MacOS process) that acquires SecureInput, but the issue is only solved by opening Bitwarden. In this test, I realized that the issue is solved as soon as Bitwarden is opened (no need to restart it). From my understanding of SecureInput, the only way Bitwarden can release SecureInput is if it was the app that acquired it in the first place -- which indicates that the Espanso log is not correct in stating that it was 'loginwindow' that acquired it.

## Environment

- Operating system: Mac OS Big Sur 11.2.3
- Installation method: Mac App Store
- Build Version (go to "Settings" → "About"): 1.25.0

## Additional Context
A similar issue was raised in 2019 (#298), but it was slightly different, and it seems that a solution to that issue at that time was implemented.

## Edits
Edited to reflect the fact, that I have just updated to 1.25.1, and the issue still occurs.
Screenshot of Espanso log posted

**Comment by Doomd** [comment]
I just wanted to confirm this bug...I am running an up to date MacMini 2018, Big Sur v11.2.3

This disrupts my keyboard/mouse sharing programs (Synergy and Sharemouse)...particularly the keyboard input.

**Comment by cho-m** [comment]
> A similar issue was raised in 2019 (#298), but it was slightly different, and it seems that a solution to that issue at that time was implemented.

Just to note, the linked bug is still open and was never fixed.
It does reference code changes in Electron API, but Bitwarden didn't do anything with the new API.

It seems likely that the root cause is the same.
You mention that SecureInput is released upon opening the client, which is a similar behavior observed in other issue.

**Comment by andr984g** [comment]
Thanks for the clarification, I apologize for misunderstanding #298 .
I think you’re right that this is a duplicate of #738. I will close this issue and leave a comment there.

**Duplicate of #738 **

**Comment by SixDemonBag** [comment]
Also confirming this bug. I can replicate @andr984g issue using 'aText' instead of 'Espanso' (similar apps).

**Comment by eliykat** [comment]
Hi @SixDemonBag, this issue should have been fixed in 1.28.0 and later. Please make sure you're using the latest version. If the issue is still persisting, please ping me in #298, which is the main issue we used to track this bug.
