### ISSUE TITLE
Mouse cursor different under Ubuntu (using the snap package)

### ISSUE THREAD

**Issue by logix2** [bitwarden/desktop#81]
The Ubuntu snap package for Bitwarden uses a different mouse cursor than what's default. Here are a couple of screenshots:

![bitwarden_2](https://user-images.githubusercontent.com/38005360/39306993-4e35091c-496a-11e8-9326-127ed0531d9e.png)

![bitwarden_1](https://user-images.githubusercontent.com/38005360/39306996-50e6a850-496a-11e8-9694-98e27944d0f8.png)

My default mouse cursor theme is white.

According to this: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268 there is a simple workaround: https://github.com/Ubuntu/snapcraft-desktop-helpers/commit/4008601d

**Comment by kspearrin** [comment]
Seems like a snapd bug. I'm not sure what that fix is suggesting that we do to workaround the problem?

**Comment by favadi** [comment]
The mouse cursor not only looks different, it doesn't scale on HiDPI monitor, so it looks tiny in my machine. It doesn't happen with other snap packages like Spotify or Skype.

**Comment by lekseven** [comment]
Snap apps still can't honor system theme settings including mouse cursors.

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1585332
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268

**Comment by freeedrik** [comment]
Any news on this?

**Comment by freeedrik** [comment]
Any news on this?
For me it only happens in some snap packages (chromium and robo3t) but not other (like Intelij Idea).

**Comment by mgeorge94** [comment]
what file needs to be changed?
