### ISSUE TITLE
Clear search input button hard to notice

### ISSUE THREAD

**Issue by PlugaruT** [bitwarden/desktop#82]
If the search input contains some text, a small "X" button appears but because it's colour is almost the same as the colour of input, it's very hard to notice.
![screenshot from 2018-04-29 21-29-03](https://user-images.githubusercontent.com/6437932/39409711-9a5aebea-4bf4-11e8-9f40-47444da29466.png)

**Comment by kspearrin** [comment]
This is something that the browser adds to search fields. Unfortunately I do not know a way to change its color.

**Comment by PlugaruT** [comment]
I've tried to somehow investigate this issue but without luck. Didn't knew that this is added by the browser.

**Comment by kspearrin** [comment]
As far as I know it is not possible to style the X. If you find otherwise please let me know and I will re-open and fix it.
