### ISSUE TITLE
Use 'delete()' to clear values Error

### ISSUE THREAD

**Issue by Kgeorgar** [bitwarden/desktop#820]
Hello!
Since the last update when i am trying to login from the desktop version i am getting the following error.
Thanks in advance.

![ErrorBW](https://user-images.githubusercontent.com/81669644/113093883-6ad28d80-91f9-11eb-90a6-e71f6248d5bb.PNG)

**Comment by eliykat** [comment]
Hi @Kgeorgar, this issue has already been reported here: #781. I'll close this issue as a duplicate, but please comment on #781 with any further information or updates you can provide.
