### ISSUE TITLE
Browser Integraiton doesn't work on Manjaro

### ISSUE THREAD

**Issue by NovaViper** [bitwarden/desktop#833]
## Describe the Bug
Im trying to enable biometrics on my laptop but it keeps saying I need to enable browser integration on the desktop, despite I already have it enabled. I'm using the desktop version 1.25.0

## Steps To Reproduce

1. Go to 'Settings' in the extension
2. Click on 'Unlock with biometrics`
3. It should say "Browser integration is not enabled"

## Expected Result
Brower extension works properly

## Actual Result
Browser extension keeps saying I don't have Browser Integration enabled, but it is enabled

## Environment

- Operating system: Manjaro KDE 21.0.1
- Installation method: ArchLinux Repo/Manjaro Community repo
- Build Version (go to "Settings" → "About"): Version 1.25.1 for Desktop; Version 1.49.1 for extension
- Browser: Vivaldi v3.7.2218.52

**Comment by sso-bitwarden** [comment]
Hi @NovaViper 

Unfortunately, Biometrics on Linux is not supported yet

**Comment by clayadams5226** [comment]
Based on the comment above this will be closed. Bio support for Linux is on the roadmap but there's no date on when it will be made available.
