### ISSUE TITLE
Broken gtk dialogs on desktop version

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [bitwarden/desktop#835]
## Describe the Bug

Dialogs render text as boxes - Missing charset in gtk based dialogs? 

## Steps To Reproduce

1. Invoke any action that requires external dialog popup from window manager (eg. send file, regenerate existing password... )

## Expected Result

Any kind of charset loaded or at least error to log

## Actual Result

Instead of text I only see boxes

## Screenshots or Videos

https://imgur.com/a/IvbeINE

## Environment

- Operating system: Arch Linux under gnome (gtk 3.24, mutter 3.38)
- Installation method: Installed from snap store
- Build Version (go to "Settings" → "About"): 1.25.1

**Comment by MGibson1** [comment]
This is a snap issue. As far as I've been able to find there isn't a way for package maintainers to fix this. For what it's worth, here's the recommended fix: https://wiki.archlinux.org/index.php/Snap#Text_unreadable, though it hasn't worked for me in the past.
