### ISSUE TITLE
Possible leak of password due to spell checker

### ISSUE THREAD

**Issue by rangzen** [bitwarden/desktop#842]
## Describe the Bug

The password field in the desktop app does not invoke spellcheck false

## Steps To Reproduce

1. Go to the start screen
2. Click on the eye to see the password

## Expected Result

The spell checker should not be called on this field.

## Actual Result

If the spell checker recognize a wrong word, it’s underlined.

## Environment

- Operating system: Linux
- Installation method: Downloaded from Bitwarden.com
- Build Version (go to "Settings" → "About"): 1.25.1

## Additional Context

Check https://community.bitwarden.com/t/is-there-a-possible-leak-with-the-spell-checker/28870 for some information already extracted.

**Comment by crjeder** [comment]
The same issue exists for any password in the windows desktop client.

Version 1.29.1
Shell 14.0.1
Renderer 93.0.4577.63
Node 14.17.0
Architecture x64

**Comment by eliykat** [comment]
Thanks for the report @rangzen! I've updated the desktop client to match the other clients. It'll be included in the January release.
