### ISSUE TITLE
Windows portable creating leftover log files in AppData

### ISSUE THREAD

**Issue by sh1ft-github** [bitwarden/desktop#843]
## Describe the Bug

Upon launching the Bitwarden Windows portable release a folder containing leftover log files is created with every launch of Bitwarden. Since the release is titled as portable this makes the app non-portable. If the log files are necessary to be stored the app should store them in the folder with the app. Storing the data in AppData not only makes the app not portable but also poses a security risk such as when one takes the app with them on a flashdrive and expects to launch the app and exit the computer without traces (ofcourse it makes sense that the program might be storing some files in the Temp directory however the AppData directory never gets cleared unless a user does so and the files are left on the host computer forever)

## Steps To Reproduce

1. Go to '%appdata%\Bitwarden'
2. You can see the log files

If you delete the folder it will get automatically recreated on each launch of the app.

## Expected Result

The folder should not exist in the first place and definitely not in the AppData directory where junk of non-portable apps is pretty much always left. Bad apps with no choice like Spotify will forcefully install into the AppData directory. If the Bitwarden developer is kind enough to make a portable release for the people who need it I can't understand why would he willingly leave the app creating log files in AppData specifically.

## Actual Result

The app creates leftover traces of log files in the system's AppData folder for anyone to see. They probably don't contain any confidential information but the sole existence of the Bitwarden folder in the AppData folder already reveals that the app has been used by someone of that computer and perhaps leaks even more information from the log files themselves.

## Environment

- Operating system: [Windows 10]
- Installation method: [Using an executable file downloaded from the bitwarden/desktop GitHub releases page] 
- Build Version: [1.25.1]

**Comment by SergeantConfused** [comment]
Hi there,

1. Do you have a standard installation of the Bitwarden desktop client installed on that machine, by any chance?
2. After you run the portable version, do you see a new 'bitwarden-appdata' folder get created in the same folder as the portable .exe?

Thank you in advance,

**Comment by sh1ft-github** [comment]
Hey,

1. I do not have a standard installation of Bitwarden present on the machine. Last time I was uninstalling the client I used an uninstaller program that supposedly removed all of the traces or leftovers.
2. Yes the folder is created with that file name in the same location as where the portable executable is located.

**Comment by marcoXbresciani** [comment]
I can see it as well, never installed but used only the portable version. It creates a `Bitwarden` folder containing `Bitwarden` and `Dictionaries`, the latter being empty. `Bitwarden\Bitwarden` folder contains a `logs` folder that, at least in my situation, is empty.
Version 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3

WIndows 10 64bits.

**Comment by marcoXbresciani** [comment]
> Thank you both.
> Do your C:\Users<username>\AppData\Roaming\Bitwarden folders contain any files?
> 
> Thank you in advance,

Hello, sorry for the delay. For me, as I wrote, it's only this:
```
C:\Users<username>\AppData\Roaming\Bitwarden\
  |
  +- Bitwarden\
  |   |
  |   +- logs\
  |
  +- Dictionaries\
```
but all folders are emtpy.

**Comment by sh1ft-github** [comment]
Hello, I can confirm that both the `Bitwarden`` and the `Dictionaries`` folders are empty so thankfully by default this should not should not be a security issue. 

My fear is that Bitwarden might write log files into the folder on an event like a crash. Since no files were written yet I can't verify whether anything that might be considered confidential is to be written inside of them. The folders don't seem to be used by the app at all by default so I am not sure if they are supposed to exist.

**Comment by sh1ft-github** [comment]
Hello, I can confirm that both the `Bitwarden` and the `Dictionaries` folders are empty so thankfully by default this should not should not be a security issue.

However Bitwarden might perhaps write logs into the folder on an event like a crash. Since no log files were created in my case I have no way of checking what information would the log files contain.

The folder don't seem to be used be the app in any way. This leads me to believe that they're not created purposefully.

**Comment by djsmith85** [comment]
This was potentially an issue with electron prior to version 14 (https://github.com/electron/electron/pull/29865) @Hinton bumped the versions to 14 today. Closing this now as it should be fixed with the next release, if any issues occur after the new release, please feel free to re-open.
