### ISSUE TITLE
Some identity fields are not saved

### ISSUE THREAD

**Issue by MrClayPole** [bitwarden/desktop#85]
Version 1.2.0
Shell 1.8.4
Renderer 59.0.3071.115
Node 8.2.1
Architecture x64
OS Windows 10 Pro x64

When creating a new identity and hit save the follow fields are not saved: First Name, Middle Name, Last Name, Social Security Number, Passport Number, License Number & Post Code. If I edit the entry they are not visable and if I enter them again and hit save they are also not saved.

**Comment by kspearrin** [comment]
I'm not able to reproduce the problem. Seem to work fine for me. Do you also have this problem in other apps?

**Comment by MrClayPole** [comment]
Yes, I' get the same issue in the firefox browser pluggin but both these run on the same machine. I'll see if I can run it on another machine to rule out a local issue.

**Comment by MrClayPole** [comment]
I've ran it from Windows 2012 R2 Server using the Firefox plugin with the same issue. I'm running self hosted which I should have made clear at first and thinking about it I'm also running [https://github.com/jcs/bitwarden-ruby](url) backend. Could a none compliant back-end case the local client to fail to save the fields above?

**Comment by kspearrin** [comment]
This is likely a problem with your server then. I'd reach out to those folks.

**Comment by MrClayPole** [comment]
Thanks I'll log it with bitwarden-ruby
