### ISSUE TITLE
Search should include all URIs

### ISSUE THREAD

**Issue by rggjan** [bitwarden/desktop#86]
Searching for items currently does not search for URI's. This would be useful, for example:

My login for "google.com" also works for "gmail.com". When having this entry in bitwarden:

```
Name:
google.com
Username:
...
Password:
...

URI
google.com
URI
gmail.com
```

Searching for "gmail" should also show this entry, but does not currently.

**Comment by kspearrin** [comment]
Searching should already include the first URI of the item. Are you not seeing this?

**Comment by rggjan** [comment]
I guess that's the problem: In my case (and also example above) searching the second URI would be necessary.

Any specific reason not all URI's are searched? I don't expect a significant performance drop, as items usually only have one URI. On the other hand, items with more than one URI are all the more interesting for searching all of them...

**Comment by kspearrin** [comment]
Right now search is pretty inefficient. We are tracking making it better here https://community.bitwarden.com/t/advanced-vault-searching/36 , which could include all item URIs

**Comment by rggjan** [comment]
Fine for me to track it there
