### ISSUE TITLE
Bitwarden breaks speech to text input on Mac OSX

### ISSUE THREAD

**Issue by arterrey** [bitwarden/desktop#867]
## Describe the Bug 

When running the BitWarden app I find that speech to text is disabled globally in Mac OSX.

## Steps to Reproduce

1. Run BitWarden.
2. Go to another app that has a text input and place a cursor in the input
3. Press the speech to text button on the keyboard (above F5 on my Mac)

The computer will beep and will not pop-up the expected speech to text widget.

To get it to work again, involves either:

- Clicking the BitWarden icon in the system tray to foreground the app. This make speech to text work again.

- Exiting BitWarden totally. Subsequently running BitWarden breaks speech to text again.

## Other context

In my preferences for BitWarden I have enabled:

- "Enable Menubar Icon"

- "Minimise to Menubar"

- "Start automatically on login"

BitWarden Version: 1.25.1 (518)
Mac OS Version: 11.2.3 (20D91) (MacBook Air (M1, 2020))

**Comment by arterrey** [comment]
Here is a screen capture.

https://user-images.githubusercontent.com/616688/116769984-6c96a780-aa6a-11eb-93a6-5f6cf4529f4e.mov

**Comment by eliykat** [comment]
This appears to be the same underlying issue as #298, so I'll close it as a duplicate.
