### ISSUE TITLE
biometrics not enabled "in settings"

### ISSUE THREAD

**Issue by scatterjoy** [bitwarden/desktop#868]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by djsmith85** [comment]
Hi @scatterjoy,
could you please check the documentation here https://bitwarden.com/help/article/biometrics/ and hopefully your issues with biometrics not working are resolved. If so, please close this issue. If you are still having problems, please add some more information based on the questions asked in the issue template.

The above mentioned help-site and the community forums at https://community.bitwarden.com/ are also great places for further information/questions.

**Comment by SergeantConfused** [comment]
Hi @scatterjoy,

Please make sure you tick 'Enable browser integration' in your Bitwarden desktop client before you attempt to activate 'Unlock with biometrics' in your browser extension. If you continue to encounter this error, please check out our community forums or contact us here: https://bitwarden.com/contact/

Thank you for your assistance, @djsmith85.

All the best,

**Comment by eliykat** [comment]
Hi @scatterjoy, @djsmith85 and @SergeantConfused have provided some good links to help you with your problem. If you still need more help, please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
