### ISSUE TITLE
Windows Hello unlock black screen 

### ISSUE THREAD

**Issue by vartemenco** [bitwarden/desktop#874]
## Describe the Bug

Issue occurs when unlocking Windows client with biometrics ( Windows Hello Camera).After unlock is done, Bitwarden appears as black screen instead of showing the vault contents. 

## Steps To Reproduce=

1. Enable Windows Hello unlock in bitwared
2. Close bitwarned app
3. Open bitwarden app
4. Unlock with Windows Hello camera 

## Expected Result

Contents of bitwarden vault appear

## Actual Result

Black screen appears, and required to close and reopen client

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/5986283/117537429-afbbc200-aff8-11eb-84a1-c8956602cf2f.png)

## Environment

- Operating system: Windows 10 20H2
- Installation method: Download from bitwarden.com
- Build Version (go to "Settings" → "About"): 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

## Additional Context

Same appears if unlocking browser extension with Windows Hello

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for bringing this to my attention. I tested this on the same operating system and Bitwarden versions, and Bitwarden displayed the vault correctly after unlocking it using Window Hello through facial recognition.
I recommend you uninstall all your Bitwarden clients, remove all leftover data, turn your machine off and back on, reinstall Bitwarden from the .exe file from our Download page, and test that again. Our Download page and the locations of any leftover data are linked below.
https://bitwarden.com/help/article/data-storage/
https://bitwarden.com/download/

Please keep me posted on this.

**Comment by vartemenco** [comment]
Hi, 

I've done the steps above. Still no luck. 
Same I've mentioned this happens only when the Windows Hello is invoked automatically. (i.e if I start bitwarden) and not if I lock the vault, and after press Use Windows Hello.

**Comment by PixsaOJ** [comment]
For Linux with no Windows hello. Happens periodically on reboot
https://github.com/bitwarden/desktop/issues/1045
