### ISSUE TITLE
Autostart without Login in vault / Fingerprinting !

### ISSUE THREAD

**Issue by Ruffythemonkey** [bitwarden/desktop#875]
Hey Bitwarden guys.
Can you create a method/option that allows the user not to log into the vault at the time of autostart. With fingerprint, the app asks for the start to authenticate.

**Comment by sso-bitwarden** [comment]
We appreciate your feedback.  

We ask that any future feature requests or product enhancements be directed to our Community Forums as this is our official location for them. https://community.bitwarden.com/c/feature-requests/5
