### ISSUE TITLE
Search in Notes is on whole words only but in item names it is a partial match

### ISSUE THREAD

**Issue by keeneye** [bitwarden/desktop#877]
## Steps To Reproduce

Add a word to notes. Search for part of it. 

## Expected Result

Find the matching items

Nothing is found.

## Environment

- Operating system: [e.g. Windows 10]
- Installation method: [e.g. Downloaded from Bitwarden.com] 
- Build Version 
- Version 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by gryffs** [comment]
I can correct this issue if it is a good idea. I've tracked down the search functionality in jslib [here](https://github.com/bitwarden/jslib/blob/1e2c56cacf975eab4527cb3c1a63cf8136b58bd4/src/services/search.service.ts#L131-L138)

If I add an additional line to cover `notes` the issue will be corrected. ie:
`q.term(t, { fields: ['notes'], wildcard: soWild });`

This will add notes for all `TYPES`: Login, Card, Identity, and Secure Note.

If this is functionality that should be added, let me know and I'll put together a PR.

**Comment by keeneye** [comment]
It might have been a ‘design’ choice to limit the number of results, but I think it would be an improvement.

Many thanks
Mark

**Comment by cscharf** [comment]
Hi @keeneye , while we deliberate whether to accept the PR from @gryffs , you may use advanced search techniques (wildcards) in this instance for partial matches in notes: see https://bitwarden.com/help/article/searching-vault/

Example:
>notes:query*

**Comment by keeneye** [comment]
Ah - that is helpful.
Thanks

Mark
________________________________

**Comment by cscharf** [comment]
Hi Mark,

Thanks again and I've already updated the PR that was submitted, the team felt adding wildcard search to notes by default would negatively impact performance too much for our customers with larger vaults or organization vaults that we decided to not accept that change at the moment.
