### ISSUE TITLE
TouchId option missing Macos desktop app

### ISSUE THREAD

**Issue by avishaan** [bitwarden/desktop#883]
## Describe the Bug

No option for touchid exists in the bitwarden desktop app settings

## Steps To Reproduce

1. Go to Preferences settings

## Expected Result

I expect to see an option to enable touchid

## Actual Result

No option to enable touchid

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5360982/117873752-27465700-b26e-11eb-9f82-8d9cb15b1822.png)

## Environment

- Operating system: MacOS 11.3.1
- Installation method: I genuinely do not remember
- Build Version (go to "Settings" → "About"): 1.25.1 (518)

**Comment by eliykat** [comment]
Hi @avishaan, we've been unable to recreate this problem at our end. Can you please contact our Customer Success team, who will help you debug the problem: https://bitwarden.com/contact. You can include a link to this issue in the message content. I'll close this issue for now, but if it's reproducible as a bug, it will be reopened and investigated further.
