### ISSUE TITLE
AppImage tries to update itself and fails

### ISSUE THREAD

**Issue by morgaraf** [bitwarden/desktop#893]
## Describe the Bug

From time to time Bitwarden says there is a new version and I should update, and that I only need to restart the application for it to update itself automatically. I click OK/Restart, Bitwarden closes, and then I get an error message about ENOSYS (cannot copy and paste text from that windows).

## Steps To Reproduce

1. Go to 'Help → Check for Updates'.
2. Click on 'Yes' in the 'Update Available' window.
3. Click on 'Yes' in the 'Restart to Update' window.
4. See the error message.

## Expected Result

I would expect Bitwarden restarts updated.
## Actual Result

Error message, and no updating.
## Screenshots or Videos

How can I attach a screenshot?
## Environment

- Operating system: Ubuntu 20.04
- Installation method: AppImage 
- Build Version (go to "Settings" → "About"): 1.25.1, but it has happens ever.

**Comment by awvalenti** [comment]
I think I had this problem when my Bitwarden AppImage was located at `/opt`. A possible solution is to move it to home folder. I don't find this very secure, though, so I moved to the snap distribution.
