### ISSUE TITLE
Error: Cannot read property 'webContents' of null - when waking up laptop from sleep

### ISSUE THREAD

**Issue by qoops-1** [bitwarden/desktop#896]
## Describe the Bug

I get an alert with error message:

> Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
at NativeTheme.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:19357:28)
at NativeTheme.emit (events.js:315:20)

## Steps To Reproduce

I cannot really reproduce, but I got the error after waking up my laptop from sleep

## Environment

- Operating system: Mac OS Big Sur
- Installation method: Homebrew
- Build Version 1.26.3 (526)

**Comment by yunruse** [comment]
I have also received this error using Big Sur on a non-homebrew MacBook Air. Here's my programmer spidey sense! ✨ 

Before I checked the code, I was fairly confident from my own experience that it was linked to switching to or from dark mode on macOS, but this is unfortunately not immediately reproducible with switching dark mode or lock-unlocking the MacBook.

The `.asar` format is new to me, but I believe the faulty code occurs in th function `electronMainMessaging_service_ElectronMainMessagingService`. It involves accessing `windowMain.win.webContents`, but `.win` is null, for some bizarre reason.

With some immediate thought, this may occur when a power-saving functionality. Perhaps macOS stops rendering a window when it has not been visible for a while? I don't have the time to test this fully, but that would be my likeliest guess.

Anyhow! This does not appear in BitWarden Desktop's code, so this is most likely a dependency. Please, devs, tell me which dependency this is so I can pass this along! :)

**Comment by eliykat** [comment]
That worked, thanks @yunruse! No doubt you saved me a bit of time trying to reproduce it. My guess is that others experiencing this issue have their system Appearance set to "auto", and their Mac has been asleep long enough that the system Appearance changes (from day > night modes) as soon as the Mac resumes.

`win.webContents` is provided by Electron, but I think it's our fault for calling it without checking for null first. I'll look into it further.
