### ISSUE TITLE
Needed update of the "copy password" icon on the desktop app

### ISSUE THREAD

**Issue by michaldybczak** [bitwarden/desktop#91]
On browser extension "copy password" icon is in shape of a key which is very distinguishable and clear. This was changed a while ago and it was a brilliant update! However, the desktop app still has the old, confusing icon:

![screenshot-2018-05-23-21 22 58](https://user-images.githubusercontent.com/10132958/40446564-e5e53bb8-5ecf-11e8-97bb-bdd6a021ca38.png)

Please, update the icon so it would be the same in browser extension as in desktop app.
Thanks

**Comment by kspearrin** [comment]
browser extension uses the same icon.

![image](https://user-images.githubusercontent.com/1190944/40461434-6b1c1208-5ed9-11e8-80ca-ce04297c2132.png)


A key is used in the listing where we need to distinguish multiple copy icons from one another. Here it is clear that the copy is for password.

**Comment by michaldybczak** [comment]
Ok, but isn't it more clear to have the same icon in all places? It is after all the same function "copy password" so why it uses different icons across the bitwarden interface?
Besides, key icon is much better and intuitive. The one showed above looks like copy or clipboard but is not indicating what is being copied. Key icon clears out that confusion. You don't have to check it by tooltips.

Sure, one can get use it with time but interface would be much more intuitive with better defined icons and key icon is such well designed and used icon. Clipboard/copy icon is too general, at least in my opinion.

Also, when I open extension I see automatically a list with the key icon, when I open desktop app, I actually cannot find the key icon anywhere.

**Comment by kspearrin** [comment]
The key icon denotes "Password", not copying via clipboard. Since we are already in a section that is clearly labeled "Password" the user can easily infer that they are clicking the clipboard icon for the password value. Since there is nothing that would clearly infer a clipboard icon as being for the password in the *vault listing*, we use the key icon there.

**Comment by michaldybczak** [comment]
It seems like a communication issue. Here is the screen from browser extension:

![screenshot-2018-05-24-13 39 54](https://user-images.githubusercontent.com/10132958/40483374-0abc34a4-5f58-11e8-8535-03eaebc5bdc9.png)

I marked the key icon and the notification that says "copied to clipboard" and it really does that. I use it every day.

On desktop app, when I mouse cursor over the clipboard icon on password line I get tooltip "copy the password" and when used I also get notification "copied to clipboard".

This is the one and the same action with different icons. Also, the clipboard icon is used to copy various information so its meaning depends on contextual placement.

The problem seems to be that there are two different systems of using icons so to speak but they also use different placement of functions so yeah, because of that such change can be justified. Since it bugs me and it feels counter intuitive. Icon in itself is the center of attention and we (or maybe me) tend to associate usage with the icon so using the same icon for different icons that depend of placement is not clear. When I think about it it is clear but not when I want to use it quickly and that is how bitwarden is used. Quick glance and things should be apparent. No time to analyze the whole window in which line clipboard icon is placed.

OK, I see that the issue is more complex and cannot be solved smoothly or quickly right now. No matter what you do, you will break some consistency.

**Comment by Crocmagnon** [comment]
I agree with @kspearrin :
The icons you're pointing to in the desktop app are on a login page, not on the list.
The icons you're referring to in the browser extension are in the list, not in the login page.
So the icons are consistent 😉
