### ISSUE TITLE
macOS - Desktop client does not display an error message or bypass the 2FA method, when the only or primary 2FA method configured is not supported.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#912]
## Describe the Bug
When logging into a Bitwarden account that has FIDO2 WebAuthn configured, the desktop client does not automatically move on to another 2FA method and does not display an error message if it's the only 2FA method that is configured.

## Steps To Reproduce
1. Configure FIDO2 WebAuthn on your Bitwarden account.
2. Log into your account through the macOS desktop client.

## Expected Result
To see an error message that the configured 2FA method is not supported in this client.

## Actual Result
Only 'Continue', 'Cancel', and 'Use another two-step login method' buttons are shown.

## Screenshots or Videos
![1](https://user-images.githubusercontent.com/73389600/118944621-673bc700-b95d-11eb-8ed2-801059676d5d.png)
![2](https://user-images.githubusercontent.com/73389600/118944627-686cf400-b95d-11eb-8ba9-9c611d00044d.png)

## Environment
- Operating system: macOS 11.3.1.
- Installation method: Apple App Store.
- Build Version: 1.25.1 (518).

## Additional Context
N/A.

**Comment by SergeantConfused** [comment]
Closing this issue because the latest version (1.26.3) automatically offers the alternate 2FA method, or shows an error when there is none configured.

**Comment by ywwry66** [comment]
Hi, can I ask how you upgrade to 1.26.3? It is not showing in my Mac App Store.

**Comment by SergeantConfused** [comment]
Hi @ywwry66,

Absolutely. I tested that using the .dmg from here: https://github.com/bitwarden/desktop/releases which you can use as well, but please note that if you use our Safari extension, you would need to wait till the latest version makes its way to your Apple App Store as it's only a matter of time till it fully propagates. More on this here: https://bitwarden.com/help/article/releasenotes/#release-announcements

I hope this helps. Please do not hesitate to reply to this message if you have any further questions.

**Comment by ywwry66** [comment]
Thanks for clarifying.
