### ISSUE TITLE
Forever Spinning

### ISSUE THREAD

**Issue by AWHCC** [bitwarden/desktop#913]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: Downloaded from Bitwarden.com
- Build Version 
- Version 1.26.3
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by cscharf** [comment]
Hi @AWHCC , thanks for the report, however this is a duplicate of #894 .
