### ISSUE TITLE
Autofill fails on Personal Capital web site

### ISSUE THREAD

**Issue by dbowman410** [bitwarden/desktop#916]
## Describe the Bug

Autofill does not work for username field on Personal Capital web site.

## Steps To Reproduce

1. Go to web site:  https://home.personalcapital.com/page/login/goHome
2. Attempt autofill of username/email.
3. Nothing happens.

Login is two pages. First has username, second has password.
Autofill on username page fails.
Autofill of password on second page works. You do have to do the autofill action again to get the password, it's not automatically filled by the autofill attempt on the first page like happens on some sites.

## Expected Result

Expect username stored in Bitwarden to be pasted into Email editbox.

## Actual Result

Nothing is put into the "Email" editbox.

## Environment

- Operating system: Windows 10 x64
- Installation method: Downloaded from Bitwarden.com
- Build Version (go to "Settings" → "About"): 1.26.3
- Web Browsers:  Firefox 88, Edge 90
- Firefox & Edge extension version: 1.50.0

## Additional Context

Thank you for a great password manager.

**Comment by cscharf** [comment]
Hi @dbowman410 , thanks for letting us know, however this repo is for our desktop app, and this looks like an issue with the [browser extension](https://github.com/bitwarden/browser). Also, we have a [pinned issue](https://github.com/bitwarden/browser/issues/1621) for this very type of report which would help us out if you could provide this detail in the form provided there. I'm going to go ahead and close this one.
