### ISSUE TITLE
Frozen 1.24.7 version no longer works

### ISSUE THREAD

**Issue by Z0l** [bitwarden/desktop#919]
## Describe the Bug

The Safari browser extension of the frozen 1.24.7 version (the one that runs on Apple devices with Safari 13) drops an error message during login: 

An error has occurred
Preflight response is not successful

The standalone application works + you can log on to the online vault from the browser, the issue is specific to the browser plugin.

## Steps To Reproduce

1. Download the frozen 1.24.7 version on e.g. High Sierra
2. Enable the browser plugin in Safari
3. Try to log in from the plugin

## Expected Result

1. Download the frozen 1.24.7 version on e.g. High Sierra
2. Enable the browser plugin in Safari
3. Try to log in from the plugin
4. Successful login

## Actual Result

1. Download the frozen 1.24.7 version on e.g. High Sierra
2. Enable the browser plugin in Safari
3. Try to log in from the plugin
4. Error message is presented before asking for the token

## Screenshots or Videos

![Screen Shot 2021-05-24 at 19 19 39](https://user-images.githubusercontent.com/601826/119384688-62f90c00-bcc5-11eb-9b8f-475658bbb10d.png)

## Environment

- Operating system: [Mac OS High Sierra]
- Installation method: [e.g. Downloaded from Bitwarden.com] 
- Build Version (go to "Settings" → "About"): 1.24.7

## Additional Context

I know this is a frozen version but would appreciate if you could clarify if the extension is expected to work or not. There is no indication on the page that it no longer works.

**Comment by cscharf** [comment]
Hi @Z0l , while we're not aware of anything that would have broken this, there is a chance something broke with reverse compatibility, although a preflight error seems odd. Are you using self-hosted or Bitwarden Cloud for your server?

**Comment by Z0l** [comment]
Hi @cscharf , I'm using Bitwarden Cloud. It works from all my other devices (desktop, tablet, phone, other laptop), only my aging Macbook Pro has this problem (which is capped at High Sierra because the graphics card doesn't support Metal, but otherwise still usable).

**Comment by Sonnenstreifer** [comment]
Hey, 

I have the same problem with macOS 10.13.6 and Bitwarden DesktopApp 1.24.7. 
As soon as I log in, the error message appears. 
On the same system Bitwarden (1.54.0) works fine as an extension in Firefox (94.0.2).

**Comment by Hinton** [comment]
Hello,

Just wanted to let everyone know that the 1.24.7 is no longer supported.

The download page has been updated with more information.
> This release is no longer functional or working with our current cloud services and infrastructure. You may still use the browser extension with Firefox and Chrome, as well as continue to access the Web Vault however Apple set the End-of-life (EOL) for High Sierra a year back and we are no longer able to maintain reverse compatibility.
