### ISSUE TITLE
Temp folders created

### ISSUE THREAD

**Issue by ghost** [bitwarden/desktop#92]
Hi, I use Portable Bitwarden for Windows:
v 1.2.0
Shell 1.8.4
Renderer 59.0.3071.115
Node 8.2.1
Architecture x64

And every launch it's creates new folder in C:\Users\NAME\AppData\Local\Temp.
One folder = 100-180mb, and it's doesn't deleting after I close Bitwarden.

So this is very bad for SSD life.

And also it's creates *.tmp.node files that doesn't deleting after close too (this issue also in non-portable version).

**Comment by kspearrin** [comment]
A new folder is created every time you re-open the application or just once?

**Comment by AL3x3y0** [comment]
> A new folder is created every time you re-open the application or just once?

Every time.

**Comment by kspearrin** [comment]
Hm. Seem related to something electron is doing. Here is one issue I found: https://github.com/electron/electron/issues/10139
