### ISSUE TITLE
Javascript exception while coming from sleep

### ISSUE THREAD

**Issue by icq25** [bitwarden/desktop#927]
## Describe the Bug

Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at NativeTheme.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:19357:28)
    at NativeTheme.emit (events.js:315:20)

## Steps To Reproduce

Not 100% reproducible, but often works like:

1. boot up laptop as usual, sign in to BW
2. close the lid (go to sleep)
3. Open the lid (couple of hours later, sometimes different Wifi)
4. Open FireFox (88.0.1 64bit)
5. See the exception

## Expected Result

No exception

## Actual Result

There is one.
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at NativeTheme.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:19357:28)
    at NativeTheme.emit (events.js:315:20)
## Environment

- Operating system: Mac OS Catalina 10.15.7
- Installation method: Downloaded from Bitwarden.com; FF addon installed from Add-on gallery.
- Build Version (go to "Settings" → "About"): 1.26.4 (527) but started on previous build

## Additional Context

<img width="418" alt="image" src="https://user-images.githubusercontent.com/44747741/120065818-08243380-c07c-11eb-901e-a154ddb56b7c.png">

**Comment by eliykat** [comment]
Hi @icq25, this issue has already been reported here: #896. I'll close this as a duplicate, but please post over in that thread. There are some reports that the App Store version doesn't have this issue, so that might be a workaround in the meantime (particularly as this bug has been difficult to reproduce).
