### ISSUE TITLE
Browser integration fails unless Firefox's NativeMessagingHosts directory exists on MacOS

### ISSUE THREAD

**Issue by vercas** [bitwarden/desktop#928]
## Describe the Bug

Browser integration doesn't work on MacOS, at least with Firefox, unless this directory exists:
```
~/Library/Application\ Support/Mozilla/NativeMessagingHosts
```
Firefox doesn't create it by default, at least for me.
Looking at the code here: https://github.com/bitwarden/desktop/blob/master/src/main/nativeMessaging.main.ts#L103-L119
Code just checks if the directories exist.  
The initial pull request that added browser integration actually checked if the parent directory exists (`~/Library/Application\ Support/Mozilla` in this case) which is great, but it also didn't create the NativeMessagingHosts directory.

## Steps To Reproduce

My Firefox did not create that directory automatically.
I guess you can remove the directory prior to starting the Bitwarden desktop app.

## Expected Result

Bitwarden needs to create the directory when it's missing.
You can check the parent directory, `~/Library/Application\ Support/Mozilla`, and if it exists, create the `NativeMessagingHosts` directory inside it.

## Actual Result

Browser integration checkbox in settings is checked, indicating that browser integration is enabled.  
The Firefox extension kept telling me that it couldn't connect to the desktop app.  

## Screenshots or Videos

Nope.

## Environment

- Operating system: Mac OS Big Sur
- Installation method: I honestly don't remember.
- Build Version (go to "Settings" → "About"): All of 'em, see link above from current `master`.

## Additional Context

Took me months to get angry enough to look at the code and see what could be wrong (I'm not familiar with *any* of the tech used here).

**Comment by kapitainsky** [comment]
it was identified and hopefully fixed by https://github.com/bitwarden/desktop/pull/808

Version including this fix has not been released in AppStore yet - so hopefully next release will put this issue to rest.

**Comment by vercas** [comment]
Oh, I see.  
I've missed this part where it actually creates the directory: https://github.com/bitwarden/desktop/blob/c7345197f72be1f95870a089d04a27d2963987ef/src/main/nativeMessaging.main.ts#L190
