### ISSUE TITLE
Javascript errors after 1.26.3 update on M1 Mac

### ISSUE THREAD

**Issue by jdpneto** [bitwarden/desktop#930]
## Describe the Bug

After the latest update, the desktop client stopped working with the error:

`Uncaught Exception:
Error: dlopen(/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node, 1): no suitable image found.  Did find:
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar/node_modules/keytar/lib/keytar.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1152:30)`

## Steps To Reproduce

Update bitwarden on an M1 Macbook Air try to run it

## Expected Result

Bitwarden runs and sits on the dock

## Actual Result

Bitwarden is running but you can't interact with it

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/870865/120176118-d5567880-c1fe-11eb-92e1-4ea3fe6d98b8.png)

## Environment

- Mac OS Big Sur 11.3 on an M1 Macbook Air
- Mac app store
- Bitwarden v1.26.3 according to the app store.

## Additional Context

The plugins run fine on both safari and chrome.

**Comment by dugeem** [comment]
Seeing same error with Bitwarden desktop for macOS v1.26.3 on Big Sur 11.4 running on MacBook Air M1

**Comment by robbedg** [comment]
It does run when using rosetta. Without it I get the same error.

![afbeelding](https://user-images.githubusercontent.com/17450057/120185150-1e63f800-c212-11eb-9a8c-39d42579ca84.png)

**Comment by darrylhodgins** [comment]
Seeing the same error; here's my full error message:

```
Uncaught Exception:
Error: dlopen(/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node, 1): no suitable image found.  Did find:
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar/node_modules/keytar/lib/keytar.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

**Comment by HVR88** [comment]
This is absolutely ridiculous, that such a simple show-stopper bug would get through to an app-store submission.  It's not like there are nightlies published to the MAP. This is the first release in a long time and to miss something so simple as to check whether the app runs on M1 is beyond unbelievable.

**Comment by andr984g** [comment]
Happens to me, too (M1 Air 2020, macOS 11.3)

**Comment by denysdovhan** [comment]
Same problem on M1 Mac. Worked fine yesterday. [A solution](https://github.com/bitwarden/desktop/issues/930#issuecomment-851417956) by @robbedg helped to fixed the issue at the moment.

**Comment by creedda** [comment]
Looks like its an issue with the arm part of the universal build not existing yet. if you enable the app to run in rosetta at @robbedg suggested that work around works for now.

**Comment by rolimans** [comment]
Same problem here! Mac Pro M1, Big Sur. Currently only being able to open it with Rosetta enabled.

**Comment by edugoar** [comment]
Seeing same error with Bitwarden desktop for macOS v1.26.3 (via App Store) on Big Sur 11.3.1 running on MacBook Air M1

**Comment by gigabytex** [comment]
Same error using App Store version. Enabling Rosetta does "fix" the issue.
Homebrew version (v1.26.4) works fine, but no browser integrations...

**Comment by tgreer-bw** [comment]
AppStore version 1.26.5 is submitted with the fix, hopefully approved soon.

**Comment by edugoar** [comment]
> Same error using App Store version (v1.26.3). Enabling Rosetta does "fix" the issue.
> Homebrew version (v1.26.4) works fine, but no browser integrations...

very nice workarround until final fix will be ready

**Comment by shermthegod** [comment]
I'm having the exact same issue. Updated my Bitwarden via the Mac App Store, and now it won't open. However, the Safari extension works, so I can at least use Bitwarden until the fix is released.

Mac mini m1
Bitwarden 1.26.3
macOS 11.4

**Comment by dodsonmg** [comment]
> AppStore version 1.26.5 is submitted with the fix, hopefully approved soon.

This version is now in the AppStore, and the update fixed the issue for me.

Thanks for the quick turnaround.

MacBook Air M1
Bitwarden 1.26.5
macOS 11.3

**Comment by PatrickBK** [comment]
yeah so the fix is to rip native apple silicon support away so one doesn't manually have to set the option to use rosetta? ;-) Or was there never native apple silicon support? Nest question, when will bitwarden be fully native? :-)

**Comment by charles-997** [comment]
Not sure if this is the same or a different Javascript error.
I'm receiving this error message when trying to update to the latest version.

> Error: Could not get code signature for running application
at Server.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:170:32)
at Object.onceWrapper (events.js:421:28)
at Server.emit (events.js:315:20)
at emitListeningNT (net.js:1347:10)
at processTicksAndRejections (internal/process/task_queues.js:83:21)

macOS 11.3.1 (20E241)
Intel Mac
Current Bitwarden Version 1.26.4 (527)

**Comment by cscharf** [comment]
Please update to [v1.26.5](https://github.com/bitwarden/desktop/releases/tag/v1.26.5) OR via the app store which resolves these issues.
