### ISSUE TITLE
Buggy TOTP display

### ISSUE THREAD

**Issue by turbo-donkey** [bitwarden/desktop#94]
OSX desktop app, shows OTP code for a login, when I switch to another login that should also have an OTP code (both logins have different keys) the original code remains and the counter stops counting down.

**Comment by kspearrin** [comment]
Just tested this and was not able to reproduce so there must be some other parameter involved.

**Comment by turbo-donkey** [comment]
One is in my personal vault and one was shared with one of my organisations collections, the login in my personal vault does not show the OTP code and the one shared in the org collection does, switching between produces the mixed result with the code not changing and the timer stopping.

**Comment by kspearrin** [comment]
Tested that use case as well, still seemed to work properly.

**Comment by turbo-donkey** [comment]
I think it’s because I’m on the Teams tier, my personal vault doesn’t have the feature but my org does, I thought my personal vault was somehow linked to the orgs feature tier.  So, my bad.  Still doesn’t remove the OTP properly when I switch from an org collection login to the personal vault login though, I still see the previous code and a stuck timer.

**Comment by kspearrin** [comment]
Ok great. I was able to reproduce the problem that way. Fixed for next version.
