### ISSUE TITLE
Extension Disappeared From Safari (Version 14.1.1)

### ISSUE THREAD

**Issue by DGShannon** [bitwarden/desktop#943]
## Describe the Bug
Upon installing the Safari Technology Preview, the Bitwarden extension disappeared from regular Safari version 14.1.1 running MacOS 11.4 on M1 Mini. The desktop app continues to work. Uninstalling the desktop app, restarting the computer, reinstalling the desktop app, from the App Store, does nothing to resolve.

## Steps To Reproduce

1. Use Bitwarden Extension in Safari Technology Preview
2. Use FreeMacSoft's "AppCleaner" to uninstall Technology Preview
3. Open Safari 14.1.1
4. Find extension missing from Preferences > Extensions

## Expected Result
The extension should appear as on option to be turned on.

## Actual Result
The extension is MIA with no provision to enable.

## Environment
- Operating system: MacOS 11.4
- Installation method: Downloaded from Mac App Store 
- Build Version: 1.26.5

**Comment by kapitainsky** [comment]
I had similar issue: https://github.com/bitwarden/browser/issues/1847

Clean Safari cache -  first time I used [Onyx](https://titanium-software.fr/en/onyx.html) but next time [CCleaner](https://www.ccleaner.com/ccleaner-mac)  also did the job.

**Comment by michaelx** [comment]
Same issue, would be good to fix the root of the issue without having to use any system cleaners.

**Comment by DGShannon** [comment]
> I had similar issue: [bitwarden/browser#1847](https://github.com/bitwarden/browser/issues/1847)
> 
> Clean Safari cache - first time I used [Onyx](https://titanium-software.fr/en/onyx.html) but next time [CCleaner](https://www.ccleaner.com/ccleaner-mac) also did the job.

I just tried Onyx. Didn't do anything for the problem.

**Comment by DGShannon** [comment]
> **Edit:** For me, when I installed the Safari Technology Preview it appeared in both Safari versions again.

Interesting. I might have to try reinstalling Technology Preview.

**Comment by DGShannon** [comment]
> **Edit:** For me, when I installed the Safari Technology Preview it appeared in both Safari versions again.

Thanks. That did the trick. Unfortunate that the fix demands this, but at least I have Bitwarden working again.

**Comment by kapitainsky** [comment]
Bad luck obviously.  Keep trying.

**Comment by secwang** [comment]
same. install Safari Technology Preview  fix this.

**Comment by fishergmn** [comment]
I have this same issue.   On my new M1 MacMini after an initial install of the desktop version of Bitwarden from the AppStore the Safari extension was installed without an issue but as of yesterday the extension completely disappeared without any warning or changes in settings from me and cannot be recovered.  Even after a TOTAL removal of all Bitwarden components on my machine and a fresh install of Bitwarden from the appstore.  Clearly not normal behavior and there most certainly is a bug or lack of process description on how to recover and restore the extension.

I would also request a stand alone Safari extension only be made available so the desktop version is not needed.

**Comment by DGShannon** [comment]
> as of yesterday the extension completely disappeared without any warning or changes in settings

Interesting! Did Safari, or Bitwarden, happen to update on their own? My issue only popped up after uninstalling Safari Technology Preview. No amount of Bitwarden uninstalling, house cleaning, etc. would bring it back. However, simply reinstalling Safari Technology Preview fixed it in both browsers (regular and preview).

BTW - The new release of Preview (for Big Sur) released yesterday, with the new features. Really great! So, you might try that. And yes, Bitwarden needs to get on the stick and fix this. Extension totally separate from desktop, and working properly.

**Comment by eliykat** [comment]
I think this is the same issue as https://github.com/bitwarden/browser/issues/1696, you've just come at it from the other direction. i.e. some users had the extension disappear, and solved it by installing Safari Tech Preview. You may have "solved" the same bug but then un-solved it when you uninstalled Safari Tech Preview. Other users in this thread had the bug occur spontaneously, unrelated to uninstalling Safari Tech Preview. I'm going to close this as a duplicate.
