### ISSUE TITLE
Default theme does not follow system theme on Linux

### ISSUE THREAD

**Issue by eliykat** [bitwarden/desktop#945]
## Describe the Bug

When the theme is set to "Default", the app does not follow system theme changes on Linux until the window is closed and reopened.

## Steps To Reproduce

1. Open Bitwarden on Ubuntu
2. Make sure theme is set to "Default"
3. Change the system theme in Settings > Appearance from light to dark (or vice versa)

## Expected Result

The Bitwarden app follows the change to the system theme.

## Actual Result

The Electron menu bar at the top of the app follows the changes. The rendered page does not reflect the changes until the window is closed and re-opened.

## Environment

- Operating system: Ubuntu 20.04 LTS
- Installation method: Snap
- Build Version (go to "Settings" → "About"): built from https://github.com/bitwarden/desktop/commit/f0716c62d2b2b4624873993e6e36e1e35f227c35

## Additional Context

This is an upstream issue with Electron: https://github.com/electron/electron/issues/25925.

This has been fixed in Electron 13, however we are on Electron 11 for the foreseeable future.

This bug is a known issue and is opened here for tracking purposes.

Live theme changes were enabled [here](https://github.com/bitwarden/desktop/pull/929) and should work for all other operating systems.

**Comment by djsmith85** [comment]
@eliykat Can this be closed? With the past released we bumped electron to 14.2 and for the upcoming to 16.07

**Comment by eliykat** [comment]
@djsmith85 good point, let's close this so I don't forget, but I've asked QA to confirm it's been fixed as well.
