### ISSUE TITLE
Changing vault timeout from 'never' to 'on browser restart' does not lock on restart

### ISSUE THREAD

**Issue by alexishorner** [bitwarden/desktop#949]
## Describe the Bug

When changing the vault timeout option from 'never' to 'on browser restart', restarting the browser does not lock bitwarden.

## Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Vault Timeout'
3. Set option to 'never'
4. Accept warning message
5. Set option to 'on browser restart'
6. Restart browser

## Expected Result

Bitwarden should be locked on browser restart.

## Actual Result

Bitwarden remains unlocked, even after a full system restart.

## Environment

- Operating system:  Kubuntu 20.04, Firefox 89.0 (64-bit)
- Installation method: addons.mozilla.org/
- Build Version: 1.50.0

## Additional Context

Locking the vault manually solves the issue. This bug does not seem to occur on Bitwarden Desktop.

**Comment by Greenderella** [comment]
Hi @alexishorner 

This issue appears to be duplicated from this one: https://github.com/bitwarden/browser/issues/1647

As a workaround at the moment, if you click on Lock Now once after you change the Vault Timeout Acton to On Browser Restart, Bitwarden will start locking the extension after closing the browser.

We will proceed to close this issue.

Let us know if there is anything else we can do for you.
