### ISSUE TITLE
JavaScript Error when updating

### ISSUE THREAD

**Issue by RyanNgCT** [bitwarden/desktop#950]
## Describe the Bug

Similar issue to those described [here](https://github.com/bitwarden/desktop/issues/228). Enabling UAC seems to trigger the issue on Windows

## Steps To Reproduce

Enable UAC to recommended and try to update the app

## Expected Result

No popup error message

## Screenshots or Videos

Logs File
![Logfile](https://user-images.githubusercontent.com/48358569/121770045-a4305d80-cb99-11eb-9f2f-a76f7d7a45ef.jpg)

## Environment

- Operating system:: Windows 10
- Installation method: Automatic through the app
- Build Version (go to "Settings" → "About"): 1.26.5 (likely from 1.26.4)

**Comment by SergeantConfused** [comment]
Hi @RyanNgCT,

1. Are you still running the old version? If so, what version were you updating from, please?
2. To which setting do you have your UAC set? The top two are both "Recommended".
3. Are you using an Administrator or a Standard account?
4. What is your OS build?

Thank you in advance,

**Comment by RyanNgCT** [comment]
1. No I'm running the newest version. Was running 1.26.4 before that. (found it from C:\Users\<username>\AppData\Roaming\Bitwarden

![Screenshot 2021-06-14 152222](https://user-images.githubusercontent.com/48358569/121854570-edf97f00-cd24-11eb-9f14-419054ba6f6a.png)

![image](https://user-images.githubusercontent.com/48358569/121854503-d4583780-cd24-11eb-8c85-ef78cc4b42bb.png)

2. UAC set to the second highest
![image](https://user-images.githubusercontent.com/48358569/121854654-07023000-cd25-11eb-8fc0-da6af0dc80a7.png)


3. Administrator (usually doesn't require me to run as admin to update when UAC was off - lowest setting)

4. Windows 10 1909, Build 18363.1440

**Comment by RyanNgCT** [comment]
Hi any updates on this?

**Comment by RyanNgCT** [comment]
Sorry accidentally closed

**Comment by Hinton** [comment]
This *might* be fixed in https://github.com/electron-userland/electron-builder/pull/6073 which requires the latest version of `electron-builder`. (Included in electron-builder 22.11.11 and electron-updater 4.4.3).

**Comment by RyanNgCT** [comment]
Yes. Can confirm that the issue no longer exists when I update.
