### ISSUE TITLE
Mac: Javascipt error when theme switches 

### ISSUE THREAD

**Issue by maxbriel** [bitwarden/desktop#954]
## Describe the Bug

When the native theme switches (Light -> Dark; Dark -> Light), the Bitwarden app when its in the background throws a Javascript error. 

## Steps To Reproduce

1. Open Bitwarden App
2. Close the Bitwarden window, but keep it running in the background.
3. Go to System Preferences, General
4. Under Appearance switch from the current theme to the other.
5. The error should pop up.

## Expected Result

For Bitwarden not to throw this error and switch themes.

## Actual Result

Error thrown. 

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/14039563/121997215-173a0e00-cdfe-11eb-8d14-70e01be215fa.png)

## Environment

OS: Mac OS Mojave (10.14.6)
Installation: Downloaded from Bitwarden.com
Build: 1.26.5 (528)

**Comment by eliykat** [comment]
Hi @maxbriel, thanks for the report. This has already been identified in #896 and will be fixed in the upcoming release. I'll close this thread as a duplicate, but if you continue to receive errors after the next update, please let me know.
