### ISSUE TITLE
Mac App Store haven't bitwarden desktop, only have bitwarden extension

### ISSUE THREAD

**Issue by yaoyi2008** [bitwarden/desktop#958]
I'm in China. According to the bitwarden desktop version download link of the Apple Store provided on your official website, after opening the link, the page does not exist (404). 

I searched for bitwarden directly in the Apple store and only got bitwarden's Safari browser extension.

![image](https://user-images.githubusercontent.com/5906825/122334375-39519e80-cf6c-11eb-8e53-4ebf66224a67.png)

**Comment by Nihal247** [comment]
Hi @yaoyi2008 and thank you for your patience.  

In case if you are not able to download Bitwarden from Mac App Store, please visit https://bitwarden.com/download/ and click on more desktop installation options, to download Bitwarden.dmg file, and you can install it.  

Alternatively, you can open Terminal and install Bitwarden by running this command 'brew install bitwarden' from Homebrew Package Manager.  

Thank You in advance

**Comment by Nihal247** [comment]
Hi @yaoyi2008 and thank you for your patience.

In case if you are not able to download Bitwarden from Mac App Store, please visit https://bitwarden.com/download/ and click on more desktop installation options, to download Bitwarden.dmg file, and you can install it.

Alternatively, you can open Terminal and install Bitwarden by running this command 'brew install bitwarden' with the help of Homebrew Package Manager.

Thank You in advance.

**Comment by SergeantConfused** [comment]
@yaoyi2008,

The desktop client and the Safari extension are bundled together on macOS, and that is how this software package is categorized on the Mac App Store. Please install it, reboot, and you should have both the desktop client and the Safari extension.
If you encounter any trouble with that, please get in touch with us here: https://bitwarden.com/contact/ so we would continue assisting you.

All the best,
