### ISSUE TITLE
changing encryption key and change my master password half of my passwords vanished

### ISSUE THREAD

**Issue by ShervinR** [bitwarden/desktop#960]
Describe the Bug

after changing encryption key and change my master password half of my passwords vanished in desktop , browser extension and web vault 

Environment

- Operating system: ubuntu 20.04
- Installation method: ubuntu software 
- Build Version 1.26.05
![Screenshot from 2021-06-17 15-57-52222](https://user-images.githubusercontent.com/45203261/122388840-855d0d00-cf85-11eb-8d07-ec56f8f4595f.png)

**Comment by Greenderella** [comment]
If you log into your Web Vault (https://vault.bitwarden.com/#/) are you able to see the passwords there?

Will you first try uninstalling the application, removing any leftover data, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/article/data-storage/#on-your-local-machine

Let us know if that helps.

**Comment by ShervinR** [comment]
its done and goes well now 
tnx for your time @Greenderella
