### ISSUE TITLE
Safari Extension disappeared on MacMini M1 - Mac Big Sur 11.4

### ISSUE THREAD

**Issue by fishergmn** [bitwarden/desktop#965]
On a new M1 MacMini after an initial install of the desktop version of Bitwarden from the AppStore the Safari extension was installed without an issue but as of yesterday the extension completely disappeared without any warning or changes in settings or configuration and cannot be recovered. 

After a total removal of all Bitwarden components using an appcleaner on the machine and a fresh install of the desktop Bitwarden app from the appstore the safari extension was unable to be reinstalled and remains absent on the extension list after the browser integration box was checked.

Hardware: 16gb MacMini M1 256GB
MacOS: BigSur 11.4
Safari: 14.1.1
Bitwarden Desktop: 1.26.5

**Comment by kapitainsky** [comment]
The same just happened for me on Intel mac. I have multiple users and Safari on some accounts still have BW extension but on others it is gone. It is extremely frustrating (it is not the first time it is gone) and so far I do not see any logic why it happens.

**Comment by kapitainsky** [comment]
I have also issue open - https://github.com/bitwarden/browser/issues/1847 - regarding disparaging extension. It the past I was able to "fix" it by running Onyx maintenance (cleaning Safari caches). But this time it does not work anymore.

**Comment by kapitainsky** [comment]
@BW  - is there any Safari logfile etc. to try to see why Safari is not picking it up? There must be some reason.

**Comment by eliykat** [comment]
This looks like an ongoing issue from https://github.com/bitwarden/browser/issues/1718. Please direct any discussion to that thread, I'll close this one as a duplicate.
