### ISSUE TITLE
Interference with Adobe Indesign hotkeys

### ISSUE THREAD

**Issue by stosumarte** [bitwarden/desktop#968]
## Describe the Bug

Bitwarden desktop client (macOS) interferes with Adobe Indesign hotkeys (shift, option/alt)

## Steps To Reproduce

Open Bitwarden and let it run for a while, then use Adobe Indesign and try to resize an element while keeping shift pressed. Indesign won't be able to grab the key pression event and won't keep the aspect ratio.
Same happens when pressing Option/alt while dragging an element in Indesign.

## Environment

macOS (Intel) Big Sur 11.4
Bitwarden (bitwarden.com) v1.26.5 (528)

## Additional Context

Closing Bitwarden makes Indesign work again, without needing to reboot the OS.

**Comment by eliykat** [comment]
Likely the same issue as #921, #738 and #298. I'll bump this up internally as it seems to be affecting a few users.

**Comment by eliykat** [comment]
Actually, I just noticed that #298 explicitly mentions Keyboard Maestro. I'll close this as a duplicate, please refer to that thread for further discussion.

**Comment by eliykat** [comment]
I'm closing this in order to centralize this issue under #298. Please refer to that thread for further discussion.
