### ISSUE TITLE
W10 Bitwarden app focus

### ISSUE THREAD

**Issue by DOFfactory** [bitwarden/desktop#972]
## Describe the Bug

Whenever the bitwarden app is in focus on Windows 10, the master password entry does not enable immediate password typing, one has to click on the Master Password section. This introduces a +1 extra step that lowers productivity

## Steps To Reproduce

1. Open Bitwarden app on W10
2. Click to a different windows
3. Alt+tab back to Bitwarden
4. The window is in focus but one has to click extra to the Master Password area to enable typing.

## Expected Result

As soon as the windows is in focus, and the Master Password is requested, the user should be able to type it immediately, without the extra click.

## Environment

- Operating system: Windows 10
- Installation method: Microsoft Store
- Build Version (go to "Settings" → "About"): 1.26.3

**Comment by Nihal247** [comment]
Hi @DOFfactory and thank you for your patience.

I realize this inconvenience. I also had download Bitwarden from Microsoft Store earlier and this was the same case for me too.
After installing it from the Bitwarden website, this inconvenience is now gone, and the cursor remains by default on the Master Password. 

Try installing it from https://bitwarden.com/download/ it might help you too.

Thank you in advance.

**Comment by DOFfactory** [comment]
Oh, thanks @Nihal247 I was unaware of this. Do we know the reason why is the app behaving differently, or the version from the website is newer compared with the MS Store

**Comment by Nihal247** [comment]
Possibly this small feature is added on the newer version of Bitwarden. When I downloaded it from the website I also realized it was a newer version as compared to the Microsoft Store one. 

Definitely the reason for this is Bitwarden is publishing the newer version lately on Microsoft Store, than it's own website.

**Comment by Nihal247** [comment]
Possibly this small feature is added to the newer version of Bitwarden. When I downloaded it from the website I also realized it was a newer version as compared to the Microsoft Store one. 

Definitely the reason for this is Bitwarden is publishing the newer version lately on Microsoft Store, than it's own website.

**Comment by Nihal247** [comment]
If your concern is now solved, kindly consider closing this issue.

**Comment by DOFfactory** [comment]
Thanks, let's close this once the MS Store is updated too

**Comment by Nihal247** [comment]
Okay, as your wish.

**Comment by Nihal247** [comment]
> 
> 
> Thanks, let's close this once the MS Store is updated too

You should close this issue now, as Bitwarden's Microsoft Store version is up to date (1.27.1)
