### ISSUE TITLE
Unlock with Fingerprint not found

### ISSUE THREAD

**Issue by Bbk2468** [bitwarden/desktop#977]
**Describe the Bug**
 In Previous version, there is option of _unlock with fingerprint_ in the setting menu but now there is only unlock with pin option.
After the update of software in my pc there is no more fingerprint unlock and any integrate fingerprint option for browser extension.

 **Steps To Reproduce**
1.  Open start menu in windows 10
2.  Search for bitwarden
3.  Open apps
4.  Log In or unlock with password
5.  Click File button in upward right
6.  Press Setting

**Expected Result**
I can unlock my apps with fingerprint whenever i open apps.

**Actual Result**
Everytime i open the apps, I need to type password  or pin to unlock apps.

**Screenshots**
![Screenshot 2021-07-04 213330](https://user-images.githubusercontent.com/60810986/124391280-8de86e00-dd0f-11eb-8be8-865c8b5247c1.png)

**Environment**

- Operating system: Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version : 1.27.0

**Comment by SergeantConfused** [comment]
Hi @Bbk2468,

Do you unlock your Windows user using Windows Hello? If you do, please uninstall Bitwarden, reboot, install it once more, and let me know if that helps.

Thank you in advance,

**Comment by djsmith85** [comment]
Hi @Bbk2468, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
