### ISSUE TITLE
Windows - Version 1.27.0 does not show a Windows Hello prompt to unlock the vault when Windows starts up.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#978]
## Describe the Bug
Version 1.27.0 of the desktop client would launch directly to the tray when Windows launches, but would not automatically prompt to authenticate using Windows Hello while the client remains in the tray. Version 1.26.5 used to launch the desktop client directly to the tray and show a Windows Hello prompt to unlock the vault while it's still in the tray. 

## Steps To Reproduce
1. Upgrade to version 1.27.0.
2. In the Settings menu, activate the following: 'Unlock with Windows Hello', 'Minimise to tray icon', 'Close to tray icon, 'Start to tray icon', 'Start automatically on login'.
3. Reboot your computer.

## Expected Result
For the Bitwarden desktop client to remain in the background when Windows launches, but for the Windows Hello prompt to show up to authenticate.

## Actual Result
The Bitwarden desktop client is launched in the background and remains locked in the tray.

## Screenshots or Videos
N/A.

## Environment
- Operating system: Windows 10 Pro 21H1 19043.1081.
- Installation method: .exe installer from GitHub.
- Build Version: 1.27.0.

## Additional Context
N/A.

**Comment by Hinton** [comment]
This is the expected behavior, we only prompt for Windows hello when the window is visible to avoid confusion.
