### ISSUE TITLE
Character limits are incorrect

### ISSUE THREAD

**Issue by dlucadou** [bitwarden/desktop#98]
I can't insert >687 characters into username, password, or custom fields, but the error message claims the maximum is 1000. The URL field says it has a max of 10,000 characters, but anything above 7439 characters is rejected. This holds true when it's just alphabetic characters, just numeric characters, just alphanumeric characters, or a mix of alphanumeric + symbols, so whether or not escape characters are used doesn't factor into the total.

I've tested this on the Windows client and web interface.

**Comment by finnoleary** [comment]
Windows could be using Unicode-16, which IIRC is four bytes per character. Can you replicate this on another operating system?

**Comment by kspearrin** [comment]
This is a server error, which limits to 1000 and 10,000 characters, encrypted.

**Comment by dlucadou** [comment]
Should I open an issue on the core project then?

**Comment by kspearrin** [comment]
There is an issue open there about it already: https://github.com/bitwarden/core/issues/87
