### ISSUE TITLE
macOS app consumes modifier keys

### ISSUE THREAD

**Issue by stathisaska** [bitwarden/desktop#990]
## Describe the Bug

When Bitwarden is launched, modifier keys + clicks do not work. E.g. cmd+click, option+click etc.

## Steps To Reproduce

Get an application that supports a functionality using modifier keys + click and just try it out

## Expected Result

Bitwarden should not override os keys functionality throughout the OS.

## Actual Result

After quitting Bitwarden app, the modifier keys + click work again

## Environment

- Operating system: macOS Catalina
- Installation method: Mac App Store
- Build Version: Version 1.26.5 (528)

**Comment by eliykat** [comment]
Does this happen all the time, or only when the app is on the unlock/login screen and not in focus? (e.g. when the vault timeout occurs.) If it only happens on the unlock/login screen, it could be a duplicate of #298 which has been fixed.

**Comment by stathisaska** [comment]
Yes, after testing, this problem is the same with #298
