### ISSUE TITLE
macOS Secure Input enabled when launching app

### ISSUE THREAD

**Issue by probablykasper** [bitwarden/desktop#991]
## Describe the Bug

When launching the app without being logged in and without the window being visible, I'm getting secure input being stuck enabled.

I believe this issue should've been fixed by #970, but I'm getting this issue in 1.27.1.

## Steps To Reproduce

1. Enable the `Start to menu bar` setting
2. Log out of Bitwarden
3. Launch Bitwarden

## Environment

- Operating system: macOS 10.15.7
- Installation method: Downloaded from Bitwarden.com
- Build Version: 1.27.1

**Comment by eliykat** [comment]
Unfortunately #970 did not make the current release - it'll be in the next release. Even though it was merged before the release date, we'd already created release branches for testing, which is the effective cut-off date for what's included in a release.

This fix should be included in the next minor release - 1.28.0. If the problem persists after then, please let us know.

**Comment by probablykasper** [comment]
Ah okay, my bad
