### ISSUE TITLE
Bitwarden desktop blocks keyboard shortcut for photoshop

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/desktop#993]
Some Photoshop shortcut keys aren't working when using Bitwarden.
Space key shortcuts cannot be used.

## Steps To Reproduce

Have photoshop and Bitwarden installed. Run both and try to use photoshop shortcuts

## Expected Result

Photoshop shortcuts shouldn't be affected.

## Actual Result

Can't use photoshop shortcuts like space key

## Environment

The operating environment is
MacOS 11.4
MacBook Pro (15-inch, 2017)
Wacom Cintiq Pro 13 DTH-1320
Wacom EK Remote
Adobe PhotoshopCC 2021
Adobe IllustratorCC 2021

**Comment by eliykat** [comment]
This is a known issue and will be fixed in the next release: https://github.com/bitwarden/jslib/pull/419
