### ISSUE TITLE
Folder structure not showing

### ISSUE THREAD

**Issue by courtbarns** [bitwarden/desktop#999]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system:  Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version Version 1.27.1
- Shell 11.4.5
- Renderer 87.0.4280.141
- Node 12.18.3
- Architecture ia32

**Comment by courtbarns** [comment]
![martin 2021 07 22 @ 11-38 001](https://user-images.githubusercontent.com/87808858/126626705-7313df62-ad37-4c22-bfc0-ce8fc9fd2f90.PNG)

**Comment by tgreer-bw** [comment]
Hi! This was fixed in a recent release, but you'll need to delete the error-causing file from your computer first:

Here's the issue's main thread, with the solution:

https://github.com/bitwarden/desktop/issues/894#issuecomment-843641498

**Comment by courtbarns** [comment]
Many thanks
